feat(connector): add dispute and refund webhooks for Airwallex
juspay/hyperswitch pull request #1021
Opened 2023-04-28 07:19 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Implemented Dispute and Refund Webhooks for Airwallex

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Dispute and Refund webhooks can not be tested, but the schema has been followed https://www.airwallex.com/docs/online-payments__disputes__dispute-notifications 

<img width="852" alt="Airwallex_test" src="https://user-images.githubusercontent.com/83439957/235078148-f6a08e8e-7d2c-49e4-8598-4d1abbc74e0e.png">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-01 13:59 UTC, ArjunKarthik approved these changes

2023-05-02 10:00 UTC, sai-harsha-vardhan requested changes

2023-05-02 10:20 UTC, Narayanbhat166 commented on crates/router/src/connector/airwallex.rs
> +        Err(errors::ConnectorError::WebhookReferenceIdNotFound).into_report()
We can avoid the return statement here. Also the error type is not appropriate, If we are not able to match the event type to any of the required types, then we should not raise `WebhookReferenceIdNotFound`. It should be `UnsupportedWebhookEventType`.

2023-05-02 10:20 UTC, Narayanbhat166 commented on crates/router/src/connector/airwallex/transformers.rs
> +pub enum AirwallexWebhookEvenType {
typo
```suggestion
pub enum AirwallexWebhookEventType
```

2023-05-04 13:30 UTC, sai-harsha-vardhan requested changes

2023-05-04 14:30 UTC, sai-harsha-vardhan approved these changes
LGTM

2023-05-05 13:10 UTC, jagan-jaya approved these changes

2023-05-09 14:22 UTC, jarnura approved these changes

2023-05-09 17:50 UTC, merged