feat/Now we can eve cancel the payments that are in the states of req…
juspay/hyperswitch pull request #1027
Opened 2023-05-02 10:50 UTC by prajjwalkumar17

…uires_payment_method, requires_capture, requires_confirmation, requires_action

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Previously while cancelling payment from some of the the payment intent statuses like requires_payment_method, requires_capture, requires_confirmation, requires_action there was an error thrown that these can't be cancelled as they haven't been authorized. Hence now we can cancel these payments too.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
As for the above statuses we aren't involving the connector and handling the requests ourselves in update method hence having a check and voding the payment attempt and cancelling the payment_intent status in DB.

## How did you test it?
Tested it by using postman as now we are able to cancel the payment in all those cases.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-02 11:07 UTC, Narayanbhat166 requested changes

2023-05-02 11:07 UTC, Narayanbhat166 commented on crates/router/src/core/payments.rs
> +                                                         // | storage_enums::IntentStatus::RequiresCustomerAction
are these comments required?

2023-05-02 11:07 UTC, Narayanbhat166 commented on crates/router/src/core/payments/operations/payment_cancel.rs
> +                Some(enums::AttemptStatus::VoidInitiated)
If this block always returns a value in both the branches, then this should not be optional

2023-05-03 11:17 UTC, Narayanbhat166 commented on crates/router/src/core/payments/operations/payment_cancel.rs
> +        )?;
add this validation right after we get the `payment_intent` object. We do not need to query other entities if this function returns error.

2023-05-03 11:20 UTC, Narayanbhat166 commented on crates/router/src/core/payments/operations/payment_cancel.rs
> +                    .to_not_found_response(errors::ApiErrorResponse::PaymentNotFound)?;
This block is doing two tasks. Make this block return the `intent_status` as an option and then do `async_map` on the status to update the `payment_intent`

2023-05-05 04:09 UTC, Narayanbhat166 commented on crates/router/src/core/payments/operations/payment_cancel.rs
> +        let attempt_status_update =
Destructure this as a tuple of intent_status_update and attempt_status_update

2023-05-08 04:53 UTC, Narayanbhat166 approved these changes

2023-05-08 06:32 UTC, SanchithHegde approved these changes

2023-05-08 12:53 UTC, jarnura approved these changes

2023-05-09 14:48 UTC, merged