feat:Implemented ACH Direct Debits for Adyen
juspay/hyperswitch pull request #1033
Opened 2023-05-03 06:21 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Implemented Bank Debit Data for Adyen Payment Method.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
In Adyen connector ACH Bank Debits was not implemented, but it is important payment method which is needed in market so I implemented it.

## How did you test it?
I tested it using Postman.
<img width="1728" alt="Screenshot 2023-05-03 at 11 45 42 AM" src="https://user-images.githubusercontent.com/85639103/235843981-7db4c82a-09db-4ef1-bb30-88cb5d9f8892.png">

<img width="1728" alt="Screenshot 2023-05-03 at 11 46 07 AM" src="https://user-images.githubusercontent.com/85639103/235844040-ca44784f-3507-4054-92a4-7fdb72c96f65.png">

<img width="1728" alt="Screenshot 2023-05-03 at 11 46 00 AM" src="https://user-images.githubusercontent.com/85639103/235844020-8df9857b-5b34-4317-9369-916c3fb5a9cc.png">

<img width="1728" alt="Screenshot 2023-05-03 at 11 46 18 AM" src="https://user-images.githubusercontent.com/85639103/235844055-294e1b10-2471-4cea-b921-f8a3b1363799.png">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-03 06:48 UTC, ArjunKarthik requested changes

2023-05-03 06:48 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +            country_code: None,
Why we are making country as None here?

2023-05-03 06:48 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +        crate::logger::debug!(adyen_request=?request);
remove logger. We should not log anything inside connector code

2023-05-03 06:48 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +        let additional_data = get_additional_data(item);
Does Adyen support manual capture for bank debits? Cause `get_additional_data` will add authorisation_type type in the request?

2023-05-05 12:52 UTC, jagan-jaya commented on crates/api_models/src/payments.rs
> +        bank_account_holder_name: Secret<String>,
is this mandatory for all connector? stripe was implemented without this field right?

2023-05-07 11:07 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +            country_code: None,
This was resolved without any comments/changes?

2023-05-08 06:13 UTC, ArjunKarthik approved these changes

2023-05-08 06:13 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +    webhooks::IncomingWebhookEvent,
```suggestion
use api_models::{enums, payments, webhooks};
```

Lets change this, Specificc import can cause conflicts in the import part, So lets keep it in this way

2023-05-08 06:50 UTC, ArjunKarthik approved these changes

2023-05-08 07:38 UTC, jagan-jaya approved these changes

2023-05-09 14:28 UTC, jarnura submitted a review, later dismissed

2023-05-09 17:48 UTC, jagan-jaya approved these changes

2023-05-09 18:51 UTC, merged