feat: encrypt PII fields before saving it in the database
juspay/hyperswitch pull request #1043
Opened 2023-05-03 13:39 UTC by dracarys18

## Type of Change

- [x] New feature

## Description

This PR adds support for encrypting PII fields in following tables
- MerchantAccount
- MerchantConnectorAccount
- Address
- Customer

Here's how the basic flow goes, the main encryption key `master_key` will be encrypted with KMS and configured in `development.toml`. For every merchant we will create seperate encryption key and encrypt that key with `master_key` and push it to the database and we will use that key to encrypt the PII fields.

This PR also has migration script that will migrate currently decrypted database to encrypted database.

### Additional Changes
- [x] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

This is for GDPR compliance for saving PII data in an encrypted format.

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-05-04 07:22 UTC, vspecky requested changes

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +pub async fn crate_merchant_key_store(
typo

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +        .change_context(errors::ApiErrorResponse::InternalServerError)?;
I only see a single DB operation here. Why does this need to be in a transaction?

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +        )
Same here. Why a transaction when there's only one DB operation?

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +        )
Same here. Transaction probably not required.

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +        )
Transaction probably not required.

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/types/domain/types.rs
> +        crate::logger::error!("data - {:?}, encrypted - {:?}", data, encrypted,);
probably shouldn't be an `error!()`

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/types/domain/types.rs
> +        );
probably shouldn't be an `error!()`

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/types/domain/types.rs
> +        );
probably shouldn't be an `error!()`

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/types/domain/types.rs
> +        crate::logger::error!("data - {:?}, encrypted - {:?}", data, encrypted);
probably shouldn't be an `error!()`

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/types/domain/types.rs
> +        );
probably shouldn't be an `error!()`

2023-05-04 07:22 UTC, vspecky commented on crates/router/src/types/transformers.rs
> +//         let merchant_ca = item;
Remove commented code

2023-05-04 07:22 UTC, vspecky commented on migrations/2023-04-06-092008_create_merchant_ek/up.sql
> +);
change table name to `merchant_key_store` for consistency with other table names.

2023-05-04 07:31 UTC, NishantJoshi00 commented on crates/common_utils/src/crypto.rs
> +    // nonce: Vec<u8>,
The nonce is attached to the end of the generated encrypted data. You can check out the varied implementation of the `GcmAes256`.
CC: @SanchithHegde @dracarys18

2023-05-04 09:35 UTC, NishantJoshi00 submitted a review, later dismissed

2023-05-04 09:45 UTC, vspecky requested changes

2023-05-04 09:45 UTC, vspecky commented on migrations/2023-04-06-092008_create_merchant_ek/up.sql
> +CREATE TABLE MERCHANT_KEY_STORE(
Make the name lowercase

2023-05-04 11:23 UTC, SanchithHegde commented on crates/router/src/types/domain/types.rs
> +pub const TIMESTAMP: i64 = 1682425530;
Why is this needed?

2023-05-04 11:23 UTC, SanchithHegde commented on crates/router/src/types/domain/types.rs
> +        crate::logger::debug!("data - {:?}, encrypted - {:?}", data, encrypted,);
Remove this.

2023-05-04 11:23 UTC, SanchithHegde commented on crates/router/src/types/domain/types.rs
> +        );
This one as well.

2023-05-04 11:23 UTC, SanchithHegde commented on crates/router/src/types/domain/types.rs
Please ensure no sensitive data is being logged anywhere in this module.

2023-05-04 11:23 UTC, SanchithHegde commented on crates/storage_models/src/address.rs
Please remove the commented lines in this file.

2023-05-04 11:23 UTC, SanchithHegde commented on migrations/2023-04-06-092008_create_merchant_ek/up.sql
> +    CREATED_AT TIMESTAMP NOT NULL DEFAULT now()
Could you make these lowercase, just to be on the safer side?

2023-05-04 11:23 UTC, SanchithHegde commented on migrations/2023-04-11-084958_pii-migration/down.sql
Nit: Name this directory as PII encryption maybe?

2023-05-04 13:28 UTC, dracarys18 commented on migrations/2023-04-11-084958_pii-migration/down.sql
this is just migration doesn't encrypt so i feel pii-migration could be proper name

2023-05-04 14:06 UTC, SanchithHegde submitted a review, later dismissed

2023-05-04 18:21 UTC, NishantJoshi00 approved these changes

2023-05-04 19:54 UTC, SanchithHegde commented on crates/router/src/configs/settings.rs
> +    pub master_enc_key: String,
If you'd prefer to provide a default value only for the purpose of local development, you can add an obvious placeholder value in the `config/development.toml` file.

2023-05-05 07:21 UTC, NishantJoshi00 approved these changes

2023-05-05 09:28 UTC, vspecky requested changes

2023-05-05 09:28 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +    );
Probably shouldn't be a `warn!()`

2023-05-05 09:28 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +    crate::logger::warn!("Updating MerchantConnectorAccount for {}", merchant_id);
Probably shouldn't be a `warn!()`

2023-05-05 09:28 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +        crate::logger::warn!("Started for {}", merchant_id);
Probably shouldn't be a `warn!()`

2023-05-05 09:28 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +    crate::logger::warn!("Updating Customer for {}", merchant_id);
Probably shouldn't be `warn!()`

2023-05-05 09:28 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +    crate::logger::warn!("Done: Updating Customer for {}", merchant_id);
Same

2023-05-05 09:28 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +    crate::logger::warn!("Updating Address for {}", merchant_id);
Same

2023-05-05 09:28 UTC, vspecky commented on crates/router/src/scripts/pii_encryption.rs
> +    crate::logger::warn!("Done: Updating Address for {}", merchant_id);
Same

2023-05-05 09:28 UTC, vspecky commented on migrations/2023-04-06-092008_create_merchant_ek/up.sql
> +CREATE UNIQUE INDEX merchant_key_store_unique_index ON merchantkeystore(merchant_id);
I'm pretty sure this query is not required since `PRIMARY KEY` implies a unique index. If it is required, update the table name to the correct one.

2023-05-05 10:39 UTC, vspecky requested changes

2023-05-05 10:39 UTC, vspecky commented on migrations/2023-04-26-090005_remove_default_created_at_modified_at/up.sql
> +ALTER TABLE merchantkeystore
Update table name.

2023-05-05 10:44 UTC, vspecky approved these changes

2023-05-05 19:02 UTC, SanchithHegde commented on crates/router/src/types/api/customers.rs
> +}
This was removed in #819, I'm assuming this was added back during merge conflict resolution.

2023-05-06 08:25 UTC, SanchithHegde approved these changes

2023-05-22 19:01 UTC, SanchithHegde approved these changes

2023-05-30 08:01 UTC, SanchithHegde commented on crates/router/src/core/admin.rs
> +use masking::Secret; //PeekInterface
```suggestion
use masking::Secret;
```

2023-05-30 08:11 UTC, jarnura approved these changes

2023-05-30 08:13 UTC, inventvenkat approved these changes

2023-05-30 08:43 UTC, merged

2023-06-04 12:58 UTC, SanchithHegde commented on crates/router/src/core/customers.rs
> +            .change_context(errors::ApiErrorResponse::AddressNotFound)?;
This change raises an incorrect error message that the address was not found, when in reality, the deseriliazation of the address failed. Could you please fix this, and ensure that "resource not found" errors are not being raised incorrectly elsewhere?