Adyen mandates wallet
juspay/hyperswitch pull request #1046
Opened 2023-05-03 20:12 UTC by jagan-jaya

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add mandate support for gpay, apple_pay and klarna
Closes #1045 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

1. As part of enabling mandate payments for major connectors, we are adding support for gpay, apple_pay and klarna mandates in adyen
2. Core changes required as mandates for wallets and BNPL are not supported as of now in core
    Eg: mandate id need to updated during PSync when redirection is required for mandate creation, So after the /redirect call happened it will call the /sync internally and it should be updating the mandate id

## How did you test it?

<img width="1123" alt="Screen Shot 2023-05-04 at 1 27 01 AM" src="https://user-images.githubusercontent.com/20727598/236036746-0811f3e0-99c3-4096-9a9d-17e4305d7346.png">

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed submitted code
- [X] I added unit tests for my changes where possible

2023-05-04 12:05 UTC, jarnura requested changes

2023-05-04 12:05 UTC, jarnura commented on crates/router/src/core/mandate.rs
> +pub async fn update_connector_mandate_id(
We should use update trackers(trait)/post update trackers(trait) to update the models and get trackers(trait) to get the models. We can have a reusable function which can be called in trait implementation.

2023-05-08 13:33 UTC, ArjunKarthik submitted a review, later dismissed

2023-05-08 13:38 UTC, jarnura submitted a review, later dismissed

2023-05-09 14:40 UTC, merged