feat(connector) : add bank redirect support for worldline
juspay/hyperswitch pull request #1060
Opened 2023-05-05 14:16 UTC by srujanchikke

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR has following changes 
 1)Bank Redirects (Ideal and giropay)
2) Add `FrieslandBank` bank in `BankNames`  enum

**Note** : For the worldline connector , the final status of card payments remains in the processing state within their sandbox environment. Likewise, in their sandbox environment, the status of their bank redirects remains in the "redirected" state, which is `requiresCustomerAction` for us .

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Adding bank redirect support for worldline

## How did you test it?

**tested existing card payment** 
<img width="871" alt="Screenshot 2023-05-05 at 7 14 48 PM" src="https://user-images.githubusercontent.com/121822803/236483230-2eebf35a-ccf1-4661-ab59-4bc8becc34f2.png">

**tested bank redirects using postman** 
**Giropay**

<img width="1285" alt="Screenshot 2023-05-05 at 4 59 15 PM" src="https://user-images.githubusercontent.com/121822803/236480959-3451bbd6-74bd-47ba-999e-2d8be0369cc4.png">

**Redirected to return url**
<img width="1452" alt="Screenshot 2023-05-05 at 4 58 46 PM" src="https://user-images.githubusercontent.com/121822803/236480991-4ae82fc8-5f15-4484-9e78-645975d6e542.png">

**payment status**
<img width="1293" alt="Screenshot 2023-05-05 at 4 59 35 PM" src="https://user-images.githubusercontent.com/121822803/236481125-3cb42f94-c9ef-4620-ae75-e24eac9c9546.png">

**ideal**
<img width="1276" alt="Screenshot 2023-05-05 at 5 00 04 PM" src="https://user-images.githubusercontent.com/121822803/236481176-0e8bb281-e588-4acd-a5cc-cfc535fbfa40.png">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-06 13:54 UTC, jagan-jaya requested changes

2023-05-06 15:05 UTC, srujanchikke commented on crates/router/src/connector/worldline/transformers.rs
> +            .map(|address| Shipping { ..address.into() });
yes , this does work.

2023-05-08 07:20 UTC, jagan-jaya approved these changes

2023-05-09 14:30 UTC, ArjunKarthik approved these changes

2023-05-09 18:28 UTC, jagan-jaya approved these changes

2023-05-09 18:38 UTC, jarnura approved these changes

2023-05-09 18:59 UTC, merged