feat(connector):  add support for bank redirect for Paypal
juspay/hyperswitch pull request #1107
Opened 2023-05-10 10:07 UTC by prasunna09

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add bank redirects - Ideal, Eps, Giropay, and Sofort for Paypal connector.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Tested using postman.
<img width="1264" alt="Screenshot 2023-05-10 at 2 54 12 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/4959d087-59eb-446e-8d16-d8300a48fe4a">
<img width="1240" alt="Screenshot 2023-05-10 at 2 55 11 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/0cfbd9f7-a745-4e83-aa21-f20d4e3ab26f">

Tested a successful payment
<img width="1240" alt="Screenshot 2023-05-10 at 2 55 11 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/2e9f5c9e-f6e5-4fab-b947-85c30010c791">
<img width="1276" alt="Screenshot 2023-05-10 at 2 56 26 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/f5d02eb1-51ba-4218-9223-631593b321b4">

Tested a failed payment
<img width="1181" alt="Screenshot 2023-05-10 at 2 59 02 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/a59684e1-d999-468c-a5df-b6eda7d26ec8">
<img width="1212" alt="Screenshot 2023-05-10 at 2 59 23 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/2cba6e5b-559a-4d18-8065-c6cbc5b625d6">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-10 13:16 UTC, jagan-jaya requested changes

2023-05-10 13:16 UTC, jagan-jaya commented on crates/api_models/src/payments.rs
> +            PaymentMethodData::BankRedirect(bank_redirect_data) => {
is this discussed with @Narayanbhat166 , will it break any other flow?

2023-05-10 13:16 UTC, jagan-jaya commented on crates/router/src/compatibility/stripe/errors.rs
> +    #[error(error_type = StripeErrorType::InvalidRequestError, code = "resource_missing", message = "No such payment method")]
```suggestion
    #[error(error_type = StripeErrorType::InvalidRequestError, code = "resource_missing", message = "No such payment method type")]
```

2023-05-10 13:16 UTC, jagan-jaya commented on crates/router/src/connector/paypal/transformers.rs
> +                cancel_url: item.request.complete_authorize_url.clone(),
is cancel flow tested?

2023-05-10 13:16 UTC, jagan-jaya commented on crates/router/src/core/payments/helpers.rs
> +            && !matches!(payment_method, Some(api_enums::PaymentMethod::BankRedirect)),
why there is a change here? aren't you getting payment_method_data and payment_method

2023-05-10 13:16 UTC, jagan-jaya commented on crates/router/src/core/payments/operations/payment_complete_authorize.rs
> +                    .foreign_into(),
use foreign_from

2023-05-10 13:16 UTC, jagan-jaya commented on crates/router/src/core/payments/operations/payment_complete_authorize.rs
> +                    .foreign_into(),
use foreign_from

2023-05-10 13:17 UTC, jagan-jaya requested changes

2023-05-10 13:17 UTC, jagan-jaya commented on crates/router/src/connector/paypal/transformers.rs
> +                cancel_url: item.request.complete_authorize_url.clone(),
if cancellation is possible then it it handled in complete_authorize_flow?

2023-05-10 13:21 UTC, prasunna09 commented on crates/router/src/connector/paypal/transformers.rs
> +                cancel_url: item.request.complete_authorize_url.clone(),
yes!

2023-05-11 10:25 UTC, jagan-jaya submitted a review, later dismissed
Other than cancellation feature handling in complete_authorize, it looks good to me

2023-05-12 15:56 UTC, ArjunKarthik submitted a review, later dismissed
Please confirm your changes on new stripe error with abhishek

2023-05-12 16:04 UTC, prasunna09 commented on crates/router/src/compatibility/stripe/errors.rs
> +    PaymentMethodTypeNotFound,
So I have removed this error in the other pr as it is no longer needed!

2023-05-16 07:35 UTC, ArjunKarthik submitted a review, later dismissed

2023-05-16 18:30 UTC, jarnura requested changes

2023-05-16 18:30 UTC, jarnura commented on crates/api_models/src/payments.rs
> +    BankRedirect(BankRedirectData),
Is this changes are discussed with dependent teams?

2023-05-16 18:30 UTC, jarnura commented on crates/router/src/connector/paypal/transformers.rs
> +            country_code: api_models::enums::CountryAlpha2::AT,
Why we are hard-coding country here?

2023-06-29 12:05 UTC, jagan-jaya requested changes
@prasunna09 Add comments in the description on why vault changes are need here. 
Also add the testcases in [hs-tool](https://hs-payments-test.netlify.app)

2023-06-29 12:05 UTC, jagan-jaya commented on crates/router/src/connector/paypal/transformers.rs
> +                let intent = PaypalPaymentIntent::Capture;
why are we hardcoding `capture`?

2023-07-28 14:10 UTC, jarnura approved these changes

2023-08-01 07:41 UTC, ArjunKarthik requested changes
Please resolve open comments

2023-08-02 11:09 UTC, jarnura approved these changes

2023-08-02 11:20 UTC, jagan-jaya approved these changes

2023-08-02 11:27 UTC, ArjunKarthik approved these changes

2023-08-02 12:17 UTC, merged