feat(connector): [Stripe] Implement Przelewy24 bank redirect
juspay/hyperswitch pull request #1111
Opened 2023-05-10 12:09 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Implemented Przelewy24 Bank Redirect payment method for Stripe.

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
In Stripe connector Przelewy24 Bank Redirect was not implemented, but it is important payment method which is needed in market so I implemented it.

## How did you test it?
I tested it using Postman
Create payment
<img width="1728" alt="Screenshot 2023-05-10 at 5 33 25 PM" src="https://github.com/juspay/hyperswitch/assets/131388445/e51776a0-1b4e-4cd7-8472-1916f6ca80a9">
Retrieve Payment
<img width="1728" alt="Screenshot 2023-05-10 at 5 33 30 PM" src="https://github.com/juspay/hyperswitch/assets/131388445/0f11ca82-6e5c-435e-a3be-4b99968635b8">
Create Refund
<img width="1728" alt="Screenshot 2023-05-10 at 5 33 37 PM" src="https://github.com/juspay/hyperswitch/assets/131388445/6791b60a-14da-462a-ade8-f322f184b143">
RetrieveRefund
<img width="1728" alt="Screenshot 2023-05-10 at 5 33 51 PM" src="https://github.com/juspay/hyperswitch/assets/131388445/d85338fc-0734-45dd-88b6-0752bfb221f2">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-11 08:25 UTC, SanchithHegde commented on crates/router/src/connector/stripe/transformers.rs
> +    #[serde(rename = "idea_bank")]
Since there's a `#[serde(rename_all = "snake_case")]`, this rename is not needed.

2023-05-11 11:12 UTC, SanchithHegde approved these changes

2023-05-12 15:50 UTC, jarnura submitted a review, later dismissed

2023-05-13 10:04 UTC, SanchithHegde submitted a review, later dismissed

2023-05-13 11:05 UTC, SanchithHegde submitted a review, later dismissed

2023-05-13 13:44 UTC, jagan-jaya requested changes

2023-05-13 13:44 UTC, jagan-jaya commented on crates/router/src/connector/worldline/transformers.rs
> +                                field_name: "account_holder_name",
```suggestion
                                field_name: "billing_details.billing_name",
```

2023-05-13 14:37 UTC, SanchithHegde approved these changes

2023-05-13 14:39 UTC, jagan-jaya approved these changes

2023-05-15 10:28 UTC, merged