refactor(connector): update error handling for Nexinets, Cybersource and unit tests for globalpay
juspay/hyperswitch pull request #1151
Opened 2023-05-12 14:56 UTC by srujanchikke

Signed-

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR contains following changes
1)Refactor error handling for nexinets
2)Refactor error handling for Cybersource
3)Refactor and add unit tests for Globalpay

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Modified error message from dynamic to static messages. Also modified the tests accordingly.

## How did you test it?

Connector unit tests

<img width="1038" alt="Screenshot 2023-05-12 at 8 05 43 PM" src="https://github.com/juspay/hyperswitch/assets/121822803/b0df4baf-3f12-4f98-9eb7-575a2011baf0">

<img width="1042" alt="Screenshot 2023-05-12 at 7 54 54 PM" src="https://github.com/juspay/hyperswitch/assets/121822803/7e0ed09d-5975-4428-bb8d-d6afed19cee0">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-13 12:18 UTC, jagan-jaya requested changes

2023-05-13 12:18 UTC, jagan-jaya commented on crates/router/src/connector/cybersource.rs
> +        let details = response.details.map_or(vec![], |details| details);
```suggestion
        let details = response.details.unwrap_or(vec![]);
```

2023-05-13 12:18 UTC, jagan-jaya commented on crates/router/tests/connectors/cybersource.rs
> +        r#"Declined - One or more fields in the request contains invalid data"#,
assert reason also here, it should convey the expiryMonth issue to the user

2023-05-13 12:18 UTC, jagan-jaya commented on crates/router/tests/connectors/cybersource.rs
> +        r#"Declined - One or more fields in the request contains invalid data"#,
assert reason also here, it should convey the securityCode issue to the user

2023-05-13 12:18 UTC, jagan-jaya commented on crates/router/tests/connectors/cybersource.rs
> +#[ignore = "Connector Error, needs to be looked into and fixed"]
is it possible to fix it right now

2023-05-13 12:18 UTC, jagan-jaya commented on crates/router/tests/connectors/cybersource.rs
> +#[ignore = "Connector Error, needs to be looked into and fixed"]
is it possible to fix it now

2023-05-17 15:49 UTC, ArjunKarthik requested changes

2023-05-17 15:49 UTC, ArjunKarthik commented on crates/router/src/connector/cybersource.rs
> +        for det in details.iter() {
lets use join method

2023-05-19 15:23 UTC, ArjunKarthik approved these changes

2023-05-19 19:39 UTC, jagan-jaya submitted a review, later dismissed

2023-05-20 12:11 UTC, SanchithHegde reviewed
Minor changes. Other than that, looks good to me!

2023-05-20 12:11 UTC, SanchithHegde commented on crates/router/tests/connectors/cybersource.rs
> +#[ignore]
Would be great if you could include a reason for ignoring this test.

2023-05-20 12:11 UTC, SanchithHegde commented on crates/router/tests/connectors/cybersource.rs
> +        r#"Declined - One or more fields in the request contains invalid data"#,
```suggestion
        "Declined - One or more fields in the request contains invalid data",
```

This can be a regular string literal.

2023-05-20 12:11 UTC, SanchithHegde commented on crates/router/tests/connectors/cybersource.rs
> +        r#"Declined - One or more fields in the request contains invalid data"#,
```suggestion
        "Declined - One or more fields in the request contains invalid data",
```

2023-05-20 12:11 UTC, SanchithHegde commented on crates/router/tests/connectors/cybersource.rs
> +        r#"Declined - One or more fields in the request contains invalid data"#
```suggestion
        "Declined - One or more fields in the request contains invalid data"
```

2023-05-21 07:51 UTC, SanchithHegde submitted a review, later dismissed

2023-05-25 06:48 UTC, SanchithHegde approved these changes

2023-05-29 05:42 UTC, ArjunKarthik approved these changes

2023-05-29 22:19 UTC, merged