feat(connector): [Stripe] implement Bancontact Bank Redirect for stripe
juspay/hyperswitch pull request #1169
Opened 2023-05-15 15:03 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Implemented Bancontact Bank Redirect, payment method for Stripe.

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
In Stripe connector Bancontact Bank Redirect was not implemented, but it is important payment method which is needed in market so I implemented it.

## How did you test it?
Tested it using Postman

Create Payment Intent
<img width="1728" alt="Screenshot 2023-05-15 at 8 16 07 PM" src="https://github.com/juspay/hyperswitch/assets/131388445/0b2e58aa-5742-4ab2-99c5-96b241460a6b">

Retrieve Payment Intent 
<img width="1728" alt="Screenshot 2023-05-15 at 8 16 19 PM" src="https://github.com/juspay/hyperswitch/assets/131388445/db909aaf-1cdf-4fdb-8ed1-61d7280583a4">

Create Refund
<img width="1728" alt="Screenshot 2023-05-15 at 8 16 28 PM" src="https://github.com/juspay/hyperswitch/assets/131388445/c85d967e-6818-4765-a970-a189e127401a">

Retrieve Refund
<img width="1728" alt="Screenshot 2023-05-15 at 8 16 36 PM" src="https://github.com/juspay/hyperswitch/assets/131388445/f43a4265-cfda-41cd-a894-97adedaefc2d">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-15 16:46 UTC, jagan-jaya commented on crates/router/src/connector/adyen/transformers.rs
> +                            field_name: "Card Exp Month",
```suggestion
                            field_name: "bancontact_card.card_exp_month",
```

2023-05-15 16:46 UTC, jagan-jaya commented on crates/router/src/connector/adyen/transformers.rs
> +                            field_name: "Card Holder Nsame",
```suggestion
                            field_name: "bancontact_card.card_holder_name",
```

2023-05-15 16:51 UTC, jagan-jaya requested changes

2023-05-15 16:51 UTC, jagan-jaya commented on crates/router/src/connector/stripe/transformers.rs
> +                        field_name: "billing_name",
```suggestion
                        field_name: "bancontact_card.billing_name",
```

2023-05-16 07:01 UTC, jagan-jaya approved these changes

2023-05-16 07:54 UTC, ArjunKarthik approved these changes

2023-05-16 10:49 UTC, jarnura approved these changes

2023-05-16 11:27 UTC, merged