feat(payments): add support for manual retries in payments confirm call
juspay/hyperswitch pull request #1170
Opened 2023-05-15 15:11 UTC by Abhicodes-crypto

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Previously,
- In Payments Flows if the payment was failed due to any reason other payment attempts were not allowed.
- If tried to make confirm call we would get error, 'payment already in Failed status'. 
- So the user is forced to create a new payment_intent using Server API key and then use the client secret and publishable key to confirm the payment. 

Issues: 
- The above is inefficient and a bad user experience, the user should be allowed to enter a new payment method and create try the payment again.

About Solution:
- This PR addresses the above issue. 
- We have multiple payment flows, and the flows through which we can do payment authorization is Create, confirm , update and payment complete authorization flow.
- In create flow manual retry won't be happening as new payment is created in this flow
- This PR adds manual retry support in confirm API only. Will raise a separate PR for support in complete_authorization flow , and update flow(or maybe update flow will be removed to have a cleaner API contract and only be used to update non-critical payment data).

Changes made in this PR 
- Added a bool field `manual_retry` in PaymentsRequest and the default value is `false`.
- In manual retry case, a new payment attempt is created, and the payment intent is updated. 
- A new connector_response is created.

Also possible  todo , should there be a max number of manual retries a merchant can do  ?

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

![image](https://github.com/juspay/hyperswitch/assets/68317979/c7bf1487-73fa-4a83-8db4-514e8657c059)
![image](https://github.com/juspay/hyperswitch/assets/68317979/66cbf649-17bb-412c-a973-9cd6f8a14a1e)
![image](https://github.com/juspay/hyperswitch/assets/68317979/fa6b116e-dde8-4bce-8e3b-45d16699f322)
![image](https://github.com/juspay/hyperswitch/assets/68317979/be349daf-8c40-4fec-9d3e-e08297fce3f4)
```
hyperswitch_db=# select * from payment_attempt where payment_id= 'pay_220wdZUOHL8pt7BE8Uwg'
;
-[ RECORD 1 ]--------------+------------------------------------------------------
id                         | 28
payment_id                 | pay_220wdZUOHL8pt7BE8Uwg
merchant_id                | merchant_1683795848
attempt_id                 | ab80aab13abe4b94b7a136776174b054
status                     | failure
amount                     | 6540
currency                   | USD
save_to_locker             | 
connector                  | checkout
error_message              | Full card payments disabled
offer_amount               | 
surcharge_amount           | 
tax_amount                 | 
payment_method_id          | 
payment_method             | card
connector_transaction_id   | 
capture_method             | automatic
capture_on                 | 2022-09-10 10:11:12
confirm                    | t
authentication_type        | no_three_ds
created_at                 | 2023-05-15 14:07:17.288937
modified_at                | 2023-05-15 14:07:18.311236
last_synced                | 2023-05-15 14:07:17.288937
cancellation_reason        | 
amount_to_capture          | 
mandate_id                 | 
browser_info               | 
error_code                 | No error code
payment_token              | token_0XaJob9VtPd6l09fOGb6
connector_metadata         | 
payment_experience         | 
payment_method_type        | credit
payment_method_data        | {"card": {"card_issuer": null, "card_network": null}}
business_sub_label         | 
straight_through_algorithm | {"algorithm": {"data": "checkout", "type": "single"}}
-[ RECORD 2 ]--------------+------------------------------------------------------
id                         | 29
payment_id                 | pay_220wdZUOHL8pt7BE8Uwg
merchant_id                | merchant_1683795848
attempt_id                 | be3c0240ed90464ebe10380f10baa826
status                     | charged
amount                     | 6540
currency                   | USD
save_to_locker             | 
connector                  | stripe
error_message              | 
offer_amount               | 
surcharge_amount           | 
tax_amount                 | 
payment_method_id          | 
payment_method             | card
connector_transaction_id   | pi_3N823oD5R7gDAGff1m65JGBV
capture_method             | automatic
capture_on                 | 2022-09-10 10:11:12
confirm                    | t
authentication_type        | no_three_ds
created_at                 | 2023-05-15 14:07:35.747434
modified_at                | 2023-05-15 14:07:38.238459
last_synced                | 2023-05-15 14:07:35.747434
cancellation_reason        | 
amount_to_capture          | 
mandate_id                 | 
browser_info               | 
error_code                 | 
payment_token              | token_GJuk7ixB33EhnL9u6f08
connector_metadata         | 
payment_experience         | 
payment_method_type        | credit
payment_method_data        | {"card": {"card_issuer": null, "card_network": null}}
business_sub_label         | 
straight_through_algorithm | {"algorithm": {"data": "stripe", "type": "single"}}
```
<img width="989" alt="image" src="https://github.com/juspay/hyperswitch/assets/68317979/302cbdae-15a7-4d1c-a54a-54ae62dd9e6b">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-16 18:33 UTC, jarnura requested changes

2023-05-16 18:33 UTC, jarnura commented on crates/router/src/core/payments/helpers.rs
> +                    storage_enums::AttemptStatus::AuthenticationFailed
Remove the statuses which can't be manually retried.

2023-05-16 18:33 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_confirm.rs
> +            authentication_type: old_payment_attempt.authentication_type,
use the authentication_type from the request. And add comments for fields also, why we are taking data from the old_payment_attempt and not from the request.

2023-05-18 08:13 UTC, jarnura approved these changes

2023-05-18 08:16 UTC, jagan-jaya approved these changes

2023-05-18 08:50 UTC, merged