feat(connector): [Noon] Add Card Payments, Capture, Void and Refund
juspay/hyperswitch pull request #1207
Opened 2023-05-18 13:44 UTC by SamraatBansal

## Type of Change

- [ ] Bugfix
- [X] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Added Card Payments (3DS and Non-3DS) along with all the listed flows:

- [Authorize](https://docs.noonpayments.com/payment-api/reference/initiate)
- [Capture](https://docs.noonpayments.com/payment-api/reference/capture)
- [Void](https://docs.noonpayments.com/payment-api/reference/reverse)
- [Refund](https://docs.noonpayments.com/payment-api/reference/refund)

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Closes #1185

## How did you test it?

Unit Tests are not updated as all the tests trigger 3DS

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-19 06:10 UTC, ArjunKarthik requested changes

2023-05-19 06:10 UTC, ArjunKarthik commented on crates/router/src/connector/noon/transformers.rs
> +#[derive(Debug, Serialize, Eq, PartialEq)]
We don't need Eq & PartialEq in any of the structs

2023-05-19 06:10 UTC, ArjunKarthik commented on crates/router/src/connector/noon/transformers.rs
> +        let payment_action = match item.request.capture_method {
Use is_auto_capture method in utils.

2023-05-19 09:24 UTC, jagan-jaya requested changes

2023-05-19 09:24 UTC, jagan-jaya commented on crates/router/src/connector/noon.rs
> +            .change_context(errors::ConnectorError::MissingConnectorTransactionID)?;
```suggestion
        let connector_transaction_id = req
            .request
            .get_connector_transaction_id()?;
```

2023-05-19 09:24 UTC, jagan-jaya commented on crates/router/src/connector/noon/transformers.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
need both serialize and deserialize ? what about PartialEq, do you need that also?

2023-05-19 09:24 UTC, jagan-jaya commented on crates/router/src/connector/noon/transformers.rs
> +#[derive(Debug, Clone, Deserialize, PartialEq)]
PartialEq required?

2023-05-19 09:25 UTC, jagan-jaya commented on crates/router/src/connector/noon/transformers.rs
> +#[derive(Debug, Clone, Deserialize, PartialEq)]
remove PartialEq wherever not required

2023-05-22 13:54 UTC, ArjunKarthik submitted a review, later dismissed

2023-05-22 14:07 UTC, jagan-jaya requested changes

2023-05-22 14:07 UTC, jagan-jaya commented on crates/router/src/connector/noon/transformers.rs
> +            NoonPaymentStatus::ThreeDsEnrollInitiated => Self::AuthenticationPending,
there is no pending status?

2023-05-23 07:33 UTC, HyperSwitchers approved these changes

2023-05-23 07:33 UTC, jagan-jaya approved these changes

2023-05-23 07:38 UTC, ArjunKarthik approved these changes

2023-05-23 11:05 UTC, jarnura approved these changes

2023-05-23 11:30 UTC, merged