fix(connector) : [Globalpay] fix globalpay unit tests
juspay/hyperswitch pull request #1217
Opened 2023-05-19 19:54 UTC by srujanchikke

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR contains following changes 
1)unit tests for globalpay

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
unit tests for globalpay

## How did you test it?

unit tests 
Note : `should_fail_void_payment_for_auto_capture` is failing from connector end .
<img width="1190" alt="Screenshot 2023-05-20 at 1 08 02 AM" src="https://github.com/juspay/hyperswitch/assets/121822803/21317058-7295-472c-935b-64bc0000314f">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-22 19:26 UTC, SanchithHegde submitted a review, later dismissed

2023-05-24 08:32 UTC, jagan-jaya requested changes

2023-05-24 08:32 UTC, jagan-jaya commented on Cargo.lock
> - "cards",
undo all the changes in this file

2023-05-24 13:53 UTC, SanchithHegde submitted a review, later dismissed

2023-05-29 05:23 UTC, ArjunKarthik requested changes
@srujanchikke ~~There are changes in the connector auth please add the label api contract changes. So that we can mark dashboard dependency while releasing this changes in the release announcements~~

2023-05-29 05:23 UTC, ArjunKarthik commented on crates/router/tests/connectors/globalpay.rs
> +                    card_number: cards::CardNumber::from_str("").unwrap(),
This test fails for empty card number can you rerun and check this?

2023-05-29 05:23 UTC, ArjunKarthik commented on crates/router/tests/connectors/globalpay.rs
> +                    card_number: cards::CardNumber::from_str("13241313413").unwrap(),
Same here, this would fail because of Kuhn check we have. Please rerun and check

2023-05-30 05:35 UTC, jagan-jaya approved these changes

2023-06-09 12:12 UTC, ArjunKarthik approved these changes

2023-06-15 07:19 UTC, SanchithHegde approved these changes

2023-06-15 07:51 UTC, merged