refactor(core) : add `redirect_response` field to CompleteAuthorizeData
juspay/hyperswitch pull request #1222
Opened 2023-05-21 15:30 UTC by srujanchikke

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

add redirect_response field to CompleteAuthorizeData instead of payload 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Previously we were sending only payload in `CompleteAuthorizedData` , for connector `authorizedotnet` query_params are required. In this PR `redirect_response` is added in `CompleteAuthorizedData` which contains both query_params and payload. 

## How did you test it?

Bluesnap goes through complete authorize flow for 3ds payment ,which uses payload in redirect response .So ,i have tested this connector in postman. 
<img width="1290" alt="Screenshot 2023-05-21 at 7 44 05 PM" src="https://github.com/juspay/hyperswitch/assets/121822803/839709f0-82f0-45ca-b492-2f9350aa0327">
<img width="1300" alt="Screenshot 2023-05-21 at 7 44 22 PM" src="https://github.com/juspay/hyperswitch/assets/121822803/c98d4498-836b-4b93-88b5-4ccbb93e528e">

## Check

list

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-22 02:56 UTC, jarnura requested changes

2023-05-22 02:56 UTC, jarnura commented on crates/api_models/src/payments.rs
> +    pub param: Option<String>,
Make this as secret.

2023-05-22 02:56 UTC, jarnura commented on crates/router/src/types.rs
> +    pub params: Option<String>,
convert all fields as secret.

2023-05-22 19:25 UTC, SanchithHegde approved these changes

2023-05-30 07:42 UTC, jarnura approved these changes

2023-05-30 08:13 UTC, merged