refactor:  make NextAction as enum
juspay/hyperswitch pull request #1234
Opened 2023-05-23 06:12 UTC by Sangamesh26

## Type of Change

- [x] Refactoring

## Description

Earlier NextAction was struct and had only redirect_to_url as optional field but after bank transfer, there is next action which is not redirection to url, so NextAction struct is converted to enum with internally tagged with type. Now, this enum can handle both redirection kind of next action as well as just displaying the information kind of next action.

## Motivation and Context

To support both redirection and information display in next action

## How did you test it?

For redirect to url:
<img width="1097" alt="Screen Shot 2023-05-22 at 5 55 04 PM" src="https://github.com/juspay/hyperswitch/assets/59434228/585d9265-cc43-475b-aeed-39ba6222e4be">

For bank transfer information:
<img width="861" alt="Screen Shot 2023-05-23 at 11 27 38 AM" src="https://github.com/juspay/hyperswitch/assets/59434228/40e031b6-2c6a-49cc-b854-364b5651d13a">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-23 10:37 UTC, Abhicodes-crypto commented on crates/router/src/compatibility/stripe/payment_intents/types.rs
> +    },
Good catch!
The common fields could be put in a separate struct and then should be tested if `serde_qs` is able to handle it properly. Will create an issue for this.

2023-05-23 10:42 UTC, Abhicodes-crypto approved these changes

2023-05-23 10:50 UTC, jarnura requested changes

2023-05-23 10:50 UTC, jarnura commented on crates/api_models/src/payments.rs
> +pub enum NextActionData {
Add doc comments

2023-05-23 13:56 UTC, Abhicodes-crypto approved these changes

2023-05-24 05:15 UTC, jarnura approved these changes

2023-05-24 05:45 UTC, merged