feat(router): Validate payment method type in payments request against given payment method data for non-card flows
juspay/hyperswitch pull request #1236
Opened 2023-05-23 08:58 UTC by kritikmodi

## Type of Change

- [x ] Bugfix
- [ x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Added the following checks for non-card flows :

1. Check if `payment_method_type` is specified.
2. Check if the specified `payment_method_type` corresponds to the parent `payment_method`.
3. Check if the specified `payment_method_data` corresponds to the parent `payment_method`.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

This PR resolves [this](https://github.com/juspay/hyperswitch/issues/1102) issue.

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [x ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-25 09:54 UTC, prajjwalkumar17 requested changes
Add required **Labels** and **Milestone**.

2023-05-25 12:40 UTC, vspecky commented on crates/router/src/core/payments/helpers.rs
> +        !matches!(req.payment_method, Some(api_enums::PaymentMethod::Card))
I noticed this not but this `matches!()` will also return `false` for when `req.payment_method` is `None` which is basically asserting that even if `payment_method` is not given, `payment_method_type` should be given which is incorrect. The following should fix this afaik
```suggestion
        !matches!(req.payment_method, Some(api_enums::PaymentMethod::Card) | None)
```

2023-05-26 12:04 UTC, kritikmodi commented
> Add required **Labels** and **Milestone**.

2023-05-29 08:21 UTC, vspecky submitted a review, later dismissed

2023-05-29 09:26 UTC, jarnura approved these changes

2023-05-29 09:56 UTC, prajjwalkumar17 approved these changes

2023-06-24 11:22 UTC, SanchithHegde commented
1. Please avoid basing your PR on old branches and prefer basing your branches on the `main` branch instead. Having many commits in a PR adds unnecessary noise when debugging.
2. I'll be adding the `M-api-contract-changes` label, since this PR adds additional request validation.

2023-06-24 11:23 UTC, SanchithHegde submitted a review, later dismissed

2023-06-26 08:49 UTC, kritikmodi commented
> * Please avoid basing your PR on old branches and prefer basing your branches on the `main` branch instead. Having many commits in a PR adds unnecessary noise when debugging.
> * I'll be adding the `M-api-contract-changes` label, since this PR adds additional request validation.

Okay sure.

2023-06-26 15:59 UTC, prajjwalkumar17 submitted a review, later dismissed

2023-07-13 09:42 UTC, prajjwalkumar17 submitted a review, later dismissed

2023-07-17 12:38 UTC, jarnura submitted a review, later dismissed

2023-07-17 13:09 UTC, vspecky approved these changes

2023-07-20 10:44 UTC, prajjwalkumar17 approved these changes

2023-07-20 10:45 UTC, vspecky approved these changes

2023-07-26 10:06 UTC, SanchithHegde approved these changes

2023-07-26 10:20 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/helpers.rs
>                  field_name: "payment_method",
Please give an appropriate error message here based on the missing value

2023-07-26 14:20 UTC, prajjwalkumar17 approved these changes

2023-07-26 15:29 UTC, sai-harsha-vardhan approved these changes

2023-07-27 05:04 UTC, SanchithHegde approved these changes

2023-07-27 05:35 UTC, merged