feat(core): add signature to outgoing webhooks
juspay/hyperswitch pull request #1249
Opened 2023-05-24 07:00 UTC by ShankarSinghC

## Type of Change

- [x] New feature

## Description

add signature to outgoing webhooks

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

I tested this change manually

Out going webhook to merchant
<img width="1385" alt="Screenshot 2023-05-24 at 11 57 38 AM" src="https://github.com/juspay/hyperswitch/assets/83439957/dc1e2244-8ed9-4089-8e9b-2224bcfd5cf7">

signature verification
<img width="860" alt="Screenshot 2023-05-24 at 11 58 32 AM" src="https://github.com/juspay/hyperswitch/assets/83439957/a0858b45-3853-4ed3-8cdd-b09e20f831bd">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-24 14:49 UTC, Narayanbhat166 submitted a review, later dismissed

2023-05-24 17:22 UTC, SanchithHegde commented on crates/router/src/lib.rs
> +    pub const X_WEBHOOOK_SIGNATURE: &str = "X-Webhook-Signature";
There's a typo:

```suggestion
    pub const X_WEBHOOK_SIGNATURE: &str = "X-Webhook-Signature";
```

2023-05-24 17:36 UTC, SanchithHegde approved these changes

2023-05-24 18:16 UTC, Narayanbhat166 approved these changes

2023-05-29 05:38 UTC, jarnura requested changes
Add more details about this commit, in the description.

2023-05-29 06:04 UTC, vspecky requested changes

2023-05-29 06:04 UTC, vspecky commented on crates/router/src/core/webhooks.rs
> +            .change_context(errors::WebhooksFlowError::MerchantConfigNotFound)
Signing failure is not a `MerchantConfigNotFound` error. Create a new error variant for this case in `WebhooksFlowError`.

2023-05-29 09:25 UTC, vspecky approved these changes

2023-05-29 09:31 UTC, jarnura approved these changes

2023-05-29 10:02 UTC, Narayanbhat166 approved these changes

2023-05-29 11:20 UTC, merged