chore(openapi): Update Schema for Bank Transfers and address issues in generated.json
juspay/hyperswitch pull request #1271
Opened 2023-05-25 10:58 UTC by pixincreate

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

The PR aims at updating `openapi.rs` that missed Bank Transfer related changes. Also, added Schema and docs for Bank Transfers as well. This addressed issues with `generated.json`.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Schema was outdated and there was a need to update it as a part to address assertions failure.

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-29 05:41 UTC, jarnura requested changes
Attach sub-issue, milestone and project details.

2023-05-29 08:29 UTC, jarnura approved these changes

2023-05-29 10:38 UTC, Sangamesh26 submitted a review, later dismissed

2023-05-30 07:04 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>          country: api_enums::CountryAlpha2,
This is not an optional field

2023-05-30 08:52 UTC, Sangamesh26 approved these changes

2023-05-31 08:07 UTC, Narayanbhat166 submitted a review, later dismissed

2023-06-01 11:44 UTC, SanchithHegde approved these changes

2023-06-01 12:35 UTC, Narayanbhat166 approved these changes

2023-06-05 05:22 UTC, Sangamesh26 submitted a review, later dismissed

2023-06-05 07:34 UTC, Narayanbhat166 submitted a review, later dismissed

2023-06-05 07:43 UTC, SanchithHegde submitted a review, later dismissed

2023-06-07 20:57 UTC, SanchithHegde approved these changes

2023-06-08 09:42 UTC, closed without merging

2023-06-08 09:44 UTC, pixincreate commented
The commits were already cherry picked by @kritikmodi and were merged to main in the PR #1323