fix: required customer id and email error if not passed in confirm request
juspay/hyperswitch pull request #1273
Opened 2023-05-25 11:28 UTC by Sangamesh26

## Type of Change

- [x] Bugfix

## Description

We used to receive a missing required field error if the customer_id or email_id is not given in the confirm request.The reasoning for this is that if the customer_id and email were not sent with the request, we would not be able to confirm.Therefore, this issue was resolved by getting it from the database or, if present, the request.

## Motivation and Context

Fix missing required field error

## How did you test it?

![Screen Shot 2023-05-25 at 4 44 21 PM](https://github.com/juspay/hyperswitch/assets/59434228/68efb91b-5062-4a2a-8c70-c04475cb29c4)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-05-25 11:28 UTC, dracarys18 approved these changes

2023-05-25 11:41 UTC, hrithikesh026 approved these changes
LGTM

2023-05-29 03:10 UTC, Narayanbhat166 requested changes
Can you please check if this also fixes the `Required missing field customer_id` error when confirming a mandate payment?

2023-06-05 05:39 UTC, Sangamesh26 commented
closing this PR, as #1317 will solve this problem

2023-06-05 05:39 UTC, closed without merging