feat  :Added the merchant_name field in the response body
juspay/hyperswitch pull request #1280
Opened 2023-05-26 05:41 UTC by Aprabhat19

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Made some changes in the `core/payment_methods/cards.rs` and added a field of merchant_name to the response body of the List of Payment Methods

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
I tested it manually.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-29 03:06 UTC, Narayanbhat166 requested changes
Please follow the commit message conventions https://www.conventionalcommits.org/en/v1.0.0/

You can install [cocogito](https://github.com/cocogitto/cocogitto) and run the command
```shell
# Argument is the PR title
cog verify "feat:Added the merchant_name field in the response body" 
```

To know what needs to be changed in the PR title.

2023-05-29 21:18 UTC, SanchithHegde approved these changes

2023-05-30 05:35 UTC, Narayanbhat166 approved these changes

2023-05-30 05:41 UTC, Narayanbhat166 commented
Add a screenshot in the PR description as to what visible changes are in this PR

2023-06-03 16:38 UTC, SanchithHegde submitted a review, later dismissed

2023-06-05 06:09 UTC, Narayanbhat166 commented on crates/api_models/src/payment_methods.rs
> +    pub merchant_name: Option<Encryptable<masking::Secret<String>>>,
you can use this type alias 
https://github.com/juspay/hyperswitch/blob/6f1a1a3bcb7466738b018a773a5fe4adc5cf2887/crates/common_utils/src/crypto.rs#L444

2023-06-05 10:53 UTC, SanchithHegde commented on crates/api_models/src/payment_methods.rs
> +    pub merchant_name: OptionalEncryptableName,
The schema information and documentation comments annotated to this field are that of the `payment_methods` field. Could you please fix that, and add schema information and doc comments for the `merchant_name` field?

2023-06-06 05:25 UTC, Narayanbhat166 approved these changes

2023-06-06 07:18 UTC, SanchithHegde submitted a review, later dismissed

2023-06-28 11:25 UTC, Narayanbhat166 submitted a review, later dismissed

2023-07-01 11:09 UTC, SanchithHegde approved these changes

2023-07-01 11:10 UTC, SanchithHegde commented
Going ahead and merging this, only the OpenAPI spec had to be updated in the recent conflict resolution.

2023-07-01 11:10 UTC, merged