test(connector): Add tests for Paypal, Adyen and Airwallex
juspay/hyperswitch pull request #1290
Opened 2023-05-29 06:30 UTC by prasunna09

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR contains
1)ui tests for paypal(Paypal wallet)
2)ui tests for airwallex(3Ds)
3)ui tests for adyen(3Ds)

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

<img width="709" alt="Screenshot 2023-05-26 at 2 24 37 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/95b3f222-8747-4c28-ac17-646046a6c262">

<img width="666" alt="Screenshot 2023-05-26 at 12 34 38 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/39580dd8-8d5b-453b-a40d-e5ad9207f293">

<img width="709" alt="Screenshot 2023-05-26 at 6 43 47 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/db580d7f-4a52-487d-8f2b-20ec121e6af3">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-30 06:00 UTC, jagan-jaya requested changes

2023-05-30 06:00 UTC, jagan-jaya commented on crates/router/tests/connectors/airwallex_ui.rs
> +            Event::Trigger(Trigger::Goto(&format!("{CHEKOUT_BASE_URL}/card?cname=CL-BRW1&ccnum=4012000300000088&expmonth=10&expyear=2025&cvv=123&amount=2000&country=US&currency=GBP"))),
why is it not added as testcase?

2023-05-30 06:00 UTC, jagan-jaya commented on crates/router/tests/connectors/authorizedotnet_ui.rs
> +            Event::Trigger(Trigger::Goto(&format!("{CHEKOUT_BASE_URL}/card?cname=CL-BRW1&ccnum=4000027891380961&expmonth=10&expyear=25&cvv=123&amount=200&country=US&currency=USD&setup_future_usage=of
why is it not added as testcase?

2023-06-29 06:43 UTC, jagan-jaya approved these changes

2023-06-29 07:14 UTC, ArjunKarthik approved these changes

2023-06-29 07:37 UTC, SanchithHegde approved these changes

2023-06-30 05:33 UTC, merged