feat(connector) : add template code for connector Opayo
juspay/hyperswitch pull request #1295
Opened 2023-05-29 09:23 UTC by prasunna09

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add the template code generated by script for [Opayo](https://pi-test.sagepay.com/api/v1/) with test base url.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-29 09:37 UTC, srujanchikke commented on crates/router/tests/connectors/sample_auth.toml
> +
Please remove this newline.

2023-05-29 10:23 UTC, srujanchikke submitted a review, later dismissed

2023-05-31 04:57 UTC, ArjunKarthik requested changes

2023-05-31 04:57 UTC, ArjunKarthik commented on crates/router/src/connector/opayo.rs
> +        .change_context(errors::ConnectorError::ResponseHandlingFailed)
change context is not required. If it is added in the template code can we remove there as well?

2023-05-31 04:57 UTC, ArjunKarthik commented on crates/router/src/connector/opayo.rs
> +        .change_context(errors::ConnectorError::ResponseHandlingFailed)
same here

2023-05-31 04:57 UTC, ArjunKarthik commented on crates/router/src/connector/opayo.rs
> +        .change_context(errors::ConnectorError::ResponseHandlingFailed)
same here

2023-05-31 04:57 UTC, ArjunKarthik commented on crates/router/src/connector/opayo.rs
> +        .change_context(errors::ConnectorError::ResponseHandlingFailed)
here also

2023-05-31 04:57 UTC, ArjunKarthik commented on crates/router/src/connector/opayo.rs
> +        .change_context(errors::ConnectorError::ResponseHandlingFailed)
.

2023-05-31 08:59 UTC, ArjunKarthik approved these changes

2023-06-08 13:07 UTC, jagan-jaya approved these changes

2023-06-19 05:15 UTC, jagan-jaya approved these changes

2023-06-19 06:34 UTC, ArjunKarthik submitted a review, later dismissed

2023-06-28 11:22 UTC, ArjunKarthik approved these changes

2023-06-28 11:32 UTC, srujanchikke approved these changes

2023-06-28 12:46 UTC, ArjunKarthik submitted a review, later dismissed

2023-06-28 13:28 UTC, ArjunKarthik approved these changes

2023-06-28 13:29 UTC, srujanchikke submitted a review, later dismissed

2023-06-28 13:29 UTC, SamraatBansal submitted a review, later dismissed

2023-06-28 14:05 UTC, Narayanbhat166 approved these changes

2023-06-28 17:44 UTC, SanchithHegde commented on crates/router/src/connector/opayo/transformers.rs
> +    pub(super) api_key: String,
Would prefer if this was `Secret`.

2023-06-28 19:39 UTC, SanchithHegde commented on crates/router/src/connector/opayo.rs
> +            auth.api_key.peek().to_string().into_masked(),
Can you use `expose()` instead?

```suggestion
            auth.api_key.expose().into_masked(),
```

You'll have to import `ExposeInterface` by the way.

2023-06-29 06:34 UTC, srujanchikke approved these changes

2023-06-29 06:44 UTC, jagan-jaya approved these changes

2023-06-29 07:16 UTC, ArjunKarthik approved these changes

2023-06-29 07:38 UTC, SanchithHegde approved these changes

2023-06-30 05:21 UTC, merged