feat(connector): [Airwallex] Implement Google Pay in Wallets
juspay/hyperswitch pull request #1316
Opened 2023-05-30 07:39 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Google pay is not available as a payment method in Airwallex so I added it.

## How did you test it?
![6D4EFE06-072F-4DD0-95D0-443FC53CC61D_4_5005_c](https://github.com/juspay/hyperswitch/assets/73734619/616fb865-6502-4679-8ef5-fd17609458a7)
<img width="1728" alt="Screen Shot 2023-05-30 at 12 37 27 PM" src="https://github.com/juspay/hyperswitch/assets/73734619/d17b69c4-7593-4819-a2a7-d6eb8f0b1cc1">
<img width="1728" alt="Screen Shot 2023-05-30 at 12 37 37 PM" src="https://github.com/juspay/hyperswitch/assets/73734619/28f1670c-4891-42ef-89ba-261b66a5844c">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-31 06:45 UTC, srujanchikke requested changes

2023-05-31 06:45 UTC, srujanchikke commented on crates/router/src/connector/airwallex/transformers.rs
> +                                payment_data_type: "encrypted_payment_token".to_string(), // airwallex gpay only accecpt encrypted_payment_token form of payment
Why this is hardcoded ? make it as an enum

2023-05-31 06:45 UTC, srujanchikke commented on crates/router/src/connector/airwallex/transformers.rs
> +#[derive(Debug, Serialize, Eq, PartialEq)]
Do we need Eq, PartialEq ? If not , please remove it at other places as well

2023-05-31 06:45 UTC, srujanchikke commented on crates/router/src/connector/airwallex/transformers.rs
> +                let wallet_details: AirwallexPaymentMethod = match wallet_data {
Move this logic to separate function something as get_wallet_data()

2023-05-31 06:45 UTC, srujanchikke commented on crates/router/tests/connectors/airwallex_ui.rs
> +            Event::Trigger(Trigger::Goto(&format!("{CHEKOUT_BASE_URL}/saved/89"))),
Don't use saved/{id} for gpay payment , it will expire after certain time . Instead pass  gateway_name and gateway_merchant_id in url

2023-05-31 06:45 UTC, srujanchikke commented on crates/router/src/connector/airwallex/transformers.rs
> +#[derive(Debug, Serialize, Eq, PartialEq)]
same here

2023-05-31 06:45 UTC, srujanchikke commented on crates/router/src/connector/airwallex/transformers.rs
> +#[derive(Debug, Serialize, Eq, PartialEq)]
same here

2023-06-02 06:44 UTC, srujanchikke submitted a review, later dismissed

2023-06-26 07:15 UTC, jagan-jaya submitted a review, later dismissed

2023-06-28 20:08 UTC, SanchithHegde approved these changes

2023-07-02 14:39 UTC, SanchithHegde commented on crates/router/tests/connectors/airwallex_ui.rs
> +async fn should_make_airwallex_gpay_payment(c: WebDriver) -> Result<(), WebDriverError> {
Please avoid using single character variable names.

2023-07-02 14:51 UTC, Sakilmostak commented on crates/router/tests/connectors/airwallex_ui.rs
> +async fn should_make_airwallex_gpay_payment(c: WebDriver) -> Result<(), WebDriverError> {
Done👍

2023-07-02 14:57 UTC, SanchithHegde approved these changes

2023-07-03 05:24 UTC, ArjunKarthik approved these changes

2023-07-03 06:00 UTC, jagan-jaya approved these changes

2023-07-03 06:25 UTC, merged