feat(headers): add optional header masking feature to outbound request
juspay/hyperswitch pull request #1320
Opened 2023-05-30 21:13 UTC by NishantJoshi00

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This is an enhanced implementation of optional masking of headers for the outgoing requests (focused mainly on connectors).
This introduces a new type, the allows optional masking on the data that it holds. This type in itself is a enum, that has 2 possible values, `Masked` and `Normal`. `new_masked` method is used, then a masked value is created. Use of `Into::into` will always create a `Normal` value. This allows ease, of use while still allowing use to provide the feature to mask certain fields.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Hiding sensitive data from logging framework.

## How did you test it?

Compiler guided & 
Following are the before and after results of this sanitization:
> Before:
<img width="1728" alt="Screenshot 2023-05-31 at 2 39 44 AM" src="https://github.com/juspay/hyperswitch/assets/51093026/3191eb86-b515-454d-ba60-110febfee834">

> After:
<img width="1728" alt="Screenshot 2023-05-31 at 2 32 20 AM" src="https://github.com/juspay/hyperswitch/assets/51093026/d3991e96-629c-4871-b206-5789112957c1">

> (PS. The API key that is visible in the before test is not a real key, but generated by an RNG)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-31 06:58 UTC, dracarys18 requested changes

2023-05-31 06:58 UTC, dracarys18 commented on crates/router/src/connector/aci.rs
> +    ) -> CustomResult<Vec<(String, request::OptionalMaskedValue<String>)>, errors::ConnectorError>
Convert this to a new type maybe use `Headers` type that's already there?

2023-05-31 06:58 UTC, dracarys18 commented on crates/router/src/connector/aci.rs
> +        )])
Can you create a  trait that will do this with `into_masked`

2023-05-31 06:58 UTC, dracarys18 commented on crates/router/src/services/api/request.rs
> +pub enum OptionalMaskedValue<T: Eq + PartialEq + Clone> {
Probably change into `Maskable`

2023-05-31 10:24 UTC, dracarys18 approved these changes
LGTM

2023-06-03 09:21 UTC, SanchithHegde reviewed
Other than that, looks good to me!

2023-06-05 06:37 UTC, NishantJoshi00 commented on crates/router/src/connector/nmi.rs
Yes please, these changes might vary across various structs and transformers throughout the connectors.

2023-06-05 06:39 UTC, NishantJoshi00 commented on crates/router/src/connector/nmi.rs
https://github.com/juspay/hyperswitch/issues/1348

2023-06-05 06:40 UTC, NishantJoshi00 commented on crates/router/src/connector/authorizedotnet.rs
>          // This connector does not require an auth header, the authentication details are sent in the request body
#1348

2023-06-05 06:41 UTC, NishantJoshi00 commented on crates/router/src/connector/airwallex.rs
> +            ("x-client-id".to_string(), req.get_request_id()?.into()),
I agree, doing the change now!

2023-06-05 07:32 UTC, SanchithHegde approved these changes

2023-06-05 07:40 UTC, ashokkjag approved these changes

2023-06-05 08:14 UTC, merged