fix(encryption): do not log encrypted binary data
juspay/hyperswitch pull request #1352
Opened 2023-06-05 18:01 UTC by dracarys18

## Type of Change

- [x] Enhancement

## Description

Add secret to encrypted fields so it wont be logged. It will be logged as `*** Encrypted ***`.

## Motivation and Context

Dont log huge encrypted binary data.

## How did you test it?

<img width="1728" alt="image" src="https://github.com/juspay/hyperswitch/assets/43412619/6ad76057-16fd-4d98-8f57-3e8a4a38a592">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-06-05 18:06 UTC, SanchithHegde approved these changes

2023-06-05 18:10 UTC, SanchithHegde submitted a review, later dismissed

2023-06-06 07:27 UTC, NishantJoshi00 requested changes

2023-06-06 07:27 UTC, NishantJoshi00 commented on crates/router/src/types/domain/types.rs
> +        let data = crypt_algo.decode_message(key, encrypted.clone().expose())?;
don't expose if possible pass the secret directly. If need be you can take it up in a separate PR

2023-06-06 07:27 UTC, NishantJoshi00 commented on crates/router/src/types/domain/types.rs
> +        let data = crypt_algo.decode_message(key, encrypted.clone().expose())?;
same here

2023-06-06 09:28 UTC, NishantJoshi00 approved these changes

2023-06-06 11:40 UTC, SanchithHegde approved these changes

2023-06-21 09:32 UTC, merged