chore(process_tracker): attempt to identify unnecessary 5xx in process_tracker
juspay/hyperswitch pull request #1359
Opened 2023-06-06 11:17 UTC by Abhicodes-crypto

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR address possible unintended 5xx raised in process tracker flows. If not found 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

compiles

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-06 12:53 UTC, NishantJoshi00 reviewed
Other than that, looks good to me

2023-06-06 12:53 UTC, NishantJoshi00 commented on crates/router/src/core/refunds.rs
> +        .insert_process(process_tracker_entry) // if the process already exists in process tracker, i.e if it is is_db_unique_voilation should the error be ignored, this already happens in save cards
please resolve the issue raised by `Github action`

2023-06-06 12:53 UTC, NishantJoshi00 reviewed
Other than that, looks good to me

2023-06-09 09:53 UTC, jarnura approved these changes

2023-06-09 09:53 UTC, jarnura commented on crates/router/src/core/refunds.rs
> +            runner, task, refund.merchant_id, refund.refund_id
Change this to InternalRequestId

2023-06-09 09:53 UTC, jarnura requested changes

2023-06-09 09:53 UTC, jarnura commented on crates/router/src/core/refunds.rs
> +            runner, task, refund.merchant_id, refund.refund_id
Change this to InternalRequestId

2023-06-13 08:25 UTC, jarnura approved these changes

2023-06-16 07:13 UTC, NishantJoshi00 approved these changes

2023-06-16 16:11 UTC, merged