feat: add bank payout test case templates and implementation for Adye…
juspay/hyperswitch pull request #1366
Opened 2023-06-06 14:23 UTC by kashif-m

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-09 05:55 UTC, jagan-jaya commented
Please attach the screenshot of the tests you ran in `how did you test?` section

2023-06-09 12:34 UTC, jagan-jaya requested changes

2023-06-09 12:34 UTC, jagan-jaya commented on connector-template/test.rs
> +        .fulfill_card_payout(payment_info)
```suggestion
        .fulfill_payout(payment_info)
```

2023-06-09 12:34 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen.rs
> +    let mut payment_info = AdyenTest::get_payment_info();
add all your default data for payout within get_payout_info and use it in all other places below
```suggestion
    let mut payout_info = AdyenTest::get_payout_info();
```

2023-06-09 12:34 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen.rs
> +    payment_info = payment_info.map(|mut pi| {
add all your default data for payout within get_payout_info and use it in all other places below
```suggestion
    let mut payout_info = AdyenTest::get_payout_info();
```

2023-06-09 12:34 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen.rs
> +    let mut payment_info = AdyenTest::get_payment_info();
add all your default data for payout within get_payout_info and use it in all other places below
```suggestion
    let mut payout_info = AdyenTest::get_payout_info();
```

2023-06-09 12:34 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen.rs
> +    let mut payment_info: Option<PaymentInfo> = AdyenTest::get_payment_info();
add all your default data for payout within get_payout_info and use it in all other places below
```suggestion
    let mut payout_info = AdyenTest::get_payout_info();
```

2023-06-09 12:34 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen.rs
> +    let mut payment_info = AdyenTest::get_payment_info();
add all your default data for payout within get_payout_info and use it
```suggestion
    let mut payout_info = AdyenTest::get_payout_info();
```

2023-06-09 12:34 UTC, jagan-jaya commented on crates/router/tests/connectors/wise.rs
> +    let mut payment_info = WiseTest::get_payment_info();
add all your default data for payout within get_payout_info and use it in all other places below
```suggestion
    let mut payout_info = WiseTest::get_payout_info();
```

2023-06-09 12:34 UTC, jagan-jaya commented on crates/router/tests/connectors/wise.rs
> +    let mut payment_info = WiseTest::get_payment_info();
add all your default data for payout within get_payout_info and use it in all other places below
```suggestion
    let mut payout_info = WiseTest::get_payout_info();
```

2023-06-09 12:34 UTC, jagan-jaya commented on crates/router/tests/connectors/wise.rs
> +    let mut payment_info = WiseTest::get_payment_info();
add all your default data for payout within get_payout_info and use it in all other places below
```suggestion
    let mut payout_info = WiseTest::get_payout_info();
```

2023-06-09 12:35 UTC, jagan-jaya commented
@kashif-m Good job on the tests, Nicely done 👍

2023-06-26 07:19 UTC, jagan-jaya approved these changes

2023-07-04 06:21 UTC, jarnura approved these changes

2023-07-04 06:21 UTC, merged