feat(payment): customer ip field inclusion
juspay/hyperswitch pull request #1370
Opened 2023-06-06 15:42 UTC by prajjwalkumar17

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Addition of customer_ip field to be taken from either x-forwarded-for or from request itself.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Will help Sdk team for minimizing latency as currently they are using 3rd party service for requesting the Ip addr.

## How did you test it?
Tested it manually

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-07 07:32 UTC, Narayanbhat166 requested changes

2023-06-07 07:32 UTC, Narayanbhat166 commented on crates/router/src/routes/payments.rs
> +            .get("x-forwarded-for")
add this string literal to `headers`.
https://github.com/juspay/hyperswitch/blob/6f1a1a3bcb7466738b018a773a5fe4adc5cf2887/crates/router/src/lib.rs#L47

2023-06-07 07:32 UTC, Narayanbhat166 commented on crates/router/src/routes/payments.rs
> +            .and_then(|val| val.to_str().ok().and_then(|ip| ip.split(',').next()))
Add the comments as to what this transformation does. Provide the original ip address format and the transformed one after running this logic

2023-06-08 12:32 UTC, vspecky commented on crates/api_models/src/payments.rs
> +    pub customer_ip: Option<Secret<String, pii::IpAddress>>,
Removed. We will make use of `BrowserInformation.ip_address`

2023-06-08 14:06 UTC, jarnura approved these changes

2023-06-09 06:13 UTC, vspecky approved these changes

2023-06-09 06:36 UTC, Narayanbhat166 requested changes

2023-06-09 06:36 UTC, Narayanbhat166 commented on crates/router/src/connector/adyen/transformers.rs
> +                        .get_required_value("accept_header")
you can use this function with `.ok_or_else()`
https://github.com/juspay/hyperswitch/blob/0575b26b4fc229e92aef179146dfd561a9ee7f27/crates/router/src/connector/utils.rs#L24

2023-06-09 06:36 UTC, Narayanbhat166 commented on crates/router/src/connector/adyen/transformers.rs
> +                        .clone()
are these clones necessary?

2023-06-09 06:36 UTC, Narayanbhat166 commented on crates/router/src/routes/payments.rs
> +    }
Why should we fail this request if ip address population fails?

2023-06-09 06:36 UTC, Narayanbhat166 commented on crates/router/src/connector/zen/transformers.rs
> +            })?
Are all these fields really mandatory? can you check the api documentation and confirm this?

2023-06-09 06:42 UTC, Narayanbhat166 approved these changes
The comments will be addressed in #1398

2023-06-09 07:00 UTC, merged