refactor(fix): [Adyen] Fix bug in Adyen
juspay/hyperswitch pull request #1375
Opened 2023-06-07 06:40 UTC by swangi-kumari

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Fixed bug:
1. Added support for 2 digits expiry year. (earlier it was accepting only 4digit exp year.)
2. In card 3DS, additional browser_info support was added as it was mandatory field for getting url. 
3. Fixed Card Mandates for multi use mandate type. (for multiple payments from merchant side)
4. Fixed webhooks source verification.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
Using Postman 

2 digit support is working now
<img width="1728" alt="Screen Shot 2023-06-15 at 12 51 44 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/1d30dd1b-9e39-4397-9c54-5ecd5c0971f0">

if we don't provide browser_info it will give proper error
<img width="1728" alt="Screen Shot 2023-06-15 at 2 24 58 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/2294333d-dc8c-4ffb-bda9-5c98ce344096">

webhooks
![Screen Shot 2023-06-15 at 12 51 44 PM (2)](https://github.com/juspay/hyperswitch/assets/85639103/aeda1e89-5792-44e9-b74c-c5d6a8145158)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-13 07:39 UTC, jagan-jaya submitted a review, later dismissed

2023-06-13 14:20 UTC, Sangamesh26 approved these changes
LGTM :)

2023-06-14 11:46 UTC, jagan-jaya requested changes

2023-06-15 06:40 UTC, jagan-jaya submitted a review, later dismissed

2023-06-15 07:40 UTC, jagan-jaya approved these changes

2023-06-15 08:03 UTC, Sangamesh26 commented
@swangi-kumari  please attach the screen shot of the response.

2023-06-16 14:41 UTC, ArjunKarthik approved these changes

2023-06-16 14:44 UTC, jarnura approved these changes

2023-06-16 15:06 UTC, merged