feat: fetch merchant key store only once per session
juspay/hyperswitch pull request #1400
Opened 2023-06-09 07:07 UTC by dracarys18

## Type of Change

- [x] Enhancement

## Description

Fetch merchant key store only once in session whenever Merchant Account is created.

## Motivation and Context

This removes redundant calls for merchant key store database.

## How did you test it?

Did payments using API Key and merchant key store only fetched once during authentication

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-06-09 11:34 UTC, lsampras commented
What does a session mean in this context?

Is it a payment_intent (& all it's api calls), or is it just one API request?

2023-06-09 12:34 UTC, Narayanbhat166 commented on crates/common_utils/src/crypto.rs
> +    /// Get the inner data while consumping self
```suggestion
    /// Get the inner data while consuming self
```

2023-06-12 07:49 UTC, SanchithHegde commented on crates/router/src/core/admin.rs
> +use masking::{PeekInterface, Secret}; //PeekInterface
```suggestion
use masking::{PeekInterface, Secret};
```

Remove this comment.

2023-06-13 06:47 UTC, dracarys18 commented
> What does a session mean in this context?
> 
> Is it a payment_intent (& all it's api calls), or is it just one API request?

It's one API request

2023-06-20 10:41 UTC, Narayanbhat166 submitted a review, later dismissed

2023-06-21 07:33 UTC, SanchithHegde approved these changes

2023-06-21 12:47 UTC, SanchithHegde submitted a review, later dismissed

2023-06-21 12:47 UTC, Narayanbhat166 approved these changes

2023-06-21 14:07 UTC, jarnura requested changes

2023-06-21 14:42 UTC, SanchithHegde approved these changes

2023-06-21 14:50 UTC, Narayanbhat166 approved these changes

2023-06-22 08:47 UTC, jarnura approved these changes

2023-06-22 09:37 UTC, merged