Legacy to basilisk-hs data migration script and an api to test the script
juspay/hyperswitch pull request #1405
Opened 2023-06-09 13:18 UTC by inventvenkat

Legacy to basilisk-hs data migration script and an api to test the script
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD
- [x] Data Migration

## Description

Added a script to migrate data from legacy locker to basilisk-hs, which does the following
Step 1: Get all merchants
Step 2: Traverse through all the merchants and get all the payment_methods for each merchant
Step 3: Traverse through all the payment_methods 
Step 4: Call get card api of legacy_locker and call add card api of basilisk-hs 

And an api to test the script
Since we cannot test this script locally, as it needs legacy locker and basilisk to setup locally, 
Step 4 is exposed as an api to verify if that is working.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible
- [x] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-09 15:16 UTC, NishantJoshi00 requested changes

2023-06-10 13:51 UTC, inventvenkat commented on crates/router/src/routes/migrate_legacy_to_basilisk.rs
> +        .pop()
routes::migrate_legacy_to_basilisk method is just for testing the migration. I'll rename the function to make it clearer

2023-06-13 06:50 UTC, inventvenkat commented on crates/storage_models/src/query/merchant_account.rs
> +    }
I am removing this method and adding find_all_payment_methods, which has ~1000 records and gonna read it from read_replica

2023-06-13 07:16 UTC, inventvenkat commented on crates/router/src/bin/router.rs
> +        let store = Store::new(&conf, true, tx).await;
We cannot get store out of state, because it is inside dynamic dispatch

2023-06-17 19:46 UTC, SanchithHegde commented
Closing this as not planned.

2023-06-17 19:46 UTC, closed without merging