fix(core):Add validation for card expiry month, expiry year and card cvc
juspay/hyperswitch pull request #1416
Opened 2023-06-12 12:26 UTC by prasunna09

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Validation for Card data - Card expiry month, expiry year, cvc given in payment request for card flows.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

<img width="507" alt="Screen Shot 2023-06-11 at 8 16 55 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/6aed722e-b9fd-4f54-ba86-712258e45f91">
<img width="445" alt="Screen Shot 2023-06-11 at 8 18 04 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/3df1d764-9bce-40c8-a462-357cba761629">
<img width="445" alt="Screen Shot 2023-06-11 at 8 18 33 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/110492db-674d-449c-8a4b-57e6efcbec11">
<img width="445" alt="Screen Shot 2023-06-11 at 8 17 39 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/2f6782f2-352a-4de5-9249-10aa2f71a22e">
Card has expired - 
<img width="438" alt="Screen Shot 2023-06-12 at 4 05 28 PM" 
src="https://github.com/juspay/hyperswitch/assets/70575890/ed47287b-af77-444c-9fed-0d5b8815ffd4">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-12 13:23 UTC, jagan-jaya requested changes

2023-06-13 06:01 UTC, jagan-jaya approved these changes

2023-06-13 09:00 UTC, ArjunKarthik submitted a review, later dismissed

2023-06-13 10:01 UTC, SanchithHegde commented
Marking this as design pending: I'd prefer the newtypes being used in request-response types as mentioned in #1012 instead.

2023-06-13 14:31 UTC, Sangamesh26 requested changes

2023-06-13 14:31 UTC, Sangamesh26 commented on crates/router/src/core/payments/helpers.rs
> +use ::cards::{CardExpiration, CardExpirationMonth, CardExpirationYear, CardSecurityCode};
Remove specific imports

2023-06-15 11:06 UTC, jagan-jaya requested changes

2023-06-15 11:06 UTC, jagan-jaya commented on crates/router/src/core/payments/operations/payment_create.rs
> +        helpers::validate_card_data(request.payment_method_data.clone())?;
add it in payment_confirm also

2023-06-15 11:06 UTC, jagan-jaya commented on crates/router/src/core/payments/helpers.rs
> +        let expiry = card_expiration.is_expired().change_context(
```suggestion
        let is_expired = card_expiration.is_expired().change_context(
```

2023-06-15 11:06 UTC, jagan-jaya commented on crates/router/src/core/payments/helpers.rs
> +        if expiry {
```suggestion
        if is_expired {
```

2023-06-16 12:19 UTC, jagan-jaya approved these changes

2023-06-17 07:45 UTC, SanchithHegde commented on crates/router/src/core/payments/helpers.rs
> +use ::cards as Card;
Please avoid using such imports, this is against the Rust naming conventions and would cause confusion for developers reading this code.

2023-06-17 07:45 UTC, SanchithHegde commented on crates/router/src/core/payments/helpers.rs
> +        Card::CardSecurityCode::try_from(card_cvc).change_context(
For example, this makes you think that `Card::CardSecurityCode` is an enum variant, while it isn't.

2023-06-20 07:20 UTC, SanchithHegde approved these changes

2023-06-20 09:43 UTC, Sangamesh26 approved these changes

2023-06-20 10:38 UTC, merged