refactor(core): use secrets for connector AuthType in connector integration
juspay/hyperswitch pull request #1441
Opened 2023-06-14 14:47 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR addresses an issue related to handling sensitive data in the connector integration. Previously, the `api_key` field in `transformers.rs` was stored as a plain text string, which posed a security risk. This could potentially expose the API key to unauthorised access or compromise.

To mitigate this risk, the code has been refactored to utilize the `Secret` type for the `api_key` field. By doing so, the sensitive data will be stored securely, following best practices for handling secrets.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

<img width="1213" alt="Screenshot 2023-05-24 at 7 13 12 PM" src="https://github.com/juspay/hyperswitch/assets/83439957/e26a8f23-ab28-4b78-a269-82f90c4ed662">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-20 08:03 UTC, NishantJoshi00 requested changes

2023-06-26 05:46 UTC, NishantJoshi00 requested changes
Please resolve the conflicts, and after the changes mentioned have you ran connector test cases, if not please run them

Other than that, looks good!

2023-06-27 08:48 UTC, NishantJoshi00 submitted a review, later dismissed

2023-06-28 07:26 UTC, Narayanbhat166 commented on crates/router/src/connector/zen.rs
> +            format!("Bearer {}", masking::ExposeInterface::expose(auth.api_key)).into_masked(),
can `.expose()` be used here?

2023-06-28 11:54 UTC, SanchithHegde approved these changes

2023-06-28 13:33 UTC, NishantJoshi00 submitted a review, later dismissed

2023-06-29 05:49 UTC, ArjunKarthik requested changes
@ShankarSinghC Connector code seems fine, but still ConnectorAuthType has api_keys and other fields in it as plain String. Why can't we make those fields also secrets, so that no where in the code connector credentials can be accessed as plain string?

2023-07-07 10:30 UTC, SanchithHegde reviewed
Other than that, looks good to me!

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/airwallex.rs
> +            format!("Bearer {}", access_token.token.expose()).into_masked(),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/bambora/transformers.rs
> +            let auth_key = format!("{}:{}", key1.clone().expose(), api_key.clone().expose());
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/braintree.rs
> +            auth_type.merchant_id.expose(),
You should be able to use `peek()` here and elsewhere in this file.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/braintree/transformers.rs
> +            );
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/cashtocode.rs
> +                    format!("Basic {}", key1.to_owned().expose()).into_masked(),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/dlocal.rs
> +            auth.secret.expose().as_bytes(),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/forte.rs
> +        );
You should be able to use `peek()` here and elsewhere in this file.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/forte/transformers.rs
> +                location_id: Secret::new(format!("org_{}", key2.to_owned().expose())),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/globalpay.rs
> +                format!("Bearer {}", access_token.token.expose()).into_masked(),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/globalpay/transformers.rs
> +        let nonce_with_api_key = format!("{}{}", nonce, globalpay_auth.key.expose());
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/iatapay.rs
> +            format!("Bearer {}", access_token.token.expose()).into_masked(),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/payu.rs
> +            format!("Bearer {}", access_token.token.expose()).into_masked(),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/rapyd.rs
> +        );
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/rapyd.rs
> +        let key = hmac::Key::new(hmac::HMAC_SHA256, secret_key.expose().as_bytes());
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/src/connector/worldpay/transformers.rs
> +                );
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/tests/connectors/airwallex.rs
> +            expires: key1.expose().parse::<i64>().unwrap(),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/tests/connectors/payu.rs
> +            expires: key1.expose().parse::<i64>().unwrap(),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/tests/integration_demo.rs
> +            &authentication.checkout.unwrap().api_key.expose(),
You should be able to use `peek()` here.

2023-07-07 10:30 UTC, SanchithHegde commented on crates/router/tests/integration_demo.rs
> +            &authentication.checkout.unwrap().api_key.expose(),
You should be able to use `peek()` here.

2023-07-09 17:03 UTC, SanchithHegde commented
Please address the failing CI checks. Other than that, looks good to me!

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/braintree.rs
Use `peek()` instead of `expose()` here.

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/braintree/transformers.rs
> +                private_key.to_owned().peek()
You don't need the clones (`to_owned()`) either.

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/cashtocode.rs
> +                    format!("Basic {}", key1.to_owned().peek()).into_masked(),
You don't need the clone.

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/forte.rs
Use `peek()` instead of `expose()`.

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/forte/transformers.rs
> +                location_id: Secret::new(format!("org_{}", key2.to_owned().peek())),
You can get rid of the clones.

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/nexinets/transformers.rs
> +                let auth_key = format!("{}:{}", key1.to_owned().peek(), api_key.to_owned().peek());
You can get rid of the clones.

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/rapyd.rs
> +            secret_key.to_owned().peek()
You can get rid of the clones.

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/rapyd.rs
> +        let key = hmac::Key::new(hmac::HMAC_SHA256, secret_key.to_owned().expose().as_bytes());
You can get rid of the clone and `expose()`.

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/worldpay/transformers.rs
> +                let auth_key = format!("{}:{}", key1.to_owned().peek(), api_key.to_owned().peek());
You can get rid of the clones.

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/tests/connectors/connector_auth.rs
Why is this file being added again?

2023-07-11 09:23 UTC, SanchithHegde commented on crates/router/src/connector/bambora/transformers.rs
> +            let auth_key = format!("{}:{}", key1.clone().peek(), api_key.clone().peek());
You can get rid of the clones.

2023-07-12 07:06 UTC, SanchithHegde approved these changes

2023-07-12 13:13 UTC, ArjunKarthik commented on crates/router/src/connector/stripe.rs
> +            format!("Bearer {}", auth.api_key.expose()).into_masked(),
Use peek()

2023-07-12 13:15 UTC, ArjunKarthik commented on crates/router/src/connector/worldline.rs
> +        Ok(format!("GCS v1HMAC:{}:{signed_data}", api_key.expose()))
Use peek()

2023-07-12 13:15 UTC, ArjunKarthik commented on crates/router/src/connector/zen.rs
> +            format!("Bearer {}", auth.api_key.expose()).into_masked(),
Use peek()

2023-07-16 12:24 UTC, Narayanbhat166 submitted a review, later dismissed

2023-07-16 12:40 UTC, SanchithHegde submitted a review, later dismissed

2023-07-17 07:13 UTC, SanchithHegde submitted a review, later dismissed

2023-07-17 08:06 UTC, ashokkjag commented on crates/router/src/connector/aci.rs
> +            auth.entity_id.peek()
@SanchithHegde , since we're moving to secret, should the value be made available in (error) logs?

2023-07-17 08:06 UTC, ashokkjag commented on crates/router/src/connector/multisafepay.rs
> +            .api_key
should `secrets` be exposed in logs

2023-07-17 08:06 UTC, ashokkjag commented on crates/router/src/connector/multisafepay.rs
> +            .api_key
should `secrets` be exposed in logs

2023-07-17 13:06 UTC, Narayanbhat166 approved these changes

2023-07-18 08:29 UTC, ashokkjag submitted a review, later dismissed

2023-07-18 08:38 UTC, SanchithHegde submitted a review, later dismissed

2023-07-18 09:12 UTC, ArjunKarthik approved these changes

2023-07-24 09:41 UTC, SanchithHegde approved these changes

2023-07-24 14:46 UTC, ArjunKarthik submitted a review, later dismissed

2023-07-24 14:56 UTC, SanchithHegde submitted a review, later dismissed

2023-07-26 11:28 UTC, SanchithHegde approved these changes

2023-07-26 11:33 UTC, ArjunKarthik approved these changes

2023-07-26 12:11 UTC, merged