feat(connector): [Noon] add error response handling in payments response
juspay/hyperswitch pull request #1494
Opened 2023-06-21 11:01 UTC by SamraatBansal

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

In `PaymentsResponse` Handling if `error_message` is received from the connector, We have to populate it in `PaymentsData`.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Error_message and code needs to be populated in response so that it can be appropriately categorized  in the dashboard.

## How did you test it?

<img width="1274" alt="Screen Shot 2023-06-21 at 4 28 20 PM" src="https://github.com/juspay/hyperswitch/assets/55536657/d758d732-e27c-4273-97c3-3e7c2fe76296">

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-21 13:06 UTC, jagan-jaya requested changes

2023-06-21 13:06 UTC, jagan-jaya commented on crates/router/src/connector/noon/transformers.rs
>          Ok(Self {
```suggestion
        let order = item.response.result.order;
        Ok(Self {
```

2023-06-21 13:06 UTC, jagan-jaya commented on crates/router/src/connector/noon/transformers.rs
> +                    ),
```suggestion
            response: match order.error_message {
                Some(error_message) => Err(ErrorResponse {
                    code: order.error_code.to_string(),
                    message: error_message.clone(),
                    reason: Some(error_message),
                    status_code: item.http_code,
                }),
                _ => Ok(types::PaymentsResponseData::TransactionResponse {
                    resource_id: types::ResponseId::ConnectorTransactionId(
                        order.id.to_string(),
                    ),
```

2023-06-27 08:50 UTC, ArjunKarthik approved these changes

2023-06-27 08:56 UTC, jagan-jaya approved these changes

2023-06-28 09:33 UTC, merged