feat(connector): [trustpay] add google pay support
juspay/hyperswitch pull request #1515
Opened 2023-06-22 13:20 UTC by Sangamesh26

## Type of Change

- [x] New feature

## Description

Add support for Google pay through Trustpay
The steps it follows:
1. Session call:
Here, the response for google pay session is an object without session object and has only connector name, delayed session token and next action information.

<img width="1259" alt="Screen Shot 2023-06-22 at 2 14 17 PM" src="https://github.com/juspay/hyperswitch/assets/59434228/a8b11f8e-445f-4c81-80f6-001d69697759">

2. Confirm call:
Here, we follow pre processing steps to hit trustpay and get secrets and google pay object that sdk needs for further sdk calls. These information are displayed in next_action.

<img width="1245" alt="Screen Shot 2023-06-22 at 6 28 42 PM" src="https://github.com/juspay/hyperswitch/assets/59434228/5317bcf7-e645-4a2e-bd37-4674fd828e60">

3. Retrieve call:
As payment ends in sdk side itself, our system should store the payment status, so to get the payment related details, sync call is done.

<img width="1249" alt="Screen Shot 2023-06-22 at 6 29 33 PM" src="https://github.com/juspay/hyperswitch/assets/59434228/13fbb46a-d00b-4fd9-a991-60db3654bd39">

API contract for confirm call :
```
{
    "confirm": true,
    "payment_method": "wallet",
    "payment_method_type": "google_pay",
    "payment_method_data": {
        "wallet": {
            "google_pay_third_party_sdk": {}
        }
    }
}
```

### Additional Changes

- [x] This PR modifies the API contract

## Motivation and Context

Add support for Google Pay through trustpay

## How did you test it?

Manual
Please refer the  attached screenshots in description

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-06-23 09:27 UTC, ArjunKarthik approved these changes

2023-06-24 11:38 UTC, SanchithHegde commented on crates/router/src/connector/trustpay/transformers.rs
> +    pub currency_code: String,
Can we use the `Currency` enum instead?

2023-06-27 07:16 UTC, SanchithHegde approved these changes

2023-06-27 07:55 UTC, ArjunKarthik approved these changes

2023-06-27 09:36 UTC, jagan-jaya requested changes

2023-06-27 09:36 UTC, jagan-jaya commented on crates/router/src/connector/trustpay/transformers.rs
> +            })?;
```suggestion
        let pmt = item.data.request.get_payment_method_type()?;
```

2023-06-28 08:03 UTC, ArjunKarthik submitted a review, later dismissed

2023-06-28 08:36 UTC, SanchithHegde approved these changes

2023-06-29 06:13 UTC, SanchithHegde submitted a review, later dismissed

2023-06-30 05:39 UTC, jagan-jaya submitted a review, later dismissed

2023-07-01 11:44 UTC, SanchithHegde commented
Going ahead and merging this, only the OpenAPI spec had to be updated in the recent conflict resolution.

2023-07-01 11:44 UTC, SanchithHegde approved these changes

2023-07-01 11:45 UTC, merged