fix(payment_methods):  return appropriate error when basilisk locker token expires
juspay/hyperswitch pull request #1517
Opened 2023-06-22 13:35 UTC by ShankarSinghC

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This pull request addresses an issue where the system throws an internal server error (5xx) instead of handling token expiry gracefully when confirming payments using the Basilisk Locker system. The code changes now check the error status code and handle the error appropriately. If the error status code is 404, indicating a token not found error due to expiry, the system returns an `UnprocessableEntity` error response. For other error status codes, the system continues to throw an InternalServerError error response and generates an error report for troubleshooting.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-22 14:16 UTC, Abhicodes-crypto requested changes

2023-06-22 14:16 UTC, Abhicodes-crypto commented on crates/router/src/core/errors/api_error_response.rs
> +            Self::UnprocessableEntity => AER::Unprocessable(ApiError::new("IR", 23, "Token expired or invalid", None)),
You can consider making it more generic instead of hardcoding to Token expired because this error could be used else where other than token flow.

2023-06-22 14:16 UTC, Abhicodes-crypto commented on crates/router/src/compatibility/stripe/errors.rs
> +            | errors::ApiErrorResponse::UnprocessableEntity
consider adding a new stripe error code or map to a more relevant code.

2023-06-26 07:35 UTC, Abhicodes-crypto approved these changes

2023-06-26 07:37 UTC, Abhicodes-crypto commented
Added API contract changes since this adds a new error type and it would be easy for frontend to track the PR.

2023-06-26 13:08 UTC, lsampras approved these changes

2023-06-26 13:47 UTC, SanchithHegde approved these changes

2023-06-26 13:47 UTC, SanchithHegde commented on crates/router/src/core/errors/api_error_response.rs
> +    UnprocessableEntity { entity: String },
Entities expiring might not apply to entities other than tokens though.

2023-06-27 08:09 UTC, merged