enhan(compatibility): added straight through routing and udf mapping …
juspay/hyperswitch pull request #1536
Opened 2023-06-23 18:02 UTC by sahkal

…in setup intent

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

added straight through routing and udf field mapping to get txn_id and other details in setup_intents

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

<img width="1136" alt="Screen Shot 2023-06-23 at 11 21 02 PM" src="https://github.com/juspay/hyperswitch/assets/26082680/0c320dc3-b8ad-4514-b557-d9a912e3cb5f">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-27 05:50 UTC, jarnura requested changes
Other than import changes, looks good to me.

2023-06-27 05:50 UTC, jarnura commented on crates/router/src/compatibility/stripe/setup_intents/types.rs
> +            .map(crate::types::api::RoutingAlgorithm::Single)
```suggestion
            .map(api::RoutingAlgorithm::Single)
```

2023-06-27 08:08 UTC, sahkal commented on crates/router/src/compatibility/stripe/setup_intents/types.rs
> +            .map(crate::types::api::RoutingAlgorithm::Single)
done!

2023-06-28 20:15 UTC, SanchithHegde approved these changes

2023-06-29 08:33 UTC, SanchithHegde approved these changes

2023-07-03 11:56 UTC, vspecky approved these changes

2023-07-03 12:48 UTC, jarnura approved these changes

2023-07-03 13:15 UTC, merged