fix(refunds): Modify refund fields to process updating of refund_reason
juspay/hyperswitch pull request #1544
Opened 2023-06-26 09:49 UTC by kritikmodi

## Type of Change

- [x] Bugfix

## Description

The `reason` field is incorrectly mapped in the core logic so this PR modifies that. Also, the `refund_reason` field is missing in the db update function so this PR adds that.

## Motivation and Context

This PR fixes [this](https://github.com/juspay/hyperswitch/issues/1523) issue.

## How did you test it?

Tested manually using Postman.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code

2023-06-26 09:58 UTC, dracarys18 requested changes

2023-06-26 09:58 UTC, dracarys18 commented on crates/api_models/src/refunds.rs
> +    #[schema(value_type = Option<String>, max_length = 255, example = "Customer returned the product")]
This is not necessary.

2023-07-03 13:25 UTC, kritikmodi commented on crates/api_models/src/refunds.rs
> +    #[schema(value_type = Option<String>, max_length = 255, example = "Customer returned the product")]
Okay

2023-07-13 09:25 UTC, NishantJoshi00 approved these changes

2023-07-13 10:16 UTC, inventvenkat approved these changes

2023-07-14 07:27 UTC, dracarys18 approved these changes

2023-07-16 12:46 UTC, SanchithHegde approved these changes

2023-07-16 13:41 UTC, merged