refactor(refunds): rename metadata to udf
juspay/hyperswitch pull request #1545
Opened 2023-06-26 10:30 UTC by Abhicodes-crypto

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Rename metadata to udf Because user defined fields make sense and metadata is going to be added as a typed object in future. 

### Additional Changes

- [x] This PR modifies the API contract
- [x] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Compiles

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-26 10:33 UTC, dracarys18 requested changes

2023-06-26 10:33 UTC, dracarys18 commented on crates/storage_models/src/refund.rs
> +                udf: metadata,
```suggestion
            RefundUpdate::MetadataAndReasonUpdate {udf , reason } => Self {
                udf,
```

2023-06-26 11:10 UTC, dracarys18 approved these changes

2023-06-26 13:06 UTC, inventvenkat requested changes
DB rename is not possible without downtime. For now, you can update the response type to send udf instead of metadata. 
In future to rename,
1. Add column  should go as a seperate PR. with application changes to pick from old column as fallback
2. migrate and delete column as a new PR

2023-06-27 10:17 UTC, Abhicodes-crypto commented
Closing because as per latest discussions we are going to have metadata field in Refunds and it accepts custom inputs from merchant.

2023-06-27 10:17 UTC, closed without merging