feat(connector): [Stripe] Add support for  WeChat Pay and Qr code support in next action
juspay/hyperswitch pull request #1555
Opened 2023-06-27 14:05 UTC by Sangamesh26

## Type of Change

- [x] New feature

## Description

Add support for WeChat Pay, we chat pay in stripe doesn't follow redirection.Qr code url is given in the next action, this qr code has to be shown in sdk.

API contract for WeChat Pay:
```
    "payment_method": "wallet",
    "payment_method_type": "we_chat_pay",
    "payment_method_data": {
        "wallet": {
            "we_chat_pay": {}
        }
    },
```

### Additional Changes

- [x] This PR modifies the API contract

## Motivation and Context

Add support for WeChat Pay payment method

## How did you test it?

Manual

Qr code url in next action
<img width="1264" alt="Screen Shot 2023-06-27 at 6 16 14 PM" src="https://github.com/juspay/hyperswitch/assets/59434228/eef065bd-f0ef-47b4-899d-89c42545a52c">

Qr code
<img width="1545" alt="Screen Shot 2023-06-27 at 6 15 53 PM" src="https://github.com/juspay/hyperswitch/assets/59434228/9c084396-8220-430e-a2e8-b2844c09416d">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-06-28 21:01 UTC, SanchithHegde commented on crates/router/src/connector/stripe/transformers.rs
> +                    bacs_bank_instructions: response.financial_addresses[0].sort_code.to_owned(),
Avoid indexing, it can cause panics. Use `first()` instead, and raise errors of handle it, as suitable.

2023-07-05 09:18 UTC, jagan-jaya requested changes

2023-07-05 09:18 UTC, jagan-jaya commented on crates/router/src/connector/stripe/transformers.rs
> +                    .and_then(|financial_address| financial_address.sort_code.to_owned());
```suggestion
                let (sepa_bank_instructions, bacs_bank_instructions) = bank_instructions
                    .and_then(|financial_address| (financial_address.iban.to_owned(), financial_address.sort_code.to_owned()));
```

2023-07-06 08:56 UTC, jagan-jaya approved these changes

2023-07-06 09:36 UTC, SanchithHegde approved these changes

2023-07-06 10:30 UTC, merged