feat: add domain type for client secret
juspay/hyperswitch pull request #1571
Opened 2023-06-30 04:39 UTC by tusharv01

Add domain type for client secret in PaymentsSessionResponse

This commit introduces a new domain type, `ClientSecretDomain`, to handle the `client_secret` field in the `PaymentsSessionResponse` struct. The `ClientSecretDomain` type ensures proper encapsulation and security of sensitive information.

Changes made in this commit:
- Updated `PaymentsSessionResponse` struct to use `Secret<ClientSecretDomain, pii::ClientSecret>` for `client_secret` field.
- Implemented serialization and deserialization for `ClientSecretDomain`.
- Updated the `From` implementation to convert `PaymentsSessionRequest` into `PaymentsSessionResponse` with the appropriate `ClientSecretDomain`.

This enhancement improves the security and maintainability of the codebase by properly handling client secrets in a more structured and encapsulated manner. It also aligns with the PR #1357, addressing the feature request to create a domain type for the client secret.

Test cases have been added to ensure the proper serialization and deserialization of the `ClientSecretDomain`.

Closes #1357

2023-07-03 10:16 UTC, Abhicodes-crypto requested changes

2023-07-03 10:16 UTC, Abhicodes-crypto commented on crates/api_models/src/payments.rs
> +impl Serialize for ClientSecretDomain {
In serialise you can concat payment_id and secret and give out a string.

2023-07-03 10:16 UTC, Abhicodes-crypto commented on crates/api_models/src/payments.rs
> +pub struct PaymentsSessionResponse {
Why was this added ?

2023-08-16 11:49 UTC, closed without merging

2023-08-17 05:51 UTC, VedantKhairnar commented
Closing due to inactivity. Feel free to open it if you are interested and assigned the corresponding issue.
Thanks.

2026-02-17 15:45 UTC, tusharv01 commented
Hello can we open this PR please as i am interested to work on it.

2026-02-17 15:45 UTC, tusharv01 commented
@VedantKhairnar @SanchithHegde

2026-02-22 14:44 UTC, SanchithHegde commented
@tusharv01 I believe #1357 was closed in #3557.