feat(connector): [Adyen] implement Online Banking Thailand for Adyen
juspay/hyperswitch pull request #1585
Opened 2023-07-02 06:16 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Online Banking Thailand is a Thailand specific payment method.
```
"payment_method": "bank_redirect",
  "payment_method_type": "online_banking_thailand",
  "payment_method_data": {
    "bank_redirect": {
      "online_banking_thailand": {
        "issuer": "bangkok_bank"
      }
    }
  }
```

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## How did you test it?

Unit Test Case
<img width="1388" alt="Screen Shot 2023-07-02 at 11 25 41 AM" src="https://github.com/juspay/hyperswitch/assets/131388445/dddbe914-3284-4353-97b5-6f66d7e11246">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-05 09:42 UTC, jagan-jaya requested changes
Once you are done with all the payment_method addition , please check it in VAS also, it should not get affected

2023-07-05 09:42 UTC, jagan-jaya commented on crates/api_models/src/payments.rs
> +        // Issuer banks
remove this comment

2023-07-05 14:25 UTC, ArjunKarthik approved these changes

2023-07-20 16:14 UTC, ArjunKarthik approved these changes

2023-07-20 16:17 UTC, jagan-jaya submitted a review, later dismissed

2023-07-20 16:33 UTC, ArjunKarthik approved these changes

2023-07-20 17:11 UTC, ashokkjag approved these changes

2023-07-20 17:18 UTC, SanchithHegde approved these changes

2023-07-20 17:48 UTC, merged