feat(connector): [Adyen] implement Atome for Adyen
juspay/hyperswitch pull request #1590
Opened 2023-07-02 17:14 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Atome is a popular buy now, pay later service in some countries of the APAC region.
Line Items must be passed as a meta data 

```
{
  "payment_method": "pay_later",
  "payment_method_type": "atome",
  "payment_method_data": {
    "pay_later": {
      "atome_redirect": {}
    }
  },
  "billing": {
    "address": {
      "line1": "1467",
      "line2": "Harrison Street",
      "line3": "Harrison Street",
      "city": "San Fransico",
      "state": "California",
      "zip": "94122",
      "country": "NO",
      "first_name": "joseph",
      "last_name": "Doe"
    },
    "phone": {
      "number": "8056594427",
      "country_code": "+91"
    }
  },
  "metadata": {
    "order_details": {
      "product_name": "shoe",
      "quantity": 1,
      "amount": 10000
    }
 }
}
```

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-03 10:55 UTC, prasunna09 requested changes

2023-07-03 10:55 UTC, prasunna09 commented on crates/router/src/types.rs
> +        crate::logger::debug!("aaaaaaaaaaa{:?}", encode);
Please remove this logger!

2023-07-05 09:47 UTC, jagan-jaya approved these changes

2023-07-05 14:32 UTC, ArjunKarthik approved these changes

2023-07-14 10:19 UTC, prasunna09 approved these changes

2023-07-20 16:52 UTC, ArjunKarthik submitted a review, later dismissed

2023-07-20 17:13 UTC, ashokkjag approved these changes

2023-07-20 17:15 UTC, SanchithHegde reviewed
Other than that, looks good to me!

2023-07-20 17:15 UTC, SanchithHegde commented on config/config.example.toml
> +adyen = { banks = "affin_bank,agro_bank,alliance_bank,am_bank,bank_islam,bank_muamalat,bank_rakyat,bank_simpanan_nasional,cimb_bank,hong_leong_bank,hsbc_bank,kuwait_finance_house,may_bank,ocbc_bank,p
Just a suggestion that you can incorporate in further PRs:

You can simplify this as `adyen.banks = "..."`, does not alter the semantics or structure.

Like so:

```suggestion
adyen.banks = "affin_bank,agro_bank,alliance_bank,am_bank,bank_islam,bank_muamalat,bank_rakyat,bank_simpanan_nasional,cimb_bank,hong_leong_bank,hsbc_bank,kuwait_finance_house,may_bank,ocbc_bank,public_bank,rhb_bank,standard_chartered_bank,uob_bank"
```

2023-07-20 17:15 UTC, SanchithHegde commented on crates/router/tests/connectors/adyen_uk_ui.rs
> +// https://hs-payments-test.netlify.app/paypal-redirect?amount=70.00&country=US&currency=USD&mandate_data[customer_acceptance][acceptance_type]=offline&mandate_data[customer_acceptance][accepted_at]=
Do you need this commented line? I believe this was removed in #1763.

2023-07-20 17:17 UTC, SanchithHegde submitted a review, later dismissed

2023-07-20 19:09 UTC, ArjunKarthik approved these changes

2023-07-20 19:18 UTC, SanchithHegde approved these changes

2023-07-20 20:04 UTC, merged