feat(connector): [Bluesnap] Remove wallet call
juspay/hyperswitch pull request #1620
Opened 2023-07-05 12:59 UTC by Sangamesh26

## Type of Change

- [x] New feature

## Description

Remove Wallet call form bluesnap which was earlier treated a session call.
We get session object now from apple only instead of bluesnap.

## Motivation and Context

Get session response from Apple pay instead of getting from connector

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-07-07 11:15 UTC, SanchithHegde submitted a review, later dismissed
@Sangamesh26 Please attach suitable labels

2023-07-10 05:53 UTC, ArjunKarthik approved these changes

2023-07-10 05:53 UTC, ArjunKarthik commented on crates/router/src/connector/bluesnap.rs
> -    fn get_headers(
@Sangamesh26 Do not remove this code, let it be and add comments. Revert only the core changes

2023-07-10 05:53 UTC, ArjunKarthik commented on crates/router/src/connector/bluesnap/transformers.rs
> -impl TryFrom<&types::PaymentsSessionRouterData> for BluesnapCreateWalletToken {
Same here.

2023-07-10 05:54 UTC, ArjunKarthik requested changes
Let's not remove the code for session call

2023-07-10 05:54 UTC, ArjunKarthik commented
@Sangamesh26 Please add necessary labels to the PR

2023-07-17 10:10 UTC, ArjunKarthik approved these changes

2023-07-18 08:06 UTC, Narayanbhat166 approved these changes

2023-07-18 08:41 UTC, merged