fix(rapyd): add router_return_url in 3DS request
juspay/hyperswitch pull request #1621
Opened 2023-07-05 13:22 UTC by ShankarSinghC

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

3DS payment status would always remain in requires_customer_action as there was no return url provided in the 3DS request. This pr adds router_return_url in 3DS request.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

<img width="1151" alt="Screenshot 2023-07-05 at 5 31 52 PM" src="https://github.com/juspay/hyperswitch/assets/83439957/6d868f8a-833e-417a-bc37-1ff9d6767245">
<img width="649" alt="Screenshot 2023-07-05 at 6 01 56 PM" src="https://github.com/juspay/hyperswitch/assets/83439957/58587a3d-4e10-4972-af3d-bc5bb1183326">
<img width="1055" alt="Screenshot 2023-07-05 at 5 32 08 PM" src="https://github.com/juspay/hyperswitch/assets/83439957/de55f357-846f-4923-9172-09793ce00e9e">
<img width="994" alt="Screenshot 2023-07-05 at 6 00 37 PM" src="https://github.com/juspay/hyperswitch/assets/83439957/2f3602f8-6922-4b74-9f41-1b2e2e941648">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-05 14:55 UTC, ArjunKarthik requested changes

2023-07-05 14:55 UTC, ArjunKarthik commented on crates/router/src/connector/rapyd/transformers.rs
> +            },
```suggestion
item.request.get_return_url()?
```

2023-07-05 16:50 UTC, ArjunKarthik approved these changes

2023-07-06 05:32 UTC, srujanchikke approved these changes

2023-07-06 06:57 UTC, Narayanbhat166 approved these changes

2023-07-06 06:57 UTC, SanchithHegde approved these changes

2023-07-06 07:27 UTC, merged