feat: Api contract for gift cards
juspay/hyperswitch pull request #1634
Opened 2023-07-06 10:49 UTC by Sangamesh26

## Type of Change

- [x] New feature

## Description

Api contract for gift cards payment method

Api contract :

```
"payment_method":  "gift_card",
"payment_method_type":  "babygiftcard",
"payment_method_data": {
       "number" : "{gift_card_number}",
       "cvc": "{cvc}"
}
```

### Additional Changes

- [x] This PR modifies the API contract

## Motivation and Context

To add new payment method, gift cards

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-07-07 11:23 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +#[serde(rename_all = "snake_case")]
You don't need this annotation.

2023-07-10 13:18 UTC, SanchithHegde commented
@Sangamesh26 Please address the failing CI checks.

2023-07-11 09:11 UTC, SanchithHegde approved these changes

2023-07-11 12:19 UTC, jagan-jaya commented
@Sangamesh26  I think changes in VAS required for this. Please keep the VAS PR ready

2023-07-11 12:20 UTC, jagan-jaya approved these changes

2023-07-11 12:22 UTC, jagan-jaya commented
Please add the testcase in https://hs-payments-test.netlify.app
@Sangamesh26

2023-07-11 12:43 UTC, jagan-jaya requested changes
@Sangamesh26 How reward and gift card differs? why don't we add it in the Reward type itself?

2023-07-18 10:00 UTC, Sangamesh26 commented
> @Sangamesh26 How reward and gift card differs? why don't we add it in the Reward type itself?

Reward type and gift card differs, customers have to buy gift cards and rewards are credited

2023-07-25 10:40 UTC, Abhicodes-crypto approved these changes

2023-07-25 11:20 UTC, jagan-jaya approved these changes

2023-07-25 14:40 UTC, SanchithHegde approved these changes

2023-07-26 07:46 UTC, merged