fix(CI): fix msrv checks on github run on push to main
juspay/hyperswitch pull request #1645
Opened 2023-07-07 09:22 UTC by ShankarSinghC

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR introduces changes to improve the CI workflow in the repository. The main goal is to separate the logic for pushes to the main branch from pull requests.
1. Created a new workflow file, `CI-push.yml`, specifically for pushes to the main branch.
2. Modified the existing CI.yml file to trigger only on pull requests.
3. Removed the logic that checked for differences in crates in the `CI-push.yml` file.
The logic we had in place for checking differences in crates in a pull request is not valid when we push directly to the main branch.

The `CI-push.yml` file contains a single job, `push-to-main`, which runs on Ubuntu latest and performs the following steps:
- Checks out the repository.
- Installs Rust and cargo-hack.
- Executes the `cargo hack check` command to check all workspace packages without considering specific differences.

By separating the workflows, we can now ensure that CI builds on the main branch do not fail due to the logic designed for PRs. The `CI-push.yml` workflow specifically targets pushes to the main branch and performs the necessary cargo-hack checks on all workspace packages.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-07 09:40 UTC, lsampras approved these changes

2023-07-07 09:41 UTC, lsampras requested changes

2023-07-07 09:41 UTC, lsampras commented on .github/workflows/CI-pr.yml
> +        run: cargo hack check --each-feature --no-dev-deps
will need to use package specific change here

2023-07-07 11:48 UTC, lsampras requested changes

2023-07-07 11:48 UTC, lsampras commented on .github/workflows/CI-pr.yml
> +          git config submodule.recurse true
```suggestion
```

2023-07-07 11:48 UTC, lsampras commented on .github/workflows/CI-pr.yml
> +          git config submodule.recurse true
```suggestion
```

2023-07-07 11:50 UTC, lsampras requested changes

2023-07-07 11:50 UTC, lsampras commented on .github/workflows/CI-pr.yml
> +          git fetch origin $GITHUB_BASE_REF --depth 1
```suggestion
        run: git fetch origin $GITHUB_BASE_REF --depth 1
```

2023-07-07 11:50 UTC, lsampras commented on .github/workflows/CI-pr.yml
> +          git fetch origin $GITHUB_BASE_REF --depth 1
```suggestion
        run: git fetch origin $GITHUB_BASE_REF --depth 1
```

2023-07-07 14:49 UTC, SanchithHegde approved these changes

2023-07-10 08:52 UTC, lsampras approved these changes

2023-07-10 10:12 UTC, merged

2023-07-12 13:26 UTC, lsampras commented
@ShankarSinghC Can we also move `merge_group` trigger to `CI-push.yaml`