test(connector): [Adyen] Add UI test for Adyen Paymet methods
juspay/hyperswitch pull request #1648
Opened 2023-07-07 10:49 UTC by swangi-kumari

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Added and fixed ui test for bank debits, bank redirects and wallets

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
<img width="1728" alt="Screenshot 2023-05-25 at 4 18 22 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/17aae44c-71b1-469d-8c53-661c9ea8fb2a">
<img width="1723" alt="Screenshot 2023-05-24 at 4 45 20 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/9735f35c-57c3-4b4d-ba34-03ec0cd06655">
<img width="1722" alt="Screenshot 2023-05-24 at 6 30 02 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/0f8d1233-c830-4ea2-a404-6239e0e73ba8">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-14 08:07 UTC, srujanchikke approved these changes

2023-07-17 11:02 UTC, jagan-jaya requested changes

2023-07-17 11:02 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen_uk_ui.rs
> +            Event::Trigger(Trigger::SendKeys(By::Id("username"), "admin")),
move username and password to connector_auth file

2023-07-17 11:02 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen_uk_ui.rs
> +            Event::Assert(Assert::IsPresent("failed")),
are we expecting it to fail always?

2023-07-17 11:02 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen_uk_ui.rs
> +fn should_make_adyen_walley_payment_test() {
ignore walley for now

2023-07-17 15:14 UTC, ArjunKarthik requested changes
For the payment methods which have processing as their final status lets add comment

2023-07-17 15:14 UTC, ArjunKarthik commented on crates/router/tests/connectors/adyen_uk_ui.rs
> +                vec!["status=processing"],
Why we are checking processing status instead of succeeded?

2023-07-18 13:49 UTC, jagan-jaya requested changes

2023-07-18 13:49 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen_uk_ui.rs
> +            Event::Assert(Assert::IsPresent("processing")), //final status of this payment method will remain in processing state
```suggestion
            Event::Assert(Assert::IsPresent("Status")),
            Event::Assert(Assert::IsPresent("processing")), //final status of this payment method will remain in processing state
```

2023-07-18 13:49 UTC, jagan-jaya commented on crates/router/tests/connectors/adyen_uk_ui.rs
> +            Event::Assert(Assert::IsPresent("processing")), //final status of this payment method will remain in processing state
```suggestion
            Event::Assert(Assert::IsPresent("Status")),
            Event::Assert(Assert::IsPresent("processing")), //final status of this payment method will remain in processing state
```

2023-07-18 16:17 UTC, ArjunKarthik approved these changes

2023-07-19 07:08 UTC, ashokkjag approved these changes

2023-07-19 07:13 UTC, ArjunKarthik approved these changes

2023-07-19 07:15 UTC, srujanchikke approved these changes

2023-07-19 07:46 UTC, jagan-jaya approved these changes

2023-07-19 08:11 UTC, merged