feat(router): add expand attempts support in payments retrieve response
juspay/hyperswitch pull request #1678
Opened 2023-07-11 11:07 UTC by sai-harsha-vardhan

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Currently we only have active payment attempt details in payments retrieve response. For retries we would have multiple attempts, need an option to see all the attempts linked to payment intent. 

Add `expand_attempts` in payments retrieve request, when enabled gives list of attempts linked to payment intent in response.

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
Tested Manually
![image](https://github.com/juspay/hyperswitch/assets/56996463/ee82400a-96d8-4330-9aa6-6c6ed4eb1675)

![image](https://github.com/juspay/hyperswitch/assets/56996463/a7efcfe3-2b54-4a1e-b174-8732cbe70310)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-12 07:50 UTC, Narayanbhat166 commented on crates/router/src/core/payments/transformers.rs
> +    };
```suggestion
    let attempts_response = option_attempts.map(|attempts| attempts.into_iter().map(ForeignInto::foreign_into).collect())
    };
```

2023-07-12 07:50 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> +    /// /// If there was an error while calling the connectors the code is received here
```suggestion
    /// If there was an error while calling the connectors the code is received here
```

2023-07-13 06:18 UTC, jarnura requested changes

2023-07-13 06:18 UTC, jarnura commented on crates/api_models/src/payments.rs
> +    pub attempt_id: String,
the key name will be `reference_id` and not `attempt_id`. It can be sometimes not attempt_id too

2023-07-13 13:42 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = Currency, example = "usd")]
```suggestion
    #[schema(value_type = Option<Currency>, example = "usd")]
```

2023-07-13 13:42 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = PaymentMethod, example = "bank_transfer")]
```suggestion
    #[schema(value_type = Option<PaymentMethod>, example = "bank_transfer")]
```

2023-07-14 06:36 UTC, Narayanbhat166 approved these changes

2023-07-14 06:44 UTC, jarnura approved these changes

2023-07-14 07:29 UTC, merged