fix(template): Address add_connector.sh throwing errors when creating new connector template
juspay/hyperswitch pull request #1679
Opened 2023-07-11 12:10 UTC by pixincreate

## Type of Change

- [x] Bugfix
- [x] Documentation

## Description

This PR aims at fixing `add_connector.sh` file that is responsible for generating new connector integration templates. Previously, the when creating a new connector template with the below command:  
```sh
sh scripts/add_connector.sh <connector_name> <connector_base_url>
```
due to changes done in the core targeting `DummyConnectors` and `enums`, broke the functionality. 

## Motivation and Context

NIL

## How did you test it?

Manually by creating a new connector template with the above given command.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-07-11 12:28 UTC, jagan-jaya requested changes

2023-07-11 12:39 UTC, pixincreate commented on scripts/add_connector.sh
> +sed -i'' -e "s/\(pub enum RoutableConnectors {\)/\1\n\t${payment_gateway_camelcase},/" crates/api_models/src/enums.rs
It is now grouped together so that, we can use it directly just by using `\1`.

2023-07-13 16:23 UTC, NishantJoshi00 reviewed
Other than that, looks good!

2023-07-13 16:23 UTC, NishantJoshi00 commented on connector-template/test.rs
> -use std::str::FromStr;
Why was this removed?

2023-07-14 05:55 UTC, NishantJoshi00 submitted a review, later dismissed

2023-07-20 06:39 UTC, NishantJoshi00 approved these changes

2023-07-20 07:03 UTC, jagan-jaya approved these changes

2023-07-20 08:56 UTC, SanchithHegde approved these changes

2023-07-20 10:45 UTC, merged