feat(connector): [Adyen] Add support for PayPal wallet mandates
juspay/hyperswitch pull request #1686
Opened 2023-07-12 07:47 UTC by prasunna09

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add PayPal wallet mandates in Adyen connector

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

CIT - 
<img width="1221" alt="Screen Shot 2023-07-12 at 12 48 59 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/f5e5995b-e02a-4b8e-94fc-add831d70cd0">

<img width="879" alt="Screen Shot 2023-07-12 at 12 49 37 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/94b8c6d6-a51a-443a-9301-de63d416baa6">

<img width="677" alt="Screen Shot 2023-07-12 at 12 50 41 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/3da5a258-c501-47b5-b8e5-f180e69ebe1d">

MIT - 
<img width="650" alt="Screen Shot 2023-07-12 at 12 53 12 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/633fa05b-7ab4-457b-8141-b8e918b82c98">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-12 08:21 UTC, ArjunKarthik requested changes

2023-07-12 08:21 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +            _ => Err(errors::ConnectorError::NotImplemented(
Doesadyen support mandates only in case of cards and PayPal?

2023-07-12 08:57 UTC, prasunna09 commented on crates/router/src/connector/adyen/transformers.rs
> +            shopper_email: item.request.email.clone(),
It is only mandatory field for PayPal mandates but option for other payment methods

2023-07-13 05:35 UTC, srujanchikke submitted a review, later dismissed

2023-07-13 05:41 UTC, ArjunKarthik approved these changes

2023-07-13 05:41 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +        storage_enums::PaymentMethodType::Paypal => {
Pass router data and use util get_email? instead of duplicating code

2023-07-13 05:41 UTC, ArjunKarthik requested changes
One comments rest looks fine

2023-07-13 08:40 UTC, ArjunKarthik requested changes

2023-07-13 08:40 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +        let shopper_email = if store_payment_method.is_some() {
let move this condition also inside the method

2023-07-13 10:24 UTC, ArjunKarthik requested changes

2023-07-13 10:24 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +            get_shopper_email(item.request.clone(), store_payment_method.is_some())?;
Don't clone, pass it as reference

2023-07-13 11:51 UTC, ArjunKarthik submitted a review, later dismissed

2023-07-13 12:15 UTC, srujanchikke submitted a review, later dismissed

2023-07-13 18:03 UTC, SanchithHegde submitted a review, later dismissed

2023-07-14 10:03 UTC, ArjunKarthik approved these changes

2023-07-14 10:04 UTC, srujanchikke approved these changes

2023-07-14 11:26 UTC, SanchithHegde approved these changes

2023-07-14 11:55 UTC, merged