test(connector): [Aci] Add UI test for Aci Payment Methods
juspay/hyperswitch pull request #1702
Opened 2023-07-13 09:15 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
<img width="1138" alt="aci" src="https://github.com/juspay/hyperswitch/assets/85639103/cd17ad68-3fa1-4222-a1b0-a5c82c1c0e3e">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-13 09:54 UTC, srujanchikke requested changes

2023-07-13 09:54 UTC, srujanchikke commented on crates/router/tests/connectors/aci_ui.rs
> +async fn should_make_aci_card_mandate_payment(c: WebDriver) -> Result<(), WebDriverError> {
Please Avoid using single variable names

2023-07-13 09:54 UTC, srujanchikke commented on crates/router/tests/connectors/aci_ui.rs
> +async fn should_make_aci_alipay_payment(c: WebDriver) -> Result<(), WebDriverError> {
same here and change it in other places too

2023-07-13 10:32 UTC, srujanchikke submitted a review, later dismissed

2023-07-14 09:42 UTC, srujanchikke submitted a review, later dismissed

2023-07-17 14:52 UTC, ArjunKarthik approved these changes

2023-07-17 18:29 UTC, srujanchikke approved these changes

2023-07-18 13:37 UTC, merged