test(connector): [Noon] Add test for Noon Payment methods
juspay/hyperswitch pull request #1714
Opened 2023-07-14 10:42 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
<img width="1227" alt="noon" src="https://github.com/juspay/hyperswitch/assets/85639103/d36e4262-652f-4adf-97ac-dca8be1021fa">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-14 10:49 UTC, srujanchikke approved these changes

2023-07-17 15:07 UTC, ArjunKarthik requested changes

2023-07-18 12:46 UTC, swangi-kumari commented on .github/testcases/ui_tests.json
> +    "connector": "aci",
These are recent changes in hs tool. whwn new payment method is saved. we need to update the ui_tests.json file

2023-07-18 16:12 UTC, ArjunKarthik approved these changes

2023-07-19 05:51 UTC, srujanchikke approved these changes

2023-07-19 06:50 UTC, jagan-jaya submitted a review, later dismissed

2023-07-19 07:05 UTC, ashokkjag approved these changes

2023-07-19 07:46 UTC, jagan-jaya approved these changes

2023-07-19 08:07 UTC, ArjunKarthik approved these changes

2023-07-19 08:11 UTC, ashokkjag approved these changes

2023-07-19 08:53 UTC, merged