feat(connector): [Boku] Template generation
juspay/hyperswitch pull request #1760
Opened 2023-07-20 09:37 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Boku is a payment connector which provides service majorly in South-Asian countries

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-07-20 12:53 UTC, prasunna09 requested changes

2023-07-20 12:53 UTC, prasunna09 commented on crates/router/tests/connectors/sample_auth.toml
> +
remove this extra new line

2023-07-20 16:24 UTC, Sakilmostak commented on crates/router/src/core/payments/flows.rs
> +    connector::Boku,
removing these breaking the build

2023-07-20 18:14 UTC, prasunna09 commented on crates/router/src/core/payments/flows.rs
> +    connector::Boku,
I mentioned to maintain them in alphabetical order, not removing them

2023-07-24 09:49 UTC, prasunna09 approved these changes

2023-07-24 12:16 UTC, ArjunKarthik approved these changes

2023-07-24 13:33 UTC, ashokkjag approved these changes

2023-07-25 07:30 UTC, merged