feat(connector): [Adyen] implement Japanese convenience stores
juspay/hyperswitch pull request #1819
Opened 2023-07-31 07:02 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

In Japan, 17% of payments for goods are paid at convenience stores or konbini in Japanese. Through our partner econtext, you can accept payments made through the following convenience stores across Japan:

    7-Eleven (Redirection)
    Lawson (Voucher)
    Mini Stop (Voucher)
    Family Mart (Voucher)
    Seicomart (Voucher)
    PayEasy (Voucher)

Payment method data 
```
"payment_method_type": "seven_eleven",
  "payment_method_data": {
    "voucher": {
      "seven_eleven": {
        "first_name": "Some",
        "last_name": "One",
        "email": "someone@something.com",
        "phone_number": "1234567890"
      }
    }
  }
```
Refund is not supported

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## How did you test it?

![Screen Shot 2023-07-31 at 11 34 57 AM](https://github.com/juspay/hyperswitch/assets/131388445/ca6bdbeb-4094-41c0-b4d6-7fdc2cca87b2)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-08 09:49 UTC, ArjunKarthik requested changes

2023-08-08 09:49 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +                Ok(AdyenPaymentMethod::SevenEleven(Box::new(JCSVoucherData {
Let's have a try from for this conversion

2023-08-08 10:39 UTC, AkshayaFoiger commented on crates/api_models/src/payments.rs
> +    Boleto(BoletoVoucherData),
By mistake

2023-08-08 11:37 UTC, ArjunKarthik approved these changes

2023-08-09 13:13 UTC, ArjunKarthik requested changes

2023-08-09 13:13 UTC, ArjunKarthik commented on crates/router/build.rs
> +    println!("cargo:rustc-env=RUST_MIN_STACK=4291456"); // 6 * 1024 * 1024 = 6 MiB
Please remove this change

2023-08-09 14:19 UTC, ArjunKarthik approved these changes

2023-08-09 15:01 UTC, ashokkjag approved these changes

2023-08-09 15:58 UTC, merged