refactor(ui_tests): move ui_tests to test_utils crate to reduce development time
juspay/hyperswitch pull request #1822
Opened 2023-07-31 09:07 UTC by jagan-jaya

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [X] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

UI tests only depend on selenium library and few common utils in tests, it doesn't need any other things present in router. This PR move all the ui_tests related changes to test_utils crate so that development time can be reduced while adding unit test. 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Currently, writing a ui_tests takes around ~30secs for each change done in *_ui.rs or selenium.rs file. this can be reduced to 3secs by moving all the ui_tests related changes to test_utils crate as it has very less dependency with other modules.

## How did you test it?

ran UI tests manually in pipeline. it worked as expected

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed submitted code

2023-07-31 09:13 UTC, jarnura requested changes

2023-07-31 09:13 UTC, jarnura commented on crates/test_utils/tests/mod.rs
> +#![allow(
use tests.rs as file name, avoid using mod.rs conventions as we don't flow that.

2023-07-31 09:13 UTC, jarnura commented on crates/test_utils/tests/main.rs
> +#![allow(
if this is just a util library rename the file to lib.rs

2023-07-31 10:16 UTC, jarnura submitted a review, later dismissed

2023-08-01 07:09 UTC, jarnura approved these changes

2023-08-01 07:47 UTC, SanchithHegde reviewed
Other than that, looks good to me!

2023-08-01 07:47 UTC, SanchithHegde commented on crates/test_utils/tests/connectors.rs
Do we need this file?

2023-08-01 07:47 UTC, SanchithHegde commented on crates/test_utils/tests/integration_tests.rs
Do we need this file as well?

2023-08-01 07:47 UTC, SanchithHegde commented on crates/test_utils/tests/lib.rs
> +)]
If you're adding it here, can you remove this annotation from the files corresponding to each of the submodules?

2023-08-01 07:47 UTC, SanchithHegde commented on crates/test_utils/tests/lib.rs
Can we have the directory structure similar to how we've done for the connectors (have a directory named `connectors` within the `tests` directory, have a `main.rs` instead, etc.)?
https://github.com/juspay/hyperswitch/tree/f32fdec290a2f303887550d8db1ae2a3c065bafe/crates/router/tests/connectors

2023-08-01 10:00 UTC, jarnura approved these changes

2023-08-01 12:51 UTC, merged