eat(core): Add all currencies in Currency Enum
juspay/hyperswitch pull request #1844
Opened 2023-08-01 21:34 UTC by tusharxoxoxo

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [x] This PR modifies the API contract
- [x] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context
#1814 

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-01 21:36 UTC, tusharxoxoxo commented
`cargo clippy` ran perfectly fine
![image](https://github.com/juspay/hyperswitch/assets/79051850/e162bef3-cf9a-41d8-bd98-ec30da29b367)
`cargo +nightly fmt` also ran perfectly fine
![Screenshot 2023-08-02 at 2 59 24 AM](https://github.com/juspay/hyperswitch/assets/79051850/ccc05496-7204-4072-89c0-3e85eeddf5c7)

But after running 
`cargo check --all-features
cargo clippy --all-features
cargo test --all-features`
there were some compilation errors
![Screenshot 2023-08-02 at 2 57 52 AM](https://github.com/juspay/hyperswitch/assets/79051850/7bd13aae-a3f0-4114-9575-69911d37e526)
![Screenshot 2023-08-02 at 2 58 19 AM](https://github.com/juspay/hyperswitch/assets/79051850/df39ae72-0bac-4ee5-8682-286c7fdb18f6)
![Screenshot 2023-08-02 at 2 58 35 AM](https://github.com/juspay/hyperswitch/assets/79051850/905a9e3b-30f8-4fa0-b675-6d486009c2a2)
![Screenshot 2023-08-02 at 2 58 57 AM](https://github.com/juspay/hyperswitch/assets/79051850/4c4608a7-85c5-4b30-8ae4-0ec84a4e9ab5)

2023-08-02 19:10 UTC, pixincreate commented
Hey @tusharxoxoxo, try running migrations, then perform a `cargo clean` once. Try compiling them again after that.

2023-08-03 06:49 UTC, tusharxoxoxo commented
I don't know how to run migrations, can u please tell me?
I have asked the very same question on the discord server of hyperswitch
today

On Thu, 3 Aug 2023 at 00:40, Pa1NarK ***@***.***> wrote:

> Hey @tusharxoxoxo <https://github.com/tusharxoxoxo>, try running
> migrations, then perform a cargo clean once. Try compiling them again
> after that.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/juspay/hyperswitch/pull/1844#issuecomment-1662824950>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS3DYSW55LKAZO2DWLZGPTTXTKQZPANCNFSM6AAAAAA3ALMAGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-03 07:17 UTC, prasunna09 commented
Hey Hi, did the previous error `linking with 'cc' failed` got fixed?

2023-08-03 07:27 UTC, prasunna09 requested changes

2023-08-03 07:27 UTC, prasunna09 commented on migrations/2023-07-19-081050_add_zero_decimal_currencies/up.sql
> +ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'AFN' AFTER 'AED';
Here you cannot edit the old file. Instead you have to create new one.
Use this command. The files will be automatically created - `diesel migration generate <migration_file_name>`.
Two files will be created - `up.sql` should have all these queries
`down.sql` should have `SELECT 1;`

2023-08-03 19:14 UTC, uddhavdave commented
@tusharxoxoxo the error logs show `library pq not found` , can you try running the steps mentioned [here](https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md#set-up-dependencies-on-macos).

>If linking diesel_cli fails due to missing libpq (if the error message is along the lines of cannot find -lpq), you may also have to install libpq and reinstall diesel_cli:
> ```
> brew install libpq
> export PQ_LIB_DIR="$(brew --prefix libpq)/lib"
> 
> cargo install diesel_cli --no-default-features --features "postgres"
> ```
> You may also choose to persist the value of PQ_LIB_DIR in your shell startup file like so:
> ```
> echo 'PQ_LIB_DIR="$(brew --prefix libpq)/lib"' >> ~/.zshrc
> ```

2024-01-13 20:17 UTC, closed without merging