refactor(connector): Handle default match cases
juspay/hyperswitch pull request #1847
Opened 2023-08-02 09:13 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Issue: defaults case in match shouldn't be handled using "_"

Solution:  "_" will never let the developer know impact of his changes incase of new addition of enum variants. By having the all cases in match compiler itself will throw errors wherever new enums needs to be handled

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-02 21:05 UTC, SanchithHegde approved these changes
Looks good to me!

By the way, you can use the `clippy::wildcard_enum_match_arm` clippy lint to identify wildcard match arms. You can temporarily add it to [`.cargo/config.toml`](https://github.com/juspay/hyperswitch/blob/c464cc510ded595ea846e7da95f60919614e2bd3/.cargo/config.toml) to try it out, but expect it to throw a lot of warnings.

2023-08-03 06:32 UTC, ArjunKarthik requested changes

2023-08-03 06:32 UTC, ArjunKarthik commented on crates/router/src/connector/stripe/transformers.rs
> +                Err(errors::ConnectorError::NotImplemented(
Error is not thrown in this scenario, Please return `Ok(Self::default()),`

2023-08-03 06:32 UTC, ArjunKarthik commented on crates/router/src/connector/utils.rs
> +pub fn payment_method_error_message(connector: &str) -> String {
rename this method to `get_unimplemented_payment_method_error_message()` you can take this in next PR

2023-08-03 06:32 UTC, ArjunKarthik commented on crates/router/src/connector/stripe/transformers.rs
> +    connector::utils::{self as util_connector, ApplePay, PaymentsPreProcessingData, RouterData},
rename this as connector_utils

2023-08-03 06:55 UTC, ArjunKarthik submitted a review, later dismissed

2023-08-03 06:57 UTC, SanchithHegde submitted a review, later dismissed

2023-08-03 12:24 UTC, ArjunKarthik approved these changes

2023-08-03 13:14 UTC, merged