chore: add connector functionality validation based on connector_type
juspay/hyperswitch pull request #1849
Opened 2023-08-02 12:00 UTC by kashif-m

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Added a variant in `ConnectorType` enum to specify payout processors. This will be used to validate the connectors configured by the merchant for payouts.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible
- [x] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-03 09:51 UTC, jagan-jaya requested changes

2023-08-03 09:51 UTC, jagan-jaya commented on crates/router/src/core/payments/helpers.rs
> +                            .attach_printable("Invalid connector passed for payouts")
use this as a variable here and in other places

2023-08-03 09:51 UTC, jagan-jaya commented on crates/router/src/core/payments/helpers.rs
> +                        Err(errors::ApiErrorResponse::InvalidRequestData {
use this as a variable here and in other places

2023-08-03 09:51 UTC, jagan-jaya commented on crates/router/src/core/payments/helpers.rs
> +                            Err(errors::ApiErrorResponse::InvalidRequestData {
use this as a variable here and in other places

2023-08-07 11:49 UTC, jagan-jaya approved these changes

2023-08-09 07:48 UTC, jagan-jaya approved these changes

2023-08-09 08:35 UTC, jarnura approved these changes

2023-08-09 08:43 UTC, merged