ci(postman): Use dynamic amount for Authorizedotnet, remove retries, add zen collection and disable globalpay
juspay/hyperswitch pull request #1859
Opened 2023-08-03 12:05 UTC by pixincreate

## Type of Change

- [x] Bugfix
- [x] CI/CD

## Description

- Modified Authorize.net collection to use dynamic amount instead of adding backoff since this backoff seems to do more harm than good. Also, removed retries and disabled Globalpay from running given its inconsistencies.
- Added Zen Collection. It works under Static IP, hence added, it will fail here since the IP is not static, and hence the Zen collection is disabled.

## Motivation and Context

Fix

## How did you test it?

Ran the collection.

## Checklist

- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible

2023-08-03 13:18 UTC, ashokkjag approved these changes

2023-08-03 21:46 UTC, SanchithHegde submitted a review, later dismissed

2023-08-04 08:47 UTC, jarnura approved these changes

2023-08-04 08:51 UTC, jarnura requested changes
Ask respective to dev to check the connector doc's, this will happen only in sandbox of their system?

2023-08-04 18:23 UTC, SanchithHegde approved these changes

2023-08-07 06:42 UTC, jarnura approved these changes

2023-08-08 09:33 UTC, jarnura approved these changes

2023-08-08 09:44 UTC, SanchithHegde approved these changes

2023-08-08 11:29 UTC, ashokkjag approved these changes

2023-08-08 14:26 UTC, merged