feat(config): add config support to pt_mapping along with redis
juspay/hyperswitch pull request #1861
Opened 2023-08-03 14:19 UTC by NishantJoshi00

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Currently, the `pt_mapping` only supported configuration set directly in the redis which can be in-consistent. This PR stabilizes this by adding support for picking the config directly from the `configs`

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
![Screenshot 2023-08-03 at 7 48 46 PM](https://github.com/juspay/hyperswitch/assets/51093026/e4fbbf56-14d8-4df2-863a-66df4bd10e51)
Tested the set functionality of config table, and then the parsing of the entry in the function changed here
<img width="1725" alt="Screenshot 2023-08-03 at 7 49 30 PM" src="https://github.com/juspay/hyperswitch/assets/51093026/4e51a736-cfdc-422b-8d12-79cac90e4cf5">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-03 21:48 UTC, SanchithHegde approved these changes

2023-08-04 09:17 UTC, dracarys18 approved these changes

2023-08-04 09:18 UTC, dracarys18 requested changes

2023-08-04 09:18 UTC, dracarys18 commented on crates/router/src/scheduler/workflows/payment_sync.rs
> +        .find_config_by_key(&format!("pt_mapping_{connector}"))
Use `find_config_by_key_cached` instead for blazingly fast results

2023-08-04 09:25 UTC, dracarys18 approved these changes

2023-08-04 11:16 UTC, inventvenkat approved these changes

2023-08-04 18:07 UTC, SanchithHegde approved these changes

2023-08-04 19:11 UTC, merged