feat(connector):[Payme] Support Apple Pay
juspay/hyperswitch pull request #1879
Opened 2023-08-07 07:06 UTC by Sangamesh26

## Type of Change

- [x] New feature

## Description

Support Apple Pay for PayMe

Steps followed:
1. Session call: We will get an empty object with delayed session and connector as `payme` and next-action as `confirm`
2. confirm call: we hit `generate-sale` endpoint of PayMe to get payme-seller-id
3. Hyperswitch provides next_action that sdk has to use whcih contains `connector_reference_id`
4. Payment will reach to terminal status in sdk, so, there should be a retrieve call to hyperswitch that updates the status in the system

### Additional Changes

- [x] This PR modifies the API contract
- [x] This PR modifies application configuration/environment variables

Added `payme` in `connectors_with_delayed_session_response`, as payme also follows delayed session flow

## Motivation and Context

Add support for Apple Pay through PayMe

## How did you test it?

Local testing not possible

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-08-07 11:29 UTC, ArjunKarthik requested changes
Please take changes required for cards also in this PR

2023-08-07 11:29 UTC, ArjunKarthik commented on crates/router/src/connector/payme/transformers.rs
> +            PaymentMethodData::Wallet(_) => Ok(Self::ApplePay), //Later when Google Pay comes, we can have a check for wallets
Let's have condition for ApplePay

2023-08-07 11:29 UTC, ArjunKarthik commented on crates/router/src/connector/payme/transformers.rs
> +                            next_action: api_models::payments::NextActionCall::InvokeSdkAndEnd,
add sync also

2023-08-08 14:05 UTC, ArjunKarthik requested changes

2023-08-14 12:47 UTC, ArjunKarthik commented
@Sangamesh26 If this PR is not required, can you close this?

2023-08-16 07:31 UTC, closed without merging

2023-08-16 07:31 UTC, Sangamesh26 commented
Closing this, as same has been covered in #1922