feat(connector): [PayMe] Implement preprocessing flow for cards
juspay/hyperswitch pull request #1904
Opened 2023-08-09 10:44 UTC by Sangamesh26

## Type of Change

- [x] New feature

## Description

Use Preprocessing flow for cards in payme instead of execute_pretasks, as we can eradicate 5xx with preprocessing flows.

## Motivation and Context

Implement preprocessing for payme cards

## How did you test it?

Handling 5xx for failures
<img width="1245" alt="Screen Shot 2023-08-09 at 2 37 42 PM" src="https://github.com/juspay/hyperswitch/assets/59434228/489c494d-7269-435b-bd9e-5a4567b53ed5">

Happy case for card payments
<img width="1266" alt="Screen Shot 2023-08-09 at 2 32 42 PM" src="https://github.com/juspay/hyperswitch/assets/59434228/a6e7af74-5256-4f2c-b94e-6a0cdd4d3e9a">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-08-09 14:10 UTC, ArjunKarthik requested changes

2023-08-10 07:25 UTC, ArjunKarthik approved these changes

2023-08-10 07:52 UTC, ArjunKarthik approved these changes

2023-08-10 07:55 UTC, Narayanbhat166 commented on crates/router/src/core/payments.rs
> +            }
Why should card payments go through pre processing flow?

2023-08-10 08:09 UTC, Narayanbhat166 approved these changes

2023-08-10 15:29 UTC, ashokkjag approved these changes

2023-08-10 17:22 UTC, SanchithHegde approved these changes

2023-08-10 18:08 UTC, merged