feat(api_client): add api client trait
juspay/hyperswitch pull request #1919
Opened 2023-08-11 07:03 UTC by harsh-sharma-juspay

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-11 13:04 UTC, lsampras requested changes

2023-08-11 13:04 UTC, lsampras commented on crates/router/src/services/api/client.rs
> +            inner: Some(self.proxy_client.request(method, url)),
```suggestion
            inner: Some(self.get_reqwest_client(...)),
```

Also add the below  methods to `trait ApiClient` & use them in this function with the default values as None

```
pub fn request_with_certificate(&self, certificate: Option<String>, certificate_key: Option<String>);
```

2023-08-16 18:21 UTC, lsampras requested changes

2023-08-16 18:21 UTC, lsampras commented on crates/router/src/services/api/client.rs
> +                    Ok(self.proxy_client.clone())
if a  client certificate is present we should build a proxied client (unless whitelisted URL's)
you can store the proxy config in the `ProxyClient` struct for this case

2023-08-22 07:14 UTC, lsampras submitted a review, later dismissed

2023-08-22 09:12 UTC, lsampras approved these changes

2023-08-22 19:30 UTC, SanchithHegde approved these changes

2023-08-24 10:33 UTC, merged