feat(router): send 2xx payments response for all the connector http responses (2xx, 4xx etc.)
juspay/hyperswitch pull request #1924
Opened 2023-08-11 08:29 UTC by sai-harsha-vardhan

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
send 2xx payments response for all the connector http responses (2xx, 4xx etc.)

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
Tested Manually
Payments 4xx from connector - 2xx payments response with Connector_http_status_code response header
![image](https://github.com/juspay/hyperswitch/assets/56996463/f85be1e9-975f-4335-b8b2-f755487ed7f6)

Payments Capture 4xx from connector
![image](https://github.com/juspay/hyperswitch/assets/56996463/97698f63-8b9f-42ca-9000-7c793ac8cb76)
![image](https://github.com/juspay/hyperswitch/assets/56996463/cdcee8f0-dfea-434e-a9a3-c856a8f18f49)

Payments Cancel 4xx from connector
![image](https://github.com/juspay/hyperswitch/assets/56996463/c1639cf5-692a-4231-9546-400f8cdcc268)
![image](https://github.com/juspay/hyperswitch/assets/56996463/fb89ab25-9a56-4df4-917f-d0aea52f3df7)

Payments Retrieve 4xx from connector
![image](https://github.com/juspay/hyperswitch/assets/56996463/3e48de5d-ff96-40b4-94ed-cecba6dede4a)
![image](https://github.com/juspay/hyperswitch/assets/56996463/b3dec1cf-a387-4fab-9c81-2091ace44d9d)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-16 06:49 UTC, Narayanbhat166 approved these changes

2023-08-17 06:52 UTC, jarnura requested changes

2023-08-17 06:52 UTC, jarnura commented on crates/router/src/services/api.rs
> +                                        .handle_response(req, body.clone())
Try to remove the clone.

2023-08-17 08:51 UTC, jarnura approved these changes

2023-08-17 09:24 UTC, Narayanbhat166 approved these changes

2023-08-17 10:04 UTC, merged