fix(frm): add new column frm_config instead of alterning the existing…
juspay/hyperswitch pull request #1925
Opened 2023-08-11 08:46 UTC by jagan-jaya

## Type of Change

- [X] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

We added a change for frm_config to support array in MCA with the below changes 
```UPDATE merchant_connector_account set frm_configs = null ;

ALTER TABLE merchant_connector_account 
ALTER COLUMN frm_configs TYPE jsonb[]
USING ARRAY[frm_configs]::jsonb[];

UPDATE merchant_connector_account set frm_configs = null ;
```
This will result in production downtime as we are touching the mca. 

So this PR will fix the downtime by adding a new column
### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

NA

## How did you test it?

Ran sanity tests manually in local

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed submitted code

2023-08-11 08:53 UTC, inventvenkat submitted a review, later dismissed

2023-08-11 09:21 UTC, jarnura requested changes

2023-08-11 09:21 UTC, jarnura commented on migrations/2023-08-11-073905_add_frm_config_in_mca/up.sql
> +ALTER TABLE "merchant_connector_account" DROP COLUMN IF EXISTS frm_configs;
The running application asks for the column and the column is removed means that will break the current application which is running in environments.

So we can't drop a existing column which a application schema uses it.

2023-08-11 11:23 UTC, jarnura approved these changes

2023-08-11 12:50 UTC, inventvenkat approved these changes

2023-08-11 13:14 UTC, merged

2023-08-16 12:08 UTC, jagan-jaya commented
This will require the sanity testing for a normal payment. As it is a breaking change this will affect all the payment flows and frm flows. so if the normal payment works frm will also work.