fix(compatibility): update BillingDetails mappings in SCL
juspay/hyperswitch pull request #1926
Opened 2023-08-11 09:23 UTC by kritikmodi

## Type of Change

- [x] Bugfix

## Description

SCL accepts `postal_code` instead of `zip` in the `payment_method_data` field. So, this PR adds the corresponding struct changes and mappings for `BillingDetails` -> `AddressDetails`.

## Motivation and Context

This PR closes https://github.com/juspay/hyperswitch/issues/1762.

## How did you test it?

Manually using Postman :

<img width="1728" alt="Screen Shot 2023-08-11 at 2 40 51 PM" src="https://github.com/juspay/hyperswitch/assets/61862301/d228b9e4-183f-4626-a093-c55f5c0e53c8">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-08-11 09:36 UTC, kritikmodi commented
Testcases :

**Testcase 1 :** Pass `payment_method_data[billing_details][address][postal_code]` in the body and it will populate the `postal_code` field.
**Testcase 2 :** Pass `payment_method_data[billing_details][address][xyz]` in the body and it won't populate the `postal_code` field.

2023-08-11 09:48 UTC, dracarys18 requested changes

2023-08-11 09:48 UTC, dracarys18 commented on crates/router/src/compatibility/stripe/payment_intents/types.rs
> +            },
```suggestion
            address: details.address.map(|address| 
               payments::AddressDetails {
                    city: address.city,
                    country: address.country,
                    line1: address.line1,
                    line2: address.line2,
                    zip: address.postal_code,
                    state: address.state,
                    first_name: None,
                    line3: None,
                    last_name: None,
                }),
```

2023-08-11 09:51 UTC, Abhicodes-crypto submitted a review, later dismissed

2023-08-11 09:53 UTC, dracarys18 approved these changes

2023-08-13 18:36 UTC, inventvenkat submitted a review, later dismissed

2023-08-23 07:07 UTC, dracarys18 submitted a review, later dismissed

2023-09-05 08:29 UTC, Abhicodes-crypto approved these changes

2023-09-06 11:40 UTC, vspecky approved these changes

2023-09-11 06:47 UTC, inventvenkat approved these changes

2023-09-25 10:15 UTC, merged

2023-09-27 08:59 UTC, kritikmodi commented
Testcase : Pass `postal_code` in `BillingAddress` while making a payment via SCL. It will be updated with the value passed as can be seen in the response body.