feat(core): add psync for multiple partial captures
juspay/hyperswitch pull request #1934
Opened 2023-08-15 20:07 UTC by hrithikesh026

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Currently there is no implementation for syncing payments with multiple partial captures.
In this pr I have added support for the same.
For any payment involving multiple partial captures, we will sync each capture with the connector and then update the attempt_status based on all capture status and total captured amount.

- Some connectors can fetch all captures for a payment in a single get request. For such connectors the status update for each pending captures should be made at the connector side. 
- For connector that can only do sync on individual captures, That logic is handled at core.

### Additional Changes

- [x] This PR modifies the API contract
- [x] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Manual
<img width="1728" alt="Screenshot 2023-08-16 at 1 36 53 AM" src="https://github.com/juspay/hyperswitch/assets/61539176/66738990-3b0c-4ad8-980a-a86086d237ad">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-16 07:36 UTC, jarnura requested changes

2023-08-16 07:36 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_capture.rs
> +                        status: None,
If this will be always None in this particular case remove status

2023-08-16 07:36 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_response.rs
> +                        // attempt status will depend on collective capture status
the comment not explains this is attempt update object

2023-08-16 07:36 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_response.rs
> +                let (capture_updates, payment_attempt_update) = if let Some(multiple_capture_data) =
use case match instead of if let some()

2023-08-16 07:36 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_response.rs
> +fn multiple_capture_update<F: Clone, T: types::Capturable>(
change function name to construct

2023-08-16 10:45 UTC, jarnura requested changes

2023-08-22 12:12 UTC, jarnura requested changes

2023-08-22 12:12 UTC, jarnura commented on crates/router/src/types/storage/payment_attempt.rs
> +                .get_required_value("connector")
Change this to Internal Server Error

2023-08-22 15:13 UTC, Narayanbhat166 submitted a review, later dismissed

2023-08-22 17:33 UTC, jarnura approved these changes

2023-08-23 04:27 UTC, Narayanbhat166 approved these changes

2023-08-23 05:01 UTC, merged