refactor(connector): [Adyen] refactor adyen payment method not implemented errors
juspay/hyperswitch pull request #1950
Opened 2023-08-17 07:39 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Issue: defaults case in match shouldn't be handled using "_"

Solution: "_" will never let the developer know impact of his changes incase of new addition of enum variants. By having the all cases in match compiler itself will throw errors wherever new enums needs to be handled

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
![Screen Shot 2023-08-17 at 1 00 15 PM 2](https://github.com/juspay/hyperswitch/assets/85639103/8b9fb3f2-b38f-444f-bef5-2e0a8d0f49d9)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-18 07:53 UTC, ArjunKarthik approved these changes

2023-08-18 07:53 UTC, ArjunKarthik commented on crates/router/src/connector/utils.rs
> +pub const UNSUPPORTED_PAYMENT_METHOD_ERROR_MESSAGE: &str = "Selected payment method";
rename this to SELECTED_PAYMENT_METHOD and use it in `get_unimplemented_payment_method_error_message` method

2023-08-18 07:53 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +                            message: format!("mandate_{:?}", item.payment_method),
change message to "Network tokenization for payment method"

2023-08-18 07:53 UTC, ArjunKarthik requested changes
Please fix the minor comments

2023-08-18 10:35 UTC, srujanchikke submitted a review, later dismissed

2023-09-04 20:54 UTC, SanchithHegde submitted a review, later dismissed

2023-09-04 20:54 UTC, SanchithHegde commented on crates/router/src/connector/utils.rs
> +    format!("{} through {}", SELECTED_PAYMENT_METHOD, connector)
This could have been:

```suggestion
    format!("{SELECTED_PAYMENT_METHOD} through {connector}")
```

Optional change, btw.

2023-09-08 13:57 UTC, SanchithHegde approved these changes

2023-09-08 14:04 UTC, merged