fix(connector): [Adyen] `ErrorHandling` in case of Balance Check for Gift Cards
juspay/hyperswitch pull request #1976
Opened 2023-08-21 12:59 UTC by Sakilmostak

`##` Type of Change

- [x] Bugfix

## Description

5xx error was being thrown in case of low balance which was unable to show the error to the merchant. Fix include failing the payment along with the error message in case of low balance

## How did you test it?
Through Postman
Success Case: 
`{
    "amount": 4100,
    "currency": "EUR",
    "confirm": true,
    "capture_method": "automatic",
    "capture_on": "2022-09-10T10:11:12Z",
    "amount_to_capture": 100,
    "customer_id": "StripeCustomer",
    "email": "guest@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+1",
    "description": "Its my first payment request",
    "authentication_type": "no_three_ds",
    "return_url": "https://google.com",
    "payment_method": "gift_card",
    "payment_method_type": "givex",
    "payment_method_data": {
        "gift_card": {
            "givex": {
                "number": "6364530000000000",
                "cvc": "122222"
            }
        }
    },
    "billing": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "GB",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        }
    },
    "browser_info": {
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36",
        "accept_header": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "language": "nl-NL",
        "color_depth": 24,
        "screen_height": 723,
        "screen_width": 1536,
        "time_zone": 0,
        "java_enabled": true,
        "java_script_enabled": true,
        "ip_address": "127.0.0.1"
    },
    "shipping": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "GB",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        }
    },
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    "metadata": {
        "udf1": "value1",
        "new_customer": "true",
        "login_date": "2019-09-10T10:11:12Z"
    }
}`
Failure Case: 
`{
    "amount": 14100,
    "currency": "EUR",
    "confirm": true,
    "capture_method": "automatic",
    "capture_on": "2022-09-10T10:11:12Z",
    "amount_to_capture": 100,
    "customer_id": "StripeCustomer",
    "email": "guest@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+1",
    "description": "Its my first payment request",
    "authentication_type": "no_three_ds",
    "return_url": "https://google.com",
    "payment_method": "gift_card",
    "payment_method_type": "givex",
    "payment_method_data": {
        "gift_card": {
            "givex": {
                "number": "6364530000000000",
                "cvc": "122222"
            }
        }
    },
    "billing": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "GB",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        }
    },
    "browser_info": {
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36",
        "accept_header": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "language": "nl-NL",
        "color_depth": 24,
        "screen_height": 723,
        "screen_width": 1536,
        "time_zone": 0,
        "java_enabled": true,
        "java_script_enabled": true,
        "ip_address": "127.0.0.1"
    },
    "shipping": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "GB",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        }
    },
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    "metadata": {
        "udf1": "value1",
        "new_customer": "true",
        "login_date": "2019-09-10T10:11:12Z"
    }
}`

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-27 09:54 UTC, ArjunKarthik commented
Please fix the conflicts and add test screenshots

2023-10-06 10:39 UTC, ArjunKarthik requested changes

2023-10-06 10:39 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +    pub currency: String,
Let's have enum for currency

2023-10-06 10:39 UTC, ArjunKarthik commented on crates/router/src/connector/adyen.rs
> +                    reason: None,
pass LOW_BALANCE_ERROR_MESSAGE in reason also

2023-10-06 10:39 UTC, ArjunKarthik commented on crates/router/src/connector/adyen.rs
> +                    message: consts::LOW_BALANCE_ERROR_MESSAGE.to_string(),
for message: pass NO_ERROR_MESSAGE

2023-10-06 10:39 UTC, ArjunKarthik commented on crates/router/src/consts.rs
> +pub(crate) const LOW_BALANCE_ERROR_MESSAGE: &str = "Balance in the payment method is low";
Insufficient balance in the payment method

2023-10-27 12:28 UTC, ArjunKarthik approved these changes

2023-10-31 07:07 UTC, srujanchikke commented on crates/router/src/connector/adyen/transformers.rs
> +                currency: item.response.balance.currency.to_string(),
Can this be also changed to `storage_enums::Currency`

2023-10-31 09:50 UTC, srujanchikke approved these changes

2023-11-28 10:36 UTC, ArjunKarthik requested changes

2023-11-28 10:36 UTC, ArjunKarthik commented on crates/router/src/connector/adyen.rs
> +                    attempt_status: None,
send failed status

2023-11-28 10:50 UTC, ArjunKarthik approved these changes

2023-11-28 10:55 UTC, srujanchikke approved these changes

2023-11-28 12:21 UTC, merged