feat(connector): (checkout_dot_com) add support for multiple partial captures
juspay/hyperswitch pull request #1977
Opened 2023-08-21 17:26 UTC by hrithikesh026

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Checkout doesn't support multiple partial captures currently. This PR brings support for multiple partial capture in checkout.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Manual

Create payment with `capture_method` = `manual_multiple`
<img width="1728" alt="Screenshot 2023-08-21 at 10 50 45 PM" src="https://github.com/juspay/hyperswitch/assets/61539176/a570d52f-6e7c-4bd0-b0a2-449739d9c5fa">

Partially capture the payment (status changes to `partially_captured`)
<img width="1728" alt="Screenshot 2023-08-21 at 10 51 09 PM" src="https://github.com/juspay/hyperswitch/assets/61539176/570c6ac3-1dae-4f86-a9b5-6f149f4afe83">

Capture remaining amount and status changes to `succeeded`
<img width="1728" alt="Screenshot 2023-08-21 at 10 51 23 PM" src="https://github.com/juspay/hyperswitch/assets/61539176/332d7abd-b95f-4e8b-ab31-291dc5a17816">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-24 05:43 UTC, ArjunKarthik requested changes

2023-08-24 05:43 UTC, ArjunKarthik commented on crates/router/src/connector/checkout/transformers.rs
> +        let capture_type = if item.request.multiple_capture_data.is_some() {
Create a util method is_multiple_capture() -> bool for types::PaymentsCaptureRouterData in `crates/router/src/connector/utils.rs`.

2023-08-24 05:43 UTC, ArjunKarthik commented on crates/router/src/connector/checkout/transformers.rs
> +            item.response.action_id
Let's have discussion on this

2023-08-28 10:19 UTC, ArjunKarthik requested changes

2023-08-28 10:19 UTC, ArjunKarthik commented on crates/router/src/connector/checkout/transformers.rs
> +        let resource_id = if item.data.request.multiple_capture_data.is_some() {
use item.request.is_multiple_capture()

2023-08-28 10:19 UTC, ArjunKarthik commented on crates/router/src/connector/checkout/transformers.rs
> +        let resource_id = if item.data.request.multiple_capture_data.is_some() {
Add comments on why we need this if else statement

2023-08-28 10:31 UTC, ArjunKarthik submitted a review, later dismissed

2023-08-28 14:21 UTC, ArjunKarthik approved these changes

2023-08-29 10:53 UTC, jarnura approved these changes

2023-08-29 11:20 UTC, merged