test(connector): add support for adyen webhooks
juspay/hyperswitch pull request #1999
Opened 2023-08-23 17:13 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
This PR add support for adyen webhooks and fix checkout webhooks.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
![Screen Shot 2023-08-23 at 8 23 35 PM 2](https://github.com/juspay/hyperswitch/assets/85639103/5ffc96cf-7a77-4325-b34d-ab81cbec32db)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [x] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-23 17:33 UTC, srujanchikke requested changes

2023-08-23 17:33 UTC, srujanchikke commented on crates/test_utils/tests/connectors/checkout_wh_ui.rs
>          "succeeded",
You need to change this too succeeded or processing . Because payment status we are asserting for both states .  Checkout sends webhooks both states

2023-08-25 06:03 UTC, srujanchikke approved these changes

2023-08-25 06:08 UTC, ArjunKarthik approved these changes

2023-08-25 06:19 UTC, SanchithHegde approved these changes

2023-08-25 06:50 UTC, merged