refactor(core): use profile id to find connector
juspay/hyperswitch pull request #2020
Opened 2023-08-25 10:47 UTC by Narayanbhat166

## Type of Change

- [x] Refactoring

## Description

This PR will make the necessary changes to use `profile_id` to query the connector in payments, refunds, disputes and payouts flow. 
For a merchant with single business_profile there would be no difference, for merchants with more than one business profile, `profile_id` will have to be sent in the payments request. 

In order to keep supporting the existing merchants to migrate to new change, passing business country and business label is still supported. This will be deprecated soon and only profile_id will be accepted.

### Additional Changes

- [x] This PR modifies the API contract.
- [x] This PR modifies database schema. 

## Motivation and Context

To move towards using `profile_id`.

## How did you test it?

- Create a payment, default profile id should be used to query the connector.
<img width="530" alt="Screenshot 2023-08-25 at 4 16 07 PM" src="https://github.com/juspay/hyperswitch/assets/48803246/c404ef6a-caf4-4ee6-b308-96d576576376">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

2023-08-29 08:55 UTC, jarnura approved these changes

2023-08-31 20:23 UTC, jarnura requested changes

2023-08-31 20:23 UTC, jarnura commented on migrations/2023-08-28-131238_make_business_details_optional/up.sql
> +CREATE UNIQUE INDEX IF NOT EXISTS business_profile_merchant_id_profile_name_index ON business_profile(merchant_id, profile_name);
we need to have profile_id alone as unique.

2023-09-01 09:06 UTC, jarnura submitted a review, later dismissed

2023-09-04 09:16 UTC, ashokkjag approved these changes

2023-09-06 07:17 UTC, jarnura submitted a review, later dismissed

2023-09-11 06:43 UTC, jarnura approved these changes

2023-09-11 07:25 UTC, bernard-eugine approved these changes

2023-09-11 07:32 UTC, merged