refactor(recon): updating user flow for recon
juspay/hyperswitch pull request #2029
Opened 2023-08-28 06:07 UTC by anji-reddy-j

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
 
Changing is_recon_enabled field to recon_status as an enum , to update the user flow

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [x] I added unit tests for my changes where possible
- [x] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-28 10:55 UTC, jagan-jaya requested changes

2023-08-28 10:55 UTC, jagan-jaya commented on migrations/2023-08-25-094551_add_recon_status_in_merchant_account/up.sql
> +ALTER TABLE merchant_account ADD recon_status "ReconStatus" NOT NULL DEFAULT "ReconStatus"('not_requested');
please move it to one place, it will be hard to maintain in 2 places

2023-08-28 13:57 UTC, jagan-jaya approved these changes

2023-08-28 14:04 UTC, kashif-m commented on crates/api_models/src/admin.rs
> +    #[schema(value_type = ReconStatus, example = "not_request")]
Make it `not_requested`

2023-08-28 14:22 UTC, kashif-m approved these changes

2023-08-28 14:23 UTC, jagan-jaya approved these changes

2023-08-29 06:38 UTC, Narayanbhat166 approved these changes

2023-08-29 10:49 UTC, merged