feat(core): enable payments void for multiple partial capture
juspay/hyperswitch pull request #2048
Opened 2023-08-29 14:12 UTC by hrithikesh026

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This feature would allow merchant to void the remaining authorized amount on the multiple partial capture payment after partial capture.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Manual

Create a payment with` capture_method = manual_multiple`
<img width="1728" alt="Screenshot 2023-08-29 at 7 36 10 PM" src="https://github.com/juspay/hyperswitch/assets/61539176/ed227ae8-5447-45ff-8c9b-e76ec8bd2b6c">

Partial Capture the payment 
<img width="1728" alt="Screenshot 2023-08-29 at 7 31 29 PM" src="https://github.com/juspay/hyperswitch/assets/61539176/60cac038-e241-4e27-9729-04c8ac36c55a">

Void the payment
<img width="1728" alt="Screenshot 2023-08-29 at 7 31 37 PM" src="https://github.com/juspay/hyperswitch/assets/61539176/079bdca0-2bc8-4728-a3e0-3d6efd6cc1e2">
4-6b7eddb0cafa">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-31 11:11 UTC, jarnura submitted a review, later dismissed

2023-09-04 09:19 UTC, jarnura requested changes

2023-09-04 09:19 UTC, jarnura commented on crates/router/src/core/payments/transformers.rs
> +                let amount_capturable = if should_calculate_amount_to_capture(payment_intent.status)
this data will be available on the parent payment_attempt as amount_to_capture right?

Can we use that instead calculating it again?.

2023-09-08 07:17 UTC, jarnura submitted a review, later dismissed

2023-09-11 12:10 UTC, Narayanbhat166 approved these changes

2023-09-11 17:14 UTC, jarnura approved these changes

2023-09-11 17:24 UTC, Narayanbhat166 approved these changes

2023-09-11 17:50 UTC, merged