fix(connector): [Paypal] fix PSync for redirection flow for PayPal
juspay/hyperswitch pull request #2068
Opened 2023-08-31 15:07 UTC by prasunna09

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

fix PSync for redirection flow for PayPal

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

<img width="1214" alt="Screenshot 2023-08-31 at 8 36 08 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/d5c5fd09-95e3-4a18-879d-a914b677075b">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-31 17:46 UTC, ArjunKarthik requested changes
as discussed let's implement try_from instead of methods

2023-08-31 20:45 UTC, jagan-jaya approved these changes

2023-08-31 20:47 UTC, SanchithHegde approved these changes

2023-09-01 05:07 UTC, ArjunKarthik approved these changes

2023-09-01 05:29 UTC, merged