feat(core): add runtime flag to disable dummy connector
juspay/hyperswitch pull request #2100
Opened 2023-09-07 10:10 UTC by apoorvdixit88

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Added flag to disable dummy connector in prod.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
For is_enabled = false;
![image](https://github.com/juspay/hyperswitch/assets/64925866/f68dfeb6-3559-4109-b5d4-cb7636491493)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-07 10:14 UTC, ThisIsMani submitted a review, later dismissed

2023-09-08 08:50 UTC, NishantJoshi00 requested changes

2023-09-08 08:50 UTC, NishantJoshi00 commented on crates/router/src/core/admin.rs
> +    }
```suggestion
    validate_dummy_connector_enabled(state, &req.connector_name).await?;
```

2023-09-08 08:50 UTC, NishantJoshi00 commented on crates/router/src/core/admin.rs
> +                    message: format!("{} is not enabled", connector_name),
Can we change the message here. This message provides significant information about the feature being present in one case and in other. Instead when disabled it shouldn't reveal the existence of this behaviour.

Something like
`invalid connector name`?

2023-09-08 08:50 UTC, NishantJoshi00 commented on crates/router/src/core/admin.rs
> +    if !state.conf.dummy_connector.is_enabled {
avoid using return, and here we don't need match. consider using 

`matches!`

2023-09-11 13:35 UTC, NishantJoshi00 submitted a review, later dismissed
LGTM

2023-09-11 13:51 UTC, ThisIsMani submitted a review, later dismissed

2023-09-11 19:30 UTC, SanchithHegde reviewed
Other than that, looks good to me!

2023-09-11 19:30 UTC, SanchithHegde commented on crates/router/src/configs/settings.rs
> +    pub is_enabled: bool,
We could have named this as `enabled` to keep it consistent with the rest of our application config values (take console or file logging configuration for example).

2023-09-12 09:11 UTC, ThisIsMani approved these changes

2023-09-12 09:26 UTC, SanchithHegde approved these changes

2023-09-12 09:37 UTC, merged