feat(connector): (adyen) add support for multiple partial capture adyen
juspay/hyperswitch pull request #2102
Opened 2023-09-07 11:34 UTC by hrithikesh026

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR enables multiple partial capture for Adyen.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-12 07:10 UTC, jarnura submitted a review, later dismissed

2023-09-13 15:05 UTC, ArjunKarthik requested changes

2023-09-13 15:05 UTC, ArjunKarthik commented on crates/router/src/core/payments/flows/psync_flow.rs
> +            if let payments::CallConnectorAction::HandleResponse(_) = call_connector_action {
Let's keep this logic outside for loop, Incase of HandleResponse execute_connector_processing_step should be called only once and For trigger use the existing loop

2023-09-15 07:28 UTC, jarnura approved these changes

2023-09-15 07:37 UTC, merged