refactor(connector): [BraintreeGraphQl] Enhance currency Mapping with `ConnectorCurrencyCommon` Trait
juspay/hyperswitch pull request #2108
Opened 2023-09-08 11:05 UTC by srujanchikke

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Problem : Currently, amount mapping for different connectors are handled by hard coding dollars/cents which has been leading to multiple bugs due to incorrect mapping. Need to handle this better in code by having separate types for dollar vs cents .

Solution : To address this issue and improve code maintainability, this pull request introduces the `ConnectorCurrencyCommon` trait. This trait allows connectors to declare their accepted currency unit as either "Base" or "Minor" using the `get_currency_unit method`.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Implement the `ConnectorCurrencyCommon` trait, where you can declare the accepted currency unit (either Base or Minor) using the `get_currency_unit method`.

## How did you test it?

tested through braintree dashboard .

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-08 13:27 UTC, SanchithHegde approved these changes

2023-09-10 13:16 UTC, ArjunKarthik requested changes

2023-09-10 13:16 UTC, ArjunKarthik commented on crates/router/src/connector/braintree/braintree_graphql_transformers.rs
> +impl ConnectorCurrencyCommon for PaymentsAuthorizeData {
Please add this in script also, Let's implement ConnectorCurrencyCommon without get_currency_unit impl in the script

2023-09-13 07:53 UTC, srujanchikke commented
Closing this pr in favor of #2143

2023-09-13 07:53 UTC, closed without merging

2023-11-05 00:16 UTC, hankqqu commented
>