fix(router): associate parent payment token with `payment_method_id` as hyperswitch token for saved cards
juspay/hyperswitch pull request #2130
Opened 2023-09-12 10:52 UTC by vspecky

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR implements some missing components of #2073 , mainly the logic to associate the generated parent payment token with the `payment_method_id` as opposed to a randomly generated temp locker token in the saved cards flow, so a call can be made directly to the persistent locker to fetch card details.

### Additional Changes
None
- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Due to the missing association between parent payment token and the payment method id as hyperswitch token for saved cards, the saved cards flow had some potential issues which needed to be addressed.

## How did you test it?

Testing pending...

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-18 12:45 UTC, jarnura requested changes
Don't

2023-09-18 12:45 UTC, jarnura commented on crates/router/src/types/storage/payment_method.rs
> +pub enum HypsTokenKind {
Avoid using hyperswitch and hyps in codebase

2023-09-18 12:45 UTC, jarnura commented on crates/router/src/types/storage/payment_method.rs
> +pub enum HypsTokenKind {
```suggestion
pub enum RouterTokenKind {
```

2023-09-18 12:45 UTC, jarnura commented on crates/router/src/types/storage/payment_method.rs
> +pub struct HyperswitchTokenData {
```suggestion
pub struct RouterTokenData {
```

2023-09-18 12:45 UTC, jarnura commented on crates/router/src/core/payments/helpers.rs
> +        (_, Some(hyperswitch_token)) => match hyperswitch_token.kind {
Avoid writing long implementation, split branching into separate functions and writing comments for those.

2023-09-20 09:03 UTC, jarnura submitted a review, later dismissed

2023-09-20 11:03 UTC, Sarthak1799 approved these changes

2023-10-12 07:38 UTC, Sarthak1799 commented on crates/router/src/core/payments/helpers.rs
> +                    .attach_printable("failed to deserialize hyperswitch token data");
So token is being serialized as a `PaymentTokenData` and expected to be parsed as `HyperswitchTokenData`?
So is the other struct for old entries in redis?

2023-10-12 10:33 UTC, Sarthak1799 approved these changes

2023-10-17 11:10 UTC, jarnura approved these changes

2023-11-07 06:57 UTC, vspecky commented
Test Case :-
1. Saved cards flow should succeed
2. Temporary tokenization flow should succeed (card details given during Payments Create, then Payment Token given during Confirm)

2023-11-09 07:47 UTC, Sarthak1799 commented
Could you resolve the conflicts on the linked PR?

2023-11-16 09:36 UTC, jarnura approved these changes

2023-11-20 09:05 UTC, Sarthak1799 approved these changes

2023-11-20 11:00 UTC, merged