refactor(connector): [BraintreeGraphQl] Enhance currency Mapping with ConnectorCurrencyCommon Trait
juspay/hyperswitch pull request #2143
Opened 2023-09-13 07:51 UTC by srujanchikke

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Problem : Currently, amount mapping for different connectors are handled by hard coding dollars/cents which has been leading to multiple bugs due to incorrect mapping. Need to handle this better in code by having separate types for dollar vs cents .

Solution : To address this issue and improve code maintainability, this pull request introduces the `get_currecny_unit` from `ConnectorCommon` trait. This function allows connectors to declare their accepted currency unit as either "Base" or "Minor" .

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Implement the ConnectorCurrencyCommon trait, where you can declare the accepted currency unit (either Base or Minor) using the get_currency_unit method in `ConnectorCommon` trait .

## How did you test it?

tested it locally 

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x]  I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-13 09:56 UTC, ArjunKarthik requested changes

2023-09-13 09:56 UTC, ArjunKarthik commented on crates/router/src/connector/braintree/braintree_graphql_transformers.rs
> +                (item.req, &item.amount),
instead of passing tuple, pass &BriantreeAmountConversion

2023-09-13 09:56 UTC, ArjunKarthik commented on crates/router/src/connector/braintree/braintree_graphql_transformers.rs
> +pub struct BriantreeAmountConversion<T> {
rename this to BraintreeRouterData

2023-09-13 09:56 UTC, ArjunKarthik commented on crates/router/src/connector/braintree/braintree_graphql_transformers.rs
> +    pub req: T,
rename this to router_data

2023-09-13 09:56 UTC, ArjunKarthik commented on crates/router/src/connector/braintree/braintree_graphql_transformers.rs
> +                        &item.amount,
Change try_from implementation to (&BriantreeAmountConversion<&types::PaymentsAuthorizeRouterData>, metadata)

2023-09-13 09:56 UTC, ArjunKarthik commented on crates/router/src/connector/braintree.rs
> +        let conversion_req =
rename this to connector_router_data where ever it is being used

2023-09-13 17:38 UTC, SanchithHegde approved these changes
Looks good to me!

Have you verified correctness of connector template changes by generating the code for a new connector, just to test things out?

2023-09-13 18:59 UTC, srujanchikke commented
> Looks good to me!
> 
> Have you verified correctness of connector template changes by generating the code for a new connector, just to test things out?

Yes, i have verified it by generating the new connector template

2023-09-14 07:35 UTC, ArjunKarthik approved these changes

2023-09-14 07:43 UTC, merged