refactor(connector): [Adyen] psync validation check for adyen
juspay/hyperswitch pull request #2160
Opened 2023-09-14 09:19 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

![Screenshot 2023-09-14 at 2 48 02 PM 2](https://github.com/juspay/hyperswitch/assets/85639103/04bd89ee-21dd-4d31-a60c-bbbad25e3d43)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-15 09:53 UTC, srujanchikke approved these changes

2023-09-15 10:25 UTC, ArjunKarthik requested changes

2023-09-15 10:25 UTC, ArjunKarthik commented on crates/router/src/connector/adyen.rs
> +        Ok(())
Adyen supports PSync only incase of redirect flow. So we should validate the encoded data in the request, if it is not present we should not allow PSync call to the connector

2023-09-18 08:32 UTC, ArjunKarthik approved these changes

2023-09-18 12:32 UTC, srujanchikke approved these changes

2023-09-18 13:24 UTC, merged