feat(Connector): [Paypal] add support for manual multiple capture for Paypal
juspay/hyperswitch pull request #2181
Opened 2023-09-18 07:18 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
add support for manual multiple capture for Paypal Connector

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
<img width="1728" alt="Screenshot 2023-09-18 at 12 38 30 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/26a481c3-8140-4f31-99bd-96b9fba0faca">
<img width="1728" alt="Screenshot 2023-09-18 at 12 38 45 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/0a4a18b1-4668-4413-b878-39aaec3d788d">
<img width="1728" alt="Screenshot 2023-09-18 at 12 39 07 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/e2c55e07-12a2-4833-8ce2-e7ff72aed499">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-20 05:19 UTC, hrithikesh026 commented on crates/router/src/connector/paypal.rs
> +        dbg!(&response);
```suggestion
        router_env::logger::info!(connector_response=?response);
```

2023-09-20 05:21 UTC, hrithikesh026 commented
Can you please confirm if multiple captures are visible in paypal's dashboard and upload the screenshots for the same?

2023-10-09 06:56 UTC, ArjunKarthik commented
@swangi-kumari We will discuss on this change once you are back.

2023-10-09 06:59 UTC, ArjunKarthik requested changes
Only these changes not enough for multiple manual capture

2023-10-09 06:59 UTC, ArjunKarthik commented on crates/router/src/connector/utils.rs
> -            Some(diesel_models::enums::CaptureMethod::Manual) => Ok(false),
This is being used by multiple connectors, making changes here will impact all those connectors

2025-03-27 08:07 UTC, swangi-kumari commented
Not required

2025-03-27 08:07 UTC, closed without merging