feat(connector): [HELCIM] Activate Helcim
juspay/hyperswitch pull request #2210
Opened 2023-09-20 15:37 UTC by deepanshu-iiitu

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Helcim is a payment connector from North America.
Add Card payment support for Helcim.

Supported Flows:
- Authorize
- Capture
- PSync
- Void
- Refund
- RSync

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

Add Card Payments for Payments and Refunds flow for new connector helcim.

## How did you test it?

Testing was carried out via Unit Tests

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [x] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-03 10:01 UTC, ArjunKarthik requested changes

2023-10-03 13:37 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim.rs
> +
Done

2023-10-03 13:38 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim.rs
> +        Ok(header)
Done

2023-10-03 13:38 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim.rs
> +        Ok(header)
Done

2023-10-03 19:39 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim.rs
> +            reason: None,
Done

2023-10-03 19:39 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim.rs
> +            | enums::CaptureMethod::ManualMultiple => Ok(()),
Done

2023-10-03 19:40 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +    ecommerce: Option<bool>,
Added

2023-10-03 19:40 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +            _ => Err(errors::ConnectorError::NotImplemented("Payment methods".to_string()).into()),
Done

2023-10-03 19:40 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +                    .browser_info
Added

2023-10-03 19:40 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +                    ecommerce: None,
Done

2023-10-03 19:40 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +//TODO: Fill the struct with respective fields
Done

2023-10-03 19:44 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +            .get_ip_address()?;
According to Helcim Support Team:
`If these transaction types will be merchant initiated, then passing the IP address of the original transaction is sufficient.`
Hence resolving this conversation.

2023-10-04 09:37 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +                resource_id: types::ResponseId::ConnectorTransactionId(
While setting it to NoResponseId the capture transaction fails with the following error:
`{
    "error": {
        "type": "invalid_request",
        "message": "Resource ID does not exist in our records",
        "code": "HE_02"
    }
}`

Hence I am storing the `preauth_transaction_id` in `connector_transaction_id` as well as connector metadata during authorize call.
Later on while capture transaction I overwrite the `connector_transaction_id` with the `capture_id` received from connector.

2023-10-04 09:37 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +        let original_transaction_id = if item.router_data.request.connector_metadata.is_none() {
Done

2023-10-04 14:22 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim.rs
> +            code: response.errors.clone(),
Done

2023-10-09 08:57 UTC, ArjunKarthik requested changes

2023-10-09 08:57 UTC, ArjunKarthik commented on crates/router/src/connector/helcim/transformers.rs
> +            .ok_or_else(utils::missing_field_err("billing.address"))?;
let req_address = item.get_billing_address()?;

2023-10-09 08:57 UTC, ArjunKarthik commented on crates/router/src/connector/helcim/transformers.rs
> +                resource_id: types::ResponseId::ConnectorTransactionId(
In which step you are getting the above mentioned error? We should not rotate the connector_transaction_id. It is only primary id to identify the transaction at connector side

2023-10-09 08:57 UTC, ArjunKarthik commented on crates/router/src/connector/helcim/transformers.rs
> +                resource_id: types::ResponseId::ConnectorTransactionId(
Let me know, if incase you need discussion on this

2023-10-09 11:19 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +            .ok_or_else(utils::missing_field_err("billing.address"))?;
Done

2023-10-09 13:40 UTC, SamraatBansal requested changes

2023-10-09 13:40 UTC, SamraatBansal commented on crates/router/src/connector/helcim.rs
>  {
Merge with main to update the flow

2023-10-09 13:40 UTC, SamraatBansal commented on crates/router/src/connector/helcim.rs
> +    // }
Is this required?

2023-10-10 09:56 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim/transformers.rs
> +                resource_id: types::ResponseId::ConnectorTransactionId(
Implemented

2023-10-10 10:37 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim.rs
>  {
Done

2023-10-10 10:37 UTC, deepanshu-iiitu commented on crates/router/src/connector/helcim.rs
> +    // }
Yes.

2023-10-10 14:10 UTC, ArjunKarthik approved these changes

2023-10-10 14:13 UTC, SamraatBansal approved these changes

2023-10-10 14:45 UTC, SanchithHegde approved these changes
Other than that, looks good to me!

2023-10-10 14:45 UTC, SanchithHegde commented on crates/common_enums/src/transformers.rs
> +    pub const fn from_alpha2_to_alpha3(code: Self) -> CountryAlpha3 {
I'd prefer naming this just `to_alpha3`.

2023-10-13 12:53 UTC, merged