feat(router): add mertics to apple pay flow
juspay/hyperswitch pull request #2235
Opened 2023-09-21 11:26 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-21 14:26 UTC, vspecky requested changes

2023-09-21 14:26 UTC, vspecky commented on crates/router/src/core/payments.rs
> +                decide_apple_pay_flow(payment_method_type, is_apple_pay_predecrypt);
Return an `Option<ApplePayFlow>` from `is_applepay_predecrypt` function and use it in subsequent code. No need for another function.

2023-09-22 06:55 UTC, vspecky submitted a review, later dismissed

2023-09-22 07:15 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments.rs
> +            let parsed_metadata: Result<api_models::payments::ApplepaySessionTokenData, _> =
please log the error here

2023-09-22 07:15 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments.rs
> +) -> RouterResult<Option<enums::ApplePayFlow>> {
here need not return `RouterResult`

2023-09-22 07:15 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments.rs
> +) -> RouterResult<Option<enums::ApplePayFlow>> {
here need not return RouterResult

2023-09-22 09:50 UTC, Sangamesh26 approved these changes

2023-09-22 09:56 UTC, sai-harsha-vardhan approved these changes

2023-09-22 09:58 UTC, vspecky approved these changes

2023-09-22 10:36 UTC, srujanchikke approved these changes

2023-09-22 10:43 UTC, merged