feat(process_tracker): make long standing payments failed
juspay/hyperswitch pull request #2380
Opened 2023-09-27 09:00 UTC by Narayanbhat166

## Type of Change

- [x] New feature

## Description

This feature will make the payments that have been stuck in `Pending` attempt status because of connection timed out or some other 5xx error. These payments will not have the connector transaction id. So after the last retry by process tracker, these will be moved to failed.

## Motivation and Context

## How did you test it?

- Simulate a connection timed out payment.
- Wait for process tracker to make the status as `Failed`

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

2023-10-03 10:42 UTC, NishantJoshi00 submitted a review, later dismissed
If possible, it would be better to identify the payment whose status changed due to this last retry. to filter and identify them.
Other than that, looks good

2023-10-03 13:38 UTC, Narayanbhat166 commented
> If possible, it would be better to identify the payment whose status changed due to this last retry


Yes @NishantJoshi00. I have added a const error message for this purpose
`This Payment has been moved to failed as there is no response from the connector`

2023-10-05 07:48 UTC, jarnura approved these changes

2023-10-06 09:35 UTC, NishantJoshi00 submitted a review, later dismissed

2023-10-06 10:55 UTC, jarnura requested changes

2023-10-06 10:55 UTC, jarnura commented on crates/router/src/workflows/payment_sync.rs
> +                    crate::utils::trigger_payments_webhook::<
```suggestion
                    utils::trigger_payments_webhook::<
```

2023-10-06 10:55 UTC, jarnura commented on crates/router/src/workflows/payment_sync.rs
> +                                crate::consts::REQUEST_TIMEOUT_ERROR_MESSAGE_FROM_PSYNC.to_string(),
```suggestion
                                consts::REQUEST_TIMEOUT_ERROR_MESSAGE_FROM_PSYNC.to_string(),
```

2023-10-06 10:55 UTC, jarnura commented on crates/router/src/utils.rs
> +                crate::core::webhooks::create_event_and_trigger_appropriate_outgoing_webhook(
```suggestion
                core::webhooks::create_event_and_trigger_appropriate_outgoing_webhook(
```

2023-10-06 15:07 UTC, jarnura approved these changes

2023-10-09 09:01 UTC, NishantJoshi00 approved these changes

2023-10-09 09:09 UTC, merged