feat(pm_list): [Trustpay] add bank_redirect -  blik pm type required field info for trustpay
juspay/hyperswitch pull request #2390
Opened 2023-09-28 16:28 UTC by prasunna09

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add bank_redirect -  blik pm type required field info for trustpay , and made `blik_code` field as optional for blik bank redirect data

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

<img width="709" alt="Screenshot 2023-09-28 at 9 12 15 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/57ac48f1-6bde-495f-90a0-caeee8818c3a">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-09-28 16:32 UTC, ArjunKarthik approved these changes

2023-09-28 17:20 UTC, Chethan-rao commented
Regenerate openapi spec

2023-10-03 06:28 UTC, ArjunKarthik approved these changes

2023-10-03 06:28 UTC, ArjunKarthik commented
Please create an issue for this

2023-10-03 06:29 UTC, ArjunKarthik requested changes
Please link the issue if already exists and create new issue

2023-10-03 11:39 UTC, Chethan-rao approved these changes

2023-10-03 12:29 UTC, ArjunKarthik approved these changes

2023-10-03 14:14 UTC, SanchithHegde approved these changes

2023-10-03 14:46 UTC, merged