feat(connector): [Volt] Template generation
juspay/hyperswitch pull request #2480
Opened 2023-10-06 11:33 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Add template code for Volt Connector

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
Template code testing not required

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-06 11:44 UTC, SamraatBansal requested changes

2023-10-06 11:44 UTC, SamraatBansal commented on config/config.example.toml
> +volt.base_url = "https://api.sandbox.volt.io/"
Place it alphabetically

2023-10-06 11:44 UTC, SamraatBansal commented on config/docker_compose.toml
> +volt.base_url = "https://api.sandbox.volt.io/"
Place it alphabetically

2023-10-06 11:44 UTC, SamraatBansal commented on crates/router/src/core/payments/flows.rs
>      connector::Opennode,
Fix the alphabetical order

2023-10-06 11:44 UTC, SamraatBansal commented on crates/test_utils/src/connector_auth.rs
> +        // Do `export CONNECTOR_AUTH_FILE_PATH="/hyperswitch/crates/router/tests/connectors/sample_sample_sample_auth.toml"`
Don't include this change

2023-10-06 11:44 UTC, SamraatBansal commented on crates/test_utils/src/connector_auth.rs
> +        // Do `export CONNECTOR_AUTH_FILE_PATH="/hyperswitch/crates/router/tests/connectors/sample_sample_sample_auth.toml"`
Don't include this change

2023-10-06 11:44 UTC, SamraatBansal commented on loadtest/config/development.toml
>  trustpay.base_url_bank_redirects = "https://aapi.trustpay.eu/"
Place in alphabetical order

2023-10-09 06:38 UTC, ArjunKarthik approved these changes

2023-10-09 07:06 UTC, SamraatBansal approved these changes

2023-10-10 09:41 UTC, SanchithHegde approved these changes

2023-10-11 07:06 UTC, merged