[Dlocal] Use connector_request_reference_id as reference to the conne…
juspay/hyperswitch pull request #2491
Opened 2023-10-07 18:17 UTC by nikita812

…ctor #2297

## Type of Change

- [x ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-09 07:59 UTC, prasunna09 reviewed
Hi @nikita812, Please follow [commit message guidelines ](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md#commit-message-guidelines)

2023-10-10 15:34 UTC, nikita812 commented
Thanks for the commands, I am working on it.

2023-10-11 20:12 UTC, prasunna09 requested changes

2023-10-11 20:12 UTC, prasunna09 commented on crates/router/src/connector/dlocal/transformers.rs
> +            connector_request_reference_id: item.connector_request_reference_id.clone(),
```suggestion
            order_id: item.connector_request_reference_id.clone(),
```

2023-10-11 20:12 UTC, prasunna09 commented on crates/router/src/connector/dlocal/transformers.rs
> +    pub connector_request_reference_id: String,
same here, please revert this change

2023-10-11 20:12 UTC, prasunna09 commented on crates/router/src/connector/dlocal/transformers.rs
> +            connector_request_reference_id: item.request.connector_request_reference_id.clone(),
here acc to [dev docs](https://docs.dlocal.com/reference/make-a-refund) of Dlocal we don't need this change, we have to send connector_transaction_id as payment id to make refund for the respective payment.
Hence please revert back this change

2023-10-15 15:02 UTC, SargamPuram commented
hey @prasunna09 , I recently raised a PR that was just merged today which solves something like this #2446 . I guess this PR #2491 is of a duplicate issue please have a look.  As @srujanchikke had already closed the PR #2490 , that @nikita812 had raised previously since the issue was originally assigned to me. I request you to look into this please.

2023-10-15 19:38 UTC, prasunna09 commented
> hey @prasunna09 , I recently raised a PR that was just merged today which solves something like this #2446 . I guess this PR #2491 is of a duplicate issue please have a look. As @srujanchikke had already closed the PR #2490 , that @nikita812 had raised previously since the issue was originally assigned to me. I request you to look into this please.

Hi @SargamPuram, the issue you resolved is related to connector response reference id but this is connector request reference id, both are different.

2023-10-15 19:56 UTC, SargamPuram commented
> > hey @prasunna09 , I recently raised a PR that was just merged today which solves something like this #2446 . I guess this PR #2491 is of a duplicate issue please have a look. As @srujanchikke had already closed the PR #2490 , that @nikita812 had raised previously since the issue was originally assigned to me. I request you to look into this please.
> 
> Hi @SargamPuram, the issue you resolved is related to connector response reference id but this is connector request reference id, both are different.

Hi @prasunna09 I apologise for the confusion. Thanks for the clarification.

2023-10-20 11:59 UTC, swangi-kumari commented
Hello @nikita812 ,
Let us know if you are facing any issue, happy to help:)

2023-10-26 10:48 UTC, nikita812 commented
Hello to all maintainers
Due to breakdown of my machine I wasn't able to continue with this issue and it might take a bit more time to get my machine fixed. I thank all of you for being considerate to what issues I was facing, its rare to see that but sorry for the inconvenience caused.

2023-10-31 08:10 UTC, closed without merging