Use connector_request_reference_id as reference to the connector for …
juspay/hyperswitch pull request #2492
Opened 2023-10-08 00:13 UTC by daniloff200

…Shift4 #2316

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-08 12:54 UTC, srujanchikke commented
Hey @daniloff200 ,

Please use the following cargo commands -

`cargo check --all-features`                                                                 
`cargo clippy --all-features` 

ref -[ Cargo commands](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md#cargo-commands), and fix the errors thrown by clippy for the checks to pass .

Please run `cargo +nightly fmt`  to fix failing formatting check

2023-10-08 13:27 UTC, daniloff200 commented
hi, @srujanchikke . Thanks for your review! I've executed the commands

2023-10-10 19:47 UTC, daniloff200 commented
hi, @srujanchikke , could you help me with an issue, I have here? I've tried various fixes, but, got a problem with a Some (as here -> https://github.com/juspay/hyperswitch/actions/runs/6459469231/job/17538567259?pr=2492) or with borrowed value.
I'm kinda new to Rust, and tried different approaches, but, it doesn't work

2023-10-12 09:47 UTC, srujanchikke commented
> hi, @srujanchikke , could you help me with an issue, I have here? I've tried various fixes, but, got a problem with a Some (as here -> https://github.com/juspay/hyperswitch/actions/runs/6459469231/job/17538567259?pr=2492) or with borrowed value. I'm kinda new to Rust, and tried different approaches, but, it doesn't work

Hi @daniloff200 ,

In Rust, when you move a value, you transfer ownership of that value to another location, and you can no longer use the original location to access the value. 

```
resource_id: types::ResponseId::ConnectorTransactionId(item.response.id.clone()) // Clone the value before moving response.id to another location

2023-10-17 19:26 UTC, srujanchikke commented on crates/router/src/connector/shift4/transformers.rs
> +        let connector_id = Some(item.response.token.id),;
Could you remove the additional comma here

2023-10-17 19:27 UTC, srujanchikke commented on crates/router/src/connector/shift4/transformers.rs
> +                resource_id: token_id,
Please revert this change , This is meant to be `NoResponseId`

2023-10-19 06:08 UTC, srujanchikke requested changes
As this PR addressing https://github.com/juspay/hyperswitch/issues/2347 , i am reassigning the issue

2023-10-19 06:08 UTC, srujanchikke commented on crates/router/src/connector/shift4/transformers.rs
> +        let token_id = types::ResponseId::ConnectorTransactionId(item.response.token.id.clone());
Shift4ThreeDsResponse don't have field id , Remove token_id

2023-10-19 06:08 UTC, srujanchikke commented on crates/router/src/connector/shift4/transformers.rs
> +                resource_id: token_id,
Revert this change too

2023-10-20 21:43 UTC, daniloff200 commented
@srujanchikke can you review my pr please? I've managed to fix all issues

2023-10-21 05:21 UTC, srujanchikke requested changes
minor changes required , other than that looks good to me !

2023-10-21 05:21 UTC, srujanchikke commented on crates/router/src/connector/shift4/transformers.rs
> +        let token_id = Some(item.response.token.id.clone());
This token id is not connector response id , it is shift4 3ds token id . revert the changes from shift4 try_from .

2023-10-21 12:24 UTC, srujanchikke approved these changes
LGTM

2023-10-21 12:26 UTC, SanchithHegde approved these changes
Looks good to me!

Thanks for the PR, @daniloff200!

2023-10-21 12:33 UTC, merged

2023-10-23 13:14 UTC, daniloff200 commented
@swangi-kumari  hey!
Thanks for the link, I've submitted the form. One question: can it be the issue, if I live in Ukraine?

2023-10-26 06:14 UTC, VedantKhairnar commented
![image](https://github.com/juspay/hyperswitch/assets/42309779/8bd30023-b889-4c16-8ef0-af6022de20a6)
Hey @daniloff200 ,
We are using [DHL courier service](https://www.dhl.com/) and they do provide service in Ukraine as shown in the above image. 
If we face any issues, we will reach out to you. If you have any queries, pls let us know.
Thanks.