refactor(payment_methods): Added mca_id in bank details
juspay/hyperswitch pull request #2495
Opened 2023-10-08 06:57 UTC by Sarthak1799

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
 
another field was required for bank account creds in payment method data. 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-09 06:08 UTC, vspecky requested changes

2023-10-09 06:08 UTC, vspecky commented on crates/api_models/src/payment_methods.rs
> +    pub mca_id: String,
This needs to be in the `BankAccountConnectorDetails` type, as two entries in the `PaymntMethodDataBankCreds.connector_details` vector may have different MCA IDs.

2023-10-09 11:00 UTC, vspecky approved these changes

2023-10-10 06:44 UTC, Chethan-rao approved these changes

2023-10-10 06:52 UTC, merged