refactor(storage): update paymentintent object to provide a relation with attempts
juspay/hyperswitch pull request #2502
Opened 2023-10-09 06:45 UTC by lsampras

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- Added interfaces in intent to access attempt
- Add a new type to allow shallow clones / fetches + future hydrations

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

- Following on our effort to unify payments as a single domain object we are now able to access all the attempt/intent related details via a single object
- This allows us to pass around only a single object without worrying about efficiency/perf or correctness
- Future updates will include unifying the storage interfaces for attempt & intent as well

## How did you test it?

- Tried creating a payments locally

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-11 07:18 UTC, harsh-sharma-juspay approved these changes

2023-10-11 11:21 UTC, ivor-juspay approved these changes

2023-10-11 11:37 UTC, Narayanbhat166 submitted a review, later dismissed

2023-10-11 11:48 UTC, jarnura requested changes

2023-10-11 11:48 UTC, jarnura commented on crates/data_models/src/payments/payment_intent.rs
> +    pub active_attempt: crate::RemoteStorageObject<PaymentAttempt>,
```suggestion
    pub active_attempt: RemoteStorageObject<PaymentAttempt>,
```

2023-10-11 11:48 UTC, jarnura commented on crates/storage_impl/src/payments/payment_intent.rs
> +                    let new_err = crate::diesel_error_to_data_error(er.current_context());
```suggestion
                    let new_err = diesel_error_to_data_error(er.current_context());
```

2023-10-11 12:00 UTC, lsampras commented on crates/data_models/src/payments/payment_intent.rs
> +        active_attempt: PaymentAttempt,
I plan to merge both (intent + attempt) storage interfaces into a single one...
In the future this same function would update the payment_attempt table as well as the active_attempt_id in payment_intent...

2023-10-12 14:28 UTC, jarnura approved these changes

2023-10-13 02:38 UTC, Narayanbhat166 approved these changes

2023-10-13 02:53 UTC, merged