feat(trace): add optional sampling behaviour for routes
juspay/hyperswitch pull request #2511
Opened 2023-10-09 12:09 UTC by NishantJoshi00

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This change introduces a new middleware for tracing requests with the specified url. Providing a filtration mechanism.
This change also includes changing the bb8 queue strategy from FIFO to LIFO.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-09 12:42 UTC, inventvenkat commented on config/development.toml
> -enabled = true
can we revert these?

2023-10-09 13:10 UTC, jarnura requested changes

2023-10-09 15:14 UTC, jarnura approved these changes

2023-10-09 18:48 UTC, SanchithHegde approved these changes

2023-10-10 07:23 UTC, inventvenkat approved these changes

2023-10-10 08:00 UTC, merged