refactor(connector): [PowerTranz] refactor powertranz payments to remove default cases
juspay/hyperswitch pull request #2547
Opened 2023-10-11 13:10 UTC by Himanshu-370

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-18 20:22 UTC, prasunna09 requested changes

2023-10-18 20:22 UTC, prasunna09 commented on crates/router/src/connector/powertranz/transformers.rs
> +            api::PaymentMethodData::CardRedirect(_)
```suggestion
            api::PaymentMethodData::Wallet(_)
            | api::PaymentMethodData::CardRedirect(_)
```
Here you haven't include wallet enum. This is the reason for clippy check to fail.

2023-10-18 20:22 UTC, prasunna09 commented on crates/router/src/connector/powertranz/transformers.rs
> +            // )),
```suggestion
```
Please remove these comments

2023-10-22 17:18 UTC, srujanchikke approved these changes
LGTM!

2023-10-22 18:56 UTC, prasunna09 approved these changes
LGTM! Thank you for you contribution. @Himanshu-370

2023-10-22 18:57 UTC, SanchithHegde approved these changes

2023-10-22 19:05 UTC, merged

2023-10-23 11:30 UTC, swangi-kumari commented
Hey @Himanshu-370 ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
Thanks!