fix(connector): [braintree] add 3ds redirection error mapping and metadata validation
juspay/hyperswitch pull request #2552
Opened 2023-10-11 17:56 UTC by SamraatBansal

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- Add Error Mapping Scenarios for 3DS payments
- Add `connector_meta_data` validation for Braintree
- Add `InvalidConfig` ConnectorError in case of missing metadata configs

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-11 18:24 UTC, Narayanbhat166 approved these changes

2023-10-12 12:43 UTC, ArjunKarthik approved these changes

2023-10-12 12:43 UTC, ArjunKarthik commented on crates/router/src/connector/braintree.rs
> +                None => Ok(payments::CallConnectorAction::StatusUpdate {
In case if the json_payload is None, we should payments::CallConnectorAction::Avoid

2023-10-12 12:43 UTC, ArjunKarthik requested changes
Minor changes

2023-10-12 12:49 UTC, ArjunKarthik approved these changes

2023-10-12 12:55 UTC, prasunna09 approved these changes

2023-10-12 13:35 UTC, Narayanbhat166 approved these changes

2023-10-12 13:42 UTC, merged