refactor(connector): [Shift4]Enhance currency Mapping with ConnectorCurrencyCommon Trait
juspay/hyperswitch pull request #2557
Opened 2023-10-12 07:33 UTC by sanketmp

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This pull request introduces the get_currecny_unit from ConnectorCommon trait for shift4. This function allows connectors to declare their accepted currency unit as either "Base" or "Minor".

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Closes #2245 

## How did you test it?

(Please review the changes and let me know if any further issues or changes to be made.)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-12 09:20 UTC, srujanchikke commented
Hi @sanketmp ,

Please use following cargo commands -

`cargo clippy --all-features`
ref -[ Cargo commands](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md#cargo-commands), and fix the errors thrown by clippy for the checks to pass and also use `cargo +nightly fmt` to fix the failing formatting check

2023-10-12 10:45 UTC, sanketmp commented
ran the `cargo +nightly fmt` and gave no errors. Please review @srujanchikke

2023-10-12 13:11 UTC, srujanchikke commented
> cargo clippy --all-features

You might also should run `cargo clippy --all-features`

2023-10-12 13:35 UTC, sanketmp commented
> > cargo clippy --all-features
> 
> You might also should run `cargo clippy --all-features`

I have done that too. I don't know what is happening.

2023-10-18 11:11 UTC, prasunna09 requested changes

2023-10-18 11:11 UTC, prasunna09 commented on crates/router/src/connector/shift4/transformers.rs
> +    // fn try_from(
can you please remove these comments?

2023-10-18 11:11 UTC, prasunna09 commented on crates/router/src/connector/shift4/transformers.rs
> +        value: (&Shift4RouterData<
can you please rename value to item
```suggestion
        item: (&Shift4RouterData<
```

2023-10-18 11:11 UTC, prasunna09 commented on crates/router/src/connector/shift4/transformers.rs
> +        let amount = value.request.amount.to_string();
```suggestion
        let amount = item.amount.clone();
```

2023-10-18 14:53 UTC, sanketmp commented
Hello @prasunna09, made the requested changes.

2023-10-18 14:59 UTC, sanketmp commented on crates/router/src/connector/shift4.rs
> +        api::CurrencyUnit::Base
made the changes

2023-10-18 20:06 UTC, SanchithHegde commented
Hey @sanketmp, could you address the failing CI checks?

2023-10-19 10:40 UTC, sanketmp commented
I couldn't figure out @SanchithHegde

2023-10-19 17:14 UTC, SanchithHegde commented
@sanketmp As mentioned earlier in https://github.com/juspay/hyperswitch/pull/2557#issuecomment-1759244561, you must run `cargo clippy --all-features` and address the errors thrown.

2023-10-20 05:43 UTC, sanketmp commented
I have done that but I'll try again

2023-10-20 05:59 UTC, closed without merging