feat(connector): [VOLT] Implement payment flows and bank redirect payment method
juspay/hyperswitch pull request #2582
Opened 2023-10-13 13:11 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Implement payment flows and bank redirect payment method for Volt Connnector

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
<img width="1728" alt="Screenshot 2023-10-13 at 6 39 58 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/48565521-8dbc-4532-9c19-4262ce0a6129">

<img width="1728" alt="Screenshot 2023-10-13 at 6 40 13 PM" src="https://github.com/juspay/hyperswitch/assets/85639103/e4921525-ce86-47fc-9579-528b7f1ca4aa">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-16 09:04 UTC, prasunna09 commented on crates/router/src/types.rs
> +
Why was this added if you are not using this in Accesstoken tryFrom?

2023-10-17 07:37 UTC, swangi-kumari commented on crates/router/src/connector/volt/transformers.rs
> +            | VoltPaymentStatus::Received => Self::AuthenticationPending,
Payment get charged only when status of Volt goes to Completed

2023-10-19 11:55 UTC, ArjunKarthik requested changes

2023-10-19 11:55 UTC, ArjunKarthik commented on crates/router/src/connector/volt/transformers.rs
> +    currency_code: String,
Use Currency enum instead of string

2023-10-19 11:55 UTC, ArjunKarthik commented on crates/router/src/connector/volt/transformers.rs
> +                connector_response_reference_id: None,
populate connector_response_reference_id

2023-10-19 11:55 UTC, ArjunKarthik commented on crates/router/src/connector/volt/transformers.rs
> +    status: Option<RefundStatus>,
Use separate struct for Refund & RSync

2023-10-19 11:55 UTC, ArjunKarthik commented on crates/router/src/connector/volt/transformers.rs
> +            VoltPaymentStatus::AbandonedByUser => Self::AuthenticationFailed,
Don't we have failure status ?

2023-10-20 08:36 UTC, ArjunKarthik commented
@swangi-kumari Since we are not clear with all Payment status and Error response structure, Let's raise this with connector.

2023-10-25 11:44 UTC, ArjunKarthik requested changes

2023-10-25 11:44 UTC, ArjunKarthik commented on crates/router/src/connector/volt/transformers.rs
> +            | VoltPaymentStatus::AwaitingCheckoutAuthorisation => Self::Pending,
AwaitingCheckoutAuthorisation should be mapped to AuthenticationPending

2023-10-25 11:51 UTC, ArjunKarthik commented
@swangi-kumari If refund sync is not supported by the connector, please remove all the implemented method for the refund sync api

2023-10-25 14:06 UTC, ArjunKarthik submitted a review, later dismissed

2023-10-26 10:00 UTC, swangi-kumari commented on crates/router/src/connector/volt/transformers.rs
> +                    let notification_url = item.router_data.request.webhook_url.clone();
Yes it does. But not implemented yet.

2023-10-26 10:31 UTC, prasunna09 requested changes

2023-10-26 10:31 UTC, prasunna09 commented on crates/router/src/connector/volt/transformers.rs
> +            VoltPaymentStatus::Received
Please map this to `Charged`

2023-10-26 10:31 UTC, prasunna09 commented on crates/router/src/connector/volt/transformers.rs
> +            | VoltPaymentStatus::NotReceived
Map this to `Failure`

2023-10-26 10:31 UTC, prasunna09 commented on crates/router/src/connector/volt/transformers.rs
> +                connector_response_reference_id: Some(item.response.id),
add merchantInternalReference as optional field in PSync Response struct, and use the same for connector_response_reference_id and put `item.response.id` as fallback

2023-10-26 10:31 UTC, prasunna09 commented on crates/router/src/connector/volt/transformers.rs
> +                refund_status: enums::RefundStatus::Pending,
Please add a comment on why we are hardcoding the refund status.

2023-10-26 10:33 UTC, prasunna09 requested changes

2023-10-26 10:33 UTC, prasunna09 commented on crates/router/src/connector/volt/transformers.rs
> +                refund_status: enums::RefundStatus::Pending,
Please add a comment on why are we hardcoding this refund status

2023-10-26 11:02 UTC, swangi-kumari commented on crates/router/src/connector/volt/transformers.rs
> +                        organisation_name: address.get_full_name()?.to_owned(),
It is Shopper's organisation name (required when firstName and lastName not provided).
I have removed this field as we are already passing `first_name` and `last_name`

2023-10-26 11:03 UTC, swangi-kumari commented on crates/router/src/connector/volt/transformers.rs
> +            | VoltPaymentStatus::Processing
Yes, earlier I had some confusion regarding Volt Payment Status

2023-10-26 12:02 UTC, prasunna09 approved these changes
Please add the test cases and postman collection(connector tests) for volt

2023-10-26 12:17 UTC, ArjunKarthik submitted a review, later dismissed

2023-10-26 15:32 UTC, prasunna09 submitted a review, later dismissed

2023-10-27 12:29 UTC, ArjunKarthik approved these changes

2023-10-27 12:31 UTC, prasunna09 approved these changes

2023-10-27 17:19 UTC, pixincreate commented
@swangi-kumari, please update base branch to latest main to get spell-checks to pass.

2023-10-28 20:53 UTC, swangi-kumari commented
> @swangi-kumari, please update base branch to latest main to get spell-checks to pass.

Done👍🏻

2023-10-30 06:21 UTC, ArjunKarthik approved these changes

2023-10-30 07:20 UTC, prasunna09 approved these changes

2023-10-30 07:39 UTC, Gnanasundari24 approved these changes

2023-10-30 07:43 UTC, SanchithHegde approved these changes

2023-10-30 08:03 UTC, merged