feat(connector): [Bitpay] Add order id as the reference id
juspay/hyperswitch pull request #2591
Opened 2023-10-15 04:51 UTC by ashh1215

## Type of Change

- [ ] Bugfix
- [x ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

[Relevant documentation] (https://developer.bitpay.com/docs/create-invoice#notificationurl)

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Closes #2325

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ x] I addressed lints thrown by `cargo clippy`
- [ x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-20 04:00 UTC, ashh1215 commented
@SanchithHegde Please do review and suggest changes if required

2023-10-31 10:57 UTC, deepanshu-iiitu approved these changes

2023-10-31 11:15 UTC, deepanshu-iiitu commented on crates/router/src/connector/bitpay/transformers.rs
> +        let connector_id = types::ResponseId::ConnectorTransactionId(item.response.data.id.clone());
Add a field `order_id` in `BitpayPaymentResponseData` and use it in connector_response_reference_id

2023-10-31 11:59 UTC, deepanshu-iiitu requested changes

2023-10-31 11:59 UTC, deepanshu-iiitu commented on crates/router/src/connector/bitpay/transformers.rs
> +                connector_response_reference_id: Some(item.response.data.id),
```suggestion
                connector_response_reference_id: item.response.data.order_id.or(Some(connector_id)),
```

2023-10-31 11:59 UTC, deepanshu-iiitu commented on crates/router/src/connector/bitpay/transformers.rs
> +                connector_response_reference_id: Some(item.response.data.id),
@ashh1215

2023-11-02 12:01 UTC, AkshayaFoiger commented
Hey @ashh1215 
Thanks for your interest in contributing to hyperswitch.
Let us know if you need any assistance from our end.
.
Also, even if hacktoberfest is over, we should celebrate open source everyday and we are open for more contributions from you.
We would still be rewarding folks with goodies even if the PR gets merged post hacktoberfest.
May the Source be with you!

2023-11-02 14:32 UTC, ashh1215 commented
@deepanshu-iiitu 
I've made the changes. Please review.
Thank you.

2023-11-02 17:19 UTC, AkshayaFoiger commented
Hey @deepanshu-iiitu  ,
Pls address the CI fails
Run `cargo clippy` and addressed lints thrown by it.

2023-11-03 07:51 UTC, deepanshu-iiitu approved these changes

2023-11-03 07:51 UTC, AkshayaFoiger commented
@ashh1215, please run `cargo +nightly fmt`

2023-11-03 17:12 UTC, ashh1215 commented
@deepanshu-iiitu I've fixed the issues. It should work now.

2023-11-04 09:27 UTC, deepanshu-iiitu approved these changes
LGTM

2023-11-06 06:03 UTC, AkshayaFoiger approved these changes

2023-11-06 17:47 UTC, SanchithHegde approved these changes
Looks good to me!

Thanks for the PR, @ashh1215!

2023-11-06 18:10 UTC, merged

2023-11-16 11:40 UTC, deepanshu-iiitu commented
Hey @ashh1215  ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.
Thanks!