[FEATURE]: [Authorizedotnet] Use connector_request_reference_id as re…
juspay/hyperswitch pull request #2593
Opened 2023-10-15 08:07 UTC by amitroy-thedev

…ference to the connector

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-20 12:23 UTC, swangi-kumari commented
Hello @amitroy-thedev ,

Pls address the CI fails

Run `cargo +nightly fmt` for formatting

2023-10-22 05:08 UTC, Rohxn16 commented
i wanna work on this issue

2023-10-23 12:10 UTC, swangi-kumari commented
> i wanna work on this issue

Hey @Rohxn16 ,
 We appreciate your interest, but it seems that @amitroy-thedev  is already actively addressing this particular issue. However, we have several other open issues available for you to choose from. Feel free to let us know which issue among them you'd like to work on, and we'll be happy to assist you in any way we can.

2023-10-25 17:34 UTC, SamraatBansal commented
Hey @amitroy-thedev Please tag the issue assigned to you with this PR

2023-10-25 18:00 UTC, SamraatBansal requested changes

2023-10-25 18:28 UTC, amitroy-thedev commented on crates/router/src/connector/authorizedotnet/transformers.rs
>                      status: payment_status,
Hey @SamraatBansal 
i've made all the required changes please review it now
and so sorry for the delay and for the mistakes

2023-10-27 09:18 UTC, SamraatBansal commented on crates/router/src/connector/authorizedotnet/transformers.rs
> +            reference: item.router_data.connector_request_reference_id.clone(),
Hey @amitroy-thedev I think you removed this change by mistake, as this is a required change, I asked to remove from `response` but `request` is required.
The only change here you would need to make is change the field name from `reference` to `ref_id`

2023-10-27 09:19 UTC, SamraatBansal commented
Hey @amitroy-thedev Can you please address the unresolved comment

2023-10-27 10:31 UTC, amitroy-thedev commented on crates/router/src/connector/authorizedotnet/transformers.rs
> +            reference: item.router_data.connector_request_reference_id.clone(),
`ref_id: item.router_data.connector_request_reference_id.clone(),`
Do I replace with this code

2023-10-27 10:56 UTC, amitroy-thedev commented on crates/router/src/connector/authorizedotnet/transformers.rs
> +            reference: item.router_data.connector_request_reference_id.clone(),
@SamraatBansal 
and remove `pub reference: Option<String>` this code from response

2023-10-28 11:10 UTC, amitroy-thedev commented
@SamraatBansal
Hello there,
Sir I've changed the code please review it and merge the code, hacktoberfest is going to be end 🥲

2023-10-28 18:24 UTC, amitroy-thedev commented
@SanchithHegde 
Sir i've changed the required changes would you check it

2023-10-28 18:25 UTC, amitroy-thedev commented
@SanchithHegde 
Sir i've changed the required changes would you please check it

2023-10-30 09:01 UTC, amitroy-thedev commented
@SanchithHegde @Sangamesh26 @SamraatBansal 
This PR is being solved can you please review and merge it ..

2023-10-31 10:29 UTC, deepanshu-iiitu approved these changes

2023-10-31 10:40 UTC, prasunna09 approved these changes

2023-10-31 10:59 UTC, SamraatBansal approved these changes

2023-10-31 11:37 UTC, merged

2023-10-31 12:03 UTC, deepanshu-iiitu commented
Hey @amitroy-thedev  ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
Thanks!