feat(connector): [Multisafepay] add error handling
juspay/hyperswitch pull request #2595
Opened 2023-10-15 14:08 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

### Description 
- Resolves [#2636](https://github.com/juspay/hyperswitch-cloud/issues/2636)

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

resolves 

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-17 07:35 UTC, ArjunKarthik requested changes

2023-10-17 07:35 UTC, ArjunKarthik commented on crates/router/src/connector/multisafepay/transformers.rs
> +                    reason: None,
Populate reason with error_response.error_info

2023-10-17 07:35 UTC, ArjunKarthik commented on crates/router/src/connector/multisafepay/transformers.rs
> +                    reason: None,
Populate reason with error_response.error_info

2023-10-17 07:35 UTC, ArjunKarthik commented on crates/router/src/connector/multisafepay/transformers.rs
> +                    reason: None,
same here

2023-10-17 09:53 UTC, ArjunKarthik approved these changes

2023-10-17 10:02 UTC, prasunna09 requested changes

2023-10-17 10:02 UTC, prasunna09 commented on crates/router/src/connector/multisafepay/transformers.rs
> +                let refund_stat = if refund_data.success {
```suggestion
                let refund_status = if refund_data.success {
```

2023-10-17 10:02 UTC, prasunna09 commented on crates/router/src/connector/multisafepay/transformers.rs
> +                        refund_status: enums::RefundStatus::from(refund_stat),
```suggestion
                        refund_status: enums::RefundStatus::from(refund_status),
```

2023-10-17 10:02 UTC, prasunna09 commented on crates/router/src/connector/multisafepay/transformers.rs
> +                let status = payment_response.data.status.unwrap_or(default_status);
why are we using `unwrap_or` here?

2023-10-17 10:14 UTC, prasunna09 commented
@AkshayaFoiger Please take these changes in separate PR.

2023-10-17 10:14 UTC, prasunna09 approved these changes

2023-10-17 10:40 UTC, ArjunKarthik submitted a review, later dismissed

2023-10-17 18:30 UTC, prasunna09 submitted a review, later dismissed

2023-10-18 06:36 UTC, AkshayaFoiger commented
Test Case
1. Create a payment with incorrect Multisafepay API key. This should populate appropriate error code and error message in the response.

2023-10-18 09:20 UTC, Gnanasundari24 commented
@AkshayaFoiger Kindly update the postman collections for the supported connectors and update the description with the relevant screenshots.
You can refer to the rustman documentation [here](https://github.com/juspay/hyperswitch/blob/main/crates/test_utils/README.md)

2023-10-27 12:30 UTC, ArjunKarthik approved these changes

2023-10-30 06:22 UTC, prasunna09 approved these changes

2023-10-30 07:10 UTC, Gnanasundari24 approved these changes

2023-11-02 07:35 UTC, merged