fix(connector): [Paypal]fix error deserelization for source verification call
juspay/hyperswitch pull request #2611
Opened 2023-10-17 09:58 UTC by srujanchikke

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

fix error deserelization for source verification call . Make description in error response as optional field as it is not expected incase of webhook source verification call

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

fix error deserelization for source verification call . Make description in error response as optional field as it is not expected incase of webhook source verification call

## How did you test it?

1)error deserilization success scenario , Source verifcation failure as secret is not set in merchant connector account by default we provide secret as default_string. when we include` _` in webhook secret paypal throws error as
` "name": "INVALID_REQUEST",
    "message": "Request is not well-formed, syntactically incorrect, or violates schema.",
    "debug_id": "c2a4be266f6d6",
    "details": [
        {
            "field": "/webhook_id",
            "value": "sruj*an",
            "location": "body",
            "issue": "must match \"^[a-zA-Z0-9]+$\""
        }
    ],` 
<img width="1108" alt="Screenshot 2023-10-17 at 2 59 40 PM" src="https://github.com/juspay/hyperswitch/assets/121822803/edfdcac9-666e-46dd-8248-1d29babba671">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-17 10:27 UTC, ArjunKarthik requested changes

2023-10-17 10:27 UTC, ArjunKarthik commented on crates/router/src/connector/paypal.rs
> +        };
```suggestion
        let reason = error_reason
            .unwrap_or(response.message.to_owned())
            .is_empty()
            .then_some(response.message.to_owned());
```

2023-10-17 13:27 UTC, ArjunKarthik approved these changes

2023-10-18 07:39 UTC, prasunna09 approved these changes

2023-10-18 08:34 UTC, Gnanasundari24 approved these changes

2023-10-18 08:41 UTC, merged