Feature/cybersource minor currency conversion
juspay/hyperswitch pull request #2626
Opened 2023-10-18 09:03 UTC by mdrokz

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
This PR implements `get_currency_unit` for cybersource to convert payments from `Base` to `Minor` it also implements router data to handle the conversion.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Closes #2222 

## How did you test it?

I tested by sending a payment request & verifying the amount is showed in minor units in the cybersource console

![image](https://github.com/juspay/hyperswitch/assets/33598169/db8bea1c-23ed-4df4-a8a2-72f2e55c6131)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-18 19:26 UTC, SanchithHegde commented
Hey @mdrokz, could you address the failing CI checks?

2023-10-19 06:08 UTC, mdrokz commented
> Hey @mdrokz, could you address the failing CI checks?

Just synced the changes from main can you run the CI checks again ?

2023-10-19 07:24 UTC, SanchithHegde commented
@mdrokz The formatting check is failing, could you please address it?

2023-10-19 08:30 UTC, mdrokz commented
> @mdrokz The formatting check is failing, could you please address it?

Done

2023-10-20 08:38 UTC, mdrokz commented
@SanchithHegde can you review this ?

2023-10-22 17:18 UTC, srujanchikke requested changes

2023-10-23 07:35 UTC, mdrokz commented on crates/router/src/connector/cybersource/transformers.rs
>      fn try_from(item: &types::PaymentsAuthorizeRouterData) -> Result<Self, Self::Error> {
> 

Done i removed the old try form since both of them were same.

2023-10-25 08:33 UTC, srujanchikke approved these changes
LGTM

2023-10-25 08:50 UTC, Sangamesh26 approved these changes

2023-10-25 09:29 UTC, SanchithHegde approved these changes
Looks good to me!

Thanks for the PR, @mdrokz!

2023-10-25 09:38 UTC, merged

2023-10-25 10:44 UTC, swangi-kumari commented
Hey @mdrokz ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
Thanks!

2023-10-25 10:53 UTC, mdrokz commented
> Hey @mdrokz ,
> Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
> Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
> Thanks!

Hey thanks a lot for this let me fill it up :)