fix issue:: [REFACTOR]: [CryptoPay] Remove Default Case Handling #2267
juspay/hyperswitch pull request #2643
Opened 2023-10-19 10:21 UTC by ashutuptiwari

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Removed the default match case as mentioned in the issue

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-19 10:31 UTC, ashutuptiwari commented
Please review @swangi-kumari and let me know of any changes that are to be made.

2023-10-19 18:03 UTC, ashutuptiwari commented
On it @SanchithHegde

2023-10-19 19:02 UTC, ashutuptiwari commented
@SanchithHegde I'm unable to run this locally, please check if the changes i made are working as expected. If yes, I'll revisit the formatting issues and that should be it.

2023-10-19 19:17 UTC, SanchithHegde commented
@ashutuptiwari Yeah looks like compilation would be successful, formatting should be the only one remaining.

2023-10-19 19:20 UTC, ashutuptiwari commented
Alright then @SanchithHegde

2023-10-19 20:12 UTC, ashutuptiwari commented
Should work just fine @SanchithHegde

2023-10-19 21:34 UTC, ashutuptiwari commented
Please review

2023-10-21 11:59 UTC, ashutuptiwari commented
Alright, I'll loo into it @swangi-kumari

2023-10-21 14:18 UTC, ashutuptiwari commented
Please approve the workflow @SanchithHegde

2023-10-22 19:51 UTC, prasunna09 requested changes

2023-10-22 19:51 UTC, prasunna09 commented on crates/router/src/connector/cryptopay/transformers.rs
> +            api_models::payments::PaymentMethodData::CardRedirect(_)
```suggestion
            api_models::payments::PaymentMethodData::Card(_)
            | api_models::payments::PaymentMethodData::CardRedirect(_)
```

2023-10-22 20:23 UTC, prasunna09 requested changes

2023-10-22 20:23 UTC, prasunna09 commented on crates/router/src/connector/cryptopay/transformers.rs
> +            | api_models::payments::PaymentMethodData::Crypto(_)
```suggestion
```
Please remove these two match arms, as these were already covered.

2023-10-23 20:32 UTC, ashutuptiwari commented
please review @prasunna09

2023-10-25 07:13 UTC, prasunna09 approved these changes

2023-10-25 07:29 UTC, SanchithHegde approved these changes
Looks good to me!

Thanks for the PR, @ashutuptiwari!

2023-10-25 07:30 UTC, Sangamesh26 approved these changes
LGTM :)

2023-10-25 07:30 UTC, ashutuptiwari commented
Happy Happy Happy

2023-10-25 07:37 UTC, merged

2023-10-25 07:39 UTC, ashutuptiwari commented
Thank you @SanchithHegde @prasunna09 @swangi-kumari for your inputs on this. Learnt a lot throught this contribution. Will definitely look forward to making more contributions. 
Cheers!

2023-10-25 07:39 UTC, swangi-kumari commented
Hey @ashutuptiwari , 
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
Thanks!

2023-12-13 11:57 UTC, ashutuptiwari commented
Hi guys, I see my name isn't on the contributors list, nor have I received the swag. 
Is this a mistake or is it amid the delivery process?
Thank you
@SanchithHegde @swangi-kumari @Sangamesh26 @prasunna09

2023-12-13 12:23 UTC, VedantKhairnar commented
Hey @ashutuptiwari 
I'll have a word with the vendor around the shipment status.
Will get back to you soon. Thanks for your patience.

2023-12-14 13:58 UTC, ashutuptiwari commented
Alright thanks @VedantKhairnar