feat(connector): implement authorize and capture flows for Fiserv
juspay/hyperswitch pull request #266
Opened 2022-12-31 22:07 UTC by zereraz

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Authorize and capture flow
Todo: Issue for optimising the encoding process in header and body #370 

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Adding a new connector `Fiserv`

Closes #229.

## How did you test it?
Added unit tests for mentioned payment flows.

<img width="784" alt="Screenshot 2023-01-13 at 7 43 38 PM" src="https://user-images.githubusercontent.com/55536657/212340057-35e12934-a1a8-4ca6-b411-729d27d6e357.png">

## Checklist

- [x] I formatted the code `cargo +nightly fmt`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-01-11 13:26 UTC, jarnura requested changes

2023-01-11 13:26 UTC, jarnura commented on crates/router/src/connector/fiserv.rs
> +        let fiserv_req = utils::Encode::<fiserv::FiservCaptureRequest>::convert_and_encode(req)
we can call the `Self::get_request_body` here

2023-01-11 13:26 UTC, jarnura commented on crates/router/src/connector/fiserv.rs
> +        let fiserv_req = utils::Encode::<fiserv::FiservPaymentsRequest>::convert_and_encode(req)
we can use `Self::get_request_body` here

2023-01-11 16:40 UTC, zereraz commented on crates/router/src/connector/fiserv/test.rs
> +use futures::future::OptionFuture;
I think these got autogenerated. No I didn't run them.

2023-01-11 17:53 UTC, SanchithHegde commented on crates/router/src/connector/fiserv.rs
> +        let timestamp = time::OffsetDateTime::now_utc().unix_timestamp();
Sorry I forgot to mention this earlier, could you please add a utility function in the `common_utils::date_time` module called `now_unix_timestamp()` which returns this value?

2023-01-11 17:53 UTC, SanchithHegde submitted a review, later dismissed

2023-01-12 14:19 UTC, SamraatBansal commented on crates/router/src/connector/fiserv/transformers.rs
> +                };
Added Comments to these fields to provide context

2023-01-12 14:49 UTC, SanchithHegde commented
@SamraatBansal Please run the tests and attach a screenshot in the PR description.

2023-01-13 08:43 UTC, jarnura approved these changes

2023-01-13 14:49 UTC, SanchithHegde approved these changes

2023-01-14 14:56 UTC, jarnura approved these changes

2023-01-14 17:23 UTC, SanchithHegde approved these changes

2023-01-14 17:24 UTC, SanchithHegde approved these changes

2023-01-15 10:13 UTC, jarnura approved these changes

2023-01-15 10:33 UTC, merged