feat(connector): [Multisafepay] Currency Unit Conversion
juspay/hyperswitch pull request #2679
Opened 2023-10-25 08:21 UTC by shivam-jainn

## Type of Change

- [ ] Bugfix
- [x ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Addressing Issue: https://github.com/juspay/hyperswitch/issues/2232
Modified two files in hyperswitch/crates/router/src/connector/
multisafepay.rs
Implement get_currency_unit function
Modify ConnectorIntegration implementations for Multisafepay

multisafepay/transformers.rs
Implement MultisafepayRouterData<T> structure and functionality
Modify implementation for MultisafepayPaymentsRequest

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-27 08:14 UTC, SamraatBansal requested changes

2023-10-27 08:14 UTC, SamraatBansal commented on crates/router/src/connector/multisafepay.rs
> +        let req_obj = multisafepay::MultisafepayPaymentsRequest::try_from(&connector_router_data)?;
Hey @shivam-jainn 
You have to similarly do for the `Refunds` function that you can find in `line 950`.
There you would be using `req.request.refund_amount`

2023-10-27 08:14 UTC, SamraatBansal commented on crates/router/src/connector/multisafepay/transformers.rs
> +            amount: item.amount,
Similarly you have to do for `RefundRequest` in line number 672, there also we have to use `item.amount`

2023-10-28 15:29 UTC, shivam-jainn commented
@SamraatBansal hey 
I have done the required changes .
 Please do guide me if there is something else that I might need to do .
Thank you

2023-10-31 11:12 UTC, SamraatBansal approved these changes

2023-10-31 11:26 UTC, srujanchikke approved these changes
Looks good to me!
Thanks for the PR @shivam-jainn

2023-10-31 11:45 UTC, merged

2023-10-31 12:03 UTC, deepanshu-iiitu commented
Hey @shivam-jainn  ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.  
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.  
Thanks!