feat(events): add masked json serializer for logging PII values
juspay/hyperswitch pull request #2681
Opened 2023-10-25 09:25 UTC by lsampras

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- Add a serializer that replicates the existing JSON serializer
- Add a type check in the secret serialize methods where it can optionally mask values when the custom serializer is used
- add a util method to provide masked serialization

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

- while we use the secret type to mask values
- the behaviour for debug representations is pretty common whereas the serialization behaviour needs to satisfy both the use cases of masking or non-masking serializations
- Currently there is no OOTB approach where we can pass metadata to serde to control the serialization behaviour
- In this case we are relying on the std::any::type_name to identify whether a custom serializer was passed...

In this case I'm sticking with no-masking by default & specific functions to mask values

## How did you test it?

<img width="1665" alt="image" src="https://github.com/juspay/hyperswitch/assets/21202349/d36791a4-eba2-4fdf-b930-d4dcf6585710">

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-25 11:26 UTC, NishantJoshi00 requested changes
LGTM

2023-10-25 11:26 UTC, NishantJoshi00 commented on crates/masking/src/serde.rs
> +        }
can we make this into a function to promote reusibility

2023-10-27 07:15 UTC, NishantJoshi00 approved these changes

2023-10-27 07:27 UTC, dracarys18 approved these changes

2023-10-27 07:37 UTC, merged