fix: handle session and confirm flow discrepancy in surcharge details
juspay/hyperswitch pull request #2696
Opened 2023-10-26 07:05 UTC by hrithikesh026

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

In case of wallet payment method types like google pay and apple pay, before confirm call, we will have to do a session call. 
It may  be possible that in this session call, we will be sending the original amount to the connector and later in confirm call, the merchant can send some surcharge amount. This will cause some problems since, amount being sent in session call and confirm call will differ.

Above issue is solved in this PR by following steps:
1. Merchant can send some surcharge details during payments create. This will be stored in `payment_attempt.surcharge_amount` and `payment_attempt.tax_amount`.
2. in session flow, before calling the connector, we will store surcharge for the particular payment_method_type(wallet type) in redis (0 if no surcharge was being passed in payment_create).
3. During confirm call, if there is some surcharge_details in request and payment method is wallet, we will verify that amount sent in session call is same as total amount we will be sending in confirm. If the amounts do not match, We throw an error saying "session call has already being done with a different amount for this payment method type".

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Manual

Pass surcharge in Payment create. Will get updated in payment_attempt
<img width="1728" alt="Screenshot 2023-10-26 at 12 32 54 PM" src="https://github.com/juspay/hyperswitch/assets/61539176/1a18ad8e-f6b1-4232-bd96-aa270ebfaf29">

<img width="1728" alt="Screenshot 2023-10-26 at 12 34 46 PM" src="https://github.com/juspay/hyperswitch/assets/61539176/d9e28a0b-5397-41cd-945d-4a1cebff7f42">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-31 07:08 UTC, Narayanbhat166 commented on crates/router/src/core/payments.rs
> +    connectors: &Vec<api::SessionConnectorData>,
name it as session connectors data

2023-10-31 07:13 UTC, Narayanbhat166 approved these changes

2023-11-07 08:10 UTC, Narayanbhat166 commented on crates/router/src/core/utils.rs
> +                    .unwrap_or(DEFAULT_FULFILLMENT_TIME),
use `set_hash_fields` redis function here. The key would be `surcharge_metadata_<attempt_id>` and the individual fields can be hashmap keys.

2023-11-07 08:11 UTC, Narayanbhat166 commented on crates/router/src/types/api.rs
> +    /// Surcharge is calculated by us
```suggestion
    /// Surcharge is calculated by hyperswitch
```

2023-11-08 09:05 UTC, jarnura requested changes

2023-11-08 09:05 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_confirm.rs
> +                            Err(_) => {
don't discard the error, lift the into InternalServerError.

2023-11-08 09:05 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_confirm.rs
> +                                if surcharge_details
when function can be used here. Below if else block it is applicable.

2023-11-08 13:51 UTC, jarnura approved these changes

2023-11-09 08:09 UTC, Narayanbhat166 commented on crates/router/src/types/api.rs
> +                .get_surcharge_details(payment_method, payment_method_type, card_network)
Please avoid having two functions with the same name

2023-11-09 08:09 UTC, Narayanbhat166 approved these changes

2023-11-09 09:13 UTC, jarnura approved these changes

2023-11-09 14:42 UTC, jarnura submitted a review, later dismissed

2023-11-10 09:00 UTC, Narayanbhat166 submitted a review, later dismissed

2023-11-10 11:44 UTC, jarnura submitted a review, later dismissed

2023-11-10 12:10 UTC, Narayanbhat166 submitted a review, later dismissed

2023-11-13 13:11 UTC, jarnura approved these changes

2023-11-13 13:35 UTC, Narayanbhat166 commented on crates/router/src/core/payments/operations/payment_confirm.rs
> +                    if let Some(attempt_surcharge_amount) = payment_attempt.surcharge_amount {
Can you make these two if lets into a single match statement?

2023-11-13 14:07 UTC, hrithikesh026 commented on crates/router/src/core/utils.rs
> +        }
This function  `surcharge_metadata.get_individual_surcharge_key_value_pairs(`) returns a `Vec<(String, SurchargeDetails)>`.

I am just converting it into Vec<(String, String)> inside for loop.

2023-11-14 06:25 UTC, Narayanbhat166 commented
https://github.com/juspay/hyperswitch/actions/runs/6854446608/job/18637405889?pr=2696#step:19:436
Can you please address this?

2023-11-14 08:42 UTC, jarnura approved these changes

2023-11-14 09:48 UTC, Narayanbhat166 approved these changes

2023-11-14 10:57 UTC, merged