feat(connect): [NMI] Use connector_response_reference_id as reference to merchant
juspay/hyperswitch pull request #2702
Opened 2023-10-26 17:24 UTC by TejasMate

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-26 17:28 UTC, swangi-kumari commented
Hey @TejasMate ,
Pls address the CI fails
Run `cargo +nightly` fmt for formatting.

2023-10-31 11:53 UTC, deepanshu-iiitu requested changes

2023-10-31 11:53 UTC, deepanshu-iiitu commented on crates/router/src/connector/nmi/transformers.rs
> +                        item.response.transactionid.clone(),
Add variable `orderid` in struct `StandardResponse` and use it as `connector_response_reference_id`
Refer https://secure.nmi.com/merchants/resources/integration/integration_portal.php#transaction_response_variables @TejasMate

2023-10-31 11:53 UTC, deepanshu-iiitu commented on crates/router/src/connector/nmi/transformers.rs
> +                    connector_response_reference_id: Some(item.response.transactionid),
```suggestion
                    connector_response_reference_id: item.response.orderid.or(Some(item.response.transactionid)),
```

2023-10-31 11:53 UTC, deepanshu-iiitu commented on crates/router/src/connector/nmi/transformers.rs
> +                    connector_response_reference_id: Some(item.response.transactionid),
```suggestion
                    connector_response_reference_id: item.response.orderid.or(Some(item.response.transactionid)),
```

2023-10-31 11:53 UTC, deepanshu-iiitu commented on crates/router/src/connector/nmi/transformers.rs
> +                    connector_response_reference_id: Some(item.response.transactionid),
```suggestion
                    connector_response_reference_id: item.response.orderid.or(Some(item.response.transactionid)),
```

2023-10-31 11:53 UTC, deepanshu-iiitu commented on crates/router/src/connector/nmi/transformers.rs
> +                    connector_response_reference_id: Some(item.response.transactionid),
```suggestion
                    connector_response_reference_id: item.response.orderid.or(Some(item.response.transactionid)),
```

2023-10-31 11:53 UTC, deepanshu-iiitu commented on crates/router/src/connector/nmi/transformers.rs
> +                connector_response_reference_id: Some(response.transaction.transaction_id),
```suggestion
                connector_response_reference_id: item.response.orderid.or(Some(item.response.transactionid)),
```

2023-10-31 11:53 UTC, deepanshu-iiitu commented on crates/router/src/connector/nmi/transformers.rs
> +                connector_response_reference_id: Some(response.transaction.transaction_id),
@TejasMate

2023-11-02 08:05 UTC, deepanshu-iiitu requested changes

2023-11-02 08:05 UTC, deepanshu-iiitu commented on crates/router/src/connector/nmi/transformers.rs
> +                connector_response_reference_id: item.response.orderid.or(Some(item.response.transactionid)),
```suggestion
                connector_response_reference_id: None,
```

2023-11-02 08:08 UTC, deepanshu-iiitu commented on crates/router/src/connector/nmi/transformers.rs
> +                connector_response_reference_id: item.response.orderid.or(Some(item.response.transactionid)),
Hey @TejasMate 
Thanks for the quick changes.
Can you also do the below change.

Also in line 348 of this file make it as(StandardResponse Struct) :
`pub orderid: Option<String>,`

Also run the following command before you commit the changes to handle the code formatting
`cargo +nightly fmt`

2023-11-02 11:55 UTC, swangi-kumari commented
Hey @TejasMate ,
Thanks for your interest in contributing to hyperswitch.
Let us know if you need any assistance from our end.
Also, even if hacktoberfest is over, we should celebrate open source everyday and we are open for more contributions from you.
We would still be rewarding folks with goodies even if the PR gets merged post hacktoberfest.
May the Source be with you!

2023-11-06 10:23 UTC, deepanshu-iiitu commented
Hey @TejasMate ,
Are you working on the requested changes?

2023-11-07 14:44 UTC, TejasMate commented
@deepanshu-iiitu, I apologize for the delay. I will address all the issues this Sunday once I am free from exams

2024-02-05 11:53 UTC, ArjunKarthik approved these changes

2024-02-05 12:37 UTC, deepanshu-iiitu approved these changes

2024-02-06 06:08 UTC, merged