refactor(connector): added default case for Cybersource
juspay/hyperswitch pull request #2705
Opened 2023-10-26 21:29 UTC by TejasMate

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-27 07:20 UTC, SanchithHegde commented
@TejasMate Could you address the failing CI checks?

2023-10-29 16:16 UTC, swangi-kumari submitted a review, later dismissed

2023-10-30 13:23 UTC, SamraatBansal submitted a review, later dismissed

2023-10-30 14:10 UTC, swangi-kumari commented
Hey @TejasMate ,
Can you please address the default case for Refund Status (line 316) and make the required changes there also.

2023-10-30 14:45 UTC, TejasMate commented
> Hey @TejasMate , Can you please address the default case for Refund Status (line 316) and make the required changes there also.

sure

2023-10-31 08:08 UTC, swangi-kumari requested changes

2023-10-31 08:08 UTC, swangi-kumari commented on crates/router/src/connector/cybersource/transformers.rs
> +            CybersourcePaymentStatus::Pending => Self::Pending,
Hey @TejasMate , you have not fill all the matching arms of `CybersourcePaymentStatus` . Please check it once again and do the required changes.

2023-10-31 09:20 UTC, swangi-kumari commented
Hey @TejasMate ,
Before pushing your commit please address the failing CI checks
Run `cargo clippy` and addressed lints thrown by it.

2023-10-31 15:50 UTC, TejasMate commented
hey @SanchithHegde @swangi-kumari @SamraatBansal ,

I'm not sure where to put these values **Voided, Reversed, Authorized** into the which case: **Success, Pending or Failure** for RefundStatus?

2023-11-02 10:15 UTC, swangi-kumari commented
Hey @TejasMate ,
You have to map all the default cases to `Pending` RefundStatus.

2023-11-02 11:54 UTC, swangi-kumari commented
Hey @TejasMate ,
Thanks for your interest in contributing to hyperswitch.
Let us know if you need any assistance from our end.
Also, even if hacktoberfest is over, we should celebrate open source everyday and we are open for more contributions from you.
We would still be rewarding folks with goodies even if the PR gets merged post hacktoberfest.
May the Source be with you!

2024-02-01 11:23 UTC, ArjunKarthik approved these changes

2024-02-01 13:07 UTC, swangi-kumari approved these changes

2024-02-01 13:34 UTC, merged