feat(connector): [Payeezy] Currency Unit Conversion
juspay/hyperswitch pull request #2710
Opened 2023-10-27 13:51 UTC by adarsh-jha-dev

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

Modified two files in **hyperswitch/crates/router/src/connector/**

- Addressing Issue #2241 
- **payeezy.rs**
    - Implement **get_currency_unit** function
    - Modify **ConnectorIntegration** implementations for Payeezy
- **payeezy/transformers.rs**
    - Implement **PayeezyRoutedData<T>** structure and functionality
    - Modify implementation for **PayeezyPaymentsRequest**

## Motivation and Context

Fixes #2241 

## How did you test it?

We need to create a payment using payeezy and test the currency unit from connector response and connector dashboard.

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-27 13:52 UTC, adarsh-jha-dev commented
I request any of the maintainer to please have a look at the PR and let me know if the changes are relevant.

2023-10-27 14:20 UTC, adarsh-jha-dev commented
> Hey @adarsh-jha-dev , Pls address the CI fails Run `cargo +nightly` fmt for formatting.

Hey @swangi-kumari , I am doing these changes on github codespaces due to some unavoidable reasons and it is becoming problematic for me to run the command for formatting. Is there any way you can run that command for me (it's a request) and if not then please give me a little bit of time to do the same.

2023-10-27 14:43 UTC, adarsh-jha-dev commented
> Hey @adarsh-jha-dev , Pls address the CI fails Run `cargo +nightly` fmt for formatting.

Done

2023-10-29 07:19 UTC, adarsh-jha-dev commented
@SamraatBansal , I request you to please have a look at it and let me know if the changes are relevant?

2023-10-31 10:54 UTC, swangi-kumari commented
Hey @adarsh-jha-dev ,
Please address the failing CI checks
Run `cargo clippy` and addressed lints thrown by it.

2023-10-31 11:23 UTC, adarsh-jha-dev commented
> Hey @adarsh-jha-dev , Please address the failing CI checks Run `cargo clippy` and addressed lints thrown by it.

Done, could you please review this .

2023-10-31 11:32 UTC, swangi-kumari commented
Hey @adarsh-jha-dev ,
Please address the failing CI checks
Run `cargo clippy` and addressed lints thrown by it.

2023-10-31 14:01 UTC, swangi-kumari commented
Hey @adarsh-jha-dev ,
Your PR still have some compilation errors. 
Please address the failing CI checks
Run cargo clippy and addressed lints thrown by it.

2023-10-31 14:14 UTC, adarsh-jha-dev commented
> Hey @adarsh-jha-dev , Your PR still have some compilation errors. Please address the failing CI checks Run cargo clippy and addressed lints thrown by it.

Yeah yeah , on it, would resolve it within an hour

2023-11-01 11:08 UTC, adarsh-jha-dev commented
Hey @swangi-kumari, sorry for not submitting this yesterday, trying my best to submit by tonight. I request you to please don't unassign me

2023-11-01 11:22 UTC, swangi-kumari commented
Sure @adarsh-jha-dev , Take your time and address the comments given to you. All the Best:)

2023-11-02 07:00 UTC, adarsh-jha-dev commented
Thanks @swangi-kumari for co-operating and giving me time, I have tried hard and resolved those CI fails. I request you to please have a look at them whenever you want.

2023-11-02 10:05 UTC, swangi-kumari requested changes

2023-11-02 10:05 UTC, swangi-kumari commented on crates/router/src/connector/payeezy/transformers.rs
> +    ) -> Result<Self, Self::Error> {
```suggestion
    ) -> Result<Self, Self::Error> {
            let amount = utils::get_amount_as_string(currency_unit, amount, currency)?;
```

2023-11-02 10:08 UTC, swangi-kumari commented
Hey @adarsh-jha-dev ,
Please make this changes too.
line (95-104)
```
#[derive(Serialize, Debug)]
pub struct PayeezyPaymentsRequest {
    pub merchant_ref: String,
    pub transaction_type: PayeezyTransactionType,
    pub method: PayeezyPaymentMethodType,
    pub amount: String,
    pub currency_code: String,
    pub credit_card: PayeezyPaymentMethod,
    pub stored_credentials: Option<StoredCredentials>,
    pub reference: String,
}
```
Here in this struct convert amount to String 
 `pub amount: String,`

2023-11-02 10:14 UTC, adarsh-jha-dev commented on crates/router/src/connector/payeezy/transformers.rs
> +    ) -> Result<Self, Self::Error> {
Done , thanks for your assistance

2023-11-02 11:20 UTC, AkshayaFoiger requested changes

2023-11-02 11:20 UTC, AkshayaFoiger commented on crates/router/src/connector/payeezy.rs
```
impl ConnectorIntegration<api::Capture, types::PaymentsCaptureData, types::PaymentsResponseData>
    for Payeezy
{
....
fn get_request_body(
        &self,
        req: &types::PaymentsCaptureRouterData,
    ) -> CustomResult<Option<types::RequestBody>, errors::ConnectorError> {
        let connector_req = payeezy::PayeezyCaptureOrVoidRequest::try_from(req)?;
        let payeezy_req = types::RequestBody::log_and_get_request_body(
            &connector_req,
            utils::Encode::<payeezy::PayeezyCaptureOrVoidRequest>::encode_to_string_of_json,
        )
        .change_context(errors::ConnectorError::RequestEncodingFailed)?;
        Ok(Some(payeezy_req))
}
}
```

In the above function for `PaymentsCaptureData`, do simlilar changes  as you did for `types::PaymentsAuthorizeRouterData`  and `types::RefundsRouterData<api::Execute>`  and address the corresponding changes required in `payeezy/transformers.rs` file

2023-11-02 11:20 UTC, AkshayaFoiger commented on crates/router/src/connector/payeezy/transformers.rs
> +            amount: item.router_data.request.refund_amount.to_string(),
```suggestion
            amount: item.amount,
```

2023-11-02 11:53 UTC, swangi-kumari commented
Hey @adarsh-jha-dev ,
Thanks for your interest in contributing to hyperswitch.
Let us know if you need any assistance from our end.
Also, even if hacktoberfest is over, we should celebrate open source everyday and we are open for more contributions from you.
We would still be rewarding folks with goodies even if the PR gets merged post hacktoberfest.
May the Source be with you!

2023-11-02 11:56 UTC, adarsh-jha-dev commented
> Hey @adarsh-jha-dev , Thanks for your interest in contributing to hyperswitch. Let us know if you need any assistance from our end. Also, even if hacktoberfest is over, we should celebrate open source everyday and we are open for more contributions from you. We would still be rewarding folks with goodies even if the PR gets merged post hacktoberfest. May the Source be with you!

Yeah, I am almost done with the changes, I am happy to contribute to Hyperswitch even after the fest, it helped me learn a lot of things

2023-11-02 12:16 UTC, adarsh-jha-dev commented on crates/router/src/connector/payeezy.rs
Done with the changes, could you please let me know if there are further changes required.

2023-11-02 12:34 UTC, adarsh-jha-dev commented
Hey @swangi-kumari , I have done the changes requested by you and other maintainers, I request you to please proceed further.

2023-11-02 17:00 UTC, AkshayaFoiger requested changes

2023-11-02 17:00 UTC, AkshayaFoiger commented on crates/router/src/connector/payeezy/transformers.rs
> +            amount: item.router_data.request.amount_to_capture.to_string(),
```suggestion
            amount: item.amount.clone(),
```

2023-11-02 17:10 UTC, AkshayaFoiger commented
Thanks for your quick response @adarsh-jha-dev,
Looks good to me!

2023-11-02 17:10 UTC, AkshayaFoiger approved these changes

2023-11-03 09:28 UTC, adarsh-jha-dev commented
Hey @swangi-kumari , I request you to please have a look at it, whenever you're free

2023-11-03 10:59 UTC, swangi-kumari approved these changes

2023-11-03 15:42 UTC, adarsh-jha-dev commented
@SamraatBansal  and @Sangamesh26 , could you also please approve this or let me know if there's any change needed?

2023-11-04 11:36 UTC, adarsh-jha-dev commented
Hey @swangi-kumari , could you please merge this if you're satisfied with the changes?

2023-11-05 13:22 UTC, SanchithHegde approved these changes
Looks good to me!

Thanks for the PR, @adarsh-jha-dev!

2023-11-05 13:36 UTC, merged