feat(connector): [Fiserv] Currency Unit Conversion
juspay/hyperswitch pull request #2715
Opened 2023-10-28 02:46 UTC by SagarDevAchar

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
- Addressing Issue: #2225 
- Modified two files in `hyperswitch/crates/router/src/connector/`
  - `fiserv.rs`
    - Implement `get_currency_unit` function
    - Modify `ConnectorIntegration` implementations for `Fiserv`
  - `fiserv/transformers.rs`
    - Implement `FiservRouterData<T>` structure and functionality
    - Modify implementation for `FiservPaymentsRequest` and `FiservRefundRequest`

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-31 11:19 UTC, AkshayaFoiger requested changes

2023-11-02 07:07 UTC, AkshayaFoiger requested changes

2023-11-02 07:07 UTC, AkshayaFoiger commented on crates/router/src/connector/fiserv/transformers.rs
> +        )?;
```suggestion
```

2023-11-02 07:07 UTC, AkshayaFoiger commented on crates/router/src/connector/fiserv/transformers.rs
>                  total: amount,
```suggestion
                total: item.amount.clone(),
```

2023-11-03 01:10 UTC, SagarDevAchar commented on crates/router/src/connector/fiserv/transformers.rs
>                  total: amount,
Resolved! Thanks @AkshayaFoiger!

2023-11-03 06:37 UTC, AkshayaFoiger commented
LGTM!

2023-11-03 06:37 UTC, AkshayaFoiger approved these changes

2023-11-03 11:11 UTC, swangi-kumari approved these changes
LGTM

2023-11-05 10:51 UTC, SanchithHegde approved these changes
Looks good to me!

Thanks for the PR, @SagarDevAchar!

2023-11-05 11:11 UTC, merged

2023-11-05 12:31 UTC, deepanshu-iiitu commented
Hey @SagarDevAchar  ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.
Thanks!