[UPDATED] transformers.rs
juspay/hyperswitch pull request #2722
Opened 2023-10-29 18:54 UTC by vinfinity7

## Type of Change

Fixes #2313
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-31 09:05 UTC, swangi-kumari commented
Hey @vinfinity7 ,
Please comment on the issue [2313](https://github.com/juspay/hyperswitch/issues/2313), so that we can assign that issue to you.

2023-10-31 09:06 UTC, swangi-kumari commented
Pls address the CI fails
Run `cargo +nightly` fmt for formatting.

2023-10-31 11:13 UTC, srujanchikke requested changes

2023-10-31 11:13 UTC, srujanchikke commented on crates/router/src/connector/payu/transformers.rs
> +    merchant_order_id: String,
There is no field called `merchant_order_id` in payU payment request according to[ payu docs ](https://developers.payu.com/en/restapi.html#update_notification_for_order_status) . You would have to rename this `merchant_order_id` to `ext_order_id` , Could you please make necessary changes ?

2023-11-02 11:53 UTC, swangi-kumari commented
Hi @vinfinity7 ,
Thanks for your interest in contributing to hyperswitch.
Let us know if you need any assistance from our end.
Also, even if hacktoberfest is over, we should celebrate open source everyday and we are open for more contributions from you.
We would still be rewarding folks with goodies even if the PR gets merged post hacktoberfest.
May the Source be with you!

2023-11-08 06:11 UTC, vinfinity7 commented
@swangi-kumari review the pr

2024-02-01 22:27 UTC, vinfinity7 commented
@swangi-kumari kindly review pr

2024-02-22 19:10 UTC, vinfinity7 commented
@swangi-kumari  if the pr's alright , you might wanna consider merging it 👍 or give me heads up as to what can i modify ?

2024-03-13 09:24 UTC, srujanchikke commented on crates/router/src/connector/payu/transformers.rs
> +    ext_order_id: String,
Make this field optional as suggested in payU docs and also update the branch to latest main to avoid spell check failure.

2024-03-13 09:24 UTC, srujanchikke reviewed
Hey @vinfinity7 ,
Please make suggested changes.

2024-03-15 00:39 UTC, vinfinity7 reviewed
So I've done the suggested changes @srujanchikke

2024-03-15 16:38 UTC, vinfinity7 commented on crates/router/src/connector/globalpay/requests.rs
> +    /// = AND
Sure

2024-03-15 16:41 UTC, vinfinity7 commented
@srujanchikke the suggested changes have been applied

2024-03-15 17:36 UTC, srujanchikke approved these changes

2024-03-16 10:23 UTC, vinfinity7 commented
@swangi-kumari as srujan has approved the changes , i would like to request your review too for a quick merge!

2024-03-18 06:21 UTC, vinfinity7 commented
@srujanchikke get this merged please as i have to update the branch everyday due to commits

2024-03-18 07:31 UTC, ArjunKarthik approved these changes

2024-03-19 01:20 UTC, vinfinity7 commented
@swangi-kumari any updates on this pr's merge ?

2024-03-24 11:30 UTC, vinfinity7 commented
@swangi-kumari Hello , please merge this , already been approved by two approvers
💯

2024-03-28 13:04 UTC, srujanchikke commented
@Gnanasundari24 @likhinbopanna  Could you please merge this PR ?

2024-04-02 17:59 UTC, vinfinity7 commented
@Gnanasundari24 @likhinbopanna Could you please merge this PR ?

2024-04-03 09:15 UTC, srujanchikke commented
> Make any Payment for connector PayU and see that you are getting "reference_id" field i

Hi @vinfinity7 , Can you curl request and response json for testing and also screenshots. 
CC : @likhinbopanna

2024-04-03 16:40 UTC, vinfinity7 commented
hi @srujanchikke being new to this repo , i am not aware of the route to hit , please be clear of the curl request command

2024-04-04 10:48 UTC, srujanchikke commented
> hi @srujanchikke being new to this repo , i am not aware of the route to hit , please be clear of the curl request command

You can provide `/payments` request json and screenshot of log where `raw_connector_request` (masked request) .

Please don't expose any api keys in the json or curl .

2024-04-04 10:52 UTC, srujanchikke commented
> > hi @srujanchikke being new to this repo , i am not aware of the route to hit , please be clear of the curl request command
> 
> You can provide `/payments` request & response jsons and screenshot of log where `raw_connector_request` (masked request) is logged.
> 
> Please don't expose any api keys in the json or curl .

This would look something like this 
reqeust json for making payment : 
```
{
    "amount":1000,
    "currency": "USD",
    "confirm": true,
    "capture_method": "automatic",
    "capture_on": "2022-09-10T10:11:12Z",
    "amount_to_capture": 1000,
    "customer_id": "123sdfadf",
    "email": "guest@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+1",
    "description": "Its my first payment request",
    "authentication_type": "three_ds",
    "return_url": "https://google.com",
    "payment_method": "card",
    "payment_method_type": "credit",
    "payment_method_data": {
        "card": {
            "card_number": "374245455400126",
            "card_exp_month": "05",
            "card_exp_year": "26",
            "card_holder_name": "joseph",
            "card_cvc": "1234"
        }
    },
    "billing": {
        "address": {
            "line1": "1467",
            "line2": "CA",
            "line3": "CA",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "US",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "<phone>",
            "country_code": "+91"
        }
    },
    "shipping": {
        "address": {
            "line1": "1467",
            "line2": "CA",
            "line3": "CA",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "US",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "<phone>",
            "country_code": "+91"
        }
    },
    "browser_info": {
        "user_agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/70.0.3538.110 Safari\/537.36",
        "accept_header": "text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/webp,image\/apng,\/;q=0.8",
        "language": "nl-NL",
        "color_depth": 24,
        "ip_address": "127.2.2.0",
        "screen_height": 723,
        "screen_width": 1536,
        "time_zone": 0,
        "java_enabled": true,
        "java_script_enabled": true
    },
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    
    "metadata": {
        "udf1": "value1",
        "new_customer": "true",
        "login_date": "2019-09-10T10:11:12Z"
    }
}
```

raw_connector_request : 

<img width="1024" alt="Screenshot 2024-04-04 at 4 21 19 PM" src="https://github.com/juspay/hyperswitch/assets/121822803/2aa9d53c-1a75-4276-99a2-25ba26f517d3">

You can also any other possible test cases if there.

2024-04-11 11:34 UTC, vinfinity7 commented
```
curl --location 'https://sandbox.hyperswitch.io/routing/business_profile/:business_profile_id/configs/pg_agnostic_mit' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer JWT_Token' \
--data '{
    "enabled": true
}' 
``` the request has to be somewhat like this but exactly what route i am a bit lost , @srujanchikke assistance

2024-05-14 23:23 UTC, closed without merging