feat(connector): [Elavon] Add card payments, psync, refunds, rsync and void flows
juspay/hyperswitch pull request #2728
Opened 2023-10-30 07:07 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Elavon Inc., formerly NOVA, is a processor of card transactions and a subsidiary of U.S. Bancorp. Elavon offers merchant processing in more than 30 countries and supports the payment needs of more than 1,000,000 merchant locations across the globe.

Resolves [#2957](https://github.com/juspay/hyperswitch-cloud/issues/2957)

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## How did you test it?

Can't be tested as Elavon has a closed sandbox.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-30 08:14 UTC, SamraatBansal requested changes

2023-11-30 08:14 UTC, SamraatBansal commented on crates/router/src/connector/elavon.rs
> +        ))
```suggestion
        Ok(format!(
            "{}/transactions/{}",
            self.base_url(connectors),
            req.request.connector_transaction_id
        ))
```

2023-11-30 08:14 UTC, SamraatBansal commented on crates/router/src/connector/elavon/transformers.rs
> +    pub(super) api_key: Secret<String>,
if its a `BodyKey` 2 key fields should be present in this struct

2023-11-30 08:14 UTC, SamraatBansal commented on crates/router/src/connector/elavon/transformers.rs
> +    Unknown,
Why have we set default value to unknown?

2023-11-30 08:14 UTC, SamraatBansal commented on crates/router/src/connector/elavon/transformers.rs
> +        }
```suggestion
            ElavonStatus::Declined | ElavonStatus::Voided |  ElavonStatus::Expired | ElavonStatus::Rejected => Self::Failure,
            ElavonStatus::Settled => Self::Success,
            ElavonStatus::HeldForReview => Self::ManualReview,
            ElavonStatus::Unknown => Self::Pending, // Have to get confirmation from the connector
            ElavonStatus::AuthorizationPending | ElavonStatus::SettlementDelayed | ElavonStatus::Captured | ElavonStatus::Authorized  => Self::Pending,
        }
```

2023-11-30 09:27 UTC, AkshayaFoiger commented
Elavon converge, no more supports REST API integration. For further information refer [here](https://developer.elavon.com/products/converge/v1/overview).

2024-01-09 14:19 UTC, JacobHayes commented
> Blocking this Pull Request as [Elavon converge](https://developer.elavon.com/products/converge/v1/overview), no more supports REST API integration.

I'm not sure what the API was before, but it seems they have an XML (😢) API in case that'd be possible to use.

2024-05-30 06:56 UTC, AkshayaFoiger commented
Connector contract changed

2024-05-30 06:56 UTC, closed without merging