feat(router): added Payment link new design
juspay/hyperswitch pull request #2731
Opened 2023-10-30 09:35 UTC by sahkal

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Make payment link design changes as per figma

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

`"payment_link_config": {
      "merchant_logo": null,
      "color_scheme":{
          "background_primary_color": null,
          "sdk_theme": null
      }
  }`

## Motivation and Context

## How did you test it?

<img width="1579" alt="Screenshot 2023-10-30 at 3 03 54 PM" src="https://github.com/juspay/hyperswitch/assets/26082680/c28e2702-cfde-4387-846f-8edb6cb90e60">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-03 11:41 UTC, Narayanbhat166 requested changes

2023-11-06 10:30 UTC, sahkal commented on crates/common_enums/src/enums.rs
> +    pub fn to_currency_symbol(&self) -> CurrencySymbol {
sure, will remove this

2023-11-07 08:16 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> -    pub order_details: Vec<pii::SecretSerdeValue>,
why are these changed to normal types instead of secret?

2023-11-07 08:16 UTC, Narayanbhat166 commented on crates/router/src/core/payment_link.rs
> +        ("#7EA8F6".to_string(), "#E5E5E5".to_string());
declare these as const values

2023-11-09 04:52 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> -    pub order_details: Vec<pii::SecretSerdeValue>,
You can expose when injecting in the html, these must be secret values. If these are normal types then these will be visible in the logs which we do not want

2023-11-09 12:15 UTC, Narayanbhat166 approved these changes

2023-11-09 14:27 UTC, Narayanbhat166 approved these changes

2023-11-09 14:45 UTC, jarnura requested changes

2023-11-09 14:45 UTC, jarnura commented on crates/router/src/core/payment_link.rs
> +                    .unwrap_or("https://i.imgur.com/RfxPFQo.png".to_string())
Move to consts

2023-11-09 14:45 UTC, jarnura commented on crates/router/src/core/payment_link.rs
> +                order.product_img_link = Some("https://i.imgur.com/On3VtKF.png".to_string());
Move to consts

2023-11-09 14:54 UTC, sahkal commented on crates/router/src/core/payment_link.rs
> +                    .unwrap_or("https://i.imgur.com/RfxPFQo.png".to_string())
done

2023-11-09 14:54 UTC, sahkal commented on crates/router/src/core/payment_link.rs
> +                order.product_img_link = Some("https://i.imgur.com/On3VtKF.png".to_string());
done

2023-11-09 15:12 UTC, jarnura approved these changes

2023-11-09 15:17 UTC, Narayanbhat166 approved these changes

2023-11-10 09:23 UTC, merged