Feature(Connector): Aci_Currency_Unit_Conversion
juspay/hyperswitch pull request #2750
Opened 2023-10-31 17:15 UTC by Harshwardhan9431

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-10-31 20:27 UTC, swangi-kumari submitted a review, later dismissed
LGTM!

2023-11-01 15:35 UTC, AkshayaFoiger approved these changes

2023-11-02 07:25 UTC, AkshayaFoiger requested changes

2023-11-02 07:25 UTC, AkshayaFoiger commented on crates/router/src/connector/aci/transformers.rs
> +        )?,
```suggestion
        amount:  item.amount.clone(),
```

2023-11-02 07:25 UTC, AkshayaFoiger commented on crates/router/src/connector/aci/transformers.rs
> +        )?;
```suggestion
        let amount = item.amount.clone();
```

2023-11-02 11:52 UTC, swangi-kumari commented
Hey @Harshwardhan9431 ,
Thanks for your interest in contributing to hyperswitch.
Let us know if you need any assistance from our end.
Also, even if hacktoberfest is over, we should celebrate open source everyday and we are open for more contributions from you.
We would still be rewarding folks with goodies even if the PR gets merged post hacktoberfest.
May the Source be with you!

2023-11-02 12:43 UTC, Harshwardhan9431 commented
Yeah Done :)

2023-11-03 07:32 UTC, AkshayaFoiger commented
Looks Good!

2023-11-03 07:32 UTC, AkshayaFoiger approved these changes

2023-11-03 08:05 UTC, swangi-kumari approved these changes

2023-11-05 10:48 UTC, SanchithHegde approved these changes
Looks good to me!

Thanks for the PR, @Harshwardhan9431!

2023-11-05 11:08 UTC, merged

2023-11-05 12:31 UTC, deepanshu-iiitu commented
Hey @Harshwardhan9431  ,
Thanks a bunch for all your contributions! We've got a little something for you to show our appreciation.
Just take a moment to fill out this [form](https://forms.gle/yqbtjFuP6oxLaBKN8), and get ready for some awesome swag coming your way.
Thanks!