feat(connector): [Square] Use connector_response_reference_id as reference to merchant
juspay/hyperswitch pull request #2767
Opened 2023-11-02 14:42 UTC by hegdeadithyak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-13 12:18 UTC, Adithya4720 commented
@deepanshu-iiitu  Can you check this out

2023-12-16 07:34 UTC, swangi-kumari commented
Hey @Adithya4720 ,
Can you please resolve conflicts.

2023-12-19 18:19 UTC, Adithya4720 commented
@swangi-kumari Please Check this out

2024-01-04 04:08 UTC, srujanchikke requested changes

2024-01-04 04:08 UTC, srujanchikke commented on crates/router/src/connector/powertranz.rs
> +    fn get_currency_unit(&self) -> api::CurrencyUnit {
Hi @Adithya4720 ,

This changes are not concerned with issue attached. Please refer #2052 for more info and also change the PR title accordingly.

2024-01-23 17:56 UTC, closed without merging