fix(connector): Add attempt_status in field in error_response
juspay/hyperswitch pull request #2794
Opened 2023-11-06 11:46 UTC by srujanchikke

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Payment attempt status would remain in non terminal state if psync gets 4xx or 5xx .This needs to handled in connector error response .This PR introduces optional field called attempt_status field in ErrorResponse struct by which we can update payment status in case 4xx and 5xx in connector `get_error_response` .

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Payment attempt status would remain in non terminal state if psync gets 4xx or 5xx .This needs to handled in connector error response .This PR introduces optional field called attempt_status field in ErrorResponse struct by which we can update payment status in case 4xx and 5xx in connector `get_error_response` .

## How did you test it?

tested using postman .
Same test cases as https://github.com/juspay/hyperswitch/pull/2772

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-07 09:02 UTC, sai-harsha-vardhan requested changes

2023-11-07 09:02 UTC, sai-harsha-vardhan commented on crates/router/src/services/api.rs
> +                                            router_data.status = error_res
update this value only if attempt_status is some, no need to update otherwise

2023-11-07 13:23 UTC, sai-harsha-vardhan approved these changes

2023-11-08 06:30 UTC, ArjunKarthik approved these changes

2023-11-08 08:25 UTC, SanchithHegde approved these changes

2023-11-08 08:31 UTC, likhinbopanna approved these changes

2023-11-08 10:24 UTC, merged