feat(events): add extracted fields based on req/res types
juspay/hyperswitch pull request #2795
Opened 2023-11-06 14:53 UTC by lsampras

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [x] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- Add a trait to allow adding top level fields & types for each request
- these fields are now collected from either the response or request in order
- This are exposed as top level fields allowing to query over multiple types of api events with a single tag

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

This will allow us to query multiple events with a single filter allowing some type of tag based searches
for e.g you can filter all the payment related api calls with a single payment id filter

## How did you test it?

- Make a payment create api call & check logs

<img width="1689" alt="image" src="https://github.com/juspay/hyperswitch/assets/21202349/b8c1b86d-572f-4bde-a341-652c4d2366bf">

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-07 06:55 UTC, ivor-juspay submitted a review, later dismissed

2023-11-07 07:02 UTC, harsh-sharma-juspay approved these changes

2023-11-07 07:04 UTC, harsh-sharma-juspay submitted a review, later dismissed

2023-11-08 11:35 UTC, NishantJoshi00 requested changes
Other than that, looks good!

2023-11-08 11:35 UTC, NishantJoshi00 commented on Makefile
> +	cargo clippy --all-features --all-targets -- -D warnings -A clippy::large_futures
Shouldn't we handle large futures?

2023-11-08 11:35 UTC, NishantJoshi00 commented on crates/common_utils/src/lib.rs
> +#[allow(missing_docs)] // Todo: add docs
Please create a issue or a PR to add documentation for this

2023-11-08 14:05 UTC, SanchithHegde approved these changes

2023-11-08 14:10 UTC, likhinbopanna approved these changes

2023-11-08 16:01 UTC, lsampras commented
force-merging as conditions met

2023-11-08 16:01 UTC, merged