feat(user): setup user tables
juspay/hyperswitch pull request #2803
Opened 2023-11-07 12:12 UTC by apoorvdixit88

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Setup user and user_roles table along with queries.

### Additional Changes

- [ ] This PR modifies the API contract
- [x] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-08 08:05 UTC, racnan requested changes

2023-11-08 08:05 UTC, racnan commented on crates/diesel_models/src/user_roles.rs
> +        status: enums::UserStatus,
add modified_by

2023-11-08 08:05 UTC, racnan commented on crates/diesel_models/src/user.rs
> +}
not required

2023-11-08 10:40 UTC, ThisIsMani approved these changes

2023-11-08 10:46 UTC, ThisIsMani approved these changes

2023-11-08 10:51 UTC, racnan submitted a review, later dismissed

2023-11-08 11:03 UTC, SanchithHegde approved these changes

2023-11-09 12:40 UTC, ThisIsMani approved these changes

2023-11-09 12:52 UTC, SanchithHegde submitted a review, later dismissed

2023-11-10 06:00 UTC, ThisIsMani approved these changes

2023-11-10 06:02 UTC, lsampras approved these changes

2023-11-10 06:31 UTC, merged