refactor(connector): [Shift4] change error message from NotSupported to NotImplemented
juspay/hyperswitch pull request #2880
Opened 2023-11-15 17:32 UTC by unpervertedkid

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Resolves #2860 

## How did you test it?

No test cases required. As In this PR only error message have been changed from Not Supported error message to NotImplemented error message.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-29 07:08 UTC, swangi-kumari commented
Hey @unpervertedkid ,
Please resolve the conflicts from your branch.

2023-11-29 12:30 UTC, swangi-kumari requested changes

2023-11-29 12:30 UTC, swangi-kumari commented on crates/router/src/connector/shift4/transformers.rs
> +            payments::GiftCardData::Givex(_) => Err(errors::ConnectorError::NotImplemented(
Here, as `givex` and `paysafecard` are throwing the same error now.
Could you please OR ( | ) between them and avoid the repetition of same error.

2023-11-29 12:30 UTC, swangi-kumari commented on crates/router/src/connector/shift4/transformers.rs
> +            | payments::VoucherData::PayEasy(_) => Err(errors::ConnectorError::NotImplemented(
Here, use OR( | ) between `Boleto` and `Efecty` Payment methods as we have common error message now for all the Payment Methods.

2023-11-29 12:30 UTC, swangi-kumari commented on crates/router/src/connector/shift4/transformers.rs
> +            | payments::BankTransferData::Pse {} => Err(errors::ConnectorError::NotImplemented(
Here, use OR( | ) between `MultibancoBankTransfer` and `AchBankTransfer` Payment methods as we have common error message now for all the Payment Methods.

2023-11-29 12:30 UTC, swangi-kumari commented on crates/router/src/connector/shift4/transformers.rs
> +            | payments::WalletData::SwishQr(_) => Err(errors::ConnectorError::NotImplemented(
Here, use OR( | ) between `WeChatPayRedirect` and `AliPayQr` Payment methods as we have common error message now for all the Payment Methods.

2023-11-30 06:33 UTC, unpervertedkid commented
@swangi-kumari take a look at this iteration

2023-11-30 18:48 UTC, swangi-kumari approved these changes
LGTM!

2023-11-30 19:06 UTC, merged