feat(mca): Add new `auth_type` and a status field for mca
juspay/hyperswitch pull request #2883
Opened 2023-11-16 06:18 UTC by ThisIsMani

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add a new `auth_type` called `TemporaryAuth` which describes that auth details are not yet received. When using this `auth_type` the connector status will be `inactive` and mca will be disabled.

### Additional Changes

- [x] This PR modifies the API contract
- [x] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

To support connector integration without auth details.
Closes #2895 

## How did you test it?

Postman.
Payment Connector - Create and Payment Connector - Update now supports a new auth type called `TemporaryAuth` and a new field `status`.
```
curl --location 'http://localhost:8080/account/merchant_1700133263/connectors' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: test_admin' \
--data '{
  "connector_type": "fiz_operations",
  "connector_name": "paypal",
  "connector_account_details": {
    "auth_type": "TemporaryAuth"
  },
  "status": "inactive",
  "disabled": true
}'
```
If `TemporaryAuth` is used in the request, the status field cannot be `active` and disabled cannot be `false`. This is applied for update mca as well. If a connector is inactive it cannot be enabled without changing the status to active.

There are the following error messages that will be thrown if incorrect request is used.
| auth_type     | status   | disabled | error_message                                                                             |
|---------------|----------|----------|-------------------------------------------------------------------------------------------|
| TemoraryAuth  | active   | *        | Connector status cannot be active when using TemporaryAuth                                |
| TemporaryAuth | inactive | false    | Connector cannot be enabled when connector_status is inactive or when using TemporaryAuth |
| ValidAuth     | inactive | false    | Connector cannot be enabled when connector_status is inactive or when using TemporaryAuth |

If all the fields are passed correctly you will a normal mca response.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-16 09:58 UTC, jarnura requested changes

2023-11-16 09:58 UTC, jarnura commented on migrations/2023-11-12-131143_connector-status-column/up.sql
> +ALTER TABLE merchant_connector_account
add a default value.

2023-11-16 12:01 UTC, ThisIsMani commented on migrations/2023-11-12-131143_connector-status-column/up.sql
> +ALTER TABLE merchant_connector_account
Done

2023-11-16 14:16 UTC, jarnura submitted a review, later dismissed

2023-11-17 06:26 UTC, Narayanbhat166 commented on crates/router/src/core/admin.rs
> +    };
you can extract this to a function

2023-11-17 08:51 UTC, Narayanbhat166 approved these changes

2023-11-17 08:57 UTC, apoorvdixit88 approved these changes

2023-11-17 09:01 UTC, likhinbopanna approved these changes

2023-11-17 09:28 UTC, lsampras approved these changes

2023-11-20 07:42 UTC, merged