fix: fiserv mca metadata and cybersource mandates
juspay/hyperswitch pull request #2920
Opened 2023-11-20 05:33 UTC by SamraatBansal

## Type of Change

- [X] Bugfix
- [X] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- [Fiserv] Fix MCA metadata deserialisation from `camelCase` to `snake_case`
- [Cybersource] Change connector amount to `Base`
- [Cybersource] Implement Mandates 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-20 13:02 UTC, Narayanbhat166 submitted a review, later dismissed

2023-11-20 13:08 UTC, ArjunKarthik requested changes

2023-11-20 13:08 UTC, ArjunKarthik commented on crates/router/src/core/payments.rs
> +        Some(_) if is_mandate => {
keep this logic cyber source specific

2023-11-20 13:12 UTC, SamraatBansal commented on crates/router/src/connector/cybersource/transformers.rs
> +                    Some(vec![CybersourceActionsList::TokenCreate]),
This is required only in case of `CIT` when `setup_future_usage` is present in the router_data and is implemented in accordance to cybersource's docs

2023-11-20 13:23 UTC, ArjunKarthik commented on crates/router/src/connector/cybersource/transformers.rs
> +            _ => Err(errors::ConnectorError::NotImplemented(
Let's not have default here

2023-11-20 14:09 UTC, Narayanbhat166 approved these changes

2023-11-20 14:16 UTC, ArjunKarthik approved these changes

2023-11-21 19:05 UTC, merged

2023-11-22 07:12 UTC, Gnanasundari24 reviewed
Approved by QA