feat(postman): [Prophetpay] Add test cases
juspay/hyperswitch pull request #2946
Opened 2023-11-22 11:36 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add scenario for payment through Prophetpay's Card Redirect
Payment is done with Card Redirect 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-22 16:30 UTC, pixincreate requested changes

2023-11-22 16:30 UTC, pixincreate commented on postman/collection-dir/prophetpay/Flow Testcases/.meta.json
Where are the variation cases?

2023-11-22 16:30 UTC, pixincreate commented on postman/collection-dir/prophetpay/Flow Testcases/Happy Cases/.meta.json
Only 1 test?

2023-11-22 16:30 UTC, pixincreate commented on postman/collection-dir/prophetpay/Flow Testcases/QuickStart/.meta.json
I would also prefer you add other test cases in here that has refunds. You can look into Stripe's / Adyen's collection for more info.

2023-11-22 16:30 UTC, pixincreate commented on postman/collection-dir/prophetpay/Health check/New Request/request.json
> +  ],
Remove

2023-11-22 16:30 UTC, pixincreate commented
Also, kindly add screenshots of the tests run

2023-12-14 11:07 UTC, Sakilmostak commented on postman/collection-dir/prophetpay/Flow Testcases/.meta.json
Won't be able to generate variation cases because there is only one payment method i.e, Card redirect and the payment for this flow only occur after redirection.

2023-12-14 11:07 UTC, Sakilmostak commented on postman/collection-dir/prophetpay/Flow Testcases/Happy Cases/.meta.json
Added case for confirm = false

2023-12-14 11:08 UTC, Sakilmostak commented on postman/collection-dir/prophetpay/Health check/New Request/request.json
> +  ],
Done

2023-12-14 11:09 UTC, Sakilmostak commented on postman/collection-dir/prophetpay/Flow Testcases/QuickStart/.meta.json
Post payment flows cant be tested since the payment is done only after redirection, the connector doesn't have context about payment before that.

2023-12-14 11:26 UTC, pixincreate approved these changes

2023-12-14 12:44 UTC, ArjunKarthik approved these changes

2023-12-19 10:58 UTC, merged