feat(currency_conversion): currency conversion feature
juspay/hyperswitch pull request #2948
Opened 2023-11-22 11:56 UTC by prajjwalkumar17

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

A whole new crate for Currency Conversion which takes foreign exchange rates and converts a from_currency to to_currency relatively i.e via a base_currency.

Forex rates can be fetched using the route /forexrates which for now uses [OpenExchange](https://openexchangerates.org/) Api. Moreover we have a fallback api as well for cases in which our primary api fails.

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Written Test cases in the conversion.rs for all the scenarios.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-23 11:40 UTC, vspecky requested changes

2023-11-23 11:40 UTC, vspecky commented on crates/currency_conversion/Cargo.toml
> +api_models = { version = "0.1.0", path = "../api_models", package = "api_models" }
I think `common_enums` should suffice for this crate. Use `common_enums` instead of `api_models`

2023-11-24 11:08 UTC, vspecky approved these changes

2023-11-24 11:23 UTC, ArjunKarthik approved these changes

2023-11-24 14:40 UTC, SanchithHegde submitted a review, later dismissed

2023-11-24 14:40 UTC, SanchithHegde commented on config/development.toml
Please make this change in the remaining config files: Docker Compose config file, example config file with comments, and loadtest config file.

2023-11-24 14:40 UTC, SanchithHegde commented on crates/router/src/utils/currency.rs
> +    //acquire lock one last time and try to fetch and update local&redis
```suggestion
    //acquire lock one last time and try to fetch and update local & redis
```

2023-11-24 14:40 UTC, SanchithHegde commented on crates/router/src/utils/currency.rs
> +            // fallback_forex_fetch_expired_redis(state, redis_data).await
Remove commented code

2023-11-24 14:40 UTC, SanchithHegde commented on crates/router/src/utils/currency.rs
> +    // save_forex_to_local(rates);
Remove commented code.

2023-11-28 07:28 UTC, SanchithHegde approved these changes

2023-11-28 07:30 UTC, vspecky submitted a review, later dismissed

2023-11-28 10:21 UTC, ArjunKarthik approved these changes

2023-11-28 10:25 UTC, SanchithHegde approved these changes

2023-11-28 10:28 UTC, vspecky approved these changes

2023-11-28 10:53 UTC, merged