enhancement(router): add key_vaule to locker metrics
juspay/hyperswitch pull request #2995
Opened 2023-11-28 10:17 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

add key_vaule to locker metrics to identify the request made to different locker (Rust or Basilisk HS).

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Testing is not required as this is just updating the key_value of the existing locker metrics.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-11-28 13:52 UTC, sai-harsha-vardhan submitted a review, later dismissed

2023-11-29 04:22 UTC, NishantJoshi00 requested changes
Looks like there is no counter to know successful addition, can we add that metric with appropriate attributes?

2023-11-29 06:51 UTC, NishantJoshi00 requested changes

2023-11-29 06:51 UTC, NishantJoshi00 commented on crates/router/src/core/payment_methods/cards.rs
> +                    &[router_env::opentelemetry::KeyValue::new("locker", "rust")],
should we add operation here too?

2023-11-29 06:51 UTC, NishantJoshi00 commented on crates/router/src/core/payment_methods/cards.rs
> +                );
and here?

2023-11-29 06:53 UTC, ShankarSinghC commented on crates/router/src/core/payment_methods/cards.rs
> +                    &[router_env::opentelemetry::KeyValue::new("locker", "rust")],
Yeah, I will add it.

2023-12-04 06:50 UTC, likhinbopanna approved these changes

2023-12-04 07:03 UTC, merged