feat(routing): Updated openapi spec to include routing APIs
juspay/hyperswitch pull request #3012
Opened 2023-11-29 12:31 UTC by Sarthak1799

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Updated the open-api spec to include routing APIs.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-08 07:15 UTC, vspecky requested changes

2023-12-08 07:15 UTC, vspecky commented on crates/router/src/routes/routing.rs
> +   operation_id = "Retrieve routing dictionary",
Rename this route to `list_routing_configs` and remove the word `dictionary` from the docs.

2023-12-08 07:15 UTC, vspecky commented on crates/router/src/routes/routing.rs
> +   operation_id = "Update default config",
```suggestion
   operation_id = "Update default fallback config",
```

2023-12-08 07:15 UTC, vspecky commented on crates/router/src/routes/routing.rs
> +   operation_id = "Retrieve default config",
```suggestion
   operation_id = "Retrieve default fallback config",
```

2023-12-11 07:48 UTC, vspecky submitted a review, later dismissed

2023-12-12 12:48 UTC, vspecky approved these changes

2023-12-12 18:56 UTC, SanchithHegde approved these changes

2023-12-19 10:58 UTC, tinu-hareesswar approved these changes

2023-12-19 11:43 UTC, Narayanbhat166 approved these changes

2023-12-19 11:43 UTC, merged