refactor(routing): Remove backwards compatibility for the routing crate
juspay/hyperswitch pull request #3015
Opened 2023-11-29 18:06 UTC by Aprabhat19

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Remove backwards compatibility for the routing crate

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-06 06:20 UTC, vspecky approved these changes

2024-07-17 08:08 UTC, vspecky requested changes

2024-07-17 10:02 UTC, Aprabhat19 commented on crates/api_models/src/routing.rs
> -}
Will remove these fields and open a separate PR

2024-07-17 14:18 UTC, SanchithHegde approved these changes

2024-07-18 07:43 UTC, vspecky submitted a review, later dismissed
LGTM

2024-07-18 07:57 UTC, SanchithHegde approved these changes

2024-07-18 07:59 UTC, vspecky approved these changes
LGTM

2024-07-18 08:54 UTC, jarnura approved these changes

2024-07-18 09:37 UTC, ivor-juspay approved these changes

2024-07-18 09:37 UTC, ivor-juspay approved these changes

2024-07-18 10:07 UTC, merged