feat(Braintree): Sync with Hyperswitch Reference
juspay/hyperswitch pull request #3037
Opened 2023-12-02 09:33 UTC by unpervertedkid

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
fixes #3007 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-05 18:15 UTC, prasunna09 requested changes

2023-12-05 18:15 UTC, prasunna09 commented on crates/router/src/connector/braintree/transformers.rs
> +            types::ResponseId::ConnectorTransactionId(item.response.transaction.id.clone());
```suggestion
        let id =
            item.response.transaction.id.clone();
```
Please use this id  as both resource_id and connector_response_reference_id

2023-12-05 18:15 UTC, prasunna09 commented on crates/router/src/connector/braintree/transformers.rs
> +                resource_id: connector_id,
```suggestion
                resource_id: types::ResponseId::ConnectorTransactionId(id.clone()),
```

2023-12-05 18:15 UTC, prasunna09 commented on crates/router/src/connector/braintree/transformers.rs
> +                connector_response_reference_id: Some(item.response.transaction.id),
```suggestion
                connector_response_reference_id: Some(id),
```

2023-12-05 19:52 UTC, prasunna09 approved these changes

2023-12-06 02:04 UTC, ArjunKarthik approved these changes

2023-12-06 10:13 UTC, merged