feat(pm_auth): pm_auth service migration
juspay/hyperswitch pull request #3047
Opened 2023-12-04 10:10 UTC by Chethan-rao

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-05 08:59 UTC, vspecky requested changes

2023-12-05 08:59 UTC, vspecky commented on crates/router/src/core/admin.rs
> +    match is_unroutable_connector {
```suggestion
    if  !is_unroutable_connector {
```

2023-12-05 10:21 UTC, vspecky requested changes
Also add the filter to filter out payment method auth connector accounts in routing

2023-12-05 10:26 UTC, Sarthak1799 commented
> Also add the filter to filter out payment method auth connector accounts in routing

That was already added to main in a fix PR - https://github.com/juspay/hyperswitch/pull/3019

2023-12-05 10:28 UTC, vspecky submitted a review, later dismissed

2023-12-05 11:33 UTC, vspecky submitted a review, later dismissed

2023-12-06 07:51 UTC, vspecky approved these changes

2023-12-06 13:15 UTC, pixincreate approved these changes

2023-12-06 15:32 UTC, merged