fix(connector): [Checkout] Fix status mapping for checkout
juspay/hyperswitch pull request #3073
Opened 2023-12-06 16:46 UTC by prasunna09

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

When there is delay in response, we are getting status "`Authorized`" and payment intent status is being set to "`requires_capture`" for `automatic` capture method. 
Updated the status mapping to "`Pending`" in the above case

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

make 3DS or non-3DS payment, status should be "Processing" and should make Psync with `force_sync=true` then status should be updated to "succeeded". 
<img width="971" alt="Screenshot 2023-12-06 at 9 21 27 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/6410f92f-c033-4120-bf19-b1ba0b3679c5">
<img width="763" alt="Screenshot 2023-12-06 at 9 21 37 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/3bc1698c-4f8e-462c-8b31-570c9f1acbb3">
<img width="809" alt="Screenshot 2023-12-06 at 9 22 46 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/38380fe3-bc78-43ff-9372-e895e8393230">
<img width="1039" alt="Screenshot 2023-12-06 at 9 23 03 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/12e37f95-71d8-46bc-a496-252c050ec992">
<img width="1292" alt="Screenshot 2023-12-12 at 6 12 39 PM" src="https://github.com/juspay/hyperswitch/assets/70575890/ecd4b0b2-ba98-4e4e-ae0d-7ff795a634a3">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-12 16:42 UTC, ArjunKarthik approved these changes

2023-12-12 16:46 UTC, ArjunKarthik requested changes
One minor comment

2023-12-13 11:10 UTC, ArjunKarthik approved these changes

2023-12-13 11:33 UTC, SamraatBansal submitted a review, later dismissed

2023-12-15 10:06 UTC, ArjunKarthik approved these changes

2023-12-15 10:42 UTC, SamraatBansal approved these changes

2023-12-15 11:19 UTC, merged