refactor(merchant_connector_account): change unique constraint to connector label
juspay/hyperswitch pull request #3091
Opened 2023-12-08 07:51 UTC by Narayanbhat166

## Type of Change

- [x] Refactoring

## Description

This Pr changes the unique constraint of `merchant_connector_account` to `connector_label` and `profile_id`

## Motivation and Context

In order to allow multiple instances of the same connector to be created.

## How did you test it?

- Create a stripe account with the same connector twice -> Second time an error must be thrown
```json
{
    "error": {
        "type": "invalid_request",
        "message": "The merchant connector account with the specified profile_id 'pro_BrafXvLpgRJNdRDVhS4P' and connector_label 'stripe_fallback' already exists in our records",
        "code": "HE_01"
    }
}
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

2023-12-08 09:01 UTC, vspecky commented
@Narayanbhat166 We cannot make this change until we have removed backwards compatibility from routing (i.e. made merchant_connector_id mandatory) and ensured that every connector in every payment intent/attempt is coupled with a merchant connector id.

If we remove the constraint before the aforementioned is done, we'll run into issues (eg: for PSync, if the payment attempt only has `stripe` but no merchant connector id, and the profile has 3 stripe connector accounts, there's a 2/3 chance that the call will fail since the wrong credentials will be picked)

@Aprabhat19 is working on removing the backwards compatibility and backfilling all payment intents/attempts in the DB.

2024-02-19 13:55 UTC, vspecky requested changes

2024-02-19 13:55 UTC, vspecky commented on migrations/2023-12-06-060216_change_primary_key_for_mca/up.sql
Nit: Add the new index before deleting the old one, in case it fails.

2024-02-19 14:01 UTC, vspecky approved these changes

2024-02-20 05:35 UTC, sai-harsha-vardhan approved these changes

2024-02-20 06:28 UTC, sahkal approved these changes

2024-02-20 07:45 UTC, merged