refactor(settings): make the function to deserialize hashsets more generic
juspay/hyperswitch pull request #3104
Opened 2023-12-11 11:34 UTC by SanchithHegde

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR updates the application configuration deserialization logic to use a common generic function to deserialize `HashSet<T>` instead of specific ones. In addition, this PR updates the function to be more lenient in that it allows spaces around the commas for better readability.

## Motivation and Context

Reducing duplicated code.

## How did you test it?

Unit tests:
```shell
cargo test --package router --lib --all-features -- configs::settings::hashset_deserialization_test
```

<img width="800" alt="Screenshot of unit tests run" src="https://github.com/juspay/hyperswitch/assets/22217505/e14d53f3-f1f5-471f-b0d9-0c174a407273">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-11 11:36 UTC, vspecky requested changes

2023-12-11 11:36 UTC, vspecky commented on crates/router/src/configs/settings.rs
> +        .flat_map(|s| T::from_str(s.trim()))
We probably don't want `flat_map` since it will cause any `from_str` errors to be silently ignored instead of being reported.

2023-12-11 12:10 UTC, lsampras approved these changes

2023-12-11 12:10 UTC, lsampras commented on crates/router/src/configs/settings.rs
> +            .collect::<HashSet<_>>();
why not call the `deserialize_hashset` function here...

2023-12-12 05:11 UTC, Narayanbhat166 approved these changes

2023-12-14 02:32 UTC, Narayanbhat166 commented
@SanchithHegde Deployment readiness failing, is that specific to this PR only or all the PRs in general?

2023-12-14 02:33 UTC, Narayanbhat166 submitted a review, later dismissed

2023-12-14 04:55 UTC, SanchithHegde commented
@Narayanbhat166 This PR is still WIP, there are a few errors thrown by the application when it runs, I'll fix them taking help from the connector team.

2023-12-15 07:11 UTC, vspecky requested changes

2023-12-15 07:11 UTC, vspecky commented on crates/router/src/configs/settings.rs
> +        errors.splice(0..0, [String::from("Some errors occurred:")]);
```suggestion
        errors.insert(0, String::from("Some errors occurred:"));
```

2023-12-15 08:03 UTC, vspecky submitted a review, later dismissed
Nitpick but not a blocker.

2023-12-15 08:03 UTC, vspecky commented on crates/router/src/configs/settings.rs
> +        Err(errors.join("\n"))
```suggestion
        Err(format!("Some errors occurred:\n", errors.join("\n")))
```

2023-12-15 09:12 UTC, vspecky approved these changes

2023-12-15 10:04 UTC, ArjunKarthik commented on crates/common_enums/src/enums.rs
> +            | Self::ISK
@SanchithHegde Let's not support ISK for now, I will take it in separate PR, where decision will be made based on the connector also

2023-12-15 11:01 UTC, ArjunKarthik submitted a review, later dismissed

2023-12-15 11:26 UTC, vspecky submitted a review, later dismissed

2024-01-29 08:24 UTC, ArjunKarthik approved these changes

2024-01-30 09:19 UTC, merged