feat(pm_auth): Support different pm types in PM auth
juspay/hyperswitch pull request #3114
Opened 2023-12-12 10:21 UTC by Sarthak1799

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Support for SEPA and BACS in direct debit PM auth

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-01-18 12:56 UTC, vspecky requested changes

2024-01-18 12:56 UTC, vspecky commented on crates/pm_auth/src/types.rs
> +    SEPA(BankAccountDetailsSEPA),
```suggestion
    Ach(BankAccountDetailsAch),
    Bacs(BankAccountDetailsBacs),
    Sepa(BankAccountDetailsSepa),
```

2024-02-06 09:37 UTC, vspecky requested changes

2024-02-06 09:37 UTC, vspecky commented on crates/router/src/core/payment_methods/cards.rs
> +                    .ok_or(errors::ApiErrorResponse::InternalServerError)
```suggestion
                    .get_required_value("payment_method_type")
```

2024-02-06 09:37 UTC, vspecky commented on crates/router/src/core/pm_auth.rs
> +        name: name.unwrap_or_default(),
Don't use `unwrap_or_default()`. Keep it a sensible default or keep it `None` if absent.

2024-03-14 08:13 UTC, vspecky requested changes

2024-03-14 08:13 UTC, vspecky commented on crates/router/src/core/pm_auth.rs
> +                    "{}-{}",
Lets include additional metadata like the payment method type (Bacs, Sepa), in the hash.

2024-03-14 11:35 UTC, vspecky approved these changes

2024-03-14 11:43 UTC, Chethan-rao approved these changes

2024-03-15 12:42 UTC, merged