add placetopay connector
juspay/hyperswitch pull request #3117
Opened 2023-12-12 13:24 UTC by srujanchikke

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

New connector Integration [placetopay](https://placetopay-api.stoplight.io/docs/api-services-docs/b736ea6925314-procesamiento-de-transaccion) .

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

New connector integration **Placetopay**

## How did you test it?

We don't have api-keys , we can't test this connector. 

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-14 01:49 UTC, ArjunKarthik requested changes

2023-12-14 01:49 UTC, ArjunKarthik commented on crates/router/src/connector/placetopay/transformers.rs
> +            | PlacetopayStatus::PendingProcess => Self::Authorizing,
this has to be confirmed

2023-12-14 01:49 UTC, ArjunKarthik commented on crates/router/src/connector/placetopay/transformers.rs
> +                    .reference
Since, we don't have access to their dashboard, how we did this mapping?

2023-12-14 01:49 UTC, ArjunKarthik commented on crates/router/src/connector/placetopay/transformers.rs
> +        let auth = PlacetopayAuth::try_from(&item.connector_auth_type)?;
if partial refund is not supported, we need to throw respective error

2023-12-14 01:49 UTC, ArjunKarthik commented on crates/router/src/connector/placetopay/transformers.rs
> +                Self::Pending
this has to be confirmed

2023-12-14 01:49 UTC, ArjunKarthik commented on crates/router/src/connector/placetopay/transformers.rs
> +        let internal_reference = item.request.connector_transaction_id.to_owned();
does connector support sync with our payment reference?

2023-12-14 01:49 UTC, ArjunKarthik commented on crates/router/src/connector/placetopay/transformers.rs
> +        let internal_reference = item
Does connector sync with our refund reference?

2023-12-16 16:10 UTC, ArjunKarthik approved these changes
For the open comments and current comments, please resolve it in upcoming PR

2023-12-16 16:29 UTC, ArjunKarthik approved these changes

2023-12-17 07:53 UTC, deepanshu-iiitu approved these changes

2023-12-17 08:09 UTC, merged