feat(pm_list): add required fields for google pay
juspay/hyperswitch pull request #3196
Opened 2023-12-22 07:00 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Resolves [#3706](https://github.com/juspay/hyperswitch-cloud/issues/3706)

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-26 06:11 UTC, prasunna09 reviewed
here you have only mentioned about connector list that supports google pay mandates. but what about the required fields? Are there no required fields for this pm type?

2023-12-27 05:21 UTC, AkshayaFoiger commented
> here you have only mentioned about connector list that supports google pay mandates. but what about the required fields? Are there no required fields for this pm type?

Most of the connectors don't require additional fields, but some does. I will update the PR

2023-12-31 07:42 UTC, prasunna09 requested changes

2023-12-31 07:42 UTC, prasunna09 commented on crates/router/src/configs/defaults.rs
> +                                                field_type: enums::FieldType::UserAddressLine1,
```suggestion
                                                field_type: enums::FieldType::UserAddressLine2,
```

2024-01-08 06:50 UTC, prasunna09 approved these changes

2024-01-08 06:50 UTC, prasunna09 commented on crates/router/src/configs/defaults.rs
>                                          mandate: HashMap::new(),
My bad, email is required for Paypal mandates for Adyen, not for googlepay.

2024-01-24 10:31 UTC, ArjunKarthik approved these changes

2024-01-29 06:59 UTC, Chethan-rao approved these changes

2024-01-31 09:45 UTC, merged