Updated NMI Payment Retrieval Logic
juspay/hyperswitch pull request #3211
Opened 2023-12-27 18:28 UTC by mohit07dec

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
This pull request addresses an issue in the NMI payment retrieval logic. Changed the implementation of the TryFrom trait to use the hyperswitch connector request reference id instead of the connector transaction id.  

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-29 11:42 UTC, prajjwalkumar17 commented
Hey @mohit07dec 👋, 
Can you change the tittle by following the conventions as mentioned in this [doc ](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md#commits) regarding the commits. PR title should follow the same conventions.

2024-01-04 07:59 UTC, srujanchikke requested changes
Hi @mohit07dec ,

The changes that you made in this PR are not concerned with issue attached. Could you please go through #2052. Please reach out to us if you have any queries!

2024-01-08 10:02 UTC, swangi-kumari commented
Hello @mohit07dec ,
Please resolve conflicts from your branch.

2024-03-13 09:04 UTC, swangi-kumari commented
Hey @mohit07dec ,
your pr contains 0 lines changes?
Can you please update this if you are still working on it.

2026-08-03 21:39 UTC, closed without merging