feat(connector): [Adyen] Add support for PIX Payment Method
juspay/hyperswitch pull request #3236
Opened 2024-01-04 06:13 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-01-07 06:57 UTC, ArjunKarthik requested changes

2024-01-07 06:57 UTC, ArjunKarthik commented on crates/api_models/src/payments.rs
> +    QrCodeUrl {
Please add comments stating that the enum order shouldn't be changed as this is being used during serialization and deserialization

2024-01-07 06:57 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +        .ok_or(errors::ConnectorError::ResponseHandlingFailed)?;
Why we are throwing error incase of None? This is an optional field from connector

2024-01-07 06:57 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +        payments::QrCodeInformation::QrCodeUrl {
Based on the data available, please construct QrCodeInformation::QrCodeUrl or QrCodeInformation::QrDataUrl or QrCodeInformation::QrCodeImageUrl.

2024-01-07 06:57 UTC, ArjunKarthik commented on crates/router/src/connector/adyen/transformers.rs
> +            display_to_timestamp: None,
Don't we get expiration time limit for the QR code from Aden?

2024-01-07 06:57 UTC, ArjunKarthik commented on crates/router/src/core/payments/transformers.rs
> +                                    match qr_info {
Move this to from implementation

2024-01-18 04:55 UTC, ArjunKarthik approved these changes

2024-01-23 11:17 UTC, ArjunKarthik commented on crates/api_models/src/payments.rs
> +        qr_code_url: Option<Url>,
@sai-harsha-vardhan Both are 2 different URL. One field holds the redirect link where another one holds the data url

2024-01-23 11:31 UTC, sai-harsha-vardhan submitted a review, later dismissed

2024-01-24 08:05 UTC, sai-harsha-vardhan approved these changes

2024-01-24 08:53 UTC, ArjunKarthik approved these changes

2024-01-25 07:29 UTC, merged