feat(connector): [Stripe] capture messages for failed payments and refunds
juspay/hyperswitch pull request #3237
Opened 2024-01-04 06:48 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Resolves [#3737](https://github.com/juspay/hyperswitch-cloud/issues/3737)

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-01-24 10:50 UTC, ArjunKarthik requested changes

2024-01-24 10:50 UTC, ArjunKarthik commented on crates/router/src/connector/stripe/transformers.rs
> +fn build_last_payment_error_response<T>(
Use try_from instead of method

2024-01-24 10:50 UTC, ArjunKarthik commented on crates/router/src/connector/stripe/transformers.rs
> +fn build_error_response<T>(
Use try_from instead of method

2024-01-24 10:50 UTC, ArjunKarthik commented on crates/router/src/connector/stripe/transformers.rs
> +        let status = enums::AttemptStatus::from(item.response.status);
The same logic has to be handled for PSync response also

2024-02-01 12:43 UTC, ArjunKarthik submitted a review, later dismissed

2024-02-01 14:14 UTC, srujanchikke submitted a review, later dismissed

2024-02-06 07:10 UTC, srujanchikke approved these changes

2024-02-06 11:03 UTC, merged