feat(hashicorp): implement hashicorp secrets manager solution
juspay/hyperswitch pull request #3297
Opened 2024-01-09 14:01 UTC by NishantJoshi00

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Implementing hashicorp secrets manager, to store secrets and sensitive data instead of providing it into environment variables

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
⚠️ Testing Pending

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-01-10 08:53 UTC, jagan-jaya approved these changes

2024-01-11 11:51 UTC, jagan-jaya requested changes

2024-01-11 11:51 UTC, jagan-jaya commented on crates/router/src/services/authentication.rs
> +        println!("{:?} {:?}", admin_api_key.peek(), request_admin_api_key);
remove this

2024-01-12 10:04 UTC, jagan-jaya submitted a review, later dismissed

2024-01-12 10:37 UTC, Chethan-rao approved these changes

2024-01-22 07:03 UTC, jagan-jaya approved these changes

2024-01-22 09:30 UTC, jagan-jaya submitted a review, later dismissed

2024-01-22 09:30 UTC, Chethan-rao approved these changes

2024-01-22 10:59 UTC, lsampras submitted a review, later dismissed
the cargo/makefile changes look good...

2024-01-22 11:03 UTC, jagan-jaya approved these changes

2024-01-22 11:07 UTC, lsampras approved these changes

2024-01-22 14:04 UTC, NishantJoshi00 commented on crates/drainer/src/connection.rs
>          .expect("Failed to decrypt password");
Hey! so yes. I have thought about this and the code is written in a way that, these features can co-exist together. Thanks for noticing...

So, let's consider the cases and understand the behaviour that is to be expected

| `kms`    | `hashicorp-vault` | behaviour                                                                                     |
| -------- | ----------------- | --------------------------------------------------------------------------------------------- |
| disabled | disabled          | plaintext value will be picked from env/config                                                |
| disabled | enabled           | env/config should contain the key for the value that is being stored in hashicorp-vault       |
| enabled  | disabled          | kms encrypted value to be provided in env/config                                              |
| enabled  | enabled           | env/config should contain key for the `kms` encrypted value that is stored in hashicorp-vault |

2024-01-22 14:20 UTC, SanchithHegde approved these changes

2024-01-24 08:51 UTC, merged