feat(connector): [BOA/Cyb] Include merchant metadata in capture and void requests
juspay/hyperswitch pull request #3308
Opened 2024-01-10 11:09 UTC by deepanshu-iiitu

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Include merchant metadata in capture and void requests for connectors BOA and Cybersource.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

https://github.com/juspay/hyperswitch/issues/3307

## How did you test it?

Testing can be done by creating 2 manual authorized payments for each BOA and Cybersource. While creating these payments you should pass metadata in the requests.
```
"metadata": {
    "count_tickets": 1,
    "transaction_number": "5590043"
 },
```
Then you should void one payment and capture the other. You should then be able to see this metadata in merchantDefinedInformation in BOA/Cybersource Dashboard.
![image](https://github.com/juspay/hyperswitch/assets/41580413/4ce708b8-8714-4dd3-8535-c480fdac3f30)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-01-10 11:19 UTC, Narayanbhat166 submitted a review, later dismissed

2024-01-10 13:01 UTC, ArjunKarthik approved these changes

2024-01-10 13:02 UTC, ArjunKarthik commented on crates/router/src/types.rs
> +    pub metadata: Option<pii::SecretSerdeValue>,
Same here

2024-01-10 13:03 UTC, ArjunKarthik requested changes
Some minor changes

2024-01-10 14:45 UTC, deepanshu-iiitu commented on crates/router/src/types.rs
> +    pub metadata: Option<pii::SecretSerdeValue>,
Done

2024-01-10 18:15 UTC, ArjunKarthik approved these changes

2024-01-11 08:25 UTC, Narayanbhat166 approved these changes

2024-01-11 08:41 UTC, merged