refactor(connector): [cybersource] recurring mandate flow
juspay/hyperswitch pull request #3354
Opened 2024-01-16 05:35 UTC by SamraatBansal

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [X] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

In recurring subsequent mandate payment (MIT) the payment was getting processed with card fetched from locker, now it is being processed with `connector_mandate_id`

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-01-16 11:19 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-01-16 13:34 UTC, ArjunKarthik requested changes

2024-01-16 13:34 UTC, ArjunKarthik commented on crates/router/src/services/api.rs
> +                (PreEscaped(format!("<form id=\"step-up-form\" method=\"POST\" action=\"{step_up_url}\">
will this impact normal 3ds flow?

2024-01-16 13:34 UTC, ArjunKarthik commented on crates/router/src/connector/cybersource/transformers.rs
> +                    let processing_information = ProcessingInformation::from((item, None));
I understand why we need this block, but lets have it inside try_from so that we can avoid code repetition

2024-01-17 09:15 UTC, deepanshu-iiitu approved these changes

2024-01-17 09:19 UTC, ArjunKarthik approved these changes

2024-01-17 10:14 UTC, merged