feat(router): select connector based on wallet issuer
juspay/hyperswitch pull request #336
Opened 2023-01-10 12:25 UTC by vspecky

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Automatically select a connector based on the wallet issuer for Paypal (Braintree or Adyen).

### Additional Changes
None
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

We may internally process payments for different wallets through different connectors hence we should also have the logic to choose the correct connector for this purpose.

## How did you test it?

Manual, compiler-guided

## Checklist

- [x] I formatted the code `cargo +nightly fmt`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-01-10 12:50 UTC, Narayanbhat166 commented on crates/router/src/core/payments/helpers.rs
> +        Ok(api::ConnectorCallType::Single(connector_data))
Can this block just return the connector as &str and then construction of connector be done outside of this block? Code seems to be repeated here

2023-01-10 12:58 UTC, Narayanbhat166 requested changes
Address the slight changes requested.

2023-01-10 14:35 UTC, SanchithHegde approved these changes

2023-01-11 07:29 UTC, jarnura approved these changes
LGTM :)

2023-01-11 16:24 UTC, SanchithHegde approved these changes

2023-03-31 12:30 UTC, vspecky commented
Requires further solutioning.

2023-03-31 12:30 UTC, closed without merging