feat(user): add support to delete user
juspay/hyperswitch pull request #3374
Opened 2024-01-17 13:43 UTC by apoorvdixit88

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Add support to delete the user

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-01-18 14:02 UTC, racnan requested changes

2024-01-18 14:02 UTC, racnan commented on crates/router/src/utils/user.rs
> +        | consts::user_role::INTERNAL_USER_MERCHANT_ID => {
??

2024-01-19 11:10 UTC, racnan commented
Description indicates you're deleting user from org but looks like you're deleting user from merchant account.

2024-01-19 11:35 UTC, racnan requested changes

2024-01-19 11:35 UTC, racnan commented on crates/router/src/core/user_role.rs
> +            utils::user::validate_deletion_permission_for_role_id(&user_role.role_id)?;
`user_role` util instead of `user` util

2024-01-19 11:35 UTC, racnan commented on crates/router/src/utils/user.rs
> +}
make this property of predefined permission.

2024-01-19 12:37 UTC, ivor-juspay submitted a review, later dismissed

2024-01-22 10:22 UTC, ThisIsMani approved these changes
LGTM

2024-01-23 08:12 UTC, ivor-juspay approved these changes

2024-01-25 07:22 UTC, merged