fix(connector): adyen cancel
juspay/hyperswitch pull request #339
Opened 2023-01-10 13:35 UTC by dracarys18

## Type of Change

- [x] Bugfix

## Description

Fixed adyen cancel.

## Motivation and Context

Adyen cancel was broken because of contract changes. Fixed it.

## How did you test it?

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/43412619/211565239-1bf558a0-5af7-4e23-bab8-3a9efd4e6900.png">

## Checklist

- [x] I formatted the code `cargo +nightly fmt`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-01-10 13:45 UTC, Narayanbhat166 commented on crates/router/src/connector/adyen/transformers.rs
>              _ => storage_enums::AttemptStatus::VoidFailed,
This can go into a from implementation.
response_status -> adyen_status -> attempt_status

2023-01-10 13:45 UTC, Narayanbhat166 requested changes
address the transformation changes

2023-01-10 14:02 UTC, Narayanbhat166 submitted a review, later dismissed
LGTM :)

2023-01-10 14:22 UTC, SanchithHegde reviewed
Other than that, looks good to me!

2023-01-10 14:36 UTC, SanchithHegde approved these changes

2023-01-10 20:07 UTC, dracarys18 commented on crates/router/src/connector/adyen/transformers.rs
> +}
Noted I believe that has changes only to payment. Adyen sends different status for cancel

2023-01-10 20:14 UTC, SanchithHegde commented on crates/router/src/connector/adyen/transformers.rs
> +}
I'm aware of the statuses being different for cancel, we even got it to compile on her system.
If your PR gets merged first (which is very likely), I'll suggest her to ignore changes to the cancel statuses.

2023-01-10 20:24 UTC, dracarys18 commented on crates/router/src/connector/adyen/transformers.rs
> +}
Cool

2023-01-11 07:32 UTC, jarnura approved these changes

2023-01-11 11:13 UTC, merged