fix: add keepalive while idle configurations for reqwest
juspay/hyperswitch pull request #3426
Opened 2024-01-23 09:45 UTC by inventvenkat

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
fix for intermittent connection closed error from hyper crate
`Error: IncompleteMessage: connection closed before message completed` - [Link](https://github.com/hyperium/hyper/issues/2136)

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context
Few external api calls fails due to this connection close

## How did you test it?
Running the test case collections

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-01-31 10:59 UTC, NishantJoshi00 requested changes
Other than that, looks good to me

2024-01-31 10:59 UTC, NishantJoshi00 commented on crates/router/src/services/api.rs
> +        }
```suggestion
        Err(error) if error.current_context() == &errors::ApiClientError::ConnectionClosed => {
                metrics::AUTO_RETRY_CONNECTION_CLOSED.add(&metrics::CONTEXT, 1, &[]);
                match cloned_send_request {
                    Some(cloned_request) => {
                        metrics_request::record_operation_time(
                            cloned_request,
                            &metrics::EXTERNAL_REQUEST_TIME,
                            &[metrics_tag],
                        )
                        .await
                    }
                    None => Err(error),
                }
        },
        err @ Err(_) => err
```

2024-02-05 06:21 UTC, jarnura requested changes

2024-02-05 06:26 UTC, inventvenkat commented on crates/router/src/services/api.rs
> +                        metrics_request::record_operation_time(
https://github.com/juspay/hyperswitch/pull/3426#issuecomment-1925604426

2024-02-05 07:26 UTC, NishantJoshi00 submitted a review, later dismissed

2024-02-05 09:30 UTC, jarnura approved these changes

2024-02-05 14:02 UTC, SanchithHegde commented on crates/router/src/services/api.rs
> +                None => Err(error),
Should we maybe log a message that the cloned request was `None`, or something along similar lines?

2024-02-05 14:04 UTC, jarnura approved these changes

2024-02-05 14:04 UTC, SanchithHegde approved these changes

2024-02-06 06:46 UTC, Narayanbhat166 commented
@inventvenkat instead of doing this, what if we do not have any `idle_pools`, AFAIK the error is caused mainly because of the idle pools. Would we have any significant performance hit without idle pools?

2024-02-06 09:29 UTC, merged

2024-02-06 10:35 UTC, inventvenkat commented
> @inventvenkat instead of doing this, what if we do not have any `idle_pools`, AFAIK the error is caused mainly because of the idle pools. Would we have any significant performance hit without idle pools?

[pool_idle_timeout](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.pool_idle_timeout) disabling timeout didn't help this case.