refactor(webhooks): check `is_merchant_notified` field before sending webhook to merchant
juspay/hyperswitch pull request #3455
Opened 2024-01-25 08:46 UTC by Narayanbhat166

## Type of Change

- [x] Refactoring

## Description

```mermaid
flowchart TD
    event_id --> CheckEventExists{check event exists}

    CheckEventExists --> |yes| CheckMerchantNotified{is_merchant_notified}
    CheckMerchantNotified --> |true| DoNotSendWebhook
    CheckMerchantNotified --> |false| SendWebhook

    CheckEventExists --> |no| SendWebhook
```
This change will check for the `is_merchant_notified` field and send the webhook only if it is false.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

closes #3408 

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

2024-01-29 12:00 UTC, vspecky requested changes

2024-02-05 10:04 UTC, sai-harsha-vardhan approved these changes

2024-02-05 10:33 UTC, vspecky approved these changes

2024-02-12 12:33 UTC, Narayanbhat166 commented
Closing this PR since automatic webhook retries will handle this.

2024-02-12 12:33 UTC, closed without merging