refactor(user_role): Change update user role request to take `email` instead of `user_id`
juspay/hyperswitch pull request #3530
Opened 2024-02-01 14:05 UTC by ThisIsMani

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR changes update user role api and the list users api. And fixes a bug in list roles api.
	
### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

To allow roles to be updated.

## How did you test it?

1. Update user role api
	```
	curl --location 'http://localhost:8080/user/user/update_role' \
	--header 'Content-Type: application/json' \
	--header 'Authorization: Bearer JWT' \
	--data '{
	    "email": "user_email",
	    "role_id": "merchant_admin"
	}'
	```
	If api is success, it will respond with 200 OK.

2. List users api
	```
	curl --location 'http://localhost:8080/user/user/list' \
	--header 'Authorization: Bearer JWT'
	```
	If api is success, response will be like this. Previously this response used to have `user_id` field, now it is removed.
	```
	[
	    {
	        "email": "email",
	        "name": "name",
	        "role_id": "merchant_iam_admin",
	        "role_name": "IAM",
	        "status": "InvitationSent",
	        "last_modified_at": "2024-01-22T11:16:42.283Z"
	    },
	    {
	        "email": "email",
	        "name": "name",
	        "role_id": "org_admin",
	        "role_name": "Organization Admin",
	        "status": "Active",
	        "last_modified_at": "2024-01-22T11:15:26.260Z"
	    },
	]
	```

3. List roles api
	```
	curl --location 'http://localhost:8080/user/role/list' \
	--header 'Authorization: Bearer JWT'
	```
	This api will no longer return org_admin role in the response and the response will be identical to this.
	```
	[
	    {
	        "role_id": "merchant_admin",
	        "permissions": [
	            "PaymentRead",
	            "PaymentWrite",
	            "RefundRead",
	            "RefundWrite",
	            "ApiKeyRead",
	            "ApiKeyWrite",
	            "MerchantAccountRead",
	            "MerchantAccountWrite",
	            "MerchantConnectorAccountRead",
	            "ForexRead",
	            "MerchantConnectorAccountWrite",
	            "RoutingRead",
	            "RoutingWrite",
	            "ThreeDsDecisionManagerWrite",
	            "ThreeDsDecisionManagerRead",
	            "SurchargeDecisionManagerWrite",
	            "SurchargeDecisionManagerRead",
	            "DisputeRead",
	            "DisputeWrite",
	            "MandateRead",
	            "MandateWrite",
	            "CustomerRead",
	            "CustomerWrite",
	            "FileRead",
	            "FileWrite",
	            "Analytics",
	            "UsersRead",
	            "UsersWrite"
	        ],
	        "role_name": "Admin"
	    },
	    {
	        "role_id": "merchant_operator",
	        "permissions": [
	            "PaymentRead",
	            "PaymentWrite",
	            "RefundRead",
	            "RefundWrite",
	            "ApiKeyRead",
	            "MerchantAccountRead",
	            "ForexRead",
	            "MerchantConnectorAccountRead",
	            "MerchantConnectorAccountWrite",
	            "RoutingRead",
	            "RoutingWrite",
	            "ThreeDsDecisionManagerRead",
	            "ThreeDsDecisionManagerWrite",
	            "SurchargeDecisionManagerRead",
	            "SurchargeDecisionManagerWrite",
	            "DisputeRead",
	            "MandateRead",
	            "CustomerRead",
	            "FileRead",
	            "Analytics",
	            "UsersRead"
	        ],
	        "role_name": "Operator"
	    },
	    {
	        "role_id": "merchant_customer_support",
	        "permissions": [
	            "PaymentRead",
	            "RefundRead",
	            "RefundWrite",
	            "ForexRead",
	            "DisputeRead",
	            "DisputeWrite",
	            "MerchantAccountRead",
	            "MerchantConnectorAccountRead",
	            "MandateRead",
	            "CustomerRead",
	            "FileRead",
	            "FileWrite",
	            "Analytics"
	        ],
	        "role_name": "Customer Support"
	    },
	    {
	        "role_id": "merchant_developer",
	        "permissions": [
	            "PaymentRead",
	            "RefundRead",
	            "ApiKeyRead",
	            "ApiKeyWrite",
	            "MerchantAccountRead",
	            "ForexRead",
	            "MerchantConnectorAccountRead",
	            "RoutingRead",
	            "ThreeDsDecisionManagerRead",
	            "SurchargeDecisionManagerRead",
	            "DisputeRead",
	            "MandateRead",
	            "CustomerRead",
	            "FileRead",
	            "Analytics",
	            "UsersRead"
	        ],
	        "role_name": "Developer"
	    },
	    {
	        "role_id": "merchant_iam_admin",
	        "permissions": [
	            "PaymentRead",
	            "RefundRead",
	            "ApiKeyRead",
	            "MerchantAccountRead",
	            "ForexRead",
	            "MerchantConnectorAccountRead",
	            "RoutingRead",
	            "ThreeDsDecisionManagerRead",
	            "SurchargeDecisionManagerRead",
	            "DisputeRead",
	            "MandateRead",
	            "CustomerRead",
	            "FileRead",
	            "Analytics",
	            "UsersRead",
	            "UsersWrite"
	        ],
	        "role_name": "IAM"
	    },
	    {
	        "role_id": "merchant_view_only",
	        "permissions": [
	            "PaymentRead",
	            "RefundRead",
	            "ApiKeyRead",
	            "MerchantAccountRead",
	            "ForexRead",
	            "MerchantConnectorAccountRead",
	            "RoutingRead",
	            "ThreeDsDecisionManagerRead",
	            "SurchargeDecisionManagerRead",
	            "DisputeRead",
	            "MandateRead",
	            "CustomerRead",
	            "FileRead",
	            "Analytics",
	            "UsersRead"
	        ],
	        "role_name": "View Only"
	    }
	]
	```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-02-01 14:17 UTC, apoorvdixit88 submitted a review, later dismissed

2024-02-07 12:41 UTC, apoorvdixit88 approved these changes

2024-02-07 13:23 UTC, racnan requested changes

2024-02-07 13:23 UTC, racnan commented on crates/router/src/core/user_role.rs
> +            })
filter can be simpler, no need to use `is_role_invitable`

2024-02-07 13:33 UTC, racnan requested changes

2024-02-07 13:33 UTC, racnan commented on crates/router/src/core/user_role.rs
> +    if !predefined_permissions::is_role_updatable(&user_from_token.role_id)? {
wrong parameters

2024-02-08 07:39 UTC, apoorvdixit88 approved these changes

2024-02-08 08:13 UTC, apoorvdixit88 approved these changes

2024-02-08 09:03 UTC, merged