feat(core): routes to toggle blocklist
juspay/hyperswitch pull request #3568
Opened 2024-02-06 14:08 UTC by prajjwalkumar17

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-02-06 14:18 UTC, prajjwalkumar17 commented on crates/router/src/routes/blocklist.rs
> +)]
need to refactor this accordingly.

2024-02-07 07:29 UTC, Narayanbhat166 commented on crates/router/src/core/blocklist/utils.rs
> +            return Err(errors::ApiErrorResponse::InternalServerError.into());
```suggestion
            Err(e).change_context(errors::ApiErrorResponse::InternalServerError)
```

2024-02-07 07:59 UTC, Narayanbhat166 commented on crates/router/src/routes/app.rs
> +                web::resource("/enable").route(web::post().to(blocklist::toggle_blocklist_guard)),
shouldn't this be toggle?

2024-02-07 09:49 UTC, vspecky requested changes

2024-02-07 09:49 UTC, vspecky commented on crates/router/src/core/blocklist/utils.rs
> +    })
```suggestion
    Ok(api_blocklist::ToggleBlocklistResponse {
        blocklist_guard_status: guard_status,
    })
```
No need to send back a message. If the merchant wants to make a decision based on the response, it's easier to match on the standalone status as opposed to a message.

2024-02-07 11:47 UTC, vspecky approved these changes

2024-02-07 11:50 UTC, Narayanbhat166 approved these changes

2024-02-07 12:08 UTC, merged