feat(user): implement force password reset
juspay/hyperswitch pull request #3572
Opened 2024-02-07 08:25 UTC by apoorvdixit88

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
For newly invited users, add support to have check for whether password has been changed once or not.
- Use enum `IsChangePasswordRequired` to have this check.
### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
For users with email feature flag disabled, there is no support to know whether the newly invited user has change password or not.

## How did you test it?
For Test 
Invite user
```
curl --location 'http://localhost:8080/user/user/invite' \
--header 'Authorization: Bearer JWT' \
--header 'Content-Type: application/json' \
--data-raw '{
  "email": "test_force@gmail.com",
    "name": "test3",
    "role_id": "merchant_admin"
}
'
```
Invited user signin
```
curl --location 'http://localhost:8080/user/signin' \
--header 'Content-Type: application/json' \
--header 'Cookie: token=JWT' \
--data-raw '{
    
    
    "email": "test_force@gmail.com",
    "password": "926fc057-df2e-42af-aada-5e403487f3aa"

}'
```
Check value of Enum `IsChangePasswordRequired`
```
curl --location --request GET 'http://localhost:8080/user/data?keys=IsChangePasswordRequired' \
--header 'Authorization: Bearer JWT' \
--header 'Content-Type: application/json' \
--data '
'
```
Response:
```
[
    {
        "IsChangePasswordRequired": true
    }
]
```
Change Password:
```
curl --location 'http://localhost:8080/user/change_password' \
--header 'Content-Type: application/json' \
--header 'Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMWZjNzgyOTUtM2JiMy00OGJjLThlZDgtNzFjMzVjMzMxYWU2IiwibWVyY2hhbnRfaWQiOiJtZXJjaGFudF8xNjk3NzE2ODcwIiwicm9sZV9pZCI6Im1lcmNoYW50X2FkbWluIiwiZXhwIjoxNjk3ODg5NjcxLCJvcmdfaWQiOiJvcmdfejQ5ZExMeTdmbllUODN5TDY3clEifQ.CJzEQ2qbhn-qUiiVBSdvCJiLvWp-5wCF9R54gth6QbQ' \
--header 'Authorization: Bearer JWT' \
--data '{
    "old_password": "926fc057-df2e-42af-aada-5e403487f3aa",
    "new_password": "test"
}
'
```
Again checking the value of enum after login:
```
curl --location --request GET 'http://localhost:8080/user/data?keys=IsChangePasswordRequired' \
--header 'Authorization: Bearer JWT' \
--header 'Content-Type: application/json' \
--data '
'
```
Response should be:
```
[
    {
        "IsChangePasswordRequired": false
    }
]
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-02-07 11:02 UTC, ThisIsMani commented on crates/diesel_models/src/query/dashboard_metadata.rs
> +        generics::generic_delete::<<Self as HasTable>::Table, _>(
`generic_delete_one_with_result` can be used instead of this.

2024-02-08 09:16 UTC, ThisIsMani approved these changes
Minor concerns

2024-02-08 09:16 UTC, ThisIsMani commented on crates/router/src/core/user.rs
> +                last_modified_by: user_from_token.user_id.clone(),
Don't have to clone this probably.

2024-02-08 12:43 UTC, ThisIsMani approved these changes

2024-02-08 13:02 UTC, racnan requested changes

2024-02-09 10:06 UTC, ThisIsMani approved these changes

2024-02-09 10:06 UTC, racnan approved these changes

2024-02-09 10:33 UTC, merged

2024-02-15 09:28 UTC, Narayanbhat166 commented on crates/diesel_models/src/enums.rs
> +    IsChangePasswordRequired,
This needs a migration change right @apoorvdixit88?