feat(router): add generic merchant static routing config
juspay/hyperswitch pull request #362
Opened 2023-01-12 13:05 UTC by vspecky

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

This PR removes the legacy `CustomRoutingRules` type for describing static routing and makes the static routing configuration in the merchant account generic.
It also adds a simple `Single` static routing algorithm which will allow the merchant to route all payments to a single connector and its implementation in payments core.

### Additional Changes

- [x] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

- [DB up.sql](https://github.com/juspay/hyperswitch/blob/636c758f67dd14ea8735bf05f1635002cb424a36/migrations/2023-01-12-084710_update_merchant_routing_algorithm/up.sql)
- [DB down.sql](https://github.com/juspay/hyperswitch/blob/636c758f67dd14ea8735bf05f1635002cb424a36/migrations/2023-01-12-084710_update_merchant_routing_algorithm/down.sql)

## Motivation and Context

This serves as scaffolding to integrate other forms of static routing into hyperswitch.

## How did you test it?

Compiler-guided, stripe payments.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-01-12 13:13 UTC, vspecky commented
We need to have a discussion on the implementation for the intersection of the following aspects of payments core and make necessary changes before merging the PR :-
- Static Routing
- Registering tasks in process-tracker
- Automatic retries

2023-01-16 17:06 UTC, SanchithHegde reviewed
Other than that, looks good to me!

2023-01-16 17:10 UTC, vspecky commented on crates/api_models/src/admin.rs
> +    pub routing_algorithm: Option<serde_json::Value>,
Yes, better if we refer to it as "routing algorithm config" in the doc.

2023-01-16 17:11 UTC, vspecky commented on crates/api_models/src/enums.rs
> +}
Connectors like `Applepay` are not connectors in the sense that merchants can call them to make payments. These are used internally. That's the purpose of this enum, it only enumerates merchant-callable connectors.

2023-01-16 17:12 UTC, vspecky commented on crates/router/src/core/payments/helpers.rs
> +    _merchant_account: &storage::MerchantAccount,
Might need in the future but no need to keep it now. Will remove.

2023-01-16 17:18 UTC, vspecky commented on crates/api_models/src/enums.rs
> +}
I believe those are merchant-callable. Will update.

2023-01-16 17:32 UTC, vspecky commented on crates/api_models/src/enums.rs
> +}
I guess the name could also be better. `SupportedConnectors` doesn't really drive home the purpose. Maybe something like `MerchantCallableConnectors`. Too long tho, I guess `RoutableConnectors` fits.

2023-01-16 17:49 UTC, SanchithHegde commented on crates/api_models/src/admin.rs
> +    pub routing_algorithm: Option<serde_json::Value>,
> ```rust
> /// The custom routing rules to be used for various payment methods and conditions
> pub routing_algorithm: Option<serde_json::Value>,
> ```

Should the doc comment say "custom routing rules", or would you prefer to update it?

2023-01-16 17:53 UTC, SanchithHegde submitted a review, later dismissed
Looks good to me!

2023-01-16 20:38 UTC, jarnura requested changes

2023-01-16 20:38 UTC, jarnura commented on crates/router/src/core/payments.rs
>      if let api::ConnectorCallType::Single(ref connector) = connector_details {
move this logic to a separate function.

2023-01-17 06:14 UTC, vspecky commented on crates/router/src/core/payments.rs
>      if let api::ConnectorCallType::Single(ref connector) = connector_details {
Done 👍

2023-01-17 06:27 UTC, SanchithHegde approved these changes

2023-01-17 07:00 UTC, jarnura approved these changes

2023-01-17 07:34 UTC, merged