refactor: incorporate `hyperswitch_interface` into drainer
juspay/hyperswitch pull request #3629
Opened 2024-02-12 10:38 UTC by Chethan-rao

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Added `AppState` in drainer which now contains `encryption_client` for runtime encryption and decryption of values. This PR also incorporates the newly added `hyperswitch_interface` crate for decrypting the secrets during application startup.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-02-13 17:00 UTC, jarnura requested changes

2024-02-13 17:10 UTC, Chethan-rao commented on crates/drainer/src/secrets_decryption.rs
> +pub async fn kms_decryption(
`secrets_decryption` is the appropriate name? or `fetch_raw_secrets`

2024-02-14 07:39 UTC, jarnura approved these changes

2024-02-14 08:00 UTC, SanchithHegde approved these changes

2024-02-14 08:36 UTC, dracarys18 commented on crates/drainer/src/main.rs
>      let store = std::sync::Arc::new(store);
Why is this redefined?

2024-02-14 08:38 UTC, dracarys18 commented on crates/drainer/src/main.rs
>      let store = std::sync::Arc::new(store);
Can just do Arc::new in the previous line, not necessary,

2024-02-14 08:38 UTC, dracarys18 approved these changes

2024-02-14 09:55 UTC, merged