feat(authz): Add custom roles checks in authorization
juspay/hyperswitch pull request #3719
Opened 2024-02-20 08:57 UTC by ThisIsMani

…ed_modules## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR will add checks in authorization to check for custom roles.
This PR also add custom roles functionality to apis which were dealing with roles.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

To support custom roles.

## How did you test it?

Postman.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-02-20 11:06 UTC, racnan requested changes

2024-02-20 11:06 UTC, racnan commented on crates/router/src/services/authorization/permissions.rs
> +#[derive(PartialEq, Display, Clone, Debug, Copy, Eq, Hash)]
why is `hash` required ?

2024-02-20 11:06 UTC, racnan commented on crates/router/src/services/authorization/roles.rs
> +#[allow(dead_code)]
why is this required ?

2024-02-20 11:06 UTC, racnan commented on crates/router/src/services/authorization/roles.rs
> +}
re-evaluate use of the function as it allows you to get any custom role irrespective of the merchant id.

2024-02-20 13:22 UTC, ThisIsMani commented on crates/router/src/routes/files.rs
> +            &auth::DashboardNoPermissionAuth,
Product confirmed that these apis should have JWT.

2024-02-21 12:43 UTC, racnan commented
add test cases.

2024-02-21 13:10 UTC, ShivanshMathurJuspay approved these changes

2024-02-21 13:59 UTC, merged