chore: Custom serializer for payment method list
juspay/hyperswitch pull request #373
Opened 2023-01-13 11:35 UTC by dracarys18

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Wrote a custom serializer to only serialize the field we want for list payment methods.

## Motivation and Context

Only serialize the fields we need and ignore the rest.

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-01-13 13:33 UTC, Narayanbhat166 approved these changes

2023-01-14 14:44 UTC, jarnura requested changes
Other than add comments, looks good to me :)

2023-01-14 14:44 UTC, jarnura commented on crates/api_models/src/payment_methods.rs
> +impl serde::Serialize for ListPaymentMethodResponse {
Add comments explain why this needed and how we are doing it.

2023-01-14 17:32 UTC, SanchithHegde approved these changes

2023-01-15 10:15 UTC, jarnura approved these changes

2023-01-15 10:49 UTC, merged