feat: add docs for PaymentsRequest & PaymentsResponse
juspay/hyperswitch pull request #385
Opened 2023-01-16 11:32 UTC by NishantJoshi00

## Type of Change

- [x] Enhancement

## Description

API spec for Payments Create API 

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
N/A

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-01-16 12:33 UTC, SanchithHegde requested changes
Let's move the documentation for enums to the enum doc comments itself. Other than that, looks good to me!

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub capture_method: Option<api_enums::CaptureMethod>,
Document the enum variants as doc comments for the enum instead of adding here.

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub off_session: Option<bool>,
```suggestion
    /// Set to true to indicate that the customer is not in your checkout flow during this payment, and therefore is unable to authenticate. This parameter is intended for scenarios where you collect card details and charge them later. This parameter can only be used with `confirm: true`.
    #[schema(example = true)]
    pub off_session: Option<bool>,
```

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub authentication_type: Option<api_enums::AuthenticationType>,
Same here, add documentation comment for the enum instead of adding it here.

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub billing: Option<Address>,
You can remove the `#[schema()]` lines

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub statement_descriptor_name: Option<String>,
22 or 255 characters?

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = Option<i64>, example = 6540)]
```suggestion
    #[schema(value_type = Option<u64>, example = 6540)]
```

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = Currency, example = "USD")]
```suggestion
    #[schema(value_type = Option<Currency>, example = "USD")]
```

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = CaptureMethod, example = "PaymentProcessor")]
```suggestion
    #[schema(value_type = Option<CaptureMethod>, example = "PaymentProcessor")]
```

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = Option<String>, max_length = 255, example = "+1")]
```suggestion
    #[schema(max_length = 255, example = "+1")]
```

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = FutureUsage, example = "off_session")]
```suggestion
    #[schema(value_type = Option<FutureUsage>, example = "off_session")]
```

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = AuthenticationType, example = "no_three_ds", default = "three_ds")]
```suggestion
    #[schema(value_type = Option<AuthenticationType>, example = "no_three_ds", default = "three_ds")]
```

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = PaymentMethodType, example = "bank_transfer")]
```suggestion
    #[schema(value_type = Option<PaymentMethodType>, example = "bank_transfer")]
```

2023-01-16 12:33 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub cancellation_reason: Option<String>,
Remove the empty `#[schema()]` lines.

2023-01-16 13:09 UTC, SanchithHegde submitted a review, later dismissed
Looks good to me!

2023-01-17 06:40 UTC, bernard-eugine approved these changes

2023-01-17 07:01 UTC, SanchithHegde approved these changes

2023-01-17 07:23 UTC, jarnura approved these changes

2023-01-17 07:23 UTC, merged