refactor(connector): [Prophetpay][Rapyd][Shift4][Square] Mask PII data
juspay/hyperswitch pull request #3930
Opened 2024-03-04 07:08 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Mask pii information passed and received in the connector request and response for Prophetpay, rapyd, shift4 and square.

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-03-11 07:37 UTC, Sakilmostak approved these changes

2024-03-12 10:27 UTC, deepanshu-iiitu commented
Make `recepient_email` a secret in `crates/router/src/connector/rapyd/transformers.rs`
#[derive(Debug, Serialize, Clone)]
pub struct CaptureRequest {
    amount: Option<i64>,
    receipt_email: Option<String>,
    statement_descriptor: Option<String>,
}

2024-03-12 10:35 UTC, deepanshu-iiitu requested changes

2024-03-12 10:35 UTC, deepanshu-iiitu commented on crates/router/src/connector/rapyd/transformers.rs
> +    token: Option<Secret<String>>,
Please make `receipt_email` as secret in struct `CaptureRequest`

2024-03-12 11:36 UTC, deepanshu-iiitu approved these changes

2024-03-12 13:55 UTC, Sakilmostak approved these changes

2024-03-18 06:53 UTC, merged