Refactor(core): status handling for payment_method_status
juspay/hyperswitch pull request #3965
Opened 2024-03-05 13:59 UTC by prajjwalkumar17

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-03-06 10:17 UTC, vspecky requested changes

2024-03-06 10:17 UTC, vspecky commented on crates/router/src/core/payments/flows/psync_flow.rs
> +                }
We also need to update the status in the payment method entry in DB.

2024-03-08 11:38 UTC, vspecky approved these changes

2024-03-11 07:15 UTC, srujanchikke submitted a review, later dismissed
No connector files were changed in this PR.

2024-03-11 13:32 UTC, vspecky approved these changes

2024-03-11 13:37 UTC, apoorvdixit88 approved these changes
No dashboard specific changes!

2024-03-11 14:19 UTC, srujanchikke approved these changes

2024-03-11 14:35 UTC, merged