docs:  request and response for payments route
juspay/hyperswitch pull request #400
Opened 2023-01-17 18:31 UTC by Sangamesh26

## Type of Change

- [x] Enhancement

## Description

Docs for request and response in the payments routes.

## Motivation and Context

Added docs for the request and responses in payments routes

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-01-17 19:26 UTC, SanchithHegde requested changes
1. Please check the diff for the `openapi/generated.json` file and verify that the required fields are correct as per what we've defined on the request structs.

2. Since this is going to be user/merchant facing public documentation, should we use the complete (and properly capitalized) names of the wallets:
   - `Google Pay` instead of `Gpay`/`gpay`
   - `Apple Pay` instead of `ApplePay`/`Applepay`/`applepay`
   - `PayPal` instead of `Paypal`/`paypal`

I'd like more opinions on 2, preferably from @jarnura, @ashokkjag, @bernard-eugine, @manojradhakrishnan.

2023-01-17 19:26 UTC, SanchithHegde commented on crates/api_models/src/enums.rs
>      Gpay,
Most of these wallet names are self-explanatory. Add a doc comment along the lines of "Wallets which support obtaining session object" to the enum instead.

```rust
/// Wallets which support obtaining session object
pub enum SupportedWallets {
    Paypal,
    ApplePay,
    Klarna,
    Gpay,
}
```

2023-01-17 19:26 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub data: Vec<PaymentsResponse>,
```suggestion
    /// The number of payments included in the list
    pub size: usize,
    /// The list of payments response objects
    pub data: Vec<PaymentsResponse>,
```

You had added regular comments. I'm assuming you meant to add doc comments instead.

2023-01-17 19:26 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub client_secret: String,
```suggestion
    /// This is a token which expires after 15 minutes, used from the client to authenticate and create sessions from the SDK
    pub client_secret: String,
```

2023-01-17 19:26 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub total_price_status: String,
You've used `ex` in some places to denote examples and `Ex` elsewhere. Please try to keep it uniform.

2023-01-17 19:26 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +        /// The number of retries to get the session repsonse
```suggestion
        /// The number of retries to get the session response
```

2023-01-17 19:26 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub client_secret: Secret<String, pii::ClientSecret>,
1. Please update the doc comment here as well.
2. ```suggestion
       #[schema(value_type = String)]
       pub client_secret: Secret<String, pii::ClientSecret>,
   ```

2023-01-17 19:26 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub txn_id: String,
Can you rename this field as `attempt_id` instead?

2023-01-17 19:26 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      pub wallets: Vec<api_enums::SupportedWallets>,
```suggestion
    #[schema(value_type = Vec<SupportedWallets>)]
    pub wallets: Vec<api_enums::SupportedWallets>,
```

2023-01-18 10:27 UTC, jarnura approved these changes
LGTM :)

2023-01-18 10:37 UTC, SanchithHegde commented on openapi/generated.json
> +              "$ref": "#/components/schemas/SessionToken"
There seems to be no schema for this, please fix it.

2023-01-19 10:52 UTC, jarnura approved these changes

2023-01-19 17:26 UTC, SanchithHegde approved these changes

2023-01-19 20:13 UTC, merged