feat(router): Use `NTID` in `MIT` payments if the `pg_agnostic_mit` config is enabled
juspay/hyperswitch pull request #4113
Opened 2024-03-18 03:41 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

During the MIT process, there needs to be validation to check the off_session field. If set to true, then check if the pg_agnostic_mit config is enabled. If it is, perform a lookup in the payment methods table with the payment_method_id in the MIT payment request for the NRID.

If the confirm call fails, retry across the retry-able connectors specified in the `pg_agnostic_mit` configuration.

If the NRID is not present for that particular payment_method_id, or if the `pg_agnostic_mit` flag is not enabled, call the initial connector with which the CIT was performed.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-04-01 12:56 UTC, Aprabhat19 commented on crates/router/src/connector/stripe/transformers.rs
> +                                connector: "Adyen",
```suggestion
                                connector: "Stripe",
```

2024-04-02 06:45 UTC, Aprabhat19 commented on crates/router/src/core/payments.rs
> +                .attach_printable("The conditional config was not found in the DB")?;
Throw a relevant error message

2024-04-02 07:43 UTC, Aprabhat19 requested changes

2024-04-02 07:43 UTC, Aprabhat19 commented on crates/router/src/core/payments.rs
> +) -> RouterResult<bool> {
Can we just return bool here. Also this  fn need not be async.

2024-04-02 07:43 UTC, Aprabhat19 commented on crates/router/src/core/payments.rs
> +    }
```suggestion
   return pg_agnostic == "true"
        && payment_method_info.payment_method == storage_enums::PaymentMethod::Card
        && ntid_supported_connectors.contains(&connector)
        && payment_method_info.network_transaction_id.is_some()
   
```

2024-04-02 12:22 UTC, Aprabhat19 approved these changes

2024-04-02 13:04 UTC, Aprabhat19 approved these changes

2024-04-03 14:12 UTC, jagan-jaya commented on crates/router/src/core/payments/helpers.rs
> +    if pg_agnostic_config == "true" {
can this be boolean?

2024-04-03 14:34 UTC, ShankarSinghC commented on crates/router/src/connector/stripe/transformers.rs
> +    #[serde(rename = "payment_method_options[card][mandate_options]")]
No, this is not being used in the existing flows.

2024-04-03 14:35 UTC, ShankarSinghC commented on crates/router/src/core/payments/helpers.rs
> +    if pg_agnostic_config == "true" {
Can be taken in the next pr.

2024-04-03 14:37 UTC, jagan-jaya approved these changes

2024-04-04 12:30 UTC, jagan-jaya approved these changes

2024-04-04 12:33 UTC, Narayanbhat166 approved these changes

2024-04-04 12:45 UTC, Aprabhat19 approved these changes

2024-04-04 13:03 UTC, merged