feat(connector): [Ebanx] Template for ebanx payout
juspay/hyperswitch pull request #4141
Opened 2024-03-20 07:08 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Template connector code for Ebanx payout connector

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

No testing required since this is a template

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-03-27 11:55 UTC, srujanchikke requested changes
Please add base url's in sandbox and production toml files.

2024-03-27 11:55 UTC, srujanchikke commented on crates/common_enums/src/enums.rs
> +    Ebanx,
Shouldn't this supposed to be commented out ?

2024-04-02 12:56 UTC, srujanchikke approved these changes

2024-04-02 14:36 UTC, SamraatBansal approved these changes

2024-04-03 08:33 UTC, ArjunKarthik approved these changes

2024-04-08 07:00 UTC, SamraatBansal approved these changes

2024-04-08 07:02 UTC, ArjunKarthik approved these changes

2024-04-08 07:17 UTC, merged

2024-04-10 06:02 UTC, pixincreate commented on crates/router/tests/connectors/ebanx.rs
> +// Cards Negative scenerios
Spell check failure.