feat(core): update connector_mandate_details in payment_method
juspay/hyperswitch pull request #4155
Opened 2024-03-20 11:31 UTC by Aprabhat19

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
update connector_mandate_details in payment_method

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-03-26 12:30 UTC, jagan-jaya requested changes

2024-03-26 12:30 UTC, jagan-jaya commented on crates/router/build.rs
> +    println!("cargo:rustc-env=RUST_MIN_STACK= 6291456"); // 6 * 1024 * 1024 = 6 MiB
`space` needed here?

2024-03-26 12:30 UTC, jagan-jaya commented on crates/router/src/core/payments/tokenization.rs
> +            println!("ENTER");
remove this println

2024-03-26 12:30 UTC, jagan-jaya commented on crates/router/src/core/payments/tokenization.rs
> +                println!("ENTER HERE");
remove

2024-03-27 10:43 UTC, vspecky requested changes
Please address mine and @jagan-jaya 's comments. Also please test this and add tests to the PR description.

2024-03-27 10:43 UTC, vspecky commented on crates/router/build.rs
> +    println!("cargo:rustc-env=RUST_MIN_STACK= 6291456"); // 6 * 1024 * 1024 = 6 MiB
Revert this change.

2024-04-01 07:30 UTC, jagan-jaya approved these changes

2024-04-01 10:23 UTC, Chethan-rao approved these changes

2024-04-03 11:22 UTC, merged