feat(router): add NTID flow for cybersource
juspay/hyperswitch pull request #4193
Opened 2024-03-26 07:11 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add `NTID` (network transaction id) flow cybersource.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Created a mandate or CIT in cybersource
<img width="1107" alt="image" src="https://github.com/juspay/hyperswitch/assets/83439957/3649e1f4-0e19-4c89-b978-e11120a96b92">
DB screenshot where `network_transaction_id` is stored in the `payment_methods` table
![image](https://github.com/juspay/hyperswitch/assets/83439957/f0dee8b8-193f-4013-9ebf-c749dc24643a)
Create a payment with confirm false
<img width="972" alt="image" src="https://github.com/juspay/hyperswitch/assets/83439957/fce68823-ce21-4353-9908-c19ca4f1f468">
List payment methods for customer
<img width="956" alt="image" src="https://github.com/juspay/hyperswitch/assets/83439957/c0ea7f9e-3468-41ea-8c13-ee4cba57a293">
Confirm the payment by passing the connector as stripe in routing
<img width="1021" alt="image" src="https://github.com/juspay/hyperswitch/assets/83439957/d8e496ba-90e7-431e-8877-a0aef6c6da28">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-04-03 11:15 UTC, SamraatBansal requested changes

2024-04-03 11:15 UTC, SamraatBansal commented on crates/router/src/connector/cybersource/transformers.rs
> +                    let amount = match (original_amount, original_currency) {
```suggestion
                    let original_authorized_amount = match (original_amount, original_currency) {
```

2024-04-03 11:15 UTC, SamraatBansal commented on crates/router/src/connector/cybersource/transformers.rs
> +                    commerce_indicator = "recurring".to_string();
Create an enum for commerce_indicator

2024-04-03 12:08 UTC, ShankarSinghC commented on crates/router/src/connector/cybersource/transformers.rs
> +                    commerce_indicator = "recurring".to_string();
Can be take in the next pr.

2024-04-03 12:49 UTC, SamraatBansal approved these changes

2024-04-03 13:49 UTC, Aprabhat19 submitted a review, later dismissed

2024-04-04 13:37 UTC, Aprabhat19 approved these changes

2024-04-04 14:33 UTC, merged