feat(mandate_kv) add kv support for mandate
juspay/hyperswitch pull request #4275
Opened 2024-04-02 13:48 UTC by akshay-97

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

add kv support for mandate

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-04-05 08:10 UTC, dracarys18 requested changes

2024-04-05 08:10 UTC, dracarys18 commented on crates/diesel_models/src/mandate.rs
> +}
You can use impl From<> here

2024-04-05 08:10 UTC, dracarys18 commented on crates/diesel_models/src/query/mandate.rs
> +    }
Seems redundant you can change the above function to accomodate this

2024-04-10 17:01 UTC, jarnura submitted a review, later dismissed

2024-04-10 21:36 UTC, dracarys18 submitted a review, later dismissed

2024-04-12 09:00 UTC, jarnura approved these changes

2024-04-12 10:31 UTC, dracarys18 approved these changes

2024-04-16 10:19 UTC, merged