feat(connector): [ZSL] add connector template code
juspay/hyperswitch pull request #4285
Opened 2024-04-03 09:16 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Zsl only supports automatic payment create and payment status gets updated through webhooks

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-04-08 07:30 UTC, SamraatBansal requested changes

2024-04-08 07:30 UTC, SamraatBansal commented on config/config.example.toml
> +zsl.base_url = "https://api.sitoffalb.net/ecp"
```suggestion
zsl.base_url = "https://api.sitoffalb.net/"
```

2024-04-08 07:30 UTC, SamraatBansal commented on config/config.example.toml
> +zsl.base_url = "https://api.sitoffalb.net/ecp"
And subsequently update at all the places.

2024-04-08 07:30 UTC, SamraatBansal commented on crates/common_enums/src/enums.rs
> +    Zsl,
Place it in alphabetical order

2024-04-08 07:30 UTC, SamraatBansal commented on crates/router/src/configs/settings.rs
> +    pub zsl: ConnectorParams,
Please maintain the alphabetical order.

2024-04-08 07:30 UTC, SamraatBansal commented on crates/router/src/core/payments/flows.rs
> +    connector::Zsl,
Please reorder in alphabetical order

2024-04-10 07:10 UTC, SamraatBansal submitted a review, later dismissed

2024-04-10 07:47 UTC, ArjunKarthik submitted a review, later dismissed

2024-04-10 09:40 UTC, ArjunKarthik approved these changes

2024-04-10 11:29 UTC, SamraatBansal approved these changes

2024-04-10 13:53 UTC, merged