feat(users): Add role specific fields for list merchant API
juspay/hyperswitch pull request #4326
Opened 2024-04-08 07:16 UTC by ThisIsMani

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- This PR adds `role_id`, `role_name`, `org_id` fields in list merchants for user API.
- New route `/user/merchants/list` which points to the same function as `/user/switch/list`.
### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Closes #4325.

## How did you test it?

Postman.
Both the following endpoints should produce the same results.
```
curl --location 'http://localhost:8080/user/merchants/list' \
--header 'Authorization: Bearer JWT' \
--header 'Cookie: login_token=JWT'
```
```
curl --location 'http://localhost:8080/user/switch/list' \
--header 'Authorization: Bearer JWT' \
--header 'Cookie: login_token=JWT'
```
Response: Should list all the merchant accounts that user is part of with the following structure.
```
[
    {
        "merchant_id": "merchant_1712559091",
        "merchant_name": null,
        "is_active": true,
        "role_id": "org_admin",
        "role_name": "organization_admin",
        "org_id": "org_NUwiY2HO9JRffXuYrJAx"
    },
    {
        "merchant_id": "merchant_1712559763",
        "merchant_name": null,
        "is_active": true,
        "role_id": "merchant_view_only",
        "role_name": "view_only",
        "org_id": "org_do8JuIQiH0tDQtWly4xo"
    }
]
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-04-08 11:36 UTC, apoorvdixit88 requested changes

2024-04-08 12:25 UTC, apoorvdixit88 approved these changes

2024-04-08 12:41 UTC, racnan commented on crates/router/src/core/user.rs
> +        .await?,
fetching role names can be a separate util.

2024-04-08 13:56 UTC, racnan submitted a review, later dismissed

2024-04-10 06:59 UTC, apoorvdixit88 approved these changes

2024-04-10 09:49 UTC, racnan approved these changes

2024-04-10 10:43 UTC, merged