docs:  mandates and payments routes
juspay/hyperswitch pull request #433
Opened 2023-01-19 21:40 UTC by Sangamesh26

## Type of Change

- [x] Enhancement

## Description

Docs for payments and mandates routes

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-01-20 06:32 UTC, SanchithHegde requested changes

2023-01-20 06:32 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +    /// This is used when payment is confirm and the card is not saved
```suggestion
    /// This is used when payment is to be confirmed and the card is not saved
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/mandates.rs
> +/// To get the mandates
```suggestion
/// Retrieve a mandate given the mandate ID.
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/mandates.rs
> +/// To revoke the mandate
```suggestion
/// Revoke a mandate given the mandate ID.
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/mandates.rs
> +        (status = 200, description = "Get mandates", body = MandateResponse),
```suggestion
        (status = 200, description = "The mandate was retrieved successfully", body = MandateResponse),
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/mandates.rs
> +        (status = 200, description = "Revoke mandates", body = MandateRevokedResponse),
```suggestion
        (status = 200, description = "The mandate was revoked successfully", body = MandateRevokedResponse),
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +/// The entry point for payment which has redirection flow and it redirects to the authentication page
```suggestion
/// The entry point for a payment which involves the redirection flow. This redirects the user to the authentication page.
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +        (status = 200, description = "Redirects to the authentication page", body = PaymentsResponse),
Shouldn't this be a 30X status code?

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +        (status = 400, description = "Missing Mandatory fields")
```suggestion
        (status = 400, description = "Missing mandatory fields")
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +        (status = 400, description = "Missing Mandatory fields")
```suggestion
        (status = 400, description = "Missing mandatory fields")
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +/// To capture payments for a currently uncaptured Payment with its status as requires_capture
```suggestion
/// To capture payments for a currently uncaptured payment
```

@bernard-eugine What do you think, do we need the `with its status as requires_capture` part again?

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +        (status = 400, description = "Missing Mandatory fields")
```suggestion
        (status = 400, description = "Missing mandatory fields")
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +        (status = 400, description = "Missing Mandatory fields")
```suggestion
        (status = 200, description = "Payment session object created or session token was retrieved from wallets", body = PaymentsSessionResponse),
        (status = 400, description = "Missing mandatory fields")
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +        (status = 400, description = "Missing Mandatory fields")
```suggestion
        (status = 200, description = "Received payment redirect response"),
        (status = 400, description = "Missing mandatory fields")
```

Is this supposed to be a 200 status code or 30X?

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +        (status = 400, description = "Missing Mandatory fields")
```suggestion
        (status = 400, description = "Missing mandatory fields")
```

2023-01-20 06:32 UTC, SanchithHegde commented on crates/router/src/routes/payments.rs
> +        ("created_gte" = PrimitiveDateTime, Query, description = "Time greater than or equals to the refund created time")
Replace refund with payment

2023-01-20 07:29 UTC, SanchithHegde submitted a review, later dismissed

2023-01-21 13:50 UTC, jarnura approved these changes
LGTM

2023-01-30 10:55 UTC, Sangamesh26 commented
Merged into #453

2023-01-30 10:55 UTC, closed without merging