feat(core): [Payouts] Add access_token flow for Payout Create and Fulfill flow
juspay/hyperswitch pull request #4375
Opened 2024-04-16 18:36 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Access token flow is added for payout create and payout fulfill flow.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-04-18 09:43 UTC, kashif-m commented on crates/api_models/src/enums.rs
> +    pub fn supports_create_payout_in_router(&self, payout_method: PayoutType) -> bool {
Can we add these under payouts feature flag?

2024-04-18 11:38 UTC, kashif-m requested changes

2024-04-18 11:38 UTC, kashif-m commented on crates/api_models/src/enums.rs
> +        matches!((self, payout_method), (Self::Paypal, PayoutType::Wallet))
PayoutType::Card should also be considered here

2024-04-18 11:38 UTC, kashif-m commented on crates/api_models/src/enums.rs
> +    pub fn supports_create_payout_in_router(&self, payout_method: PayoutType) -> bool {
Can we name this `supports_instant_payout`?

2024-04-18 11:38 UTC, kashif-m commented on crates/router/src/core/payments/access_token.rs
> +        // requires_later
Remove this

2024-04-22 07:17 UTC, kashif-m approved these changes

2024-04-22 11:35 UTC, sahkal commented on crates/router/src/core/payouts/access_token.rs
> +        }
can we remove `.clone()`

2024-04-22 11:42 UTC, sahkal approved these changes

2024-04-23 11:07 UTC, kashif-m submitted a review, later dismissed

2024-04-23 11:07 UTC, sahkal submitted a review, later dismissed

2024-04-23 11:44 UTC, sai-harsha-vardhan approved these changes

2024-04-23 11:50 UTC, kashif-m approved these changes

2024-04-23 11:51 UTC, sahkal approved these changes

2024-04-25 06:47 UTC, merged