feat(connector): generate connector template code for gpayments authenticaition connector
juspay/hyperswitch pull request #4584
Opened 2024-05-08 10:04 UTC by hrithikesh026

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Generated connector template code for gpayments authenticaition connector.

## How did you test it?

Cannot be tested since implementation is pending.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-05-09 09:25 UTC, SamraatBansal requested changes
Also add appropriate labels like config and env changes

2024-05-09 09:25 UTC, SamraatBansal commented on crates/api_models/src/enums.rs
> +    Gpayments,
Can you please comment this out as this is template code.

Follow any past template code PR and comment out at all the necessary places

2024-05-13 06:30 UTC, SamraatBansal approved these changes

2024-05-13 07:27 UTC, sai-harsha-vardhan approved these changes

2024-05-13 09:20 UTC, ArjunKarthik approved these changes

2024-05-13 09:35 UTC, merged