feat(payments_update): update payment_method_billing in payment update
juspay/hyperswitch pull request #4614
Opened 2024-05-09 14:34 UTC by Narayanbhat166

## Type of Change

- [x] New feature

## Description

This PR allows the `payment_method_billing` to be updated in the payments update flow.

## Motivation and Context

## How did you test it?

- Create a payment with confirm as false
```bash
curl --location 'http://localhost:8080/payments' \
--header 'Content-Type: application/json' \
--header 'api-key: dev_VTitmyLzKQhsrNhv6DmgKbzAxaXOLKuWkcY37HT3f7vgWvXBIoYuIg4FU61EGVF6' \
--data-raw '{
    "amount": 6540,
    "currency": "USD",
    "confirm": false,
    "customer": {
        "id": "cus_PAxm0MeCGM5TowgDKPc9",
        "email": "example@juspay.in"
    }
}'
```

- Update the payment with `payment_method_data.billing`
```bash
curl --location 'http://localhost:8080/payments/pay_62qJ2OaJTzci4aKkXjm9' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: dev_VTitmyLzKQhsrNhv6DmgKbzAxaXOLKuWkcY37HT3f7vgWvXBIoYuIg4FU61EGVF6' \
--data '{
    "billing": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "IN",
            "first_name": "Narayan",
            "last_name": "Bhat"
        }
    }
}'
```

- Retrieve the payment and ensure that the billing details are updated

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

2024-05-10 11:01 UTC, hrithikesh026 approved these changes

2024-05-10 12:19 UTC, sahkal requested changes

2024-05-10 12:19 UTC, sahkal commented on crates/api_models/src/payments.rs
> +    Clone, Default, Debug, Eq, serde::Deserialize, serde::Serialize, PartialEq, ToSchema, Setter,
can you remove `Setter` i think its not required

2024-05-11 10:28 UTC, sahkal approved these changes

2024-05-13 05:33 UTC, hrithikesh026 approved these changes

2024-05-13 06:36 UTC, sai-harsha-vardhan approved these changes

2024-05-13 07:51 UTC, merged