Payment charges
juspay/hyperswitch pull request #4628
Opened 2024-05-13 11:13 UTC by kashif-m

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-05-17 07:35 UTC, kashif-m commented on crates/api_models/src/enums.rs
> +pub enum PaymentChargeType {
It's not declared twice, I could not find this in payments.rs :thinking: 

Can you send a link to this declaration in payments.rs?

2024-05-17 07:36 UTC, kashif-m commented on crates/api_models/src/payments.rs
> +}
Made it a generic request

2024-05-21 08:39 UTC, SamraatBansal requested changes

2024-05-21 08:39 UTC, SamraatBansal commented on crates/router/src/connector/stripe/transformers.rs
> +    pub destination_account_id: String,
Put the fields `application_fee_amount` and `destination_account_id`  in the `PaymentIntentRequest`

2024-05-22 07:38 UTC, kashif-m commented on crates/cards/dep.dot
No, my bad

2024-05-22 08:14 UTC, SamraatBansal approved these changes
LGTM! Approving on behalf of connectors

2024-05-22 12:09 UTC, SamraatBansal submitted a review, later dismissed

2024-05-22 16:19 UTC, Narayanbhat166 approved these changes

2024-05-23 07:20 UTC, SamraatBansal approved these changes

2024-05-23 07:31 UTC, ThisIsMani submitted a review, later dismissed
Dashboard specific changes looks fine.

2024-05-23 19:19 UTC, SamraatBansal approved these changes

2024-05-24 06:30 UTC, Narayanbhat166 approved these changes

2024-05-24 06:57 UTC, ThisIsMani approved these changes

2024-05-24 08:23 UTC, merged