Multitenancy: add tenant id in sessionState and populate it from request header. All component should take tenant_id only from sessionState
juspay/hyperswitch pull request #4630
Opened 2024-05-13 12:19 UTC by jagan-jaya

## Type of Change

- [ ] Bugfix
- [X] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

1. Add tenant id in sessionState and populate it from request header. All component should take tenant_id only from sessionState
2. Prefix_tenant_id with redis key. Separate connection management for redis is not needed

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-05-24 10:53 UTC, NishantJoshi00 requested changes

2024-05-24 10:53 UTC, NishantJoshi00 commented on crates/router/src/services/api.rs
> +                    .contains(&tenant_id.to_string())
This is more expensive compared to a hash-map lookup

2024-05-27 12:41 UTC, jarnura requested changes

2024-05-28 09:31 UTC, jagan-jaya commented on crates/router/src/db/api_keys.rs
> +                prefix: String::default(),
Used only in tests, anyway added a Todo task to make it usage specific enum

2024-05-28 09:35 UTC, jagan-jaya commented on crates/storage_impl/src/redis/cache.rs
> +    pub prefix: String,
Added todo to create usage specific enum.

2024-05-28 09:35 UTC, jagan-jaya commented on crates/scheduler/src/consumer.rs
>          .await;
Those are redundant and insignificant logs.

2024-05-28 09:36 UTC, jagan-jaya commented on crates/router/src/types/storage/payment_attempt.rs
> +            .get(state.conf.multitenancy.get_tenant_names().first().unwrap())
used only in tests

2024-05-28 09:36 UTC, jagan-jaya commented on crates/router/src/types/storage/payment_attempt.rs
> +            .unwrap();
used only in tests

2024-05-28 09:36 UTC, jagan-jaya commented on crates/router/src/types/storage/payment_attempt.rs
> +            .get(state.conf.multitenancy.get_tenant_names().first().unwrap())
used only in tests

2024-05-28 09:36 UTC, jagan-jaya commented on crates/router/src/types/storage/payment_attempt.rs
> +            .unwrap();
used only in tests

2024-05-28 10:09 UTC, jagan-jaya commented on crates/redis_interface/src/commands.rs
> +    pub fn get_tenant_keys<K>(&self, keys: K) -> MultipleKeys
Renamed the method

2024-05-30 07:27 UTC, jarnura submitted a review, later dismissed

2024-05-31 12:22 UTC, NishantJoshi00 approved these changes

2024-05-31 12:22 UTC, jarnura submitted a review, later dismissed

2024-05-31 13:35 UTC, lsampras submitted a review, later dismissed
analytics changes look good

2024-06-03 10:00 UTC, jarnura submitted a review, later dismissed

2024-06-03 10:09 UTC, Aprabhat19 submitted a review, later dismissed

2024-06-03 10:24 UTC, lsampras approved these changes

2024-06-03 11:21 UTC, jarnura approved these changes

2024-06-03 11:23 UTC, lsampras approved these changes

2024-06-03 11:24 UTC, Aprabhat19 approved these changes

2024-06-03 12:43 UTC, merged

2024-06-06 17:35 UTC, lsampras commented on crates/router/src/services/api.rs
> +    incoming_request_header: &HeaderMap,
We should skip this else the request headers will be logged by tracing