add webhook support for frm
juspay/hyperswitch pull request #4662
Opened 2024-05-16 12:00 UTC by srujanchikke

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR introduces FRM webhooks . Frm webhooks are consumed when payments are held due to manual review pending from FRM processors. When merchant/ Frm provides decision , webhook is triggered . Based on decision we take action whether to approve or decline the payment.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-05-21 13:19 UTC, sai-harsha-vardhan commented on crates/router/src/core/webhooks.rs
> +                        amount_to_capture: Some(payment_attempt.amount),
Please send `payment_attempt.amount_to_capture` here

2024-05-21 13:19 UTC, sai-harsha-vardhan commented on crates/router/src/core/webhooks.rs
> +                match payments_response {
Can remove this redundant logic and get the payments_response using the event type

2024-05-21 13:19 UTC, sai-harsha-vardhan commented on crates/router/src/core/webhooks.rs
> +                        let _event_type: Option<enums::EventType> =
Please trigger an outgoing webhook here

2024-05-21 13:19 UTC, sai-harsha-vardhan commented on crates/router/src/core/webhooks.rs
> +    _request_details: &api::IncomingWebhookRequestDetails<'_>,
Please remove unused fields here

2024-05-21 16:11 UTC, srujanchikke commented on crates/router/src/core/webhooks.rs
> +                        let _event_type: Option<enums::EventType> =
added

2024-05-21 19:49 UTC, Sakilmostak requested changes

2024-05-21 19:49 UTC, Sakilmostak commented on crates/router/src/core/webhooks.rs
> +            .attach_printable("Incoming webhook flow for external authentication failed")?,
```suggestion
            .attach_printable("Incoming webhook flow for fraud check failed")?,
```

2024-05-22 05:36 UTC, kashif-m approved these changes

2024-05-22 06:59 UTC, sai-harsha-vardhan approved these changes

2024-05-22 08:28 UTC, merged