feat(core): [Paypal] Add session_token flow for Paypal sdk
juspay/hyperswitch pull request #4697
Opened 2024-05-19 17:37 UTC by SamraatBansal

## Type of Change

- [ ] Bugfix
- [X] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add session_token flow for Paypal sdk

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-05-23 14:04 UTC, prasunna09 requested changes

2024-05-24 11:36 UTC, Narayanbhat166 commented
Can you add api contracts foe each of the api calls?

2024-05-24 11:50 UTC, Narayanbhat166 submitted a review, later dismissed

2024-05-26 19:26 UTC, SamraatBansal commented on crates/router/src/connector/paypal/transformers.rs
> +    pub next_action: Option<api_models::payments::NextActionCall>,
Yes this is backwards compatible, have tested with old configuration, creating a manual payment, then updating it to the new configuration and then capturing. it works

2024-05-27 09:34 UTC, prasunna09 submitted a review, later dismissed

2024-05-27 09:50 UTC, Narayanbhat166 submitted a review, later dismissed

2024-05-27 11:00 UTC, Narayanbhat166 approved these changes

2024-05-27 11:02 UTC, prasunna09 approved these changes

2024-05-27 11:19 UTC, merged