feat(Cypress): Add routing test
juspay/hyperswitch pull request #4768
Opened 2024-05-26 19:35 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add service level test for Routing

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Tested through Cypress
<img width="843" alt="Screenshot 2024-05-27 at 1 04 52 AM" src="https://github.com/juspay/hyperswitch/assets/73734619/8c0ed803-7538-492e-9cab-4cd030f715c0">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-06-04 18:10 UTC, SamraatBansal requested changes

2024-06-04 18:10 UTC, SamraatBansal commented on cypress-tests/cypress/e2e/RoutingTest/00002-ConnectorMultipleCreate.cy.js
> +  });
Is this function used at multiple places?
If only added for routing test cases still it should be configurable, once discuss this with @vspecky

2024-06-05 10:11 UTC, vspecky approved these changes
LGTM

2024-06-05 18:46 UTC, SamraatBansal approved these changes

2024-06-07 07:56 UTC, pixincreate requested changes
Other than that, LGTM

2024-06-07 07:56 UTC, pixincreate commented on cypress-tests/cypress/e2e/RoutingTest/00000-AccountCreate.cy.js
> +      console.log("seeding globalState -> " + JSON.stringify(globalState));
Can you please remove all the console logs that exposes `globalState`.  
That includes `cy.task("cli_log")` stuffs as well. Let's keep that them only for debugging.

2024-06-07 07:56 UTC, pixincreate commented on cypress-tests/cypress/e2e/RoutingTest/00000-AccountCreate.cy.js
> +    console.log("flushing globalState -> " + JSON.stringify(globalState));
Here as well.

2024-06-07 07:56 UTC, pixincreate commented on cypress-tests/cypress/e2e/RoutingTest/00001-CustomerCreate.cy.js
> +      console.log("seeding globalState -> " + JSON.stringify(globalState));
Here as well.

2024-06-07 07:56 UTC, pixincreate commented on cypress-tests/cypress/e2e/RoutingTest/00001-CustomerCreate.cy.js
> +    console.log("flushing globalState -> " + JSON.stringify(globalState));
Here as well.

2024-06-07 07:56 UTC, pixincreate commented on cypress-tests/cypress/e2e/RoutingTest/00002-ConnectorMultipleCreate.cy.js
> +      console.log("seeding globalState -> " + JSON.stringify(globalState));
Here as well.

2024-06-07 07:56 UTC, pixincreate commented on cypress-tests/cypress/e2e/RoutingTest/00002-ConnectorMultipleCreate.cy.js
> +    console.log("flushing globalState -> " + JSON.stringify(globalState));
Here as well.

2024-06-07 07:56 UTC, pixincreate commented on cypress-tests/cypress/e2e/RoutingTest/00003-PaymentRoutingTest.cy.js
> +      );
Remove these

2024-06-07 07:56 UTC, pixincreate commented on cypress-tests/cypress/e2e/RoutingTest/00003-PaymentRoutingTest.cy.js
> +    );
Remvoe L29 and these.

2024-06-07 10:08 UTC, merged