feat(router): add an api to migrate the apple pay certificates from connector metadata to `connector_wallets_details` column in merchant connector account
juspay/hyperswitch pull request #4790
Opened 2024-05-28 13:19 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-05-30 11:29 UTC, jagan-jaya requested changes

2024-05-31 10:37 UTC, SanchithHegde commented on crates/router/src/core/payments/helpers.rs
> +            )
Avoid info log lines for error messages.

2024-05-31 10:37 UTC, SanchithHegde commented on crates/router/src/core/payments/helpers.rs
> +            .ok(),
Avoid info log lines for error messages.

2024-06-05 14:14 UTC, SanchithHegde commented on crates/router/src/core/apple_pay_certificates_migration.rs
> +        };
We can optionally add debug log lines in each case with suitable messages, as a sort of a progress indicator. Again, optional change.

2024-06-05 15:49 UTC, SanchithHegde approved these changes

2024-06-06 06:24 UTC, ivor-juspay approved these changes

2024-06-06 07:23 UTC, jagan-jaya approved these changes

2024-06-06 07:29 UTC, Chethan-rao approved these changes
@juspay/hyperswitch-routing related changes LGTM

2024-06-06 08:37 UTC, merged