feat(auth): Add support for partial-auth, by facilitating injection of authentication parameters in headers
juspay/hyperswitch pull request #4802
Opened 2024-05-29 06:40 UTC by NishantJoshi00

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Adding a wrapper over `ApiKeyAuth` and `PublishableKeyAuth` that provides an alternative to allow authentication being done outside the application. This is done by allowing the external entity (most likely a reverse proxy) to send the parameters necessary for the authentication of the request, there by reducing the need to perform db calls and improving the performance of the service.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

<img width="1728" alt="image" src="https://github.com/juspay/hyperswitch/assets/51093026/ddb3cccf-c6e8-4870-99e9-dc225e6f4194">

Using a dummy service to generate a request and header parameters, and sending this parameter to the hyperswitch application without `api-key` and getting authenticated for the request.

![image](https://github.com/juspay/hyperswitch/assets/51093026/e14abd04-af29-487c-b33a-d6dac5c139e9)

Here, you can see that the request was successful, but the payment failed. There by showcasing that the request was authenticated successfully.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-06-04 06:53 UTC, jarnura submitted a review, later dismissed
LGTM

2024-06-13 12:44 UTC, jagan-jaya requested changes

2024-07-02 08:27 UTC, akshay-97 submitted a review, later dismissed

2024-07-05 08:44 UTC, akshay-97 approved these changes

2024-07-29 09:06 UTC, dracarys18 approved these changes

2024-07-29 09:15 UTC, akshay-97 approved these changes

2024-07-29 09:15 UTC, jarnura approved these changes

2024-07-29 09:25 UTC, jarnura submitted a review, later dismissed

2024-07-29 13:51 UTC, akshay-97 approved these changes

2024-07-29 13:55 UTC, dracarys18 approved these changes

2024-07-29 16:25 UTC, jarnura approved these changes

2024-07-30 13:00 UTC, akshay-97 submitted a review, later dismissed

2024-07-30 13:00 UTC, dracarys18 approved these changes

2024-07-30 13:25 UTC, jarnura approved these changes

2024-07-31 06:29 UTC, jagan-jaya approved these changes

2024-07-31 07:46 UTC, Chethan-rao submitted a review, later dismissed

2024-07-31 07:47 UTC, ThisIsMani approved these changes
Dashboard specific changes looks fine.

2024-07-31 10:13 UTC, Chethan-rao approved these changes

2024-07-31 10:14 UTC, jarnura approved these changes

2024-07-31 10:14 UTC, akshay-97 approved these changes

2024-08-01 09:50 UTC, merged