refactor(conditional_configs): refactor conditional_configs to use Moka Cache instead of Static Cache
juspay/hyperswitch pull request #4814
Opened 2024-05-29 11:36 UTC by Aprabhat19

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
refactor conditional_configs to use Moka Cache instead of Static Cache

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-06-02 18:11 UTC, SanchithHegde commented on crates/router/src/core/payment_methods/surcharge_decision_configs.rs
> +    };
You can move the DB call to fetch the config (and thus parsing the record) within the closure, to avoid unnecessary DB calls.

2024-06-02 18:11 UTC, SanchithHegde commented on crates/router/src/core/payments/conditional_configs.rs
> +    };
Similar change can be done here.

2024-06-02 18:11 UTC, SanchithHegde commented on crates/router/src/db/merchant_account.rs
>      let kgraph_key = merchant_account.default_profile.as_ref().map(|profile_id| {
```suggestion
    let cgraph_key = merchant_account.default_profile.as_ref().map(|profile_id| {
```

2024-06-02 18:11 UTC, SanchithHegde commented on crates/router/src/db/merchant_account.rs
>      let kgraph_key = Some(CacheKind::CGraph(
```suggestion
    let cgraph_key = Some(CacheKind::CGraph(
```

2024-06-05 07:50 UTC, SanchithHegde submitted a review, later dismissed

2024-06-05 09:31 UTC, vspecky requested changes
Please add cache invalidation logic. When the 3ds decision manager config is updated or deleted, we should invalidate the cache of of all pods. Same for surcharge.

2024-06-05 09:39 UTC, hrithikesh026 submitted a review, later dismissed
Surcharge Decision Configs Related changes LGTM

2024-06-06 10:08 UTC, vspecky requested changes

2024-06-06 10:08 UTC, vspecky commented on crates/router/src/core/routing/helpers.rs
> +    let config_key = cache::CacheKind::Config(key.into());
You might want to create separate `CacheKind` variants for decision manager and surcharge, as from what I understand `CacheKind::Config` will cause an invalidation of `CONFIG_CACHE` only, not `DECISION_MANAGER_CACHE` and `SURCHARGE_CACHE`. Check `pub_sub.rs` for the invalidation logic.

2024-06-07 14:01 UTC, SanchithHegde approved these changes

2024-06-10 06:50 UTC, vspecky approved these changes
LGTM

2024-06-11 07:41 UTC, hrithikesh026 approved these changes

2024-06-11 08:01 UTC, merged