feat: Added generic cache functions to populate and invalidate cache
juspay/hyperswitch pull request #483
Opened 2023-01-31 10:21 UTC by dracarys18

## Type of Change

- [x] Enhancement

## Description

This adds generic helper functions which helps to populate cache and update cache.

## Motivation and Context

So this PR adds two generic functions to help you populate value from redis if it doesn't exist in redis it will get it from DB and insert the value in redis. Usage:

```rust
inhabit_cache(&store,&key, | | async{ function_that_inserts_into_db().await}).await
```

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-01-31 10:38 UTC, Narayanbhat166 commented on crates/router/src/db/cache.rs
> +#![allow(dead_code)]
remove this

2023-01-31 12:32 UTC, Narayanbhat166 commented on crates/router/src/db/cache.rs
> +pub async fn inhabit_cache<T, F, Fut>(
Provide meaningful function name or add comments

2023-02-01 07:22 UTC, dracarys18 commented
Closing this as this can't be generic because the logic would change for different use cases.

2023-02-03 12:30 UTC, jarnura requested changes

2023-02-03 12:30 UTC, jarnura commented on crates/router/src/db/cache.rs
> +    Ok(match redis_val {
in OK we can wrap with Ok and we don't want to use ? in line: 34

2023-02-03 14:04 UTC, SanchithHegde approved these changes

2023-02-03 14:05 UTC, merged