Refac/cg inclusion pm
juspay/hyperswitch pull request #4845
Opened 2024-06-03 07:15 UTC by prajjwalkumar17

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Adds CGraphing for Merchant Pms with all the possible filters applicable as described below. 
# Addressed in this PR:

## 1 Creation of Constraint Graph for Merchant Payment Method List:
Created a Constraint Graph with the following filters/Nodes:

From configs and MCA:
1. Countries Filter
2. Currency Filter
3. Supported for Mandates Filter
4. Allowed Payment Method Types
5. Supported for Update Mandates Filter
6. Capture Method Used

From Req:
1. Recurring Enabled
2. Installment Enabled
3. Amount Based

After Applying all these Filters and creating a Graph for a Merchant MCA with 2 PMT enabled (Credit and Debit) with one connector(Cybersource), We will get a graph equivalent to [this](https://dreampuf.github.io/GraphvizOnline/?compressed=M4FwTglgxiAEAmEDmYCGAHAFrKB7AdqGhPiAPoobYDeAULA7AHIAMA2gDaoBGAphwF4AROlQBPALa9SZKSEy54sATlRh4QgLr1GTAIyce-YaMnTyIMel7LYAV3TxUIXrNT4nLrToZMATIZ8gkIAwgT4vDC4YLAksGxQYnxgwLh2YFC8mt6MzADMgcZCAGTFOboALIXBAD6wNeW%2BAKzVJuJSMpbWthEA7m4ezryNzABsraHhkSDRsfjxEQAeJLwgwAA0sBJ2HCAQwKgAZrymm-gSEJuodvLREABevPC4IBEgm73RHPCnsEQQ1jOuAIm247gA1rhDqgpJAoKhNolkql0plNkgOLgwRxfqh4GJpNltLkmAB2CalEZMAAcE1MHQsVhsKnwBAGnmGxN0AE46e1zGQusy-qsHOyhlS9OwuEFhHUGlzfHoDDKivLJQFVcF4eoyG9PmBwXN4gA1fYI2AAWVQoF4GTU8CJPmYegKWuE3AgHA4JCQZDwdlIYDExrYACkMO5NgBVfAQFzwADKICGwAA8ocAIKw6CoJ0kvRVd1CT3e33%2BtJBkNxNgASQ8EAtsfjT2TqYz2btuc2mbsRFQPrzkpaxcpipd42LUHSYGkiVDtaYACV87o9OSpzO59X5nXl6ulbTR2Vx-peceqX5pUZtQ7BUzbPBeJ6QJeVTfhGF8BEojEa0i7RRDIskvTUPxKE9nX8N1wPVU8-CLcCvx-GY-13JYVjWTZtl2c1jl%2Bc5Llga5bkgR5nleVYPi%2BH5xERJJALSYD0UxbFcXxaRNn%2BQFYFZEFYDBfBIWhHN4QPZg-BHcCxygvxJ1g%2BpLw3BSFVko9wPhdAQHSVw5AUJQVAkdw7AHS9zw0u99WiI0azNA5NmtW17XUcSmDya9ZRLL0fXwP0AyrUMI1EfAYzjBM2xcdMs1EodTzyd9PNLHy-MrcAd3iIKo1gXt%2B0HUKWyTFNIo7GLNlrNAAEdXLyMDPJkkk8hgzzpzAWd8HnGtFxXKk8kQ5qt3a9K926uKpLqyCGvk8aeuU5q7yFWwoFnRBX20KCWFgABaAA%2BfJ4jUMBcF6TBeDxARWTAIyOAuq71jwTEwAEbgODsLIoL0Lbdrc-bWqOk6zpugdAY4O7cAep6Xrekk-E%2Bva2AOv7Tvgc7oiu4HQfB57Xri2GmAqH7DuOpGUcuoHUYHDHogh7GoKaXHSQJxGAfJ66Wcpx6sah3RRnpxmieZ0nWcF9nqa53xqVxqU%2Bf%2B5HgfR%2B6qc509uUljb4d%2B-nZZZ%2BWwcVyHT3xnaXQ%2B9XCZlkm0bZhWOf1qCGaN-QTYRzWLbJ4XrdF08pYd5VpeJuWrd1m2aYLPJJbp02ma1wWdcx22C0Nr69Aj53zYD92g8996eZ9iXI5d9Pbo9pX3vtpO89T-3tcDuOQ7XD6fZV-O0%2BrjPa7Fl0Ycbv2zoIGu9brpU6e75uq5j-vg47-QJZHyuBcttuB6nvQVYdq8e%2Bjhei8zkuSQ2teYdH%2Be3e39uvdxvxD7nzeT4p4v490PwG6%2By%2BN9doXT6X%2BCu5fsOj5vj%2Bd8d4P2aBfFOGsW7j0XpPeCicJLgLNmPLeQCz5QRni-Hm-936xy-lBVeGC36FxQbg6GYc14MywUQkG99B7wIvhQ6%2B2CJ5Z2hjnF%2BDCIFINvtQ4BtC3L7y%2BjVQhrdP4wKgvFXGQjKEiOIWIhqZDBEIKjkw6BLDdC9UkUoguMieGoOhmXfImDGFUJFrvR%2B6DDHCKgaIgQy14L4MsVgvuqizG%2BCEQ7PIRjOHH0Abokh6jh6CK8YgnxOC5HqLYfkDhISAFhKzgAX1oEAA#strict%20digraph%20constraint_graph%20%7B%0A%20%20%20%20N0%5Blabel%3D%22payment_method%20%3D%20card%22%5D%0A%20%20%20%20N1%5Blabel%3D%22payment_type%20%3D%20update_mandate%22%5D%0A%20%20%20%20N2%5Blabel%3D%22Connector%20in%20%5Bcybersource%5D%22%5D%0A%20%20%20%20N3%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N4%5Blabel%3D%22%7C%20%7C%22%5D%0A%20%20%20%20N5%5Blabel%3D%22payment_type%20%3D%20new_mandate%22%5D%0A%20%20%20%20N6%5Blabel%3D%22Connector%20in%20%5Bnexinets%2C%20multisafepay%2C%20nmi%2C%20authorizedotnet%2C%20worldpay%2C%20stripe%2C%20noon%2C%20bankofamerica%2C%20cybersource%2C%20globalpay%2C%20adyen%5D%22%5D%0A%20%20%20%20N7%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N8%5Blabel%3D%22payment_type%20%3D%20non_mandate%22%5D%0A%20%20%20%20N9%5Blabel%3D%22payment_type%20%3D%20setup_mandate%22%5D%0A%20%20%20%20N10%5Blabel%3D%22%7C%20%7C%22%5D%0A%20%20%20%20N11%5Blabel%3D%22%7C%20%7C%22%5D%0A%20%20%20%20N12%5Blabel%3D%22card_network%20in%20%5BVisa%2C%20Mastercard%5D%22%5D%0A%20%20%20%20N13%5Blabel%3D%22billing_country%20in%20%5BJapan%2C%20UnitedStatesOfAmerica%5D%22%5D%0A%20%20%20%20N14%5Blabel%3D%22billing_country%20in%20%5BIndia%2C%20UnitedStatesOfAmerica%2C%20Australia%5D%22%5D%0A%20%20%20%20N15%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N16%5Blabel%3D%22currency%20in%20%5BINR%5D%22%5D%0A%20%20%20%20N17%5Blabel%3D%22currency%20in%20%5BINR%5D%22%5D%0A%20%20%20%20N18%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N19%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N20%5Blabel%3D%22card_type%20%3D%20debit%22%5D%0A%20%20%20%20N21%5Blabel%3D%22Connector%20in%20%5Bcybersource%5D%22%5D%0A%20%20%20%20N22%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N23%5Blabel%3D%22%7C%20%7C%22%5D%0A%20%20%20%20N24%5Blabel%3D%22Connector%20in%20%5Bnexinets%2C%20multisafepay%2C%20nmi%2C%20authorizedotnet%2C%20worldpay%2C%20cybersource%2C%20globalpay%2C%20adyen%2C%20stripe%2C%20noon%2C%20bankofamerica%5D%22%5D%0A%20%20%20%20N25%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N26%5Blabel%3D%22%7C%20%7C%22%5D%0A%20%20%20%20N27%5Blabel%3D%22%7C%20%7C%22%5D%0A%20%20%20%20N28%5Blabel%3D%22capture_method%20%3D%20manual%22%5D%0A%20%20%20%20N29%5Blabel%3D%22card_network%20in%20%5BVisa%2C%20Mastercard%5D%22%5D%0A%20%20%20%20N30%5Blabel%3D%22billing_country%20in%20%5BJapan%2C%20UnitedStatesOfAmerica%5D%22%5D%0A%20%20%20%20N31%5Blabel%3D%22billing_country%20in%20%5BJapan%2C%20Australia%2C%20UnitedStatesOfAmerica%2C%20Iraq%5D%22%5D%0A%20%20%20%20N32%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N33%5Blabel%3D%22currency%20in%20%5BINR%5D%22%5D%0A%20%20%20%20N34%5Blabel%3D%22currency%20in%20%5BINR%5D%22%5D%0A%20%20%20%20N35%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N36%5Blabel%3D%22%26%26%22%5D%0A%20%20%20%20N37%5Blabel%3D%22card_type%20%3D%20credit%22%5D%0A%0A%20%20%20%20N0%20-%3E%20N3%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N1%20-%3E%20N3%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N2%20-%3E%20N3%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N3%20-%3E%20N4%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N5%20-%3E%20N7%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N6%20-%3E%20N7%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N8%20-%3E%20N10%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N9%20-%3E%20N10%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N4%20-%3E%20N11%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N7%20-%3E%20N11%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N10%20-%3E%20N11%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N13%20-%3E%20N15%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N14%20-%3E%20N15%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N16%20-%3E%20N18%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N17%20-%3E%20N18%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N11%20-%3E%20N19%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N12%20-%3E%20N19%20%5Barrowhead%3Donormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N15%20-%3E%20N19%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N18%20-%3E%20N19%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N19%20-%3E%20N20%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N0%20-%3E%20N22%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N1%20-%3E%20N22%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N21%20-%3E%20N22%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N22%20-%3E%20N23%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N5%20-%3E%20N25%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N24%20-%3E%20N25%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N8%20-%3E%20N26%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N9%20-%3E%20N26%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N23%20-%3E%20N27%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N25%20-%3E%20N27%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N26%20-%3E%20N27%20%5Barrowhead%3Dnormalnormal%2Ccolor%3Dblue%5D%0A%20%20%20%20N30%20-%3E%20N32%20%5Barrowhead%3Dnormalnormal%2Ccolor%3D [...]

2024-06-04 09:19 UTC, vspecky requested changes

2024-06-04 09:19 UTC, vspecky commented on crates/router/src/core/payment_methods/cards.rs
>                              }
This piece of code is not required right? Since we already added the connector to the context above

2024-06-04 09:19 UTC, vspecky commented on crates/router/src/core/payment_methods/cards.rs
> +                            (capture_method == common_enums::CaptureMethod::Manual).then(|| {
Add the capture method to the context regardless of whether it is automatic or manual. If tomorrow someone adds `automatic` to the config, we should be able to handle it.

2024-06-04 09:19 UTC, vspecky commented on crates/router/src/core/payment_methods/utils.rs
> +    if let Some(pm_obj_countries) = pm_countries {
You have written the code like this
```rust
if cond1 {
  match stuff {
    variant1 => {
      A;
      B;
    }
    variant2 => {
      C;
      B;
    }
  }
} else if cond2 {
  B;
}
```
i.e. you're repeating `B` 3 times, which is the code for adding config countries to the mix. Refactor it to the following.
```rust
match stuff {
  variant1 => {
    A;
  }
  variant2 => {
    C;
  }
}

if config_present {
  B;
}
```

Ensure you do this for currencies as well.

2024-06-04 11:08 UTC, vspecky requested changes

2024-06-04 11:08 UTC, vspecky commented on crates/router/src/core/payment_methods/utils.rs
> +    if let Some(pm_obj_countries) = pm_countries {
We shouldn't have an `if/else` here. You basically have
```rust
if mca_countries {
  add_mca_countries
} else if config_countries {
  add_config_countries
}
```
You're only adding one of the two, not both. It should be
```rust
if mca_countries {
  add_mca_countries
}

if config_countries {
  add_config_countries
}
```
Ensure this for currencies as well.

2024-06-05 08:49 UTC, vspecky approved these changes

2024-06-05 12:24 UTC, Aprabhat19 commented on crates/router/src/core/payment_methods/cards.rs
> +        }
Can we use the fn `get_or_populate_in_memory` instead. Can be taken up into another PR

2024-06-05 12:24 UTC, Aprabhat19 approved these changes

2024-06-05 15:27 UTC, merged