5188 amount conversion do amount conversion for iatapay
juspay/hyperswitch pull request #4866
Opened 2024-06-04 10:19 UTC by sahkal

## Type of Change

- [x] Refactoring

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-06-07 07:59 UTC, jagan-jaya requested changes

2024-06-07 07:59 UTC, jagan-jaya commented on scripts/add_connector.sh
> +    connectors=(aci adyen airwallex applepay authorizedotnet bambora bankofamerica billwerk bitpay bluesnap boku braintree cashtocode checkout coinbase cryptopay cybersource dlocal dummyconnector eba
remove `sahkal sahkal sahkal`

2024-06-07 12:03 UTC, sahkal commented on scripts/add_connector.sh
> -sed -i '' -e "s/\(pub enum Connector {\)/\1\n\t${payment_gateway_camelcase},/" crates/euclid/src/enums.rs
added it back

2024-06-07 12:50 UTC, jagan-jaya approved these changes

2024-06-28 09:04 UTC, jarnura approved these changes

2024-06-28 09:45 UTC, jagan-jaya approved these changes

2024-07-01 09:15 UTC, AkshayaFoiger approved these changes

2024-07-01 11:36 UTC, merged