refactor(payment_methods): Enable deletion of default Payment Methods
juspay/hyperswitch pull request #4942
Opened 2024-06-11 08:57 UTC by Aprabhat19

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Previously we did not support the deletion of the Default Payment Method, if it's the only PM for the particular customer. In this PR we enable deletion of default Payment Methods

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
- Create a MA and a MCA
- Do a payment , with `setup_future_usag:off_session`; the card would be saved
- Do a List PM for Customers, you'll have only one card , which has been set as default
- Delete the card, it'll be a success

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-06-11 10:13 UTC, Chethan-rao approved these changes

2024-06-12 07:36 UTC, jagan-jaya approved these changes

2024-06-12 09:16 UTC, vspecky requested changes
If we allow deleting default payment methods, then we also need to update the `default_payment_method_id` field of the customer object in DB, else it will be pointing to a deleted record.

2024-06-12 09:47 UTC, Aprabhat19 commented
> If we allow deleting default payment methods, then we also need to update the `default_payment_method_id` field of the customer object in DB, else it will be pointing to a deleted record.

Shashank here we are just allowing the deletion of the default payment method id if its 1 , the updation of the `default_payment_method_id` field of the customer object in DB , is already happening

2024-06-12 09:49 UTC, vspecky approved these changes

2024-06-12 10:30 UTC, merged