do-amount-conversion-for-iatapay
juspay/hyperswitch pull request #4978
Opened 2024-06-12 17:55 UTC by KiranKBR

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-17 16:15 UTC, sahkal submitted a review, later dismissed

2024-07-22 07:35 UTC, SamraatBansal requested changes
Line 260: `gpayments.rs` has hardcoded 0, please change it to minor_amount
```
let connector_router_data = gpayments::GpaymentsRouterData::try_from((0, req))?;
```

2024-07-25 11:38 UTC, SamraatBansal approved these changes

2024-07-25 11:38 UTC, SamraatBansal approved these changes

2024-07-25 17:57 UTC, sahkal approved these changes

2024-07-26 09:48 UTC, SanchithHegde approved these changes

2024-07-26 12:18 UTC, jarnura approved these changes

2024-08-07 17:25 UTC, merged