do-amount-conversion-for-multisafepay
juspay/hyperswitch pull request #4982
Opened 2024-06-12 19:53 UTC by KiranKBR

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-27 14:01 UTC, sahkal requested changes
```
#[serde_with::skip_serializing_none]
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Item {
    pub name: String,
    pub unit_price: f64,
    pub description: Option<String>,
    pub quantity: i64,
}
```

in the above struct the unit_price should be FloatMajorUnit, though we are sending this data as `None` to the connector it should be marked as our domain type, please look into these in other pr's as well

2024-07-27 17:26 UTC, KiranKBR commented
> ```
> #[serde_with::skip_serializing_none]
> #[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
> pub struct Item {
>     pub name: String,
>     pub unit_price: f64,
>     pub description: Option<String>,
>     pub quantity: i64,
> }
> ```
> 
> in the above struct the unit_price should be FloatMajorUnit, though we are sending this data as `None` to the connector it should be marked as our domain type, please look into these in other pr's as well

Sure I will on them

2024-07-29 06:56 UTC, sahkal approved these changes

2024-08-13 13:54 UTC, SanchithHegde approved these changes

2024-08-13 16:49 UTC, SamraatBansal approved these changes

2024-08-14 10:02 UTC, merged