do-amount-conversion-for-volt
juspay/hyperswitch pull request #4985
Opened 2024-06-13 04:51 UTC by KiranKBR

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-22 07:39 UTC, SamraatBansal approved these changes

2024-07-22 07:42 UTC, swangi-kumari approved these changes

2024-07-22 10:23 UTC, dracarys18 requested changes

2024-07-22 10:23 UTC, dracarys18 commented on crates/router/src/connector/volt.rs
> +    amount_converter: &'static (dyn AmountConvertor<Output = MinorUnit> + Sync),
There's no need of dynamic dispatch here, As I can see below you are initialising it to `MinorUnitForConnector`. 
Could be just 
```rust
struct Volt(MinorUnitForConnector);
```

2024-07-23 09:37 UTC, dracarys18 approved these changes
Minor changes otherwise looks good to me

2024-07-23 11:00 UTC, merged