do-amount-conversion-for-placetopay
juspay/hyperswitch pull request #4988
Opened 2024-06-13 06:14 UTC by KiranKBR

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-17 16:09 UTC, sahkal submitted a review, later dismissed

2024-07-22 07:27 UTC, SamraatBansal requested changes
Line 295: `transformer.rs` has a usage of below check, please handle this with `minor_amount`
if item.request.refund_amount == item.request.payment_amount {

2024-07-25 11:33 UTC, SamraatBansal approved these changes

2024-07-25 17:59 UTC, sahkal approved these changes

2024-07-26 09:46 UTC, SanchithHegde approved these changes

2024-07-26 12:18 UTC, jarnura approved these changes

2024-07-26 14:00 UTC, merged