feat(router): add payment method type duplication check for `google_pay`
juspay/hyperswitch pull request #5023
Opened 2024-06-18 11:04 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-06-18 12:59 UTC, jagan-jaya requested changes

2024-06-18 12:59 UTC, jagan-jaya commented on crates/router/src/core/payments/tokenization.rs
> +                                            || payment_method.payment_method_type
it can return apple pay PM id for a gpay PM

2024-06-19 08:00 UTC, jagan-jaya submitted a review, later dismissed

2024-06-19 09:16 UTC, vspecky requested changes

2024-06-19 09:16 UTC, vspecky commented on crates/router/src/core/payments/tokenization.rs
You probably want to rename the `customer_apple_pay_saved_pm_id_option` variable

2024-06-19 09:19 UTC, ShankarSinghC commented on crates/router/src/core/payments/tokenization.rs
Will rename it.

2024-06-19 09:21 UTC, vspecky approved these changes

2024-06-19 09:44 UTC, jagan-jaya approved these changes

2024-06-19 12:47 UTC, merged