feat(pm_auth): Added balance check for PM auth bank account
juspay/hyperswitch pull request #5054
Opened 2024-06-20 10:40 UTC by Sarthak1799

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

have added a balance check that would enable a check on the available amount in the selected bank account while doing a payment.
If the found balance is less than the intent amount, the payment would not go through.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-06-20 16:12 UTC, Chethan-rao requested changes

2024-06-20 16:12 UTC, Chethan-rao commented on crates/router/src/core/pm_auth.rs
> +                    "Payment amount is less than the available amount in selected bank account"
```suggestion
                    "Payment amount is greater than the available amount in selected bank account"
```

2024-06-20 16:12 UTC, Chethan-rao commented on crates/router/src/core/pm_auth.rs
> +            .attach_printable("Could not convert to MinorUnit")?;
could u change this error message to convey more on what conversion failed. Something like

```suggestion
            .attach_printable("Could not convert {something} to MinorUnit")?;
```

2024-06-20 16:12 UTC, Chethan-rao commented on crates/router/src/core/pm_auth.rs
> +                payment_intent.currency.unwrap_or(enums::Currency::USD),
Is it fine to make `USD` as fallback case here?

2024-06-25 11:10 UTC, Chethan-rao submitted a review, later dismissed

2024-06-26 08:53 UTC, vspecky requested changes

2024-06-26 08:53 UTC, vspecky commented on crates/router/src/core/pm_auth.rs
> +            return Err((ApiErrorResponse::InvalidRequestData {
This is more of a `PreconditionFailed` error. We're not reading any request fields.

2024-06-26 08:54 UTC, vspecky requested changes

2024-06-26 08:54 UTC, vspecky commented on crates/router/src/core/pm_auth.rs
> +                    "Payment amount is greater than the available amount in selected bank account"
Also lets simplify the error message to something along the lines of `"... insufficient balance ..."`

2024-07-03 09:13 UTC, vspecky approved these changes

2024-07-03 09:46 UTC, Chethan-rao commented on crates/router/src/core/pm_auth.rs
> +        .attach_printable("Corresponding pm_auth_key does not exist in redis")?
This should be `InternalServerError` as the first error propagation is due to redis error. If the bool is `false` then it should be 4xx.

Can be taken in the next PR.

2024-07-03 13:03 UTC, merged