feat: add an API to transfer encryption keys
juspay/hyperswitch pull request #5071
Opened 2024-06-21 08:59 UTC by dracarys18

## Type of Change

- [x] New feature

## Description

Add an API to transfer all MerchantKeyStore keys to KeyManager

## Motivation and Context

This is for moving all the Encryption Keys which are currently in the MerchantKeyStore table to move to New Encryption KeyManager

## How did you test it?

- Do an API call on the application to `accounts/transfer`
```bash
curl --location 'http://localhost:8080/accounts/transfer' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: test_admin' 
```
It should give response of 200 with number of keys moved
```bash
{
    "total_transferred": 16
}
```
## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code

2024-07-04 10:23 UTC, ArjunKarthik requested changes
Please add migration API for user_store as well

2024-07-04 10:23 UTC, ArjunKarthik commented on crates/router/src/core/errors.rs
> +pub enum KeyManagerClientError {
KeyManagerError & KeyManagerError enums are not required, since they are created already in common_utils

2024-07-04 10:23 UTC, ArjunKarthik commented on crates/common_utils/src/errors.rs
> +    #[error("Internal Server Error Receied {0:?}")]
Spell check

2024-07-04 10:23 UTC, ArjunKarthik commented on crates/common_utils/src/keymanager.rs
> +/// Get keymanager client cosntructed from the url and state
spell check

2024-07-04 13:45 UTC, ArjunKarthik approved these changes

2024-07-05 10:42 UTC, ArjunKarthik commented on crates/router/src/core/user.rs
> +pub async fn transfer_user_key_strore_keymanager(
spell check

2024-07-05 10:42 UTC, ArjunKarthik commented on crates/router/src/routes/user.rs
> +        |state, _, _, _| user_core::transfer_user_key_strore_keymanager(state),
spell check

2024-07-05 12:35 UTC, ThisIsMani approved these changes

2024-07-08 09:08 UTC, merged