refactor(router): changed payment method token TTL to api contract based config from const value
juspay/hyperswitch pull request #5115
Opened 2024-06-25 10:33 UTC by sahkal

## Type of Change

- [x] Bugfix
- [x] New feature

## Description

Currently the payment method token TLL calculation was done based on `const::TOKEN_TTL - payment_intent.created_at`

where TOKEN_TTL was 15mins, but as we have a new contract called `session_expiry` we can make our payment live for longer time constraint than just 15mins,

due to this, the value `const::TOKEN_TTL - payment_intent.created_at` might go negative if the payment is done after 15mins. Which causes negative value at redis.

To solve, This problem we have used `intent_fulfillment_time` in business profile which is set by the merchant. 

max value of `intent_fulfillment_time` can be 30mins and min can be 1min

## How did you test it?

[Scenario 1] : Create a new business account
Create a merchant -> Create business profile with intent_fulfillment_time as 60s -> do payment connector step -> Create api key -> 

Business Create
```shell
curl --location 'http://localhost:8080/account/merchant_1719312571/business_profile' \
--header 'Content-Type: application/json' \
--header 'api-key: test_admin' \
--data '{
  "profile_name": "fooddqw",
  "intent_fulfillment_time":60
}'
```

Do payment create with payment link

```shell
curl --location 'http://localhost:8080/payments' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: dev_Ccb0N9Nd43rBhCANbXit86h820vVpcXkexpgbAw5efxjwiUC6UYiTeOtW446kkpa' \
--data-raw '
{
    "amount": 250,
    "currency": "USD",
    "payment_link":true,
    "profile_id": "pro_D1CA5xM3jTuo1r0XHp9e",
    "amount_to_capture": 250,
    "capture_method": "automatic",
    "capture_on": "2022-09-10T10:11:12Z",
    "customer_id": "StripeCustomer123",
    "email": "abcdef123@gmail.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "description": "Please Pay for your XYZ",
    "authentication_type": "no_three_ds",
    "return_url": "https://google.com",
    "setup_future_usage": "off_session",
    "browser_info": {
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36",
        "accept_header": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "language": "nl-NL",
        "color_depth": 24,
        "screen_height": 723,
        "screen_width": 1536,
        "time_zone": 0,
        "java_enabled": true,
        "java_script_enabled": true,
        "ip_address": "127.0.0.1"
    },
    "routing": {
        "type": "single",
        "data": "nmi"
    },
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    "metadata": {
        "udf1": "value1",
        "new_customer": "true",
        "login_date": "2019-09-10T10:11:12Z"
    },
    "payment_link_config":{
        "enabled_saved_payment_method":true
      }}
    
'
```

Do the payment after 60 seconds it should fail, with log as 
<img width="1215" alt="Screenshot 2024-06-25 at 4 35 39 PM" src="https://github.com/juspay/hyperswitch/assets/26082680/6bf233e1-f166-429e-b3c6-f895a50ef0c5">

![Screenshot 2024-06-25 at 4 35 51 PM](https://github.com/juspay/hyperswitch/assets/26082680/f35e22b3-be38-4650-b2b5-6681d1fce49a)

[Scenario 2] : Update business account

Now Do update business profile

```
curl --location 'http://localhost:8080/account/merchant_1719312571/business_profile/pro_D1CA5xM3jTuo1r0XHp9e' \
--header 'Content-Type: application/json' \
--header 'api-key: test_admin' \
--data '{
  "intent_fulfillment_time":900
}'
```

Now do payment link create

```shell
curl --location 'http://localhost:8080/payments' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: dev_Ccb0N9Nd43rBhCANbXit86h820vVpcXkexpgbAw5efxjwiUC6UYiTeOtW446kkpa' \
--data-raw '
{
    "amount": 250,
    "currency": "USD",
    "payment_link":true,
    "profile_id": "pro_D1CA5xM3jTuo1r0XHp9e",
    "amount_to_capture": 250,
    "capture_method": "automatic",
    "capture_on": "2022-09-10T10:11:12Z",
    "customer_id": "StripeCustomer123",
    "email": "abcdef123@gmail.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "description": "Please Pay for your XYZ",
    "authentication_type": "no_three_ds",
    "return_url": "https://google.com",
    "setup_future_usage": "off_session",
    "browser_info": {
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36",
        "accept_header": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "language": "nl-NL",
        "color_depth": 24,
        "screen_height": 723,
        "screen_width": 1536,
        "time_zone": 0,
        "java_enabled": true,
        "java_script_enabled": true,
        "ip_address": "127.0.0.1"
    },
    "routing": {
        "type": "single",
        "data": "nmi"
    },
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    "metadata": {
        "udf1": "value1",
        "new_customer": "true",
        "login_date": "2019-09-10T10:11:12Z"
    },
    "payment_link_config":{
        "enabled_saved_payment_method":true
      }}
'
```
Now do`Pay now` after 3mins, it should pass
![Screenshot 2024-06-25 at 4 42 10 PM](https://github.com/juspay/hyperswitch/assets/26082680/9069b7f6-ecbc-46f6-88d7-192b8d05a064)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-06-26 09:12 UTC, jarnura requested changes

2024-06-26 09:12 UTC, jarnura commented on crates/router/src/core/payment_methods/cards.rs
> +            crate::core::utils::get_profile_id_from_business_details(
```suggestion
            core::utils::get_profile_id_from_business_details(
```

2024-06-27 09:55 UTC, jarnura approved these changes

2024-06-27 10:32 UTC, Narayanbhat166 commented on crates/router/src/core/payments/helpers.rs
> +    let business_profile = core_utils::validate_and_get_business_profile(
you can pass business profile value from parents

2024-06-27 12:50 UTC, Narayanbhat166 approved these changes

2024-06-27 12:50 UTC, Narayanbhat166 commented on crates/router/src/core/payments/helpers.rs
> +            message: "intent_fulfillment_time should be between 60(1 min) to 1800(30 mins)."
why is this value hard coded?

2024-06-27 16:17 UTC, Chethan-rao approved these changes

2024-07-02 08:35 UTC, merged