Fix(router): [CYBS] make status optional
juspay/hyperswitch pull request #5165
Opened 2024-06-28 14:27 UTC by AkshayaFoiger

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

In the confirm call response sometimes doesn't contain `status` field. This PR handles such cases and marks the payment as pending.

## How did you test it?

Sanity
1. Do a confirm call

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-01 07:25 UTC, deepanshu-iiitu requested changes

2024-07-01 07:25 UTC, deepanshu-iiitu commented on crates/router/src/connector/cybersource/transformers.rs
> +                        .map_or(CybersourcePaymentStatus::StatusNotReceived, |status| status),
Use `unwrap_or` instead of `map_or`

2024-07-01 07:25 UTC, deepanshu-iiitu commented on crates/router/src/connector/cybersource/transformers.rs
> +                        .map_or(CybersourcePaymentStatus::StatusNotReceived, |status| status),
Use `unwrap_or` instead of `map_or`

2024-07-01 07:25 UTC, deepanshu-iiitu commented on crates/router/src/connector/cybersource/transformers.rs
> +                        .map_or(CybersourcePaymentStatus::StatusNotReceived, |status| status),
Use `unwrap_or` instead of `map_or`

2024-07-01 07:25 UTC, deepanshu-iiitu commented on crates/router/src/connector/cybersource/transformers.rs
> +                        .map_or(CybersourcePaymentStatus::StatusNotReceived, |status| status),
Use `unwrap_or` instead of `map_or`

2024-07-01 07:25 UTC, deepanshu-iiitu commented on crates/router/src/connector/cybersource/transformers.rs
> +                        .map_or(CybersourcePaymentStatus::StatusNotReceived, |status| status),
Use `unwrap_or` instead of `map_or`

2024-07-02 08:26 UTC, SamraatBansal approved these changes

2024-07-02 09:20 UTC, deepanshu-iiitu approved these changes

2024-07-02 11:58 UTC, merged