feat: add a kv switch route for merchants
juspay/hyperswitch pull request #518
Opened 2023-02-07 13:03 UTC by NishantJoshi00

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

This PR will add 2 extra routes providing a way to change the storage schema of a merchant with AdminApiKey

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
<img width="827" alt="Screenshot 2023-02-07 at 6 27 02 PM" src="https://user-images.githubusercontent.com/51093026/217250973-03309586-8e8a-4705-b007-6a36b01bfb5f.png">
<img width="527" alt="Screenshot 2023-02-07 at 6 29 32 PM" src="https://user-images.githubusercontent.com/51093026/217251545-8fd441ce-1cef-4009-ac3c-5b38d4b50034.png">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-02-07 13:06 UTC, jarnura approved these changes

2023-02-07 14:27 UTC, SanchithHegde requested changes

2023-02-07 14:27 UTC, SanchithHegde commented on crates/router/src/core/admin.rs
> +            .attach_printable("failed to switch merchant_storage_schema")
```suggestion
            .attach_printable("failed to switch merchant_storage_scheme")
```

2023-02-07 14:27 UTC, SanchithHegde commented on crates/storage_models/src/merchant_account.rs
> +    },
```suggestion
    StorageSchemeUpdate {
        storage_scheme: storage_enums::MerchantStorageScheme,
    },
```

2023-02-08 08:53 UTC, jarnura submitted a review, later dismissed

2023-02-08 09:51 UTC, SanchithHegde approved these changes

2023-02-08 09:51 UTC, dracarys18 approved these changes
LGTM

2023-02-08 09:51 UTC, dracarys18 commented on crates/router/src/core/admin.rs
> +    };
```suggestion
    let kv_status = matches!(updated_merchant_account.storage_scheme, enums::MerchantStorageScheme::RedisKv);
```

2023-02-09 13:47 UTC, jarnura approved these changes

2023-02-09 13:48 UTC, merged