Razorpay
juspay/hyperswitch pull request #5200
Opened 2024-07-04 09:28 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-08 08:08 UTC, SamraatBansal requested changes

2024-07-09 05:18 UTC, SamraatBansal approved these changes

2024-07-09 11:24 UTC, SamraatBansal approved these changes

2024-07-09 11:43 UTC, sai-harsha-vardhan submitted a review, later dismissed
Core changes LGTM

2024-07-09 12:00 UTC, SanchithHegde approved these changes

2024-07-09 12:00 UTC, SanchithHegde commented on crates/router/src/connector/razorpay/transformers.rs
> +    rng.gen_range(100000000000..=999999999999)
```suggestion
    rng.gen_range(100_000_000_000..=999_999_999_999)
```

2024-07-09 12:00 UTC, SanchithHegde commented on crates/router/src/connector/razorpay/transformers.rs
> +            Secret::new("9490419802@ybl".to_string());
Why is this hard-coded?

2024-07-09 12:51 UTC, SanchithHegde approved these changes

2024-07-09 13:16 UTC, sai-harsha-vardhan approved these changes

2024-07-09 13:18 UTC, SamraatBansal approved these changes

2024-07-09 14:54 UTC, merged

2024-07-22 01:54 UTC, kushwahashiv commented
@swangi-kumari  can you please provide me link to sample app which is consuming hyperswitch + UPI ? if it does not exist can you please point me to the doc which I can refer.

Thanks