fix(core): use guard for access token result
juspay/hyperswitch pull request #522
Opened 2023-02-08 07:15 UTC by Narayanbhat166

## Type of Change

- [x] Bugfix

## Description

Klarna redirect payments were failing because of default error that was present in router data, which was populated by access token result.

## Motivation and Context

## How did you test it?

- Create payment
![Screenshot 2023-02-08 at 12 44 21 PM](https://user-images.githubusercontent.com/48803246/217459987-6d111dc4-e8d8-493f-88c6-1a9d153117fd.png)
- Successful redirection
![Screenshot 2023-02-08 at 12 44 36 PM](https://user-images.githubusercontent.com/48803246/217460052-db0359d3-efb4-4576-920a-3e88ca83ad7f.png)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-02-08 07:17 UTC, NishantJoshi00 requested changes

2023-02-08 07:17 UTC, NishantJoshi00 commented on crates/router/src/core/payments.rs
> +    if add_access_token_result.connector_supports_access_token {
can we make this into a function, we have the same pattern in 3 different places, will this guard be required in those other places?

2023-02-08 10:01 UTC, NishantJoshi00 submitted a review, later dismissed
LGTM

2023-02-09 08:24 UTC, jarnura requested changes

2023-02-09 08:24 UTC, jarnura commented on crates/router/src/core/payments/access_token.rs
> +    if add_access_token_result.connector_supports_access_token {
Add actual predicate for the issue

2023-02-10 08:19 UTC, jarnura approved these changes

2023-02-10 08:37 UTC, NishantJoshi00 approved these changes

2023-02-10 08:53 UTC, merged