Add a base struct for api error responses
juspay/hyperswitch pull request #524
Opened 2023-02-09 07:53 UTC by lsampras

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description
- Have added a base struct for Error responses 
- Adding the ErrorSwitch/ReportSwitch trait allowing for easy error propagation
- Adding basic implementations & utility functions for the base struct

Will be creating further PR's for implementing the traits & using the actual Errors

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Currently we use ApiErrorResponse as the default error response,
This does not have much modularity as each enum variant corresponds to a concrete error type (requiring all modifications to extend the enum and changes not being localized)

Also there isn't a fixed structure hierarchy/order to the error types yet, where we can miss the origins/flow of a particular error

We can use structs to add this constraints 
for e.g PaymentCore functions should only return PaymentErrors (which will be converted to APIErrorResponse)
and something like `AddressNotFoundError` can't be directly converted to `ApiErrorResponse` but needs to follow the flow `AddressNotFoundError` -> `DBError` -> `StorageError` -> `Payment/Customer Error` -> `ApiErrorResponse` maintaining the origin information in error logs

Attaching the current error propogation graph
![Error state_ propogation diagrams(2)](https://user-images.githubusercontent.com/21202349/217749817-1631e3bc-ed1e-4c23-a90d-0a45fe0367c0.svg)

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I addressed lints thrown by `cargo hack`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-02-09 13:44 UTC, jarnura requested changes

2023-02-09 13:44 UTC, jarnura approved these changes
Other than comments code looks good to me.

2023-02-10 09:32 UTC, SanchithHegde approved these changes

2023-02-10 14:12 UTC, jarnura approved these changes

2023-02-10 14:33 UTC, merged