fix: don't call connector if connector transaction id doesn't exist
juspay/hyperswitch pull request #525
Opened 2023-02-09 08:49 UTC by NishantJoshi00

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
In the case where we do not have the connector transaction id of a connector force_sync should not fail, rather we need it not to call the connector it this case.

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-02-09 13:50 UTC, jarnura requested changes

2023-02-09 13:50 UTC, jarnura commented on crates/router/src/core/payments/helpers.rs
> +pub fn can_call_connector(
change the function. This means this condition can be used everywhere

2023-02-15 08:58 UTC, jarnura approved these changes

2023-02-15 10:06 UTC, Narayanbhat166 commented
With the `force_sync` condition set to true, the merchant or the caller expects to always get the response from connector. How is setting `force_sync` to `true` and also adding our own validation help here? This fact is being hidden from the caller of the api. There is no way to know whether the status is synced or we have the stale status. If we are deciding whether to call the connector or not, then why are we asking the merchant or caller to set that field?

2023-02-15 10:06 UTC, Narayanbhat166 approved these changes

2023-02-15 10:22 UTC, merged