feat: api contract for bank redirect
juspay/hyperswitch pull request #528
Opened 2023-02-09 10:37 UTC by Sangamesh26

## Type of Change

- [x] New feature

## Description

Api contract for the bank redirect.

For EPS:
“payment_method”: “bank_redirect”
  "payment_method_data":{
      "bank_redirect"{
        "eps"{
          "billing_details"{
              "billing_name": "John Wick"
           }
        }        
      }
  }

For giropay:
payment_method”: “bank_redirect”
  "payment_method_data":{
      "bank_redirect"{
        "giropay"{
          "billing_details"{
              "billing_name": "John Wick"
           }
        }        
      }
  },

For iDEAL:
  “payment_method”: “bank_redirect”
  "payment_method_data":{
      "bank_redirect"{
        "ideal"{
          "billing_details"{
              "billing_name": "John Wick"
           }
        }        
      }
  },

For Sofort:
  “payment_method”: “bank_redirect”
  "payment_method_data":{
      "bank_redirect"{
        "sofort"{
          "billing_details"{
              "billing_country": "DE"
           },
           "preferred_language": "en"
        }        
      }
  },

## Motivation and Context

Api contract for bank redirects

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-02-09 13:56 UTC, jarnura requested changes

2023-02-09 13:56 UTC, jarnura commented on migrations/2023-02-09-093400_add_bank_redirect/up.sql
> +ALTER TYPE "PaymentMethodType" ADD VALUE 'bank_redirect' after 'paypal';
change from TYPE to VARCHAR in database and handle as Enum in Application.

2023-02-09 15:57 UTC, Narayanbhat166 commented
The json posted is not formatted, use code json code blocks

2023-02-26 13:17 UTC, closed without merging

2023-02-26 13:18 UTC, Sangamesh26 commented
Closed this PR, as #529  has all the changed of this PR