refactor(core) : customer v2 refactor for customer create end point
juspay/hyperswitch pull request #5350
Opened 2024-07-17 12:13 UTC by sahkal

## Type of Change

- [x] Refactoring

## Description

 customer v2 refactor for customer create end point

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-22 11:50 UTC, jarnura requested changes

2024-07-22 11:50 UTC, jarnura commented on crates/router/src/core/customers.rs
> +    merchant_ref_id_customer_struct
```suggestion
    merchant_reference_id_customer
```

2024-07-22 11:51 UTC, jarnura submitted a review, later dismissed

2024-07-22 11:52 UTC, jarnura submitted a review, later dismissed

2024-07-22 12:06 UTC, lsampras requested changes
rest looks good

2024-07-22 12:06 UTC, lsampras commented on crates/api_models/src/events/customer.rs
> +            customer_id: self.get_merchant_reference_id().clone(),
For now lets keep the customer_id as mandatory,
in places where we don't have a customer id we can just not log the event for now by returning a `None`

```rust
impl ApiEventMetric for CustomerResponse {
    fn get_api_event_type(&self) -> Option<ApiEventsType> {
        self.get_merchant_reference_id().clone().map(|cid| 
            ApiEventsType::Customer { customer_id: cid } 
        )
    }
}
```

2024-07-22 12:06 UTC, lsampras commented on crates/common_utils/src/events.rs
> +        customer_id: Option<id_type::CustomerId>,
lets keep this mandatory

2024-07-22 13:07 UTC, lsampras submitted a review, later dismissed

2024-07-23 06:49 UTC, lsampras approved these changes

2024-07-23 07:35 UTC, jarnura approved these changes

2024-07-23 08:03 UTC, merged