feat: create additional columns in organization table
juspay/hyperswitch pull request #5380
Opened 2024-07-19 14:06 UTC by hrithikesh026

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Added additional columns in `organization` table and added support for updating the values through `/organization` route

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Manual
1. create an organization

2. Retrieve the organization

3. Update the organization

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-23 16:05 UTC, jarnura requested changes

2024-07-24 11:14 UTC, jarnura approved these changes

2024-07-24 11:51 UTC, ThisIsMani approved these changes
Dashboard specific changes looks fine.

2024-07-24 13:21 UTC, SanchithHegde approved these changes

2024-07-24 14:44 UTC, merged