fix(pm_auth): Added mca status check in pml
juspay/hyperswitch pull request #5421
Opened 2024-07-23 14:01 UTC by Sarthak1799

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Added a check in mca for pm_auth_connectors to include only the active ones.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-24 11:22 UTC, Chethan-rao requested changes

2024-07-24 11:22 UTC, Chethan-rao commented on crates/router/src/core/payment_methods/cards.rs
> +                        {
First check the `inner_config.payment_method_type == *payment_method_type` before db call, if true only then do the db call

2024-07-25 08:31 UTC, Chethan-rao approved these changes

2024-07-26 10:39 UTC, vspecky requested changes

2024-07-26 10:39 UTC, vspecky commented on crates/router/src/core/payment_methods/cards.rs
> +                            )
Aren't we already fetching all the profile MCAs earlier in this function? Just check and reuse those objects instead of calling the DB again

2024-08-02 10:41 UTC, vspecky approved these changes

2024-08-02 11:15 UTC, Chethan-rao approved these changes

2024-08-02 13:52 UTC, merged