Hackathon klados l3
juspay/hyperswitch pull request #545
Opened 2023-02-11 16:47 UTC by khuzema786

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Added support for [intuit](https://developer.intuit.com/app/developer/qbpayments/docs/api/resources/all-entities/charges) payment gateway
Payment Method: card
Supported payment flows

[Authorize](https://developer.intuit.com/app/developer/qbpayments/docs/api/resources/all-entities/charges#create-a-charge)
[Capture](https://developer.intuit.com/app/developer/qbpayments/docs/api/resources/all-entities/charges#capture-a-charge)
[PSync](https://developer.intuit.com/app/developer/qbpayments/docs/api/resources/all-entities/charges#get-details-about-a-charge)
[Cancel](https://developer.intuit.com/app/developer/qbpayments/docs/api/resources/all-entities/charges#void-a-charge)

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-02-11 21:29 UTC, Narayanbhat166 commented on crates/router/src/connector/intuit.rs
> +        let req_obj = intuit::IntuitRefundRequest::try_from(req).unwrap();
remove unwrap. Handle this by raising an appropriate ConnectorError

2023-02-11 21:34 UTC, Narayanbhat166 requested changes
Handle unwraps by raising appropriate errors, format the code. Other than that LGTM.

2023-02-11 21:34 UTC, Narayanbhat166 commented on crates/router/src/connector/intuit.rs
> +        self.build_error_response(res)
Implement error handling

2023-02-11 21:34 UTC, Narayanbhat166 commented on crates/router/tests/connectors/sample_auth.toml
> +api_key = "Bearer eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..CpUhfKgGSXWxwg-M10E8qg.vv7ff2p9u0hRznjbaSTfpnEQchnquLcW07vQnov-IPyeYUUesLRcKMj7NJaEB_bc6bLkm968VdRmaia6T9NVQGkkIiIVFlB0_FiA3TYxwM-Ni
Do not commit sensitive information, please ensure that this api key is revoked

2023-02-14 11:28 UTC, jagan-jaya requested changes

2023-02-14 11:28 UTC, jagan-jaya commented on crates/api_models/src/enums.rs
> +	Intuit,
Pls format the document with ```cargo clippy --all-features --all-targets && cargo +nightly fmt --all```

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/src/configs/settings.rs
> +	pub intuit: ConnectorParams,
Pls format the document with ```cargo clippy --all-features --all-targets && cargo +nightly fmt --all```

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/src/connector/intuit.rs
> +        }
move this block to `build_error_response ` 
```suggestion
```

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/src/connector/intuit.rs
> +        self.build_error_response(res)
```suggestion
        self.build_error_response(res)
```

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/src/connector/intuit.rs
> +        self.build_error_response(res)
```suggestion
        self.build_error_response(res)
```

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/src/connector/intuit.rs
> +        self.build_error_response(res)
```suggestion
        self.build_error_response(res)
```

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/src/connector/intuit.rs
> +        self.build_error_response(res)
```suggestion
        self.build_error_response(res)
```

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/src/connector/intuit.rs
> +        self.build_error_response(res)
```suggestion
        self.build_error_response(res)
```

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/src/services/api.rs
> +                    println!("intuit response ---->> {:?}", response);
remove this println

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/src/types/api.rs
> +            "intuit" => Ok(Box::new(&connector::Intuit)),
format the code with 'clippy' and fix clippy warnings

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/connector_auth.rs
> +            &std::fs::read_to_string("tests/connectors/sample_auth.toml")
undo this change

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/intuit.rs
> +        response.response.is_err(),
pls add proper error message in case of an error

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/intuit.rs
> +        response.response.is_err(),
pls add proper error message in case of an error

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/intuit.rs
> +        response.response.is_err(),
pls add proper error message in case of an error

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/intuit.rs
> +        response.response.is_err(),
pls add proper error message in case of an error

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/intuit.rs
> +        response.response.is_err(),
pls add proper error message in case of an error

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/intuit.rs
> +        capture_response.response.is_err(),
pls add proper error message in case of an error

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/intuit.rs
> +        response.response.is_err(),
pls add proper error message in case of an error

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/intuit.rs
> +// [#478]: add unit tests for non 3DS, wallets & webhooks in connector tests
remove these comments

2023-02-14 11:28 UTC, jagan-jaya commented on crates/router/tests/connectors/utils.rs
> +        tokio::time::sleep(Duration::from_secs(10)).await; // to avoid 404 error
undo this change

2023-02-15 09:01 UTC, jagan-jaya approved these changes

2023-02-15 11:35 UTC, Narayanbhat166 submitted a review, later dismissed

2023-02-16 07:18 UTC, ArjunKarthik commented on crates/router/src/connector/intuit/transformers.rs
> +                        number: ccard.card_number.peek().clone(),
Don't peek the secret strings, Make the fields in the `IntuitPaymentsRequest ` as secret wherever necessary

2023-02-16 07:20 UTC, ArjunKarthik commented on crates/router/src/connector/intuit/transformers.rs
> +                    currency: item.request.currency.to_string().to_uppercase(),
Currency is an ENUM and is in UPPERCASE only, No need to call `to_uppercase`

2023-02-16 07:22 UTC, ArjunKarthik commented on crates/router/src/connector/intuit/transformers.rs
> +            IntuitPaymentStatus::Declined => Self::VoidFailed,
I hope this `Declined ` should be mapped to "AuthenticationFailed"

2023-02-16 07:23 UTC, ArjunKarthik commented on crates/router/src/connector/intuit/transformers.rs
> +            IntuitPaymentStatus::Refunded => Self::AutoRefunded,
Is it possible to get "Refunded" at the time of create payment?

2023-02-16 07:25 UTC, ArjunKarthik commented on crates/router/src/connector/intuit.rs
> +            "intuit payment authorize response ---------- {:?}",
Change this

2023-04-20 05:10 UTC, jagan-jaya commented
@khuzema786 Thanks for your contribution, Unfortunately we couldn't proceed with this PR as it is a duplicate of #659. 
Closing in favour of #659

2023-04-20 05:10 UTC, closed without merging