refactor(router): domain and diesel model changes for merchant_connector_account v2 flow
juspay/hyperswitch pull request #5462
Opened 2024-07-28 08:57 UTC by sai-harsha-vardhan

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

domain and diesel model changes for merchant_connector_account v2 flow

### Additional Changes

- [ ] This PR modifies the API contract
- [x] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Tested manually
Sanity MCA Create and subsequent flows like payment / capture / refund with v1 version

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-07-30 13:50 UTC, jarnura requested changes

2024-07-30 13:50 UTC, jarnura commented on crates/diesel_models/src/merchant_connector_account.rs
> +    pub payment_methods_enabled: Option<Vec<serde_json::Value>>,
```suggestion
    pub payment_methods_enabled: Option<Vec<pii::SecretSerdeValue>>,
```

2024-07-30 13:50 UTC, jarnura commented on crates/diesel_models/src/merchant_connector_account.rs
> +    pub frm_configs: Option<Secret<serde_json::Value>>,
```suggestion
    pub frm_configs: Option<Secret<pii::SecretSerdeValue>>,
```

2024-07-30 13:50 UTC, jarnura commented on crates/diesel_models/src/merchant_connector_account.rs
> +    pub frm_config: Option<Vec<Secret<serde_json::Value>>>,
```suggestion
    pub frm_config: Option<Vec<Secret<pii::SecretSerdeValue>>>,
```

2024-07-30 13:50 UTC, jarnura commented on crates/diesel_models/src/merchant_connector_account.rs
> +    pub frm_config: Option<Vec<Secret<serde_json::Value>>>,
There are two frm configs we should remove one which is deprecated.

2024-07-30 13:50 UTC, jarnura commented on crates/diesel_models/src/merchant_connector_account.rs
> +pub struct MerchantConnectorAccount {
connector_id is missing

2024-07-30 13:51 UTC, jarnura requested changes

2024-07-30 13:51 UTC, jarnura commented on crates/diesel_models/src/merchant_connector_account.rs
> +    pub frm_config: Option<Vec<Secret<serde_json::Value>>>,
Address all these in other related types too (like `MerchantConnectorAccountNew`, update types, update internal types)

2024-07-30 13:56 UTC, jarnura requested changes

2024-07-30 13:56 UTC, jarnura commented on crates/diesel_models/src/query/merchant_connector_account.rs
> +    pub async fn find_by_profile_id_connector_name(
we can deprecated this function and its usage, this related functionalities should be handled by id

2024-07-30 13:56 UTC, jarnura commented on crates/diesel_models/src/query/merchant_connector_account.rs
> +    pub async fn find_by_merchant_id_connector_name(
we can deprecated this function and its usage, this related functionalities should be handled by id

2024-07-30 13:59 UTC, jarnura requested changes

2024-07-30 13:59 UTC, jarnura commented on crates/router/src/core/admin.rs
> +        merchant_id: None,
This field should be deprecated, Merchant connector accounts merchant id we should not update.

2024-07-30 13:59 UTC, jarnura commented on crates/router/src/core/admin.rs
> +        connector_name: None,
This field should be deprecated, Merchant connector accounts connector name we should not update.

2024-08-01 06:37 UTC, jarnura requested changes

2024-08-01 06:37 UTC, jarnura commented on crates/diesel_models/src/query/merchant_connector_account.rs
> +    pub async fn find_by_merchant_id_connector(
This function also we can deprecate.

2024-08-01 07:39 UTC, jarnura approved these changes

2024-08-01 07:49 UTC, prajjwalkumar17 submitted a review, later dismissed

2024-08-01 08:40 UTC, ThisIsMani approved these changes
Dashboard specific changes looks fine.

2024-08-01 08:52 UTC, apoorvdixit88 approved these changes

2024-08-01 11:25 UTC, jarnura approved these changes

2024-08-01 11:27 UTC, prajjwalkumar17 approved these changes

2024-08-01 11:29 UTC, apoorvdixit88 approved these changes

2024-08-01 12:21 UTC, merged