feat:H1234-L3 - Refund and sync for Bambora
juspay/hyperswitch pull request #550
Opened 2023-02-11 18:44 UTC by hey-ritikgupta

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-02-11 20:58 UTC, jarnura reviewed
Refund related flows are in to-do's, complete the to-do's

2023-02-11 21:27 UTC, hey-ritikgupta commented
> Refund related flows are in to-do's, complete the to-do's

Done

2023-02-14 11:41 UTC, jagan-jaya requested changes

2023-02-14 11:41 UTC, jagan-jaya commented on crates/router/src/connector/bambora.rs
> +    // }
```suggestion
```
remove this commented block

2023-02-14 11:41 UTC, jagan-jaya commented on crates/router/src/connector/bambora/transformers.rs
> +            _ => todo!(),
throw proper error message as mentioned in previous PR

2023-02-14 11:41 UTC, jagan-jaya commented on crates/router/src/connector/bambora/transformers.rs
> +            _ => todo!(),
throw proper error message as mentioned in previous PR

2023-02-14 11:41 UTC, jagan-jaya commented on crates/router/tests/connectors/bambora.rs
> +// [#478]: add unit tests for non 3DS, wallets & webhooks in connector tests
remove above comments

2023-02-20 08:36 UTC, ArjunKarthik commented
Thanks for the contribution @hey-ritikgupta , We are merging the changes from different participant as it has more flows implemented. You can still continue your contributions on the [open issues](https://github.com/juspay/hyperswitch/issues?q=is%3Aissue+is%3Aopen+label%3AA-connector-integration).

2023-02-20 08:36 UTC, closed without merging