feat(core): [Payment Link] add dynamic merchant fields
juspay/hyperswitch pull request #5512
Opened 2024-08-02 07:30 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Merchant can send fields in the request which can be shown in the payment link during its rendering. The values should be key value pair and atmost 5 fields can be displayed dynamically.

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-08-06 16:08 UTC, sahkal commented on crates/router/src/core/payment_link.rs
> +        (merchant_details, IndexMap::new())
Why are we sending `IndexMap::new()` i suppose we have defined a const for it in the consts file.

2024-08-06 16:11 UTC, sahkal reviewed
Can you please add a video or screenshot depicting your changes, since this has major FE play.

2024-08-06 16:13 UTC, sahkal commented on crates/router/src/core/payment_link.rs
>      };
What is scope of this field is this transactional data, if yes then it should only be in paymentscreate payment link config. And if that is the case then we donot need this field to go through priority macro

2024-08-07 11:00 UTC, sahkal commented on crates/router/src/core/payment_link.rs
> +                })
can we also, add a error log for it!

2024-08-07 11:01 UTC, sahkal approved these changes

2024-08-07 11:28 UTC, sahkal submitted a review, later dismissed

2024-08-08 08:19 UTC, sahkal submitted a review, later dismissed

2024-08-08 08:28 UTC, jarnura requested changes

2024-08-08 08:28 UTC, jarnura commented on crates/router/src/core/payment_link.rs
> +                        Err(_) => {
Don't skip the errors, log the error

2024-08-08 09:40 UTC, jarnura approved these changes

2024-08-08 10:04 UTC, Sakilmostak commented on crates/router/src/types/transformers.rs
> +            transaction_details: None,
transaction_details will only be picked from payments create. It won't be coming from business profile level thus it is kept as none here

2024-08-08 10:11 UTC, SanchithHegde approved these changes

2024-08-08 14:43 UTC, merged