feat(customer_v2): add route for customer retrieve v2
juspay/hyperswitch pull request #5516
Opened 2024-08-02 16:24 UTC by sahkal

## Type of Change

- [x] New feature

## Description

add route for customer retrieve v2 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-08-05 07:26 UTC, jarnura requested changes

2024-08-05 07:26 UTC, jarnura commented on crates/api_models/src/customers.rs
> +    pub fn new_global_id_struct(id: String) -> Self {
```suggestion
    pub fn new(id: String) -> Self {
```

2024-08-07 04:21 UTC, jarnura approved these changes

2024-08-17 07:18 UTC, jarnura requested changes

2024-08-17 07:18 UTC, jarnura commented on crates/router/src/db/customers.rs
> +        #[cfg(all(any(feature = "v1", feature = "v2"), not(feature = "customer_v2")))]
```suggestion

```

2024-08-17 07:18 UTC, jarnura commented on crates/router/src/db/customers.rs
>          #[cfg(all(feature = "v2", feature = "customer_v2"))]
```suggestion

```

2024-08-21 09:27 UTC, jarnura approved these changes

2024-08-22 11:01 UTC, ShivanshMathurJuspay approved these changes

2024-08-22 13:05 UTC, ShivanshMathurJuspay approved these changes

2024-08-22 13:24 UTC, jarnura approved these changes

2024-08-22 15:19 UTC, merged