refactor(business_profile): wrap some JSON fields within `Secret`
juspay/hyperswitch pull request #5531
Opened 2024-08-05 21:47 UTC by SanchithHegde

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR involves wrapping the `webhook_details`, `payment_link_config` and `payout_link_config` fields in the business profile v1 domain and diesel models within `Secret`. As part of this change, the `webhook_details` within the merchant account domain and diesel models had to be wrapped within a `Secret` as well. 

In addition, it was determined that the `authentication_connector_details` field does not contain sensitive information, so the `Secret` wrapper around it has been removed in the business profile v2 domain and diesel models.

## Motivation and Context

This serves two purposes, to prevent sensitive information from possibly being logged, and to reduce the overall number of changes involved in the migration towards business profile v2 APIs.

## How did you test it?

Sanity testing with Postman, ensuring that nothing around the merchant account or business profile APIs is broken.

In addition, I've confirmed from the logs that the affected fields (for example, `webhook_details`) are not being logged in plaintext in `INSERT` / `UPDATE` database queries.

Screenshot of `webhook_details` being masked during business profile insert operation:

![Screenshot of `webhook_details` being masked](https://github.com/user-attachments/assets/25454fae-4924-4a53-86b2-788d9926b52e)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-08-06 07:34 UTC, Narayanbhat166 submitted a review, later dismissed

2024-08-06 08:03 UTC, jarnura requested changes

2024-08-06 08:03 UTC, jarnura commented on crates/hyperswitch_domain_models/src/business_profile.rs
> +    pub authentication_connector_details: Option<serde_json::Value>,
move back to `pii::SecretSerdeValue` or have the type.

2024-08-07 06:29 UTC, jarnura approved these changes

2024-08-07 07:39 UTC, Narayanbhat166 approved these changes

2024-08-07 08:51 UTC, merged