refactor(core): Adapt the usage of routing_algorithm_id in routing and payments core for v2
juspay/hyperswitch pull request #5533
Opened 2024-08-06 08:17 UTC by Aprabhat19

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
In this PR we adapt the usage of routing_algorithm_id as well as payout_routing_algorithm_id in routing and payments core for v2. 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-08-06 09:22 UTC, jarnura requested changes

2024-08-06 09:22 UTC, jarnura commented on crates/diesel_models/src/business_profile.rs
> +    pub frm_routing_algorithm: Option<serde_json::Value>,
remove this or make this into `frm_routing_algorithm_id`

2024-08-06 09:22 UTC, jarnura commented on crates/diesel_models/src/business_profile.rs
> +    pub frm_routing_algorithm: Option<serde_json::Value>,
remove this or make this into frm_routing_algorithm_id

2024-08-06 09:22 UTC, jarnura commented on crates/diesel_models/src/business_profile.rs
> +        frm_routing_algorithm: Option<serde_json::Value>,
remove this or make this into frm_routing_algorithm_id

2024-08-06 09:22 UTC, jarnura commented on crates/hyperswitch_domain_models/src/business_profile.rs
> +        frm_routing_algorithm: Option<serde_json::Value>,
remove this or make this into frm_routing_algorithm_id

2024-08-06 09:22 UTC, jarnura commented on crates/router/src/core/admin.rs
> +        .map(Secret::new);
Move this to impl based function approach

2024-08-06 09:22 UTC, jarnura commented on crates/router/src/core/admin.rs
> +        .map(Secret::new);
Below implementation which is not dependent others and just need to be parsed or convert to secret, follow impl based approach

2024-08-06 09:22 UTC, jarnura commented on crates/router/src/core/payments.rs
> +        #[allow(unused_variables)]
remove this and handle using underscore

2024-08-06 09:23 UTC, jarnura requested changes

2024-08-06 09:23 UTC, jarnura commented on crates/router/src/core/admin.rs
> +    let key_store = db
Merchant Key store is not required for v2 instead we should use the secret manager approach

2024-08-09 06:56 UTC, Narayanbhat166 commented on crates/router/src/types/api/admin.rs
> +            routing_algorithm: todo!(),
maybe add a short description as to what has to be done here and other places

2024-08-09 06:56 UTC, jarnura requested changes

2024-08-09 06:56 UTC, jarnura commented on crates/diesel_models/src/business_profile.rs
> +    pub intent_fulfillment_time: Option<i64>,
if the field already present in v1 don't change the order, lets keep the same field order

2024-08-09 07:02 UTC, Narayanbhat166 commented on crates/router/src/routes/app.rs
> +                    .service(web::resource("/routing_algorithm").route(web::get().to(
Do not call the function directly here, define a route in routes and then call that here

2024-08-09 07:07 UTC, jarnura requested changes

2024-08-09 07:07 UTC, jarnura commented on crates/router/src/core/admin.rs
> +    pub async fn update_business_profile_active_algorithm_id(
update_business_profile_and_invalidate_routing_config_for_active_algorithm_id_update

2024-08-09 07:07 UTC, jarnura commented on crates/router/src/core/payments.rs
> +    #[cfg(all(
get function based approach instead using a inline cfg's

2024-08-09 07:13 UTC, Narayanbhat166 commented on crates/router/src/routes/app.rs
> +    not(any(feature = "routing_v2", feature = "business_profile_v2"))
why is this any? This should be all

2024-08-09 07:17 UTC, jarnura commented on crates/router/src/core/routing.rs
>  pub async fn unlink_routing_config(
```suggestion
pub async fn unlink_routing_algorithm_from_profile(
```

2024-08-09 07:18 UTC, jarnura commented on crates/router/src/core/routing.rs
>      .get_required_value("BusinessProfile")?;
we can move the wrapper new function here

2024-08-12 04:27 UTC, jarnura submitted a review, later dismissed

2024-08-12 05:24 UTC, Narayanbhat166 approved these changes

2024-08-12 06:28 UTC, jarnura approved these changes

2024-08-12 07:59 UTC, lsampras approved these changes

2024-08-12 09:09 UTC, prajjwalkumar17 approved these changes

2024-08-12 09:55 UTC, merged