feat(users): add support for profile user delete
juspay/hyperswitch pull request #5541
Opened 2024-08-06 11:03 UTC by apoorvdixit88

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
- Add support to delete profile level users
- Delete is backward compatible
- Delete to support both V1 and V2 operations accordingly

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Closes [#5540](https://github.com/juspay/hyperswitch/issues/5540)

## How did you test it?
Use the curl to delete user role
```
curl --location --request DELETE 'http://localhost:8080/user/user/delete' \
--header 'Authorization: Bearer JWT' \
--header 'Content-Type: application/json' \
--data-raw '{
  "email": "email_to_delete"
}'
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-08-08 14:00 UTC, ThisIsMani reviewed
This might break when org level roles are updatable or deletable.

2024-08-12 08:48 UTC, apoorvdixit88 commented
> This might break when org level roles are updatable or deletable.

For V1 org_level roles are neither updatable nor deletable. With V2 it will work fine. Also we won't be introducing org_level roles in V1.

2024-08-12 11:05 UTC, racnan requested changes

2024-08-12 11:05 UTC, racnan commented on crates/router/src/core/user_role.rs
> +            .attach_printable("User is not associated with the merchant");
`500` is not handled.

2024-08-12 11:22 UTC, racnan commented on crates/router/src/utils/user_role.rs
> +}
https://doc.rust-lang.org/std/cmp/trait.Ord.html

2024-08-14 08:39 UTC, ThisIsMani reviewed
Please remove the old delete function.

2024-08-14 08:39 UTC, ThisIsMani commented on crates/router/src/core/user_role.rs
> +    if user_roles.is_empty() {
You can check if v2 roles are also empty.

2024-08-14 10:35 UTC, ThisIsMani approved these changes

2024-08-14 11:52 UTC, jarnura requested changes

2024-08-14 11:52 UTC, jarnura commented on crates/router/src/db/kafka_store.rs
> +        self.find_user_role_by_user_id_and_lineage(
```suggestion
        self.diesel_store.find_user_role_by_user_id_and_lineage(
```

2024-08-14 11:52 UTC, jarnura commented on crates/router/src/db/kafka_store.rs
> +        self.delete_user_role_by_user_id_and_lineage(
```suggestion
        self.diesel_store.delete_user_role_by_user_id_and_lineage(
```

2024-08-14 11:52 UTC, jarnura commented on crates/router/src/db/kafka_store.rs
> +        self.find_user_role_by_user_id_and_lineage(
In kakfaStore if we can self.functions will causes stack_overflow. So avoid following that.

2024-08-14 11:52 UTC, jarnura commented on crates/router/src/db/kafka_store.rs
> +        self.delete_user_role_by_user_id_and_lineage(
In kakfaStore if we can self.functions will causes stack_overflow. So avoid following that.

2024-08-14 12:24 UTC, jarnura approved these changes

2024-08-14 15:00 UTC, merged