feat: add test_mode for quickly testing payout links
juspay/hyperswitch pull request #5669
Opened 2024-08-22 11:01 UTC by kashif-m

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-08-23 13:51 UTC, SanchithHegde submitted a review, later dismissed

2024-08-26 09:08 UTC, jarnura requested changes

2024-08-26 09:08 UTC, jarnura commented on crates/api_models/src/admin.rs
> +    pub test_mode: Option<bool>,
```suggestion
    pub payout_test_mode: Option<bool>,
```

2024-08-26 09:08 UTC, jarnura commented on crates/diesel_models/src/business_profile.rs
> +    pub test_mode: Option<bool>,
```suggestion
    pub payout_test_mode: Option<bool>,
```

2024-08-26 10:03 UTC, jarnura approved these changes

2024-08-26 11:12 UTC, SanchithHegde approved these changes

2024-08-27 08:31 UTC, merged