feat(connector): [NOVALNET] Add template code
juspay/hyperswitch pull request #5670
Opened 2024-08-22 12:18 UTC by dg-212

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Template code added for new connector Novalnet
https://developer.novalnet.com/onlinepayments/api

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-08-22 12:25 UTC, deepanshu-iiitu requested changes

2024-08-22 12:25 UTC, deepanshu-iiitu commented on crates/api_models/src/enums.rs
> +	Novalnet,
Comment this line

2024-08-22 12:25 UTC, deepanshu-iiitu commented on crates/api_models/src/enums.rs
> +			| Self::Novalnet
Comment this line

2024-08-22 12:25 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/default_implementations.rs
> +	connectors::Novalnet,
Please maintain the alphabetical order in all places of this file.

2024-08-22 12:25 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/default_implementations_v2.rs
> +	connectors::Novalnet,
Please maintain the alphabetical order in all places of this file.

2024-08-22 12:25 UTC, deepanshu-iiitu commented on crates/router/src/core/admin.rs
> +            api_enums::Connector::Novalnet => todo!(),
Comment this line

2024-08-22 12:25 UTC, deepanshu-iiitu commented on crates/router/src/types/api.rs
> +                api_models::enums::Connector::Zsl => todo!(),
Remove this block

2024-08-23 06:38 UTC, deepanshu-iiitu requested changes

2024-08-23 06:38 UTC, deepanshu-iiitu commented on crates/router/src/types/api.rs
> +                api_models::enums::Connector::Zsl => todo!(),
This is not needed. Please remove this.

2024-08-26 06:49 UTC, deepanshu-iiitu approved these changes

2024-08-26 07:32 UTC, sai-harsha-vardhan approved these changes

2024-08-26 09:27 UTC, SanchithHegde approved these changes

2024-08-27 07:18 UTC, merged