refactor(router): add domain type for merchant_connector_account id
juspay/hyperswitch pull request #5685
Opened 2024-08-24 19:02 UTC by sai-harsha-vardhan

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

add domain type for merchant_connector_account id

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Tested Manually
1. Create, Update & Retrieve of MCA and subsequent flows like payments, captures and refunds sanity

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-08-27 06:58 UTC, jarnura requested changes

2024-08-27 06:58 UTC, jarnura commented on crates/api_models/src/admin.rs
> +    pub merchant_connector_id: Option<id_type::MerchantConnectorAccountId>,
remove this field

2024-08-27 09:04 UTC, jarnura approved these changes

2024-08-27 11:13 UTC, SanchithHegde commented on crates/common_utils/src/id_type/merchant_connector_account.rs
> +crate::impl_default_id_type!(MerchantConnectorAccountId, "mca");
Do we need the `Default` implementation, can we only use `GenerateId` implementation instead?

2024-08-27 11:13 UTC, ThisIsMani submitted a review, later dismissed
Dashboard specific changes looks fine.

2024-08-27 11:29 UTC, prajjwalkumar17 approved these changes

2024-08-27 13:49 UTC, prajjwalkumar17 approved these changes

2024-08-27 13:59 UTC, SanchithHegde approved these changes

2024-08-27 14:12 UTC, ThisIsMani approved these changes

2024-08-28 07:52 UTC, jarnura approved these changes

2024-08-28 08:17 UTC, merged