feat(connector): [FIUU] PR template code
juspay/hyperswitch pull request #5691
Opened 2024-08-26 06:10 UTC by awasthi21

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-08-26 07:01 UTC, SamraatBansal requested changes

2024-08-26 07:01 UTC, SamraatBansal commented on crates/hyperswitch_connectors/src/default_implementations.rs
> +    connectors::Fiuu,
Reorder alphabetically all the enums

2024-08-26 07:01 UTC, SamraatBansal commented on crates/hyperswitch_connectors/src/default_implementations_v2.rs
> +//             types::ExternalAuthenticationFlowData,
Is this required?

2024-08-26 07:01 UTC, SamraatBansal commented on api-reference-v2/openapi_spec.json
>            {
Get this checked with @SanchithHegde

2024-08-26 10:32 UTC, awasthi21 commented on crates/hyperswitch_connectors/src/default_implementations.rs
> +    connectors::Fiuu,
done

2024-08-26 10:32 UTC, awasthi21 commented on crates/hyperswitch_connectors/src/default_implementations_v2.rs
> +//             types::ExternalAuthenticationFlowData,
removed

2024-08-26 10:32 UTC, awasthi21 commented on api-reference-v2/openapi_spec.json
>            {
Took the latest pull, it wasn;t there

2024-08-26 11:23 UTC, deepanshu-iiitu approved these changes

2024-08-26 11:24 UTC, SamraatBansal approved these changes

2024-08-26 14:54 UTC, SanchithHegde approved these changes

2024-08-26 15:09 UTC, sahkal approved these changes

2024-08-28 11:22 UTC, deepanshu-iiitu approved these changes

2024-08-28 12:18 UTC, sahkal approved these changes

2024-08-28 12:48 UTC, sai-harsha-vardhan approved these changes

2024-08-28 12:58 UTC, SanchithHegde approved these changes

2024-08-29 07:09 UTC, merged