Thunes connector template
juspay/hyperswitch pull request #5775
Opened 2024-09-02 12:11 UTC by sumanmaji4

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Template connector code for Thunes payout

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
Template PR

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-09-03 18:30 UTC, deepanshu-iiitu requested changes

2024-09-03 18:30 UTC, deepanshu-iiitu commented on crates/router/src/types/transformers.rs
> +            // api_enums::Connector::Thunes => Self::Thunes,
Please maintain alphabetic order

2024-09-06 12:01 UTC, SanchithHegde commented on crates/router/tests/connectors/sample_auth.toml
> +
Can you add the `api_key` field for `deutschebank`?

2024-09-09 09:51 UTC, deepanshu-iiitu approved these changes

2024-09-09 09:59 UTC, SanchithHegde approved these changes

2024-09-10 08:26 UTC, jarnura approved these changes

2024-09-10 10:58 UTC, merged