refactor(connector): [Bamboraapac] shift to hyperswitch_connector crate
juspay/hyperswitch pull request #5798
Opened 2024-09-04 16:17 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Shift the connnector integration of bambora apac to hyperswitch_connectors crate

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Tested through Postman:

Note: Need testing for each flow present in bambora apac since the whole integration is shifted

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-09-09 10:11 UTC, deepanshu-iiitu requested changes

2024-09-09 10:11 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/bamboraapac/transformers.rs
> +    req: &BamboraapacRouterData<&types::RefundsRouterData<F>>,
Undo this change and add type `type RefundExecuteRouterData` in `crates/hyperswitch_domain_models/src/types.rs` instead

2024-09-10 07:56 UTC, deepanshu-iiitu requested changes

2024-09-10 07:56 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/transformers.rs
> +}
Please move these utils to `crates/hyperswitch_connectors/src/utils.rs`

2024-09-10 09:53 UTC, deepanshu-iiitu approved these changes

2024-09-11 07:53 UTC, deepanshu-iiitu approved these changes

2024-09-11 08:16 UTC, sai-harsha-vardhan submitted a review, later dismissed

2025-05-06 19:35 UTC, Sakilmostak commented
Closing against https://github.com/juspay/hyperswitch/pull/6652

2025-05-06 19:35 UTC, closed without merging