Payout translated unified error messages
juspay/hyperswitch pull request #5810
Opened 2024-09-05 09:45 UTC by kashif-m

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
This adds `unified_code` and `unified_message` in the payout's API response. These values are looked up in the DB and populated in the API response.

`unified_code` and `unified_message` are then used to fetch the translated message string from DB (if present). This is finally returned in the payouts API response and / or embedded in the payout link.

### Additional Changes

- [x] This PR modifies the API contract
- [x] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-09-17 05:49 UTC, Sakilmostak submitted a review, later dismissed

2024-09-17 06:20 UTC, srujanchikke commented on crates/router/src/core/payouts.rs
> +                unified_message,
Since we are fetching it from gsm and not translating them, Will these unified code & message translated ?

2024-09-17 08:54 UTC, kashif-m commented on crates/router/src/core/payouts.rs
> +    pub current_locale: String,
It's the same!

Just named it `current_locale` in PayoutData, and `locale` in the functions

2024-09-17 08:56 UTC, kashif-m commented on crates/router/src/core/payouts.rs
> +                unified_message,
No, these would always be stored in English in DB

Translation will happen only in two places -

- `response_handler` for payout APIs
- when this has to be embedded in payout links

2024-09-17 08:57 UTC, kashif-m commented on crates/router/src/core/payouts.rs
> +                unified_message,
Yes, not needed to translate in intermediary functions.

2024-09-17 08:59 UTC, kashif-m commented on crates/router/src/connector/adyenplatform/transformers/payouts.rs
> +                payout_eligible: error_code.clone().map(|_| false),
`payout_eligible` can be kept empty here 👍

2024-09-17 09:35 UTC, srujanchikke approved these changes

2024-09-18 04:50 UTC, jarnura requested changes
create domain types for unified message with a generate or new function having maximum length restriction of 1024, and the same can be done for unified code also but the maximum length can be 255. So that we handle these in application instead going to database and failing to insert there.

2024-09-18 04:50 UTC, jarnura commented on crates/api_models/src/payouts.rs
> +    pub unified_code: Option<String>,
In  create api if somethings fails we throws 4xx so this response we will send only in valid case so these fields not required in create response

2024-09-19 01:53 UTC, jarnura approved these changes

2024-09-19 04:30 UTC, srujanchikke approved these changes

2024-09-19 13:54 UTC, merged