Feat(connector): [Fiuu] Add DuitNow PaymentMethod
juspay/hyperswitch pull request #5841
Opened 2024-09-09 12:59 UTC by awasthi21

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Added DuitNowQR 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
**Request**
```
curl --location 'http://localhost:8080/payments' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key:' \
--data '{
    "amount": 1222,
    "currency": "MYR",
    "confirm": true,
    "capture_method": "manual",
    "return_url": "https://google.com",
    "authentication_type": "no_three_ds",
    "payment_method": "real_time_payment",
    "payment_method_type": "duit_now",
    "payment_method_data": {
        "real_time_payment": {
            "duit_now":{
            }
        }
    },
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS"
}'
```
Response
```
{
    "payment_id": "pay_9l079slQTfxcnWXcvVWv",
    "merchant_id": "postman_merchant_GHAction_ff03d9c9-f319-4cf4-b657-f45aefd4cf5b",
    "status": "requires_customer_action",
    "amount": 1222,
    "net_amount": 1222,
    "amount_capturable": 1222,
    "amount_received": null,
    "connector": "fiuu",
    "client_secret": "pay_9l079slQTfxcnWXcvVWv_secret_eLSU6KF41kqq8PFWzEDZ",
    "created": "2024-09-09T11:59:34.213Z",
    "currency": "MYR",
    "customer_id": null,
    "customer": null,
    "description": null,
    "refunds": null,
    "disputes": null,
    "mandate_id": null,
    "mandate_data": null,
    "setup_future_usage": null,
    "off_session": null,
    "capture_on": null,
    "capture_method": "manual",
    "payment_method": "real_time_payment",
    "payment_method_data": {
        "real_time_payment": {},
        "billing": null
    },
    "payment_token": null,
    "shipping": null,
    "billing": null,
    "order_details": null,
    "email": null,
    "name": null,
    "phone": null,
    "return_url": "https://google.com/",
    "authentication_type": "no_three_ds",
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    "next_action": {
        "type": "qr_code_information",
        "image_data_url": "data:image/png;base64",
        "display_to_timestamp": null,
        "qr_code_url": null
    },
    "cancellation_reason": null,
    "error_code": null,
    "error_message": null,
    "unified_code": null,
    "unified_message": null,
    "payment_experience": null,
    "payment_method_type": "duit_now",
    "connector_label": null,
    "business_country": null,
    "business_label": "default",
    "business_sub_label": null,
    "allowed_payment_method_types": null,
    "ephemeral_key": null,
    "manual_retry_allowed": null,
    "connector_transaction_id": null,
    "frm_message": null,
    "metadata": null,
    "connector_metadata": null,
    "feature_metadata": null,
    "reference_id": null,
    "payment_link": null,
    "profile_id": "pro_glzU2Ijq0fPKjPpGv4VV",
    "surcharge_details": null,
    "attempt_count": 1,
    "merchant_decision": null,
    "merchant_connector_id": "mca_hqcC5QIpdCOQMXIKCzum",
    "incremental_authorization_allowed": null,
    "authorization_count": null,
    "incremental_authorizations": null,
    "external_authentication_details": null,
    "external_3ds_authentication_attempted": false,
    "expires_on": "2024-09-09T12:14:34.213Z",
    "fingerprint": null,
    "browser_info": null,
    "payment_method_id": null,
    "payment_method_status": null,
    "updated": "2024-09-09T11:59:35.101Z",
    "charges": null,
    "frm_metadata": null,
    "merchant_order_reference_id": null
}
```
![image](https://github.com/user-attachments/assets/9a0bff1f-61ec-4ba4-b43f-2c3e8a5e851c)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-09-10 08:30 UTC, deepanshu-iiitu requested changes

2024-09-10 08:30 UTC, deepanshu-iiitu commented on config/config.example.toml
> +fiuu.third_base_url="https://api.merchant.razer.com/"
Add this in `loadtest/config/development.toml`

2024-09-10 08:30 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/utils.rs
> +}
Remove this struct from crate router and reexport from here

2024-09-10 08:30 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/utils.rs
> +pub(crate) const BASE64_ENGINE: base64::engine::GeneralPurpose =
use `BASE64_ENGINE` which is already present at `crates/common_utils/src/consts.rs` and remove this declaration

2024-09-10 08:30 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
> +}
Move this struct to line 235 of this file

2024-09-10 12:49 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-09-11 06:35 UTC, SanchithHegde commented on crates/hyperswitch_connectors/Cargo.toml
> +qrcode = "0.14.0"
Remove these 2 dependencies from the `router` crate if it no longer needs them.

2024-09-11 06:52 UTC, SanchithHegde approved these changes

2024-09-11 07:44 UTC, deepanshu-iiitu approved these changes

2024-09-11 11:31 UTC, merged