Add encryption support payment attempt domain model
juspay/hyperswitch pull request #5882
Opened 2024-09-13 10:28 UTC by SanchithHegde

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR introduces encryption support for the payment attempt domain model by adding implementations for the `Conversion` and `ReverseConversion` traits, and adds new methods in the `PaymentAttemptInterface` trait for v2 insert, update and find operations which internally call the `Conversion` / `ReverseConversion` implementations. For now, I've ignored the KV implementations for the new v2 `PaymentAttemptInterface` methods, they just call the underlying PSQL based implementations.

In addition, this PR involves the following changes:

- Moves the incorrectly placed implementation of `Conversion` / `ReverseConversion` traits on `PaymentIntent` to the correct file.
- Addresses some clippy lints.
- Updates payment attempt diesel models to use `MinorUnit` instead of `i64` for amount values.
- Updates some of the usages of find / insert / update payment attempt methods in code to call v1 or v2 implementations based on the enabled feature flags, while some of the other usages have been replaced with a `todo!()` for the v2 implementations.

## Motivation and Context

This allows for adding new fields in payment attempt types for payments v2, which may need encryption support.

## How did you test it?

The new code added in this PR cannot be tested via any APIs, since there are no payments v2 APIs. As for the existing code that was modified, it must be ensured that the existing Postman / Cypress tests should not be affected.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-09-16 04:03 UTC, jarnura requested changes

2024-09-16 04:03 UTC, jarnura commented on crates/router/src/db/kafka_store.rs
> +            logger::error!(message="Failed to log analytics event for payment attempt {attempt:?}", error_message=?er)
Good one

2024-09-16 15:19 UTC, jarnura approved these changes

2024-09-17 07:05 UTC, Chethan-rao approved these changes

2024-09-17 07:49 UTC, ThisIsMani approved these changes

2024-09-17 10:32 UTC, Narayanbhat166 approved these changes

2024-09-17 11:21 UTC, merged