Hackathon h1014 l4 wallets
juspay/hyperswitch pull request #591
Opened 2023-02-13 22:39 UTC by vsrivatsa25

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added wallet support for Bluesnap

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-02-15 12:34 UTC, SamraatBansal requested changes
Please attend to comments raised in previous PR also.

2023-02-15 12:34 UTC, SamraatBansal commented on config/Development.toml
I have added the reviews for most of the files in this PR in L1-L3 PR (PR: #533 ).

Please attend to those changes.

2023-02-15 12:34 UTC, SamraatBansal commented on crates/router/src/connector/bluesnap/transformers.rs
> +                    wallet_id: Some("21".to_string()),
Why is this `wallet_id` hardcoded?

2023-02-15 12:34 UTC, SamraatBansal commented on crates/router/src/connector/bluesnap/transformers.rs
> +                    wallet_id: Some("21".to_string()),
No need to write `payment_request` again, you can see other connectors to understand how to use the same struct with different values.

2023-03-18 09:49 UTC, jagan-jaya commented
Closing this PR in favour of #649

2023-03-18 09:49 UTC, closed without merging