refactor(router): api-key routes refactoring
juspay/hyperswitch pull request #600
Opened 2023-02-16 10:33 UTC by racnan

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [X] Refactoring
- [ ] Dependency updates

## Description
- Refactored API keys routes to use `/{merchant_id}`.
- Refactored authentication errors.

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
These changes enable extending projects to have merchant based authentication for api routes.

## How did you test it?

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-02-16 11:44 UTC, dracarys18 requested changes

2023-02-16 11:44 UTC, dracarys18 commented on crates/router/src/services/authentication.rs
> +            .into_report()
```suggestion
                if e.current_context().is_db_not_found() {
                    e.change_context(errors::ApiErrorResponse::Unauthorized)
                } else {
                    e.change_context(errors::ApiErrorResponse::InternalServerError)
                }
            })
```

2023-02-16 11:44 UTC, dracarys18 commented on crates/router/src/services/authentication.rs
> +            .into_report()
```suggestion
               if e.current_context().is_db_not_found() {
                    e.change_context(errors::ApiErrorResponse::Unauthorized)
                } else {
                    e.change_context(errors::ApiErrorResponse::InternalServerError)
                }
            })
```

2023-02-16 12:28 UTC, racnan commented
@dracarys18 bro resolved comment. Can you check ?

2023-02-16 12:48 UTC, dracarys18 submitted a review, later dismissed

2023-02-16 12:51 UTC, dracarys18 approved these changes

2023-02-16 13:00 UTC, jarnura approved these changes

2023-02-16 13:23 UTC, merged

2023-02-17 06:45 UTC, SanchithHegde commented on crates/router/src/routes/api_keys.rs
> +    let (key_id, _merchant_id) = path.into_inner();
Won't the `key_id` and `merchant_id` variables have interchanged values? Same with update and revoke endpoints.