chore: v2 api changes for session token endpoint
juspay/hyperswitch pull request #6032
Opened 2024-09-25 13:42 UTC by hrithikesh026

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-09-26 11:26 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> +    pub client_secret: String,
can you use `ClientSecret` type for this?

2024-10-03 08:12 UTC, jarnura requested changes

2024-10-03 08:12 UTC, jarnura commented on crates/api_models/src/payments.rs
> +    pub client_secret: ClientSecret,
Move client_secret to headers

2024-10-03 08:12 UTC, jarnura commented on crates/openapi/src/routes/payments.rs
> +  post,
Change to get since we don't have body for this

2024-10-03 12:26 UTC, jarnura approved these changes
Add description

2024-10-04 11:28 UTC, Narayanbhat166 approved these changes

2024-10-07 15:16 UTC, merged