Const email subject
juspay/hyperswitch pull request #6110
Opened 2024-09-26 11:47 UTC by SummerGram

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Change the hardcoded email subject to constants

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

The open issue - #5940 

## How did you test it?

[change_apply_before.txt](https://github.com/user-attachments/files/17147768/change_apply_before.txt)
[change_apply_after.txt](https://github.com/user-attachments/files/17147771/change_apply_after.txt)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-09-26 13:21 UTC, ThisIsMani commented
Fix the PR title and link the issue. I'll approve the workflow.

2024-09-26 13:39 UTC, SummerGram commented
What is the title of the PR supposed be?

2024-09-26 16:55 UTC, SummerGram commented
@ThisIsMani 

I link the issue in the motivation and context part but I still cannot pass the check.

2024-09-26 18:15 UTC, ThisIsMani requested changes

2024-09-26 18:15 UTC, ThisIsMani commented on crates/router/src/core/recon.rs
> +            consts::user::EMAIL_SUBJECT_DASHBOARD_REQUEST,
Can we move the constants related to Recon files in to this file instead
https://github.com/juspay/hyperswitch/blob/5912936f9f2178f002c96e25636b25f532b1ecb2/crates/router/src/consts.rs#L137.

2024-09-26 18:15 UTC, ThisIsMani commented on crates/router/src/core/recon.rs
> +        subject: consts::user::EMAIL_SUBJECT_APPROVAL_RECON_REQUEST,
Same here as well.

2024-09-26 18:15 UTC, ThisIsMani commented on crates/router/src/consts/user.rs
> +pub const EMAIL_SUBJECT_WELCOME: &str = "Welcome to the Hyperswitch community!";
```suggestion
pub const EMAIL_SUBJECT_SIGNUP: &str = "Welcome to the Hyperswitch community!";
```

2024-09-26 18:15 UTC, ThisIsMani commented on crates/router/src/consts/user.rs
> +pub const EMAIL_SUBJECT_UNLOCK: &str = "Unlock Hyperswitch: Use Your Magic Link to Sign In";
```suggestion
pub const EMAIL_SUBJECT_MAGIC_LINK: &str = "Unlock Hyperswitch: Use Your Magic Link to Sign In";
```

2024-09-26 18:15 UTC, ThisIsMani commented on crates/router/src/consts/user.rs
> +pub const EMAIL_SUBJECT_API_KEY_EXPIRY: &str = "API Key Expiry Notice";
Move this as well to `consts.rs`.

2024-09-26 18:15 UTC, ThisIsMani commented on crates/router/src/consts/user.rs
> +pub const EMAIL_SUBJECT_NEW_PROD: &str = "New Prod Intent";
```suggestion
pub const EMAIL_SUBJECT_NEW_PROD_INTENT: &str = "New Prod Intent";
```

2024-09-27 16:23 UTC, SummerGram commented
@ThisIsMani 
Please review the change.

2024-09-30 08:59 UTC, ThisIsMani approved these changes

2024-09-30 12:25 UTC, SummerGram commented
@ThisIsMani 

Why is it failed to run?

2024-09-30 13:06 UTC, ThisIsMani commented on crates/router/src/core/recon.rs
> +            consts::EMAIL_SUBJECT_DASHBOARD_REQUEST,
```suggestion
            consts::EMAIL_SUBJECT_DASHBOARD_FEATURE_REQUEST,
```

2024-09-30 13:07 UTC, ThisIsMani commented
Please recheck the variables again.

2024-09-30 13:11 UTC, SummerGram commented
> Please recheck the variables again.

Those failure in ci-pr is related to the variables name?

2024-09-30 13:59 UTC, ThisIsMani commented
You code is not compiling. That's why the run is failed.

You can check by running `just check`.

2024-09-30 16:45 UTC, SummerGram commented
> You code is not compiling. That's why the run is failed.
> 
> You can check by running `just check`.

Thanks!

2024-10-01 19:07 UTC, SanchithHegde commented
> I think "clonable" typo is not related to this PR.

You can ignore that, shouldn't be a problem. Moreover, it's not a required check, so it shouldn't block your PR from being merged.

2024-10-04 04:27 UTC, ThisIsMani approved these changes

2024-10-07 09:21 UTC, SanchithHegde approved these changes

2024-10-16 07:12 UTC, merged