feat(connector): [Digital Virgo] template for integration
juspay/hyperswitch pull request #6145
Opened 2024-09-27 11:37 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

template code for digital virgo connector

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-09-30 06:21 UTC, srujanchikke requested changes

2024-09-30 06:21 UTC, srujanchikke commented on crates/common_enums/src/enums.rs
> +    Digitalvirgo,
comment this line

2024-09-30 06:21 UTC, srujanchikke commented on crates/api_models/src/enums.rs
> +    Digitalvirgo,
comment this line too

2024-09-30 06:21 UTC, srujanchikke commented on crates/api_models/src/enums.rs
> +			| Self::Digitalvirgo
this too

2024-09-30 06:21 UTC, srujanchikke commented on crates/router/src/core/admin.rs
> +            }
this is not required for template code, can you comment this line ?

2024-09-30 06:21 UTC, srujanchikke commented on crates/router/src/types/transformers.rs
> +            api_enums::Connector::Digitalvirgo => Self::Digitalvirgo,
this too

2024-09-30 10:04 UTC, srujanchikke submitted a review, later dismissed

2024-09-30 11:35 UTC, deepanshu-iiitu requested changes

2024-09-30 11:35 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/digitalvirgo/test.rs
> +use crate::utils::{self, ConnectorActions};
Please rename this file to digitalvirgo.rs and move it to `crates/router/tests/connectors`

2024-10-01 08:10 UTC, deepanshu-iiitu approved these changes

2024-10-01 08:48 UTC, srujanchikke approved these changes

2024-10-01 09:20 UTC, sai-harsha-vardhan approved these changes

2024-10-03 07:28 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-10-03 08:05 UTC, srujanchikke approved these changes

2024-10-03 08:29 UTC, srujanchikke approved these changes

2024-10-03 08:30 UTC, sai-harsha-vardhan approved these changes

2024-10-03 08:56 UTC, jarnura approved these changes
On behalf of core approving the PR since there is no core changes.

2024-10-03 09:59 UTC, merged