Correction of database accessing
juspay/hyperswitch pull request #6167
Opened 2024-09-30 19:50 UTC by zeel991

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-01 08:25 UTC, ThisIsMani requested changes
Please change only the files mentioned in the issue.

2024-10-01 10:30 UTC, ThisIsMani requested changes

2024-10-01 10:30 UTC, ThisIsMani commented on crates/router/src/db/user.rs
> +        let conn = connection::pg_connection_read(self).await?;
This shouldn't be read.

2024-10-01 11:01 UTC, ThisIsMani approved these changes

2024-10-01 11:04 UTC, ThisIsMani commented
Please add something in description saying that this is a internal changes and all the user related APIs should work without any issues in the testcases section.

2024-10-01 11:18 UTC, zeel991 commented
> Please add something in description saying that this is a internal change and all the user related APIs should work without any issues in the testcases section.

Done @ThisIsMani , I apologize for any beginner mistakes I made while raising this PR. Thank you for your patience and support

2024-10-01 11:21 UTC, SanchithHegde approved these changes

2024-10-01 11:22 UTC, ThisIsMani commented
Hey @zeel991, can you check the original template and change you PR description into that template.

2024-10-01 12:07 UTC, zeel991 commented
> Hey @zeel991, can you check the original template and change you PR description into that template.

Are these changes appropriate ?

2024-10-01 12:24 UTC, ThisIsMani commented
Yeah, looks fine.

2024-10-01 14:10 UTC, zeel991 commented
Hello @ThisIsMani ,would you please consider adding the `hactoberfest` tag to the PR

2024-10-03 03:14 UTC, zeel991 commented
Hey @ThisIsMani , since this PR is approved, when can it be merged ?

2024-10-04 04:32 UTC, ThisIsMani commented
@zeel991, will get this merged by Monday.

2024-10-04 11:55 UTC, ThisIsMani commented
Hey @zeel991, can you resolve the conflicts. I will get this merged as soon as you resolve.

2024-10-04 14:56 UTC, zeel991 commented
> Hey @zeel991, can you resolve the conflicts.

Done ! 👍🏻

2024-10-04 19:04 UTC, zeel991 commented
Hello @ThisIsMani ,
I am Zeel Darji , C4GT community Lead and Open source Lead of Development Wing of IIITN . I am organizing an open source event in my college's techfest which higlights the importance of DPGs and DPIs .

I wanted to ask you if participants could contribute to the repos of Juspay for our Event ?

2024-10-05 03:39 UTC, gorakhnathy7 commented
Hey @zeel991,
Happy to help with the event.
Pinged you in community workspace, we can continue the discussion there.

2024-10-05 06:13 UTC, zeel991 commented
> Hey @zeel991, Happy to help with the event. Pinged you in community workspace, we can continue the discussion there.

Can you please send the link , I couldn't find it

2024-10-06 04:49 UTC, gorakhnathy7 commented
> > Hey @zeel991, Happy to help with the event. Pinged you in community workspace, we can continue the discussion there.
> 
> Can you please send the link , I couldn't find it

Please check [Hyperswitch Slack workspace
](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-2jqxmpsbm-WXUENx022HjNEy~Ark7Orw)

2024-10-07 04:06 UTC, ThisIsMani approved these changes

2024-10-07 09:13 UTC, SanchithHegde submitted a review, later dismissed

2024-10-07 11:26 UTC, zeel991 commented
@ThisIsMani Should I update the branch ?

2024-10-07 12:08 UTC, ThisIsMani commented
But seems like formatting check if failing in the PR, can you format the code using `just fmt` and push the changes.

2024-10-08 13:15 UTC, zeel991 commented
> But seems like formatting check if failing in the PR, can you format the code using `just fmt` and push the changes.

I have removed the merge conflict and formatted the PR

2024-10-09 13:16 UTC, zeel991 commented
Hey @ThisIsMani If my contribution is as required , can you please merge my PR , as I have been getting conflicts

2024-10-09 14:26 UTC, ThisIsMani approved these changes

2024-10-09 15:45 UTC, zeel991 commented
@ThisIsMani All the tests have passed

2024-10-15 07:32 UTC, SanchithHegde approved these changes

2024-10-18 07:18 UTC, merged