feat(core): add Mobile Payment (Direct Carrier Billing) as a payment method
juspay/hyperswitch pull request #6196
Opened 2024-10-02 12:06 UTC by Sakilmostak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-09 04:34 UTC, srujanchikke requested changes

2024-10-09 04:34 UTC, srujanchikke commented on crates/hyperswitch_connectors/src/connectors/digitalvirgo.rs
> +        Ok(format!("{}{}", self.base_url(connectors), "/payment"))
Please make the same changes in all get_url functions.

```suggestion
        Ok(format!("{}/payment", self.base_url(connectors)))
```

2024-10-09 04:34 UTC, srujanchikke commented on crates/hyperswitch_connectors/src/connectors/digitalvirgo.rs
> +            .parse_struct("Digitalvirgo PaymentsAuthorizeResponse")
```suggestion
            .parse_struct("DigitalvirgoPaymentsResponse")
```

2024-10-10 04:09 UTC, srujanchikke approved these changes
Reviewed connector code!

2024-10-10 10:08 UTC, deepanshu-iiitu approved these changes

2024-10-10 10:23 UTC, Chethan-rao requested changes

2024-10-10 10:23 UTC, Chethan-rao commented on crates/router/src/core/payments/transformers.rs
> +            payment_intent.clone(),
clone not required here, you can pass the reference

2024-10-10 10:23 UTC, Chethan-rao commented on crates/euclid/src/frontend/dir.rs
> +        detailed_message = "Supported types of mobile payment payment method",
```suggestion
        detailed_message = "Supported types of mobile payment method",
```

2024-10-10 13:38 UTC, Chethan-rao approved these changes
Routing and core changes LGTM

2024-10-14 07:04 UTC, deepanshu-iiitu approved these changes
Approving on behalf of connectors.

2024-10-14 08:13 UTC, srujanchikke submitted a review, later dismissed

2024-10-14 13:45 UTC, Narayanbhat166 commented
> This next action gives an URL in the response through which you collect OTP for the transaction

Is this like a redirection? If so then we can send the redirect url right?

2024-10-15 06:13 UTC, Sakilmostak commented
> Is this like a redirection? If so then we can send the redirect url right?

Yes, this is a redirection but generally redirection is either done by connector or is used to invoke their sdk. Here, we are collecting the OTP with our own hosted site to confirm the payment.

2024-10-18 08:32 UTC, Chethan-rao submitted a review, later dismissed

2024-11-11 09:36 UTC, srujanchikke commented on crates/hyperswitch_connectors/src/connectors/digitalvirgo/transformers.rs
> +                        })?;
Should required fields to be added in payment_connector_required_fields.rs ?

2024-11-11 11:01 UTC, srujanchikke submitted a review, later dismissed

2024-11-11 11:09 UTC, srujanchikke approved these changes

2024-11-11 13:18 UTC, sai-harsha-vardhan commented on crates/api_models/src/payments.rs
> +        msisdn: String,
This should be a Secret value

2024-11-11 13:18 UTC, sai-harsha-vardhan commented on crates/api_models/src/payments.rs
> +        client_uid: Option<String>,
Is this sensitive data?

2024-11-11 13:18 UTC, sai-harsha-vardhan approved these changes

2024-11-11 13:25 UTC, Chethan-rao approved these changes

2024-11-12 09:05 UTC, jarnura approved these changes

2024-11-13 09:48 UTC, Gnanasundari24 commented
@Sakilmostak Can you add the cypress testcases for this

2024-11-13 10:13 UTC, Sakilmostak commented
The flow is incomplete for the new payment method. The subsequent PR as stated by this issue (https://github.com/juspay/hyperswitch-cloud/issues/7441) should be able to complete the flow. The cypress test will be raised along with this PR

2024-11-13 20:24 UTC, merged