refactor(connector): add amount conversion framework to payu
juspay/hyperswitch pull request #6199
Opened 2024-10-02 14:12 UTC by rahulpatwal0922

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
This PR adds amount conversion framework to payu, for sending to connector

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-06 16:18 UTC, Sakilmostak requested changes

2024-10-06 16:18 UTC, Sakilmostak commented on crates/router/src/connector/payu.rs
> +}
Please use `MinorUnit` instead of `StringMinorUnit`

2024-10-06 16:18 UTC, Sakilmostak commented on crates/router/src/connector/payu/transformers.rs
> +    pub amount: StringMinorUnit,
Same Here

2024-10-06 16:18 UTC, Sakilmostak commented on crates/router/src/connector/payu/transformers.rs
> +    total_amount: StringMinorUnit,
And Here

2024-10-06 16:18 UTC, Sakilmostak commented on crates/router/src/connector/payu/transformers.rs
> +    amount: Option<StringMinorUnit>,
And Here

2024-10-08 08:09 UTC, gorakhnathy7 commented
Hey @rahulpatwal0922 Kindly look into the changes

2024-10-08 10:13 UTC, rahulpatwal0922 commented
Sure @gorakhnathy7 I Will make the requested changes.

2024-10-08 17:34 UTC, rahulpatwal0922 commented
@gorakhnathy7 @Sakilmostak changes done.

2024-10-14 06:43 UTC, Sakilmostak approved these changes
LGTM!

2024-10-15 05:32 UTC, mrudulvajpayee4935 commented
> @gorakhnathy7 @Sakilmostak changes done.

hey @rahulpatwal0922 can you push one empty commit, we want to run the remaining checks before merging this.

2024-10-15 07:07 UTC, Sakilmostak approved these changes

2024-10-15 07:33 UTC, mrudulvajpayee4935 approved these changes

2024-10-16 19:31 UTC, SanchithHegde submitted a review, later dismissed

2024-10-17 06:04 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-10-24 11:39 UTC, Gnanasundari24 commented
@rahulpatwal0922 Can you resolve the conflicts

2024-10-24 11:42 UTC, rahulpatwal0922 commented
> @rahulpatwal0922 Can you resolve the conflicts

sure

2024-10-25 10:13 UTC, SanchithHegde approved these changes

2024-10-28 12:08 UTC, SanchithHegde approved these changes

2024-10-28 12:19 UTC, mrudulvajpayee4935 approved these changes

2024-10-28 13:15 UTC, Sakilmostak approved these changes

2024-10-29 06:40 UTC, deepanshu-iiitu approved these changes

2024-10-29 12:10 UTC, merged