feat(connector): add dynamic duitnow qr code flow for fiuu
juspay/hyperswitch pull request #6204
Opened 2024-10-03 06:48 UTC by srujanchikke

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR adds support for duitnow dynamic qr code flow.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-03 14:04 UTC, deepanshu-iiitu requested changes

2024-10-03 14:04 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
> +        };
Please move this logic to individual payment methods where 3DS is supported

2024-10-04 07:08 UTC, deepanshu-iiitu approved these changes

2024-10-04 07:36 UTC, ShankarSinghC approved these changes

2024-10-04 07:43 UTC, SamraatBansal requested changes

2024-10-04 07:43 UTC, SamraatBansal commented on crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
> +    pub txn_currency: String,
Use currency enum

2024-10-04 07:43 UTC, SamraatBansal commented on crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
> +    pub txn_amount: String,
Use the amount_converter object that you have defined

2024-10-04 08:01 UTC, SamraatBansal approved these changes

2024-10-04 08:05 UTC, ShankarSinghC approved these changes

2024-10-04 08:32 UTC, deepanshu-iiitu approved these changes

2024-10-04 09:06 UTC, merged