refactor(routing): add admin api key as auth for toggling dynamic routing
juspay/hyperswitch pull request #6235
Opened 2024-10-04 11:22 UTC by Aprabhat19

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
add admin api key as auth for toggling dynamic routing

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-04 11:24 UTC, Chethan-rao approved these changes, later dismissed

2024-10-04 11:25 UTC, Sarthak1799 approved these changes, later dismissed

2024-10-04 12:22 UTC, prajjwalkumar17 approved these changes, later dismissed

2024-10-04 18:08 UTC, Chethan-rao requested changes

2024-10-04 18:08 UTC, Chethan-rao commented on crates/router/src/routes/routing.rs
> +    )>,
Now that you are capturing both of these in path itself, can we remove `ToggleSuccessBasedRoutingPath`? if so, please remove it from openapi.rs too

2024-10-08 08:15 UTC, prajjwalkumar17 approved these changes

2026-06-23 08:52 UTC, Aprabhat19 commented
Not required

2026-06-23 08:52 UTC, closed without merging