refactor(connector): added amount conversion to FISERV
juspay/hyperswitch pull request #6256
Opened 2024-10-08 03:28 UTC by ravikiran232

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

added MinorUnit for amount conversion

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

fixes #5947 

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-17 05:56 UTC, deepanshu-iiitu requested changes

2024-10-17 05:56 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/utils.rs
> +#[allow(dead_code)]
Please remove this

2024-10-17 05:56 UTC, deepanshu-iiitu commented
@ravikiran232 Please implement the suggested changes.

2024-10-24 10:42 UTC, gorakhnathy7 commented
Hey @ravikiran232 Any updates on the changes!

2025-03-12 07:58 UTC, closed without merging