refactor(connector): Move connector Forte from Router to Hyperswitch Connector Trait
juspay/hyperswitch pull request #6261
Opened 2024-10-08 08:03 UTC by spritianeja03

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Moved connector Forte from Router to HyperswitchConnector Trait

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-08 11:39 UTC, deepanshu-iiitu requested changes

2024-10-08 11:39 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/forte/transformers.rs
> +
Remove these comments

2024-10-08 11:39 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/default_implementations.rs
> +    connectors::Fiservemea,
Remove these extra spaces everywhere

2024-10-08 11:39 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/utils.rs
> +
Remove this trait and instead of using `foreign_from` create a function instead in `crates/router/src/connector/forte/transformers.rs`

2024-10-08 11:39 UTC, deepanshu-iiitu commented on crates/router/src/connector.rs
> +    volt::Volt, worldline, worldline::Worldline, forte, forte::Forte,
Please maintain alphabetical order

2024-10-17 10:21 UTC, deepanshu-iiitu requested changes

2024-10-17 10:21 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/nexinets.rs
> +// };
Remove these comments

2024-10-17 10:21 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/nexinets.rs
> +    // types::{AmountConvertor, MinorUnit, MinorUnitForConnector},
remove this

2024-10-17 10:21 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/nexinets.rs
> +// use self::bitpay::BitpayWebhookDetails;
remove this

2024-10-17 10:21 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/nexinets/transformers.rs
> +// impl ForeignFrom<(NexinetsPaymentStatus, NexinetsTransactionType)> for AttemptStatus {
remove these comments

2024-10-17 11:38 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-10-17 13:42 UTC, sai-harsha-vardhan approved these changes

2024-10-21 09:27 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-10-21 11:58 UTC, SanchithHegde approved these changes

2024-10-21 12:47 UTC, sai-harsha-vardhan submitted a review, later dismissed

2024-10-22 08:41 UTC, deepanshu-iiitu approved these changes

2024-10-22 09:31 UTC, SanchithHegde approved these changes

2024-10-22 09:34 UTC, sai-harsha-vardhan approved these changes

2024-10-23 12:54 UTC, merged