Payment confirm api
juspay/hyperswitch pull request #6263
Opened 2024-10-08 08:38 UTC by Narayanbhat166

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-21 10:57 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/transformers.rs
> +        connector_request_reference_id: payment_data
we should give priority to merchant_reference_id right?

2024-10-21 10:57 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/transformers.rs
> +            .get_required_value("connector")
can we throw a 5xx here instead?

2024-10-21 11:40 UTC, Narayanbhat166 commented on crates/hyperswitch_domain_models/src/payments/payment_attempt.rs
> +            amount_capturable: MinorUnit::new(0),
we should not be using the default values for amount, I would prefer to be implicit and provide the value zero.

2024-10-21 11:51 UTC, Narayanbhat166 commented on crates/router/src/core/payments/operations/payment_confirm_intent.rs
> +        let current_payment_attempt = payment_data.payment_attempt.clone();
This has already been discussed, The refactor will be taken up in subsequent PRs

2024-10-21 11:52 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> +    pub shipping: Option<Address>,
No, we should always accept `payment_method_data.billing` during confirm.

2024-10-21 12:40 UTC, Narayanbhat166 commented on crates/hyperswitch_domain_models/src/payments.rs
> +    pub payment_method_data: Option<crate::payment_method_data::PaymentMethodData>,
This is not the same payment method data that is stored in payment attempt. This is the domain model which stores the actual payment method data. The one in payment_attempt stores insensitive data

2024-10-22 04:18 UTC, jarnura requested changes

2024-10-22 04:18 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_response.rs
> +        #[cfg(all(feature = "v1", feature = "dynamic_routing"))] routable_connector: Vec<
V1 and V2 are mutually exclusive features, so v1 related field should be removed

2024-10-22 04:18 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_response.rs
> +        #[cfg(all(feature = "v1", feature = "dynamic_routing"))] business_profile: &domain::Profile,
V1 and V2 are mutually exclusive features, so v1 related field should be removed

2024-10-23 08:53 UTC, jarnura submitted a review, later dismissed

2024-10-23 08:53 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_confirm_intent.rs
> +                    current_flow: "cofirm_intent".to_string(),
fix typos

2024-10-23 10:48 UTC, Narayanbhat166 commented on crates/router/src/core/payments/transformers.rs
> +            .net_amount
yes, will take this up separately. Will need to make these as private fields as well and provide access through getters and setters

2024-10-24 05:20 UTC, jarnura approved these changes

2024-10-24 05:56 UTC, sai-harsha-vardhan approved these changes

2024-10-24 06:15 UTC, ShankarSinghC approved these changes

2024-10-24 07:58 UTC, apoorvdixit88 approved these changes

2024-10-24 07:58 UTC, apoorvdixit88 commented on crates/diesel_models/src/user/sample_data.rs
> +//         //     payment_method_id: self.payment_method_id,
having two set of comment `//` is redundant?

2024-10-24 08:00 UTC, lsampras approved these changes

2024-10-24 11:08 UTC, merged