refactor(connector): Move connector Billwerk form Router to HyperswitchConnestor Trait
juspay/hyperswitch pull request #6266
Opened 2024-10-08 09:30 UTC by spritianeja03

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Moved connector Billwerk from Router to HyperswitchConnector Trait

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-08 12:06 UTC, deepanshu-iiitu requested changes

2024-10-08 12:06 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors.rs
> +    tsys::Tsys, volt::Volt, worldline::Worldline, billwerk::Billwerk,
Please maintain alphabetical order

2024-10-08 12:06 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors.rs
> +pub mod billwerk;
Please maintain alphabetical order

2024-10-08 12:06 UTC, deepanshu-iiitu commented on crates/router/src/connector.rs
> +    volt::Volt, worldline, worldline::Worldline, billwerk, billwerk::Billwerk,
Please maintain alphabetical order

2024-10-09 08:02 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-10-09 09:37 UTC, sai-harsha-vardhan submitted a review, later dismissed

2024-10-09 10:28 UTC, SanchithHegde approved these changes

2024-10-15 09:44 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-10-15 11:10 UTC, sai-harsha-vardhan submitted a review, later dismissed

2024-10-15 12:32 UTC, SanchithHegde submitted a review, later dismissed

2024-10-17 13:48 UTC, deepanshu-iiitu approved these changes

2024-10-17 13:49 UTC, sai-harsha-vardhan approved these changes

2024-10-17 18:20 UTC, SanchithHegde approved these changes

2024-10-18 13:44 UTC, merged