feat(core): add api locking interface POC
juspay/hyperswitch pull request #630
Opened 2023-02-23 13:19 UTC by Abhicodes-crypto

WIP

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

This PR contains the functions used for API locking. 

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Api locking is required to prevent threads from modifying the same resource simultaneously. 

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-08 14:47 UTC, jarnura requested changes

2023-03-08 14:47 UTC, jarnura commented on crates/router/src/core/locking.rs
> +pub async fn get_key_and_lock_resource(
Change the function name, `get_key` operation is not happening inside the function.

And if this function only going to works on a key type, can't we have a unit struct for each type.

And `Trait` `LockResource` having a `lock()` method

2023-03-08 14:47 UTC, jarnura commented on crates/router/src/core/locking.rs
> +    if is_locking_enabled_for_merchant && is_locking_enabled_on_api {
We can have a discuss why redis? and why not environment variables

2023-03-08 14:47 UTC, jarnura commented on crates/router/src/core/locking.rs
> +    let redis_key_for_lock = get_redis_key_for_locks(locking_key);
`get_redis_key_for_locks` are we doing mulitple locks?

2023-03-08 14:47 UTC, jarnura commented on crates/router/src/core/locking.rs
> +        delay_between_retries_in_seconds
time value are parsed in lots of places, parse once and parse in single place. Avoid parsing multiple times.

2023-07-20 09:40 UTC, shakthi-22 commented
This is being worked on again by @Abhicodes-crypto

2023-07-20 09:40 UTC, closed without merging