fix(payments_list): skip count query if no filters and add logging
juspay/hyperswitch pull request #6331
Opened 2024-10-15 21:20 UTC by apoorvdixit88

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
- Skip count query if no filters are applied for attempts, in this we don't need to filter attempts as count of active attempt ids will be the total count.
- Profile id filter is already getting applied in intents, so removing it from last active attempts.
- Add logging around count query.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Closes [#6330](https://github.com/juspay/hyperswitch/issues/6330)

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-16 05:45 UTC, dracarys18 requested changes

2024-10-16 05:45 UTC, dracarys18 commented on crates/router/src/core/payments.rs
> +        && constraints.merchant_connector_id.is_none()
Maybe add a seperate function in `PaymentListFilterConstraints` to get this

2024-10-16 12:12 UTC, NishantJoshi00 commented on crates/router/src/routes/payments.rs
> +                &[],
can you add `merchant_id` as an attribute

2024-10-16 12:12 UTC, NishantJoshi00 commented on crates/router/src/routes/payments.rs
> +                &[],
here also

2024-10-16 18:21 UTC, NishantJoshi00 approved these changes

2024-10-17 06:06 UTC, dracarys18 approved these changes

2024-10-17 06:32 UTC, sai-harsha-vardhan approved these changes

2024-10-17 10:51 UTC, merged