Novalnet wallets
juspay/hyperswitch pull request #6370
Opened 2024-10-18 12:58 UTC by cookieg13

## Type of Change

- [ ] Bugfix
- [X] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Integrated Googlepay and Paypal for Novalnet 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
https://github.com/juspay/hyperswitch-cloud/issues/6731

## How did you test it?

## Checklist

- [X] I formatted the code `cargo +nightly fmt --all`
- [X] I addressed lints thrown by `cargo clippy`
- [X] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-21 07:02 UTC, srujanchikke commented on crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs
> +                    .clone()
can we pass reference here ?

2024-10-21 07:51 UTC, deepanshu-iiitu requested changes

2024-10-21 07:51 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/novalnet.rs
> +        let mandate_supported_pmd: HashSet<PaymentMethodDataType> = HashSet::from([
Please add the changes in `crates/connector_configs/toml` as well

2024-10-21 07:51 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/novalnet.rs
> +                api_models::webhooks::RefundIdType::ConnectorRefundId(parent_tid.to_string()),
Are we supposed to populate `ConnectorRefundId` with `parent_tid`?

2024-10-21 07:52 UTC, deepanshu-iiitu commented
@cookieg13 
Did you test Google Pay and Paypal Flows?

2024-10-21 11:21 UTC, srujanchikke submitted a review, later dismissed

2024-10-21 11:28 UTC, cookieg13 commented
> @cookieg13 Did you test Google Pay and Paypal Flows?

yes tested locally, webhooks and mandates are tested too

2024-10-21 11:56 UTC, cookieg13 commented on crates/hyperswitch_connectors/src/connectors/novalnet.rs
> +                api_models::webhooks::RefundIdType::ConnectorRefundId(parent_tid.to_string()),
according to docs,
[event.tid](https://developer.novalnet.com/asynchronousnotification/parameterspassed#response-event-tid) - The TID which is relevant to this event.
[event.parent_tid](https://developer.novalnet.com/asynchronousnotification/parameterspassed#response-event-parent_tid) - During the course of followup events like chargebacks, credit entry etc.., this field will contain the value of the original/initial transaction TID.

I have removed this change. Not needed.

2024-10-21 12:05 UTC, srujanchikke submitted a review, later dismissed

2024-10-21 14:54 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-10-23 12:04 UTC, Gnanasundari24 commented
@cookieg13 You add the response aswell then only will get to know whether its worked or not

2024-10-24 05:37 UTC, cookieg13 commented
> @cookieg13 Can you add the response aswell then only will get to know whether its worked or not. and add the mandate req and res also

added testing doc with req and responses in readme

2024-10-24 11:41 UTC, srujanchikke approved these changes

2024-10-24 11:43 UTC, deepanshu-iiitu approved these changes

2024-10-24 13:35 UTC, merged