feat(connector): [NOMUPAY] Add template code
juspay/hyperswitch pull request #6382
Opened 2024-10-21 13:05 UTC by sumanmaji4

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Template connector code for Nomupay payout

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-22 07:32 UTC, ImSagnik007 commented
resolve the failing checks and add openapi changes as well

2024-10-23 07:31 UTC, cookieg13 requested changes

2024-10-23 07:31 UTC, cookieg13 commented on config/development.toml
> +nomupay.base_url = "https://payout-api.sandbox.nomupay.com"
please fix the alphabetical here

2024-10-23 07:31 UTC, cookieg13 commented on config/docker_compose.toml
> +    "nomupay",
same

2024-10-23 07:31 UTC, cookieg13 commented on crates/hyperswitch_interfaces/src/configs.rs
> +    pub nomupay: ConnectorParams,
same

2024-10-23 07:31 UTC, cookieg13 commented on loadtest/config/development.toml
> +    "nomupay",
same

2024-10-23 12:15 UTC, cookieg13 approved these changes

2024-10-24 06:21 UTC, deepanshu-iiitu approved these changes

2024-10-24 06:35 UTC, sai-harsha-vardhan approved these changes

2024-10-24 10:38 UTC, sai-harsha-vardhan approved these changes

2024-10-24 12:42 UTC, deepanshu-iiitu approved these changes

2024-10-25 10:27 UTC, SanchithHegde approved these changes

2024-11-06 10:01 UTC, cookieg13 submitted a review, later dismissed

2024-11-06 10:20 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-11-06 10:28 UTC, SanchithHegde commented on crates/router/tests/connectors/nomupay.rs
> +        // }
Remove commented code.

2024-11-06 13:40 UTC, SanchithHegde approved these changes

2024-11-07 03:01 UTC, cookieg13 submitted a review, later dismissed

2024-11-07 05:53 UTC, sai-harsha-vardhan approved these changes

2024-11-11 05:45 UTC, deepanshu-iiitu approved these changes

2024-11-11 07:36 UTC, cookieg13 approved these changes

2024-11-11 08:17 UTC, sai-harsha-vardhan approved these changes

2024-11-11 09:44 UTC, dracarys18 approved these changes

2024-11-12 06:54 UTC, ArjunKarthik approved these changes

2024-11-12 07:30 UTC, merged