feat(router): add api_models and openapi changes for refunds create api v2
juspay/hyperswitch pull request #6385
Opened 2024-10-22 06:32 UTC by sai-harsha-vardhan

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

add api_models and openapi changes for refunds create api v2

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Run `mintlify dev` locally to test api-reference changes
![image](https://github.com/user-attachments/assets/45f13313-fee3-4772-95ec-c2c24cd4a5d8)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-10-22 10:41 UTC, jarnura requested changes

2024-10-22 10:41 UTC, jarnura commented on crates/api_models/src/refunds.rs
> +    pub currency: String,
Use `Currency` Enum

2024-10-22 10:47 UTC, jarnura submitted a review, later dismissed

2024-10-22 10:55 UTC, tsdk02 submitted a review, later dismissed

2024-10-22 11:21 UTC, Narayanbhat166 commented on crates/api_models/src/refunds.rs
> +    pub merchant_reference_id: common_utils::id_type::RefundReferenceId,
is this mandatory? We will create a refund id right if reference id is not passed.

2024-10-22 11:28 UTC, Narayanbhat166 commented on crates/api_models/src/refunds.rs
> +    pub merchant_connector_id: Option<common_utils::id_type::MerchantConnectorAccountId>,
This will be a mandatory field

2024-10-22 11:28 UTC, Narayanbhat166 commented on crates/api_models/src/refunds.rs
> +    pub created_at: Option<PrimitiveDateTime>,
These fields, created_at and updated_at are not optional, these are mandatory fields in the response. We will not have any case where created_at and updated_at will be None

2024-10-22 11:28 UTC, Narayanbhat166 commented on crates/api_models/src/refunds.rs
> +    pub error_message: Option<String>,
we can group these errors.

2024-10-22 11:28 UTC, Narayanbhat166 commented on crates/api_models/src/refunds.rs
> +    #[schema(value_type = Option<String>)]
we will also have connector refund id ? or connector refund reference id?

2024-10-22 11:28 UTC, Narayanbhat166 commented on crates/common_utils/src/events.rs
> +        payment_id: Option<id_type::PaymentId>,
we will always have payment id, and this will be global payment id

2024-10-23 08:03 UTC, Narayanbhat166 commented on crates/api_models/src/refunds.rs
> +    /// Total amount for which the refund is to be initiated. Amount for the payment in lowest denomination of the currency. (i.e) in cents for USD denomination, in paisa for INR denomination etc., I
if not provided this will default to the `amount_captured` right?

2024-10-23 08:03 UTC, Narayanbhat166 commented on crates/api_models/src/refunds.rs
> +    pub merchant_reference_id: common_utils::id_type::RefundReferenceId,
This will be optional here as well right?

2024-10-23 09:06 UTC, Narayanbhat166 approved these changes

2024-10-23 09:26 UTC, tsdk02 approved these changes

2024-10-23 11:23 UTC, jarnura approved these changes

2024-10-23 11:49 UTC, merged