refactor(connector): Added amount conversion framework to Wise.
juspay/hyperswitch pull request #6469
Opened 2024-10-30 14:13 UTC by shuklamaneesh23

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This pull request introduces significant changes to the Wise connector in the `crates/router` module, focusing on the integration of a new amount conversion utility and refactoring to utilize a new `WiseRouterData` struct. The changes enhance how amounts are handled and improve the overall structure and clarity of the code.

### Refactoring and Enhancements:

* **Amount Conversion Utility Integration:**
  - Added `amount_converter` to the `Wise` struct and integrated it into the `new` method.
  - Updated `convert_amount` usage in `WisePayoutQuoteRequest` and `WiseRecipientCreateRequest` implementations to use the new `amount_converter`. [[1]](diffhunk://#diff-a149ab1c35f89dd3b0eed2fca15df170708e81962550226b958ae6c367515043L365-R382) [[2]](diffhunk://#diff-a149ab1c35f89dd3b0eed2fca15df170708e81962550226b958ae6c367515043L444-R467)

* **Introduction of `WiseRouterData` Struct:**
  - Added `WiseRouterData` struct to encapsulate amount and router data, and implemented conversion from a tuple.
  - Modified `WisePayoutQuoteRequest` and `WiseRecipientCreateRequest` to use `WiseRouterData` for transformations. [[1]](diffhunk://#diff-1e46db110c015ea743fbbe850bf756011b4311a1ef56fe5ee75c911bb4960b15L351-R371) [[2]](diffhunk://#diff-1e46db110c015ea743fbbe850bf756011b4311a1ef56fe5ee75c911bb4960b15L423-R451)

### Codebase Simplification:

* **Removal of Unnecessary Debug Trait:**
  - Removed the `Debug` trait from the `Wise` struct.

* **Update in Connector Initialization:**
  - Updated the initialization of the `Wise` connector to use the `new` method in `api.rs` and test files. [[1]](diffhunk://#diff-71935350b305eb696195bc45f26e6f2a16097fb17bd5ac55192eb1d03558bf9aL483-R483) [[2]](diffhunk://#diff-0177b5efcc163c3f657a8c60b0162bf272a68a5e22beb13f6eb309bd34d54166L31-R31)

### Minor Enhancements:

* **Type Adjustments:**
  - Changed various fields in `WiseRecipientCreateRequest` and `WisePayoutQuoteRequest` to use `StringMajorUnit` instead of `String` or `i64`. [[1]](diffhunk://#diff-1e46db110c015ea743fbbe850bf756011b4311a1ef56fe5ee75c911bb4960b15L64-R79) [[2]](diffhunk://#diff-1e46db110c015ea743fbbe850bf756011b4311a1ef56fe5ee75c911bb4960b15L159-R175)

These changes collectively improve the robustness and maintainability of the Wise connector, ensuring better handling of amount conversions and a cleaner code structure.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-11-04 08:04 UTC, deepanshu-iiitu requested changes

2024-11-04 08:04 UTC, deepanshu-iiitu commented on crates/router/src/connector/wise.rs
> +            amount_converter: &StringMajorUnitForConnector,
```suggestion
            amount_converter: &MinorUnitForConnector,
```

2024-11-04 08:04 UTC, deepanshu-iiitu commented on crates/router/src/connector/wise.rs
> +    amount_converter: &'static (dyn AmountConvertor<Output = StringMajorUnit> + Sync),
```suggestion
    amount_converter: &'static (dyn AmountConvertor<Output = MinorUnit> + Sync),
```

2024-11-04 08:04 UTC, deepanshu-iiitu commented on crates/router/src/connector/wise.rs
> +use common_utils::types::{AmountConvertor, StringMajorUnit, StringMajorUnitForConnector};
```suggestion
use common_utils::types::{AmountConvertor, MinorUnit, MinorUnitForConnector};
```

2024-11-04 08:04 UTC, deepanshu-iiitu commented on crates/router/src/connector/wise/transformers.rs
> +    pub amount: StringMajorUnit,
```suggestion
    pub amount: MinorUnit,
```

2024-11-04 08:04 UTC, deepanshu-iiitu commented on crates/router/src/connector/wise/transformers.rs
> +    fn from((amount, router_data): (StringMajorUnit, T)) -> Self {
```suggestion
    fn from((amount, router_data): (MinorUnit, T)) -> Self {
```

2024-11-04 08:04 UTC, deepanshu-iiitu commented on crates/router/src/connector/wise/transformers.rs
> +impl<T> From<(StringMajorUnit, T)> for WiseRouterData<T> {
```suggestion
impl<T> From<(MinorUnit, T)> for WiseRouterData<T> {
```

2024-11-04 08:04 UTC, deepanshu-iiitu commented on crates/router/src/connector/wise/transformers.rs
> +    currency: StringMajorUnit,
Please revert this change

2024-11-04 08:04 UTC, deepanshu-iiitu commented on crates/router/src/connector/wise/transformers.rs
> +    target_amount: Option<StringMajorUnit>,
```suggestion
    source_amount: Option<MinorUnit>,
    target_amount: Option<MinorUnit>,
```

2024-11-04 08:04 UTC, deepanshu-iiitu commented on crates/router/src/connector/wise/transformers.rs
> +                    currency: item_data.amount.clone(),
Please revert this change.

2024-11-04 08:05 UTC, deepanshu-iiitu commented
Hey @shuklamaneesh23 
The amount in this payment processor should be `MinorUnit` and not `StringMajorUnit`. Please implement the above suggested changes.
Also currency should be of type string.

2024-11-04 17:57 UTC, shuklamaneesh23 commented
hey @deepanshu-iiitu , I have updated the code as per the suggested change.
Please let me know if I could fix something else.
Thanks!

2024-11-05 07:42 UTC, deepanshu-iiitu approved these changes

2024-11-05 13:13 UTC, Sakilmostak approved these changes

2024-11-06 06:39 UTC, dracarys18 approved these changes

2024-11-07 07:36 UTC, merged