feat(router): add start_redirection api for three_ds flow in v2
juspay/hyperswitch pull request #6470
Opened 2024-10-30 15:34 UTC by sai-harsha-vardhan

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

add start_redirection api for three_ds flow in v2
1. introduce next_action block in confirm intent response and add support for three_ds flow of card payments
2. add start_redirection api to support three ds flow for card payments in v2

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Tested Manually
1. create a payment with authentication_type: three_ds
CURL
```
curl --location '{{BASE_URL}}/v2/payments/create-intent' \
--header 'api-key: {{API_KEY}}' \
--header 'X-Profile-Id: {{PROFILE_ID}}' \
--header 'Content-Type: application/json' \
--data '{
    "amount_details": {
        "order_amount": 100,
        "currency": "USD"
    },
    "authentication_type": "three_ds"
}'
```
Response
```
{
    "id": "12345_pay_0192dd8aae0b7050af8ff8849326fefb",
    "amount_details": {
        "order_amount": 100,
        "currency": "USD",
        "shipping_cost": null,
        "order_tax_amount": null,
        "skip_external_tax_calculation": "Skip",
        "skip_surcharge_calculation": "Skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null
    },
    "client_secret": "12345_pay_0192dd8aae0b7050af8ff8849326fefb_secret_0192dd8aae0b7050af8ff896254521c8",
    "merchant_reference_id": null,
    "routing_algorithm_id": null,
    "capture_method": "automatic",
    "authentication_type": "three_ds",
    "billing": null,
    "shipping": null,
    "customer_id": null,
    "customer_present": "Present",
    "description": null,
    "return_url": null,
    "setup_future_usage": "on_session",
    "apply_mit_exemption": "Skip",
    "statement_descriptor": null,
    "order_details": null,
    "allowed_payment_method_types": null,
    "metadata": null,
    "connector_metadata": null,
    "feature_metadata": null,
    "payment_link_enabled": "Skip",
    "payment_link_config": null,
    "request_incremental_authorization": "default",
    "expires_on": "2024-10-30T13:23:26.251Z",
    "frm_metadata": null,
    "request_external_three_ds_authentication": "Skip"
}
```

2. confirm a payment and get the next_action block for redirect_url
CURL
```
curl --location '{{BASE_URL}}/v2/payments/{{PAYMENT_ID}}/confirm-intent' \
--header 'Content-Type: application/json' \
--header 'X-Profile-Id: {{PROFILE_ID}}' \
--header 'X-Client-Secret: {{CLIENT_SECRET}}' \
--data '{
    "payment_method_data": {
            "card": {
                "card_number": "4242424242424242",
                "card_exp_month": "01",
                "card_exp_year": "2097",
                "card_holder_name": "John Doe",
                "card_cvc": "100"
            }
    },
    "payment_method_type": "card",
    "payment_method_subtype": "credit",
    "browser_info": {
        "user_agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/70.0.3538.110 Safari\/537.36",
        "accept_header": "text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/webp,image\/apng,*\/*;q=0.8",
        "language": "nl-NL",
        "color_depth": 24,
        "screen_height": 723,
        "screen_width": 1536,
        "time_zone": 0,
        "java_enabled": true,
        "java_script_enabled": true,
        "ip_address": "125.0.0.1"
    }
}'
```
Response:
```
{
    "id": "12345_pay_0192dd8aae0b7050af8ff8849326fefb",
    "status": "requires_customer_action",
    "amount": {
        "order_amount": 100,
        "currency": "USD",
        "shipping_cost": null,
        "order_tax_amount": null,
        "skip_external_tax_calculation": "Skip",
        "skip_surcharge_calculation": "Skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null,
        "net_amount": 100,
        "amount_to_capture": null,
        "amount_capturable": 0,
        "amount_captured": null
    },
    "connector": "checkout",
    "client_secret": "12345_pay_0192dd8aae0b7050af8ff8849326fefb_secret_0192dd8aae0b7050af8ff896254521c8",
    "created": "2024-10-30T13:08:26.251Z",
    "payment_method_data": null,
    "payment_method_type": "card",
    "payment_method_subtype": "credit",
    "next_action": {
        "type": "redirect_to_url",
        "redirect_to_url": "http://localhost:8080/v2/payments/12345_pay_0192dd8aae0b7050af8ff8849326fefb/start_redirection?merchant_id=cloth_seller1_CLporg83u4dFG54nP7z3"
    },
    "connector_transaction_id": "pay_zwj4ebatyseeppxcqv7fsjkz7u",
    "connector_reference_id": null,
    "merchant_connector_id": "mca_uxXfZhmnm6sRI6fOgDiw",
    "browser_info": null,
    "error": null
}
```

3. click on the redirect_url to see the redirection going to connector page
![image](https://github.com/user-attachments/assets/423d2985-dcca-43c3-b9d5-e32829e26ead)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-11-04 06:05 UTC, Narayanbhat166 commented on v2_migrations/2024-08-28-081838_update_v2_primary_key_constraints/up.sql
> +ALTER TABLE payment_intent
This is already run on the above line right?

2024-11-04 06:31 UTC, jarnura requested changes

2024-11-04 06:31 UTC, jarnura commented on crates/api_models/src/payments.rs
> +    /// The identifier for the Merchant Account.
We should include profile-id also

2024-11-04 06:31 UTC, jarnura commented on crates/router/src/core/payments.rs
> +pub async fn payment_start_redirection(
@sai-harsha-vardhan can you confirm this, are we using any connector related calls, if using those why we are using also.

2024-11-04 11:48 UTC, Narayanbhat166 commented on crates/router/src/core/payments.rs
> +pub async fn payment_start_redirection(
we are not doing any connector call, but some information related to payment instrument is required for a connector. So we fetch these details from the temp locker.

2024-11-04 13:25 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments.rs
> +pub async fn payment_start_redirection(
@SamraatBansal can you please confirm this?

2024-11-04 14:11 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments.rs
> +            Err(errors::ApiErrorResponse::PaymentUnexpectedState {
I'll add a TODO for this

2024-11-04 14:35 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments.rs
> +pub async fn payment_start_redirection(
I can see that we're using card_cvc in bluesnap redirect form, is it needed? @SamraatBansal 
```
RedirectForm::BlueSnap {
            payment_fields_token,
        } => {
            let card_details = if let Some(PaymentMethodData::Card(ccard)) = payment_method_data {
                format!(
                    "var saveCardDirectly={{cvv: \"{}\",amount: {},currency: \"{}\"}};",
                    ccard.card_cvc.peek(),
                    amount,
                    currency
                )
            } else {
                "".to_string()
            };
```

2024-11-05 07:54 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments.rs
> +pub async fn payment_start_redirection(
we are currently not supporting payment method data fetch in this API, as it is an open API without authentication. We will need to verify the connector implementation when necessary, as sending card_cvc to the client is not the appropriate way to handle this flow @Narayanbhat166

2024-11-05 08:48 UTC, Narayanbhat166 approved these changes

2024-11-05 08:48 UTC, Narayanbhat166 commented on crates/hyperswitch_domain_models/src/payments.rs
> +    pub fn create_start_redirection_url(&self, base_url: &str) -> String {
this should ideally give out `url` type

2024-11-05 08:48 UTC, Narayanbhat166 commented on crates/router/src/core/payments.rs
> +pub async fn payment_start_redirection(
Okay sure, makes sense to not expose card details in this api.

2024-11-05 08:48 UTC, Narayanbhat166 commented on crates/router/src/core/payments.rs
> +    helpers::authenticate_client_secret(Some(&payment_intent.client_secret), &payment_intent)?;
we are passing the same client secret here? should we not take the client secret in the api query params?

2024-11-05 08:48 UTC, Narayanbhat166 commented on crates/router/src/core/payments.rs
> +            amount: payment_intent.amount_details.order_amount.to_string(),
where do we need amount? should this be net amount from payment attempt?

2024-11-06 06:07 UTC, jarnura approved these changes

2024-11-06 08:02 UTC, Narayanbhat166 approved these changes

2024-11-06 08:37 UTC, apoorvdixit88 approved these changes

2024-11-06 08:43 UTC, tsdk02 approved these changes

2024-11-06 08:44 UTC, ThisIsMani approved these changes
You can create an issue and pick these up in a different PR, approving for now.

2024-11-06 08:44 UTC, ThisIsMani commented on crates/router/src/services/authentication.rs
> +            })?;
NIT: Can you `to_not_found_response` instead.

2024-11-06 08:44 UTC, ThisIsMani commented on crates/router/src/services/authentication.rs
> +            .find_business_profile_by_profile_id(
```suggestion
          .find_business_profile_by_profile_id_merchant_id(
```

2024-11-08 10:05 UTC, Narayanbhat166 approved these changes

2024-11-08 10:07 UTC, ThisIsMani approved these changes

2024-11-08 10:07 UTC, apoorvdixit88 approved these changes

2024-11-08 10:13 UTC, tsdk02 approved these changes

2024-11-08 10:23 UTC, jarnura approved these changes

2024-11-08 14:57 UTC, merged