feat:H1083-L1-L3-L4-L5 [Payment Authorise and Sync] + [Refunds and Sync] + [Redirection Flow (BNPL)] + [3DS Payment and Sync] for MultiSafePay
juspay/hyperswitch pull request #652
Opened 2023-02-25 14:47 UTC by jagan-jaya

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Implemented
`L1 - Payment Authorise and Sync`
`L3 - Refunds and Sync`
`L4 - Redirection Flow (BNPL)`
`L5 - 3DS Payment and Sync`

Not supported from Connector
`L2 - Manual Capture and Sync` 
`L6 - Mandate Flow`

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
Tested via. [Postman](https://drive.google.com/file/d/1M-Vu2XUsg8gsOgW25Du-vNTom4XDDun5/view?usp=sharing)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-02-25 15:44 UTC, ArjunKarthik requested changes

2023-02-25 15:44 UTC, ArjunKarthik commented on crates/router/src/connector/worldline/transformers.rs
> +            _ => Self::Visa,
Default should throw error saying PaymentMethod/Issuer not supported, as this can prevent Create Payment api call with wrong product ID.

2023-02-25 17:01 UTC, ArjunKarthik requested changes

2023-02-25 17:01 UTC, ArjunKarthik commented on crates/router/src/connector/multisafepay.rs
> +        let response: multisafepay::MultisafepayErrorResponse = res
We can move this logic to `build_error_response`

2023-02-26 10:01 UTC, ArjunKarthik approved these changes

2023-02-26 10:24 UTC, jagan-jaya commented
Closing this PR as it is not directly raised by actual contributors

2023-02-26 10:24 UTC, closed without merging