feat:H1083-L1-L3-L4-L5 [Payment Authorise and Sync] + [Refunds and Sync] + [Redirection Flow (BNPL)] + [3DS Payment and Sync] for MultiSafePay
juspay/hyperswitch pull request #658
Opened 2023-02-26 10:25 UTC by rupakrajak

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Implemented
`L1 - Payment Authorise and Sync`
`L3 - Refunds and Sync`
`L4 - Redirection Flow (BNPL)`
`L5 - 3DS Payment and Sync`

Not supported from Connector
`L2 - Manual Capture and Sync` 
`L6 - Mandate Flow`

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?
Tested via. [Postman](https://drive.google.com/file/d/1M-Vu2XUsg8gsOgW25Du-vNTom4XDDun5/view?usp=sharing)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-02-26 15:21 UTC, ArjunKarthik approved these changes

2023-02-27 19:43 UTC, jagan-jaya submitted a review, later dismissed

2023-02-27 22:25 UTC, jarnura requested changes

2023-02-27 22:25 UTC, jarnura commented on crates/router/src/configs/settings.rs
> +    pub multisafepay: ConnectorParams,
move this above

2023-02-27 22:25 UTC, jarnura commented on crates/router/src/connector/multisafepay/transformers.rs
> +    pub card_holder_name: Option<String>,
Add secrets for PII information

2023-02-27 22:25 UTC, jarnura commented on crates/router/src/connector/multisafepay.rs
> +        let api_key = self.get_auth_header(&req.connector_auth_type)?[0].1.clone();
remove indexing of `0`, this will cause panics, use safer function like `first` or `iter().next()`

2023-02-27 22:25 UTC, jarnura commented on crates/router/src/connector/multisafepay.rs
> +        let api_key = self.get_auth_header(&req.connector_auth_type)?[0].1.clone();
Same here , avoid indexing with id's

2023-02-27 22:25 UTC, jarnura commented on crates/router/src/connector/multisafepay.rs
> +        let api_key = self.get_auth_header(&req.connector_auth_type)?[0].1.clone();
Same here , avoid indexing with id's

2023-02-27 22:55 UTC, ArjunKarthik approved these changes

2023-02-27 22:59 UTC, jarnura requested changes

2023-02-27 23:06 UTC, jarnura approved these changes

2023-02-27 23:46 UTC, merged