refactor(connector): Move connectors Bamboraapac, Boku, Gocardless,  Prophetpay, Rapyd
juspay/hyperswitch pull request #6652
Opened 2024-11-25 08:23 UTC by spritianeja03

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Moved connectors Bamboraapac, Boku, Ebanx, Gocardless, Prophetpay and Rapyd from router crate to hyperswitch_connectors crate

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Rapyd: Testing not possible because account has been deactivated
---
Prophetpay
1. Merchant Account Create
```
curl --location 'http://localhost:8080/accounts' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: test_admin' \
--data-raw '{"merchant_id":"postman_merchant_GHAction_cb9398ef-f35f-46f1-b811-da024a94bba5","locker_id":"m0010","merchant_name":"NewAge Retailer","merchant_details":{"primary_contact_person":"John Test","primary_email":"JohnTest@test.com","primary_phone":"sunt laborum","secondary_contact_person":"John Test2","secondary_email":"JohnTest2@test.com","secondary_phone":"cillum do dolor id","website":"www.example.com","about_business":"Online Retail with a wide selection of organic products for North America","address":{"line1":"1467","line2":"Harrison Street","line3":"Harrison Street","city":"San Fransico","state":"California","zip":"94122","country":"US"}},"return_url":"https://duck.com","webhook_details":{"webhook_version":"1.0.1","webhook_username":"ekart_retail","webhook_password":"password_ekart@123","payment_created_enabled":true,"payment_succeeded_enabled":true,"payment_failed_enabled":true},"sub_merchants_enabled":false,"metadata":{"city":"NY","unit":"245"},"primary_business_details":[{"country":"US","business":"default"}]}'
```
2. API Key Create
```
curl --location 'http://localhost:8080/api_keys/postman_merchant_GHAction_c6ca85d0-9cfe-4c63-b6f8-501e3bddec30' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: test_admin' \
--data '{"name":"API Key 1","description":null,"expiration":"2069-09-23T01:02:03.000Z"}'
```
3. Payment Connector Create
```
curl --location 'http://localhost:8080/account/postman_merchant_GHAction_c6ca85d0-9cfe-4c63-b6f8-501e3bddec30/connectors' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: test_admin' \
--data '{
    "connector_type": "payment_processor",
    "connector_name": "prophetpay",
    "connector_account_details": {
        "auth_type": "SignatureKey",
        "api_key": "*********",
        "api_secret": "***********",
        "key1": "**********"
    },
    "business_country": "US",
    "business_label": "default",
    "test_mode": false,
    "disabled": false,
    "payment_methods_enabled": [
        {
            "payment_method": "card_redirect",
            "payment_method_types": [
                {
                    "payment_method_type": "card_redirect",
                    "payment_experience": "redirect_to_url",
                    "card_networks": null,
                    "accepted_currencies": null,
                    "accepted_countries": null,
                    "minimum_amount": 1,
                    "maximum_amount": 68607706,
                    "recurring_enabled": true,
                    "installment_payment_enabled": true
                }
            ]
        }
    ],
    "metadata": {
        "city": "NY",
        "unit": "245"
    }
}'
```
4. Payments Create
```
curl --location 'http://localhost:8080/payments' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: dev_rkLYc4TkjKRGLZdY774ujcSF3ugQR4BNtXIET7kfST57QmW1eW7II9sTffhT2jv6' \
--data '{
    "amount": 10000,
    "currency": "USD",
    "confirm": true,
    "amount_to_capture": 10000,
    "business_country": "US",
    "customer_id": "not_a_rick_roll",
    "return_url": "https://www.google.com",
    "payment_method": "card_redirect",
    "payment_method_type": "card_redirect",
    "payment_method_data": {
        "card_redirect": {
            "card_redirect": {}
        }
    }
}'
```
Response
```
{
    "payment_id": "pay_Z4j23nC96dZRw1v9swbm",
    "merchant_id": "postman_merchant_GHAction_3bd2bcf9-fc0d-4bb3-9a92-9a7134405e12",
    "status": "requires_customer_action",
    "amount": 10000,
    "net_amount": 10000,
    "shipping_cost": null,
    "amount_capturable": 10000,
    "amount_received": null,
    "connector": "prophetpay",
    "client_secret": "pay_Z4j23nC96dZRw1v9swbm_secret_cl5RhD95NrOuiJcZCBDA",
    "created": "2024-12-03T12:17:06.875Z",
    "currency": "USD",
    "customer_id": "not_a_rick_roll",
    "customer": {
        "id": "not_a_rick_roll",
        "name": null,
        "email": null,
        "phone": null,
        "phone_country_code": null
    },
    "description": null,
    "refunds": null,
    "disputes": null,
    "mandate_id": null,
    "mandate_data": null,
    "setup_future_usage": null,
    "off_session": null,
    "capture_on": null,
    "capture_method": null,
    "payment_method": "card_redirect",
    "payment_method_data": {
        "card_redirect": {
            "card_redirect": {}
        },
        "billing": null
    },
    "payment_token": null,
    "shipping": null,
    "billing": null,
    "order_details": null,
    "email": null,
    "name": null,
    "phone": null,
    "return_url": "https://www.google.com/",
    "authentication_type": "no_three_ds",
    "statement_descriptor_name": null,
    "statement_descriptor_suffix": null,
    "next_action": {
        "type": "redirect_to_url",
        "redirect_to_url": "http://localhost:8080/payments/redirect/pay_Z4j23nC96dZRw1v9swbm/postman_merchant_GHAction_3bd2bcf9-fc0d-4bb3-9a92-9a7134405e12/pay_Z4j23nC96dZRw1v9swbm_1"
    },
    "cancellation_reason": null,
    "error_code": null,
    "error_message": null,
    "unified_code": null,
    "unified_message": null,
    "payment_experience": null,
    "payment_method_type": "card_redirect",
    "connector_label": "prophetpay_US_default",
    "business_country": "US",
    "business_label": "default",
    "business_sub_label": null,
    "allowed_payment_method_types": null,
    "ephemeral_key": {
        "customer_id": "not_a_rick_roll",
        "created_at": 1733228226,
        "expires": 1733231826,
        "secret": "epk_0fd4497cec8a45009e0ee050e9496bd9"
    },
    "manual_retry_allowed": null,
    "connector_transaction_id": null,
    "frm_message": null,
    "metadata": null,
    "connector_metadata": null,
    "feature_metadata": null,
    "reference_id": null,
    "payment_link": null,
    "profile_id": "pro_0rEpfGBRM6uOaedbCVgY",
    "surcharge_details": null,
    "attempt_count": 1,
    "merchant_decision": null,
    "merchant_connector_id": "mca_8TGosSooBN4mvfxJMDue",
    "incremental_authorization_allowed": null,
    "authorization_count": null,
    "incremental_authorizations": null,
    "external_authentication_details": null,
    "external_3ds_authentication_attempted": false,
    "expires_on": "2024-12-03T12:32:06.875Z",
    "fingerprint": null,
    "browser_info": null,
    "payment_method_id": null,
    "payment_method_status": null,
    "updated": "2024-12-03T12:17:07.306Z",
    "charges": null,
    "frm_metadata": null,
    "merchant_order_reference_id": null,
    "order_tax_amount": null,
    "connector_mandate_id": null
}
```
5. Payments Retrieve
```
curl --location 'http://localhost:8080/payments/pay_Z4j23nC96dZRw1v9swbm' \
--header 'Accept: application/json' \
--header 'api-key: dev_79y4Bk6BJl0eDg66Z97SHQfKMwairDyPC5uSDw7Tk5Eycai3G6VFMx4LyBhtVDct'
```
Response
```
{
    "payment_id": "pay_Z4j23nC96dZRw1v9swbm",
    "merchant_id": "postman_merchant_GHAction_3bd2bcf9-fc0d-4bb3-9a92-9a7134405e12",
    "status": "requires_customer_action",
    "amount": 10000,
    "net_amount": 10000,
    "shipping_cost": null,
    "amount_capturable": 10000,
     [...]

2024-12-02 10:40 UTC, deepanshu-iiitu requested changes

2024-12-02 10:40 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/rapyd/transformers.rs
> +// impl ForeignFrom<(RapydPaymentStatus, NextAction)> for enums::AttemptStatus {
Remove these comments

2024-12-02 10:40 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/rapyd/transformers.rs
> +// }
Remove these comments

2024-12-02 11:20 UTC, deepanshu-iiitu approved these changes

2024-12-02 12:03 UTC, Narayanbhat166 submitted a review, later dismissed

2024-12-02 14:41 UTC, SanchithHegde submitted a review, later dismissed

2024-12-04 11:40 UTC, deepanshu-iiitu approved these changes

2024-12-04 12:02 UTC, Narayanbhat166 approved these changes

2024-12-04 12:15 UTC, SanchithHegde approved these changes

2024-12-05 08:14 UTC, merged