feat(routing): build the gRPC interface for communicating with the external service to perform elimination routing
juspay/hyperswitch pull request #6672
Opened 2024-11-27 07:23 UTC by Aprabhat19

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
build the gRPC interface for communicating with the external service to perform elimination routing

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-11-27 12:52 UTC, Chethan-rao approved these changes

2024-12-06 08:28 UTC, Chethan-rao requested changes

2024-12-06 08:28 UTC, Chethan-rao commented on crates/external_services/src/grpc_client/dynamic_routing/elimination_rate_client.rs
> +                .bucket_ttl_in_mins
could u rename this too?

2024-12-06 08:49 UTC, Chethan-rao commented
please add test cases to all 3 endpoints and check the validations too

2024-12-06 08:49 UTC, Chethan-rao approved these changes

2024-12-09 10:23 UTC, NishantJoshi00 approved these changes

2024-12-09 10:23 UTC, NishantJoshi00 commented
> please add test cases to all 3 endpoints and check the validations too

+1 on that.

It would be better to have test cases. attached showing an example execution of these functionality.

2024-12-12 05:13 UTC, Aprabhat19 commented
> > please add test cases to all 3 endpoints and check the validations too
> 
> +1 on that.
> 
> It would be better to have test cases. attached showing an example execution of these functionality.

Okay sure

2024-12-13 05:41 UTC, merged