ci(cypress) : Add Session Token Testcases
juspay/hyperswitch pull request #6683
Opened 2024-11-27 13:57 UTC by Gnanasundari24

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [x] CI/CD

## Description
Added Session Token Call Testcases in cypress

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
 To include session token testcases in automation.

## How did you test it?
<img width="660" alt="Screenshot 2024-11-27 at 6 35 26 PM" src="https://github.com/user-attachments/assets/e43d53c1-5a12-4e39-b818-8a6213788f15">
<img width="1095" alt="Screenshot 2024-11-27 at 6 41 46 PM" src="https://github.com/user-attachments/assets/634c27f8-e6df-4b20-a1db-92978e32f063">
<img width="892" alt="Screenshot 2024-11-27 at 7 13 16 PM" src="https://github.com/user-attachments/assets/645a054f-fed5-4012-8b32-c62a372a4376">

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-11-29 10:36 UTC, jagan-jaya approved these changes

2024-11-29 10:36 UTC, jagan-jaya commented on cypress-tests/cypress/e2e/PaymentUtils/Cybersource.js
> +                domain_name: "hyperswitch-demo-store.netlify.app",
are those dummy values?

2024-11-29 12:33 UTC, jagan-jaya requested changes

2024-11-29 12:33 UTC, jagan-jaya commented on cypress-tests/cypress/e2e/PaymentUtils/Stripe.js
> +                  "Apple pay:6ACD34193A900BA07E215155E3647CF4759340CF486BABAEE6C0840F9267AB10",
remove/replace with dummy values if not already

2024-11-29 12:34 UTC, jagan-jaya commented on cypress-tests/cypress/e2e/PaymentUtils/Stripe.js
> +                  "Apple pay:6ACD34193A900BA07E215155E3647CF4759340CF486BABAEE6C0840F9267AB10",
move this to creds.json file it should not be hardcoded here

2025-01-02 10:26 UTC, pixincreate commented on cypress-tests/cypress/support/commands.js
> +        "x-merchant-domain": "hyperswitch - demo - store.netlify.app",
is the space intentional?

2025-01-03 10:18 UTC, SanchithHegde approved these changes
CI workflow changes look good to me!

2025-01-03 10:41 UTC, Gnanasundari24 commented on cypress-tests/cypress/support/commands.js
> +        "x-merchant-domain": "hyperswitch - demo - store.netlify.app",
This is how we are sending in frontend

2025-01-03 11:10 UTC, pixincreate approved these changes

2025-01-06 07:39 UTC, jagan-jaya approved these changes

2025-01-06 10:21 UTC, merged