feat(connector): [INESPAY] Sepa Bank Debit Auth and PSync Flow
juspay/hyperswitch pull request #6755
Opened 2024-12-05 08:14 UTC by ImSagnik007

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2025-01-07 10:35 UTC, AkshayaFoiger requested changes

2025-01-07 10:35 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/inespay.rs
> +        api::CurrencyUnit::Minor
Remove comments

2025-01-07 10:35 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/inespay.rs
> +        println!("{:?}<<>>", notif_item.signature_data_return);
Remove this logging

2025-01-09 07:34 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/inespay/transformers.rs
> +#[derive(Debug, Serialize, Default, Deserialize, Clone, PartialEq)]
Why do we have `#[allow(dead_code)]` ?

2025-01-09 07:34 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/inespay/transformers.rs
> +            | InespayRSyncStatus::Mistake => Self::Failure, //TODO: Review mapping
Is the review of mapping done ?, if yes please remove this comment

2025-01-09 10:40 UTC, AkshayaFoiger submitted a review, later dismissed

2025-01-13 07:01 UTC, AkshayaFoiger approved these changes

2025-01-23 06:55 UTC, deepanshu-iiitu approved these changes

2025-01-23 07:50 UTC, AkshayaFoiger approved these changes

2025-01-24 08:00 UTC, sai-harsha-vardhan approved these changes

2025-01-24 09:11 UTC, ShankarSinghC approved these changes
Add pr description.

2025-02-05 15:18 UTC, merged