feat(routing): Contract based routing integration
juspay/hyperswitch pull request #6761
Opened 2024-12-05 20:19 UTC by Sarthak1799

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- Built an interface for Contract based routing
- Integrated Contract based routing with hyperswitch
- Built new APIs for contract routing config setup
- Refactored some existing dynamic routing code

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-12-16 17:44 UTC, Chethan-rao requested changes

2024-12-16 17:44 UTC, Chethan-rao commented on crates/router/src/core/routing.rs
> +                    message: "Failed to invalidate the routing keys".to_string(),
```suggestion
                    message: "Failed to invalidate the contract based routing keys".to_string(),
```

2024-12-23 10:02 UTC, prajjwalkumar17 commented on crates/router/src/core/routing/helpers.rs
> +        core_metrics::DYNAMIC_CONTRACT_BASED_ROUTING.add(
I think Prometheus should be suffice, 
we can add something like for this particular `mca_id`, these many transactions went through this particular connector.

2024-12-24 12:07 UTC, Chethan-rao requested changes

2024-12-26 11:20 UTC, Sarthak1799 commented on crates/api_models/src/routing.rs
> +                    self.label_info = Some(vec![new_label_info.clone()]);
This case would only arise when we don't have any existing entries in the vec

2025-01-16 10:09 UTC, Chethan-rao requested changes

2025-01-16 10:09 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +    let mut connector_list = routable_connectors.clone();
no need to assign here since you are anyways doing `unwrap_or(routable_connectors);` at the end

2025-01-16 10:09 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +        .flatten()
why are you ignoring error here?

2025-01-16 10:09 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +        .flatten()
why are you ignoring error here?

2025-01-16 10:09 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +                "".to_string(),
will this be empty? makes sense since contract will be associated to id and label and not param but still just making sure

2025-01-16 10:09 UTC, Chethan-rao commented on crates/router/src/core/payments/operations/payment_response.rs
>                      .ok();
This will be called when

```
if payment_intent.status.is_in_terminal_state()
            && business_profile.dynamic_routing_algorithm.is_some()
```
`business_profile.dynamic_routing_algorithm.is_some()` is this enough to decide on whether to call sr and cr? should we parse the type outside before calling individual push metrics functions

2025-01-16 12:59 UTC, Sarthak1799 commented on crates/api_models/src/routing.rs
>      pub fn update_specific_ref(
The selected code updates the entire algorithm.

2025-01-16 13:02 UTC, Sarthak1799 commented on crates/router/src/core/payments/routing.rs
> +                "".to_string(),
We're not sending params for now, so this remains empty

2025-01-16 13:13 UTC, Sarthak1799 commented on crates/api_models/src/routing.rs
> +        }
This is updating the algorithm right?

2025-01-19 08:51 UTC, Chethan-rao requested changes

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/payments/operations/payment_response.rs
>              let business_profile = business_profile.clone();
you can only clone the `profile_id` instead of whole profile object since below methods only require id
```suggestion
            let profile_id = business_profile.get_id().clone();
```

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +        .inspect_err(|e| logger::error!("Dynamic_routing error {:?}", e))
can we follow the same logger fields everywhere for dynamic routing errors for quick and easy finding. Also since we are anyways dropping the error after this log and not propagating it, we can use map_err instead of inspect_err

```suggestion
        .map_err(|e| logger::error!(dynamic_routing_error=?e))
```

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +        .inspect_err(|e| logger::error!("Dynamic_routing error {:?}", e))
```suggestion
        .map_err(|e| logger::error!(dynamic_routing_error=?e))
```

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +        .attach_printable("unable to perform success_based_routing")
this `attach_printable` won't have any effect since we are not propagating the error but instead we are calling `.ok()` on Result. So we can remove this

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +        .attach_printable("unable to perform contract_based_routing")
Same here. remove this

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +            perform_contract_based_routing(
also do we want to go forward with performing contract based routing even if success based routing failed? because I see that you are only logging the error after success based failed and doing unwrap_or to original connector list

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
>      business_profile: &domain::Profile,
No need to receive whole profile object because I see that only profile_id is getting used in this method

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/payments/routing.rs
> +    business_profile: &domain::Profile,
same here, only get profile_id as argument

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/routing.rs
> +                })?;
can we do tokio join?

2025-01-19 08:51 UTC, Chethan-rao commented on crates/router/src/core/routing.rs
> +                timestamp: common_utils::date_time::now_unix_timestamp(),
call `DynamicAlgorithmWithTimestamp::new`

2025-01-19 08:52 UTC, Chethan-rao commented on crates/router/src/core/routing.rs
> +pub async fn contract_based_dynamic_routing_setup(
why didn't you make use of existing `toggle_specific_dynamic_routing` function to activate

2025-01-19 11:39 UTC, Sarthak1799 commented on crates/router/src/core/payments/routing.rs
> +        .inspect_err(|e| logger::error!("Dynamic_routing error {:?}", e))
Can you give more reasoning into why `map_err` instead?

2025-01-19 11:58 UTC, Sarthak1799 commented on crates/router/src/core/routing.rs
> +pub async fn contract_based_dynamic_routing_setup(
Because CR cannot be set to default, we can use that for routing types that can be always be toggled to some default config.

2025-01-19 12:48 UTC, Sarthak1799 commented on crates/router/src/core/payments/operations/payment_response.rs
> +                    .unwrap_or_default();
let expressions in the same condition are unstable. We'd have to have two nested loops then. 
I'll try to find a way better way of doing this

2025-01-19 12:51 UTC, Sarthak1799 commented on crates/router/src/core/payments/routing.rs
> +            perform_contract_based_routing(
Success routing can only fail here if,
It's set up but call fails, in this case contract won't be activated so the call won't happen.
It's not set up, in which case call won't happen and contract call would take place next.

2025-01-19 16:31 UTC, Chethan-rao requested changes

2025-01-19 16:31 UTC, Chethan-rao commented on crates/router/src/core/routing/helpers.rs
>      success_based_routing_id: id_type::RoutingId,
since this is generic function now rename this parameter to `routing_id`

2025-01-19 16:31 UTC, Chethan-rao commented on crates/router/src/core/routing/helpers.rs
> +            get_desired_payment_status_for_success_routing_metrics(payment_attempt.status);
name this method generic as this is being called in both sr and cr

2025-01-19 16:31 UTC, Chethan-rao commented on crates/router/src/core/routing/helpers.rs
> +        let outcome = get_success_based_metrics_outcome_for_payment(
same here, name it generic

2025-01-19 16:31 UTC, Chethan-rao commented on crates/router/src/core/routing/helpers.rs
> +        core_metrics::DYNAMIC_CONTRACT_BASED_ROUTING.add(
Should this metric be pushed only if `payment_status_attribute` is `charged`?

2025-01-19 16:31 UTC, Chethan-rao commented on crates/router/src/core/routing/helpers.rs
> +                dynamic_routing.clone(), // check this in review
comment?

2025-01-19 16:31 UTC, Chethan-rao commented on crates/router/src/core/routing/helpers.rs
> +        // Should we provide a default for this?
comment?

2025-01-19 17:40 UTC, Sarthak1799 commented on crates/router/src/core/routing/helpers.rs
> +        // Should we provide a default for this?
Won't go ahead with default

2025-01-19 17:40 UTC, Sarthak1799 commented on crates/router/src/core/routing/helpers.rs
> +                dynamic_routing.clone(), // check this in review
Was to check the updation logic above, removing this.

2025-01-20 13:29 UTC, Chethan-rao approved these changes

2025-01-20 16:15 UTC, tsdk02 submitted a review, later dismissed

2025-01-21 10:37 UTC, prajjwalkumar17 submitted a review, later dismissed

2025-01-21 10:37 UTC, prajjwalkumar17 commented on crates/router/src/core/payments/routing.rs
> +    );
Can we possible log this once the `dynamic_routing_algorithm` is found in `profile` and is de-serialized, So that we will be certain that dynamic_routing will be performed for sure. Right now if the algo is not found, the action won't happen itself.
Basically after line 1310.

2025-01-21 10:37 UTC, prajjwalkumar17 commented on crates/router/src/core/payments/routing.rs
> +    _dynamic_routing_config_params_interpolator: routing::helpers::DynamicRoutingConfigParamsInterpolator,
Can we remove this, if redundant ?

2025-01-21 16:52 UTC, Sarthak1799 commented on crates/router/src/core/payments/routing.rs
> +    _dynamic_routing_config_params_interpolator: routing::helpers::DynamicRoutingConfigParamsInterpolator,
Had kept this as we had decided to use the params in the upcoming PRs,

2025-01-21 18:02 UTC, Chethan-rao submitted a review, later dismissed

2025-01-27 12:05 UTC, NishantJoshi00 reviewed
Looks good, some questions:
1. Is this enabled by default?
2. Have you tested if this works for a contract?
3. Where are the state for this being stored?
4. Where is the flow this is being called?
5. Are any interactions with dynamic routing service in the critical path (if so, how do we handle network failures)
6. I was able to see some caching changes, will this affect the state management for managing contract.


I think its imperative to follow micro PR model to avoid such confusions; 
1. it becomes difficult to follow the code changes.
2. Such massive changes can hide bugs which are difficult to find due to its sheer size.

2025-01-27 12:48 UTC, Sarthak1799 commented
- We have to enable contract based routing using setup APIs introduced in this PR
- have tested the flow locally
- The actual config is stored in `routing_algorithm` with it's ref stored in profile, like all other DR algorithms
- Similar to other routing types, this will be called in the payment flow, if the contract based algo is enabled.
- In case of Dynamic routing failure, the list of eligible of connectors are defaulted to the list from static routing
- The caching changes here are to make the caching code generic to all categories of Dynamic routing (SR, ER, Contracts) and making use of specific functions from redis interface (like `get_or_populate_in_memory`)
cc: @Chethan-rao 


Agreed on the micro PR model @NishantJoshi00, had thought about breaking up in several PRs but much of the reviews were already completed at the time.

2025-01-28 15:11 UTC, NishantJoshi00 submitted a review, later dismissed

2025-01-28 15:49 UTC, tsdk02 submitted a review, later dismissed

2025-02-05 19:05 UTC, NishantJoshi00 approved these changes

2025-02-06 05:12 UTC, Chethan-rao approved these changes

2025-02-06 05:19 UTC, tsdk02 approved these changes

2025-02-06 14:35 UTC, merged