Add ctp support
juspay/hyperswitch pull request #6769
Opened 2024-12-06 11:29 UTC by sahkal

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-12-13 10:45 UTC, jarnura requested changes

2024-12-13 10:45 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_confirm.rs
> +use hyperswitch_domain_models::router_request_types::unified_authentication_service::UasAuthenticationResponseData;
```suggestion
use hyperswitch_domain_models::router_request_types::unified_authentication_service;
```

2024-12-13 10:45 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_confirm.rs
> +        println!("logg1 {:?}", payment_data.payment_method_data);
remove println

2024-12-13 10:45 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_confirm.rs
> +                    Ok(UasAuthenticationResponseData::PreAuthentication {}) => {
For PreAuthentication we creating authentication entry?

2024-12-13 10:46 UTC, jarnura requested changes

2024-12-13 10:46 UTC, jarnura commented on crates/router/src/core/payments/operations/payment_confirm.rs
> +                let network_token = match response.response.clone() {
Return status from the branch and have one                         unified_authentication_service::create_new_authentication(

2024-12-13 17:31 UTC, jarnura approved these changes

2024-12-16 07:49 UTC, deepanshu-iiitu approved these changes

2024-12-16 10:28 UTC, prajjwalkumar17 approved these changes

2024-12-16 13:44 UTC, likhinbopanna approved these changes

2024-12-16 14:25 UTC, merged