feat(payment_methods): add support to pass apple pay recurring details to obtain apple pay merchant token
juspay/hyperswitch pull request #6770
Opened 2024-12-06 12:20 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-12-10 13:53 UTC, jarnura requested changes

2024-12-10 13:53 UTC, jarnura commented on crates/api_models/src/payments.rs
> +    pub management_url: String,
Use Url type

2024-12-10 13:53 UTC, jarnura commented on crates/api_models/src/payments.rs
> +    pub amount: String,
We should not allow pass amount here, we need to derive this from intent.

2024-12-10 13:53 UTC, jarnura commented on crates/api_models/src/payments.rs
> +    pub amount: i32,
We should not allow pass amount here, we need to derive this from intent.

2024-12-17 12:51 UTC, sai-harsha-vardhan approved these changes

2024-12-18 06:23 UTC, jarnura approved these changes

2024-12-19 13:32 UTC, merged