feat(core): Core changes for support overcapture
juspay/hyperswitch pull request #6824
Opened 2024-12-12 07:09 UTC by AkshayaFoiger

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Overcapture allows you to capture with an amount that’s higher than the authorised amount for a card payment. Unlike incremental authorisations, overcapture doesn’t result in additional authorisations with the card networks.

### Additional Changes

- [x] This PR modifies the API contract
- [x] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-12-24 07:19 UTC, deepanshu-iiitu requested changes

2024-12-24 07:19 UTC, deepanshu-iiitu commented on crates/router/src/connector/adyen/transformers.rs
> +        );
Can we please remove this?

2025-01-02 07:58 UTC, hrithikesh026 commented on crates/common_utils/src/types.rs
> +    pub maximum_capturable_amount: Option<MinorUnit>,
There already is an `amount_capturable` column in attempt. we can use that

2025-01-02 07:58 UTC, hrithikesh026 commented on crates/common_utils/src/types.rs
> +    pub overcaptured_amount: Option<MinorUnit>,
`amount_captured` field in payment_intent can be used instead.

2025-01-02 07:58 UTC, hrithikesh026 commented on crates/common_utils/src/types.rs
> +pub struct OvercaptureData {
Lets just create `request_overcapture` and `overcapture_applied` field on payment_attempt instead of having this struct. Will be helpful for analytics.

2025-01-02 07:58 UTC, hrithikesh026 commented on crates/diesel_models/src/payment_attempt.rs
> +    pub overcapture_details: Option<common_utils::types::OvercaptureData>,
create new individual columns for each field instead of struct.

2025-01-02 07:58 UTC, hrithikesh026 commented on crates/hyperswitch_domain_models/src/router_data.rs
> +    pub request_overcapture: Option<bool>,
This should be added in `struct PaymentsAuthorizedata`

2025-01-02 07:58 UTC, hrithikesh026 commented on crates/hyperswitch_domain_models/src/router_data.rs
> +    pub request_overcapture: Option<bool>,
The connector response can be populated in `RouterData::connector_response ` instead of `RouterData::response`.  This will lead to less code changes.

2025-01-08 07:33 UTC, hrithikesh026 commented on crates/router/src/services/api.rs
> +            }
Why is this needed?

2025-01-08 07:33 UTC, hrithikesh026 commented on crates/router/src/types.rs
> +            common_enums::CaptureMethod::Manual => maximum_capturable_amount.or(Some(payment_data.payment_attempt.get_total_amount())).map(|amount_capturable| amount_capturable.get_amount_as_i64()),
unwrap_or can be used instead of or

2025-01-08 07:33 UTC, hrithikesh026 commented on crates/router/src/types.rs
> +            common_enums::CaptureMethod::Manual => maximum_capturable_amount.or( Some(payment_data.payment_attempt.get_total_amount())).map(|amount_capturable|amount_capturable.get_amount_as_i64()),
unwrap_or can be used instead of or

2025-01-08 08:56 UTC, AkshayaFoiger commented on crates/api_models/src/admin.rs
> +    pub always_request_overcapture: bool,
No will remove this.

2025-01-08 09:00 UTC, AkshayaFoiger commented on crates/router/src/services/api.rs
> +            }
This was pushed by mistake

2025-01-08 10:38 UTC, AkshayaFoiger commented on crates/router/src/core/payments/operations/payment_update.rs
>          let surcharge_details = request.surcharge_details.map(|request_surcharge_details| {
For `payment_update`, we will validate this in `get_trackers()` because requires previously stored value of capture_method

2025-01-08 16:55 UTC, AkshayaFoiger commented on crates/router/src/core/payments/helpers.rs
> +    is_overcapture_applied: Option<bool>,
As `amount_capturable` is not a nullable value, we are not validating the amount with `net_amount`

2025-01-08 17:00 UTC, AkshayaFoiger commented on crates/router/src/core/payments/transformers.rs
> +        request_overcapture: None,
This field of `PaymentsAuthorizeData` is in use, here we are passing `None` value because we have not implemented overcapture for v2

2025-01-10 06:55 UTC, hrithikesh026 commented on crates/router/src/core/payments/helpers.rs
> +    is_overcapture_applied: Option<bool>,
But amount_to_capture must not be greater than amount_capturable right?

2025-01-17 04:51 UTC, hrithikesh026 submitted a review, later dismissed

2025-01-17 11:52 UTC, deepanshu-iiitu approved these changes

2025-01-17 11:57 UTC, sagarnaikjuspay approved these changes

2025-01-17 12:38 UTC, ThisIsMani approved these changes
Dashboard specific changes looks fine.

2025-01-19 13:59 UTC, sai-harsha-vardhan commented on crates/api_models/src/admin.rs
> +    pub always_request_overcapture: Option<bool>,
There's no need to have optional value for Boolean, unless there's any special meaning for value being null. You are anyways using serde default, so it should work fine even if you remove Option

2025-01-19 13:59 UTC, sai-harsha-vardhan commented on crates/api_models/src/admin.rs
> +    #[schema(default = false, example = false)]
There's no default false during ProfileUpdate

2025-01-19 13:59 UTC, sai-harsha-vardhan commented on crates/hyperswitch_domain_models/src/business_profile.rs
> +    pub always_request_overcapture: Option<bool>,
```suggestion
    pub always_request_overcapture: bool,
```

2025-01-19 13:59 UTC, sai-harsha-vardhan commented on crates/hyperswitch_domain_models/src/payments.rs
> +    pub request_overcapture: Option<storage_enums::OverCaptureRequest>,
```suggestion
    pub request_overcapture: storage_enums::OverCaptureRequest,
```

2025-01-19 13:59 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/helpers.rs
> +        request_overcapture == Some(api_enums::OverCaptureRequest::Enable)
We can have impl based fns for these checks, something like request_overcapture.is_enabled() && !capture_method.is_manual()

2025-01-19 13:59 UTC, sai-harsha-vardhan commented on crates/common_enums/src/transformers.rs
> +    pub fn as_bool(&self) -> bool {
All of this bool conversions could simply be impl based fns, something like OverCaptureStatus::is_applicable()

2025-01-19 13:59 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/operations/payment_create.rs
> +                    .and_then(|pmd: PaymentMethodsData| match pmd {
Is this change required?

2025-01-19 13:59 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/helpers.rs
> +    match payment_attempt.capture_method {
We could call `validate_overcapture_request` instead of this match here right?

2025-01-19 13:59 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/helpers.rs
> +            match payment_attempt.request_overcapture {
what's the case we are trying to handle here?

2025-01-21 12:33 UTC, AkshayaFoiger commented on crates/router/src/core/payments/helpers.rs
> +            match payment_attempt.request_overcapture {
This handles the case where request_overcapture is enabled, but capture method is not manual

2025-01-21 12:44 UTC, AkshayaFoiger commented on crates/api_models/src/admin.rs
> +    pub always_request_overcapture: Option<bool>,
request overcapture is treated differently for None and false

2025-01-21 12:48 UTC, AkshayaFoiger commented on crates/router/src/core/payments/operations/payment_create.rs
> +                    .and_then(|pmd: PaymentMethodsData| match pmd {
Not Required

2025-01-21 15:08 UTC, AkshayaFoiger commented on crates/router/src/core/payments/helpers.rs
> +    match payment_attempt.capture_method {
We still need to call the match statement because we have to set the value of `request_overcapture` in `payment_attempt`, only when the capture method is manual.

2025-01-22 07:59 UTC, sai-harsha-vardhan approved these changes

2025-01-22 08:58 UTC, ThisIsMani approved these changes

2025-01-22 09:09 UTC, hrithikesh026 submitted a review, later dismissed

2025-01-22 09:25 UTC, sai-harsha-vardhan submitted a review, later dismissed

2025-01-22 13:41 UTC, deepanshu-iiitu approved these changes

2025-01-24 08:57 UTC, jarnura submitted a review, later dismissed

2025-01-24 11:07 UTC, swangi-kumari submitted a review, later dismissed

2025-01-24 12:45 UTC, deepanshu-iiitu approved these changes

2025-02-25 09:19 UTC, hrithikesh026 commented on crates/hyperswitch_domain_models/src/business_profile.rs
> +            always_request_overcapture: None,
why is this none?

2025-02-25 09:49 UTC, hrithikesh026 commented on crates/router/src/core/payments/helpers.rs
> +                .is_manual()),
```suggestion
            && !(capture_method.is_some_and(|capture_method| capture_method.is_manual())),
```

2025-02-27 04:39 UTC, AkshayaFoiger commented on crates/hyperswitch_domain_models/src/business_profile.rs
> +            always_request_overcapture: None,
As overcapture is not implemented for v2 version,  `always_request_overcapture` is not added to the `ProfileSetter` struct of the v2 version.  Hence at this function we cannot access always_request_overcapture field.

2025-02-27 07:47 UTC, hrithikesh026 submitted a review, later dismissed
LGTM

2025-02-27 07:51 UTC, swangi-kumari approved these changes

2025-03-03 06:22 UTC, hrithikesh026 submitted a review, later dismissed

2025-03-03 08:51 UTC, deepanshu-iiitu submitted a review, later dismissed

2025-03-03 09:44 UTC, ThisIsMani approved these changes

2025-03-07 08:23 UTC, hrithikesh026 approved these changes

2025-03-07 08:35 UTC, swangi-kumari approved these changes

2025-03-07 08:35 UTC, ThisIsMani submitted a review, later dismissed

2025-03-07 09:17 UTC, deepanshu-iiitu approved these changes

2025-03-07 13:03 UTC, jarnura submitted a review, later dismissed

2025-03-24 11:27 UTC, deepanshu-iiitu submitted a review, later dismissed

2025-03-24 11:43 UTC, ThisIsMani submitted a review, later dismissed

2025-03-24 11:46 UTC, hrithikesh026 submitted a review, later dismissed

2025-03-24 11:54 UTC, swangi-kumari submitted a review, later dismissed

2025-04-15 08:23 UTC, AkshayaFoiger commented
@CodiumAI-Agent /review

2025-04-15 08:25 UTC, CodiumAI-Agent commented
## PR Reviewer Guide 🔍

Here are some key observations to aid the review process:

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 5 🔵🔵🔵🔵🔵</td></tr>
<tr><td>🧪&nbsp;<strong>PR contains tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Recommended focus areas for review</strong><br><br>

<details><summary><a href='https://github.com/juspay/hyperswitch/pull/6824/files#diff-f0784ab665a40d6a96f6f52e548bcd7ac7a86a119f2d1b46cb9c3d900bf92542R7426-R7472'><strong>Validation Logic</strong></a>

The new functions validate_overcapture_request and validate_and_get_overcapture_status add business logic for overcapture. Please ensure their edge-case handling and error messages correctly cover scenarios when the capture method is not manual.
</summary>

```rust
pub fn validate_overcapture_request(
    capture_method: Option<api_enums::CaptureMethod>,
    request_overcapture: Option<api_enums::OverCaptureRequest>,
) -> Result<(), errors::ApiErrorResponse> {
    utils::when(
        request_overcapture.is_some_and(|request_overcapture| request_overcapture.is_enabled())
            && !(capture_method.is_some_and(|capture_method| capture_method.is_manual())),
        || {
            Err(errors::ApiErrorResponse::PreconditionFailed {
                message: "Requesting overcapture is only supported when the capture method is set to manual".to_string(),
            })
        },
    )
}

#[cfg(feature = "v1")]
pub fn validate_and_get_overcapture_status(
    capture_method: &Option<storage_enums::CaptureMethod>,
    request_overcapture: &Option<api_enums::OverCaptureRequest>,
    profile: &domain::Profile,
    confirm: bool,
) -> Result<Option<api_enums::OverCaptureStatus>, errors::ApiErrorResponse> {
    if let Some(api_enums::CaptureMethod::Manual) = capture_method {
        let is_overcapture_applied = match *request_overcapture {
            Some(request_overcapture) => {
                Some(api_enums::OverCaptureStatus::from(request_overcapture))
            }
            None => {
                if confirm {
                    profile
                        .always_request_overcapture
                        .map(api_enums::OverCaptureStatus::from)
                } else {
                    None
                }
            }
        };
        Ok(is_overcapture_applied)
    } else {
        request_overcapture.map_or(
            Ok(None),
            |_| Err(errors::ApiErrorResponse::PreconditionFailed {
                message: "Requesting overcapture is only supported when the capture method is set to manual".to_string(),
            })
        )
    }
}
```

</details>

<details><summary><a href='https://github.com/juspay/hyperswitch/pull/6824/files#diff-955707712c9bdbbd986dc29a9dd001579001580cf0a65e286ac8a2a25a2a49f2R7567-R8110'><strong>Enum Conversions</strong></a>

The implementations that convert between OverCaptureRequest and OverCaptureStatus (including From<bool> and other utility methods) should be reviewed to ensure they consistently reflect business intent and cover all cases.
</summary>

```rust
    Skip,
}

/// Whether overcapture is requested for the payment
#[derive(
    Clone,
    Copy,
    Debug,
    Default,
    Eq,
    Hash,
    PartialEq,
    ToSchema,
    serde::Deserialize,
    serde::Serialize,
    strum::Display,
    strum::EnumIter,
    strum::EnumString,
)]
#[router_derive::diesel_enum(storage_type = "text")]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum OverCaptureRequest {
    /// Request for applying overcapture
    Enable,
    /// Skip overcapture
    #[default]
    Skip,
}

/// Whether overcapture is applicable for the payment
#[derive(
    Clone,
    Copy,
    Debug,
    Default,
    Eq,
    Hash,
    PartialEq,
    ToSchema,
    serde::Deserialize,
    serde::Serialize,
    strum::Display,
    strum::EnumIter,
    strum::EnumString,
)]
#[router_derive::diesel_enum(storage_type = "text")]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum OverCaptureStatus {
    /// Overcapture is allowed
    Applicable,
    /// Overcapture is not allowed
    #[default]
    NotApplicable,
}

/// Whether payment link is requested to be enabled or not for this transaction
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize, Default, ToSchema)]
pub enum EnablePaymentLinkRequest {
    /// Request for enabling payment link
    Enable,
    /// Skip enabling payment link
    #[default]
    Skip,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize, Default, ToSchema)]
pub enum MitExemptionRequest {
    /// Request for applying MIT exemption
    Apply,
    /// Skip applying MIT exemption
    #[default]
    Skip,
}

/// Set to `present` to indicate that the customer is in your checkout flow during this payment, and therefore is able to authenticate. This parameter should be `absent` when merchant's doing merchant initiated payments and customer is not present while doing the payment.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize, Default, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum PresenceOfCustomerDuringPayment {
    /// Customer is present during the payment. This is the default value
    #[default]
    Present,
    /// Customer is absent during the payment
    Absent,
}

impl From<ConnectorType> for TransactionType {
    fn from(connector_type: ConnectorType) -> Self {
        match connector_type {
            #[cfg(feature = "payouts")]
            ConnectorType::PayoutProcessor => Self::Payout,
            _ => Self::Payment,
        }
    }
}

impl From<RefundStatus> for RelayStatus {
    fn from(refund_status: RefundStatus) -> Self {
        match refund_status {
            RefundStatus::Failure | RefundStatus::TransactionFailure => Self::Failure,
            RefundStatus::ManualReview | RefundStatus::Pending => Self::Pending,
            RefundStatus::Success => Self::Success,
        }
    }
}

impl From<RelayStatus> for RefundStatus {
    fn from(relay_status: RelayStatus) -> Self {
        match relay_status {
            RelayStatus::Failure => Self::Failure,
            RelayStatus::Pending | RelayStatus::Created => Self::Pending,
            RelayStatus::Success => Self::Success,
        }
    }
}

#[derive(
    Clone, Copy, Debug, PartialEq, serde::Serialize, serde::Deserialize, Default, ToSchema,
)]
#[serde(rename_all = "snake_case")]
pub enum TaxCalculationOverride {
    /// Skip calling the external tax provider
    #[default]
    Skip,
    /// Calculate tax by calling the external tax provider
    Calculate,
}

impl From<Option<bool>> for TaxCalculationOverride {
    fn from(value: Option<bool>) -> Self {
        match value {
            Some(true) => Self::Calculate,
            _ => Self::Skip,
        }
    }
}

impl TaxCalculationOverride {
    pub fn as_bool(self) -> bool {
        match self {
            Self::Skip => false,
            Self::Calculate => true,
        }
    }
}

#[derive(
    Clone, Copy, Debug, PartialEq, serde::Serialize, serde::Deserialize, Default, ToSchema,
)]
#[serde(rename_all = "snake_case")]
pub enum SurchargeCalculationOverride {
    /// Skip calculating surcharge
    #[default]
    Skip,
    /// Calculate surcharge
    Calculate,
}

impl From<Option<bool>> for SurchargeCalculationOverride {
    fn from(value: Option<bool>) -> Self {
        match value {
            Some(true) => Self::Calculate,
            _ => Self::Skip,
        }
    }
}

impl SurchargeCalculationOverride {
    pub fn as_bool(self) -> bool {
        match self {
            Self::Skip => false,
            Self::Calculate => true,
        }
    }
}

/// Connector Mandate Status
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize, strum::Display,
)]
#[strum(serialize_all = "snake_case")]
#[serde(rename_all = "snake_case")]
pub enum ConnectorMandate [...]

2025-04-15 09:08 UTC, AkshayaFoiger commented
@CodiumAI-Agent /review

2025-04-15 09:09 UTC, CodiumAI-Agent commented
## PR Reviewer Guide 🔍

Here are some key observations to aid the review process:

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 5 🔵🔵🔵🔵🔵</td></tr>
<tr><td>🧪&nbsp;<strong>PR contains tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Recommended focus areas for review</strong><br><br>

<details><summary><a href='https://github.com/juspay/hyperswitch/pull/6824/files#diff-f0784ab665a40d6a96f6f52e548bcd7ac7a86a119f2d1b46cb9c3d900bf92542R7422-R7472'><strong>Overcapture Request Validation</strong></a>

The new validation functions (e.g. validate_overcapture_request) introduce logic that enforces overcapture only with manual capture. It is important to review that all edge cases are handled and that error responses are consistent with business rules.
</summary>

```rust

    Ok(())
}

pub fn validate_overcapture_request(
    capture_method: Option<api_enums::CaptureMethod>,
    request_overcapture: Option<api_enums::OverCaptureRequest>,
) -> Result<(), errors::ApiErrorResponse> {
    utils::when(
        request_overcapture.is_some_and(|request_overcapture| request_overcapture.is_enabled())
            && !(capture_method.is_some_and(|capture_method| capture_method.is_manual())),
        || {
            Err(errors::ApiErrorResponse::PreconditionFailed {
                message: "Requesting overcapture is only supported when the capture method is set to manual".to_string(),
            })
        },
    )
}

#[cfg(feature = "v1")]
pub fn validate_and_get_overcapture_status(
    capture_method: &Option<storage_enums::CaptureMethod>,
    request_overcapture: &Option<api_enums::OverCaptureRequest>,
    profile: &domain::Profile,
    confirm: bool,
) -> Result<Option<api_enums::OverCaptureStatus>, errors::ApiErrorResponse> {
    if let Some(api_enums::CaptureMethod::Manual) = capture_method {
        let is_overcapture_applied = match *request_overcapture {
            Some(request_overcapture) => {
                Some(api_enums::OverCaptureStatus::from(request_overcapture))
            }
            None => {
                if confirm {
                    profile
                        .always_request_overcapture
                        .map(api_enums::OverCaptureStatus::from)
                } else {
                    None
                }
            }
        };
        Ok(is_overcapture_applied)
    } else {
        request_overcapture.map_or(
            Ok(None),
            |_| Err(errors::ApiErrorResponse::PreconditionFailed {
                message: "Requesting overcapture is only supported when the capture method is set to manual".to_string(),
            })
        )
    }
}
```

</details>

<details><summary><a href='https://github.com/juspay/hyperswitch/pull/6824/files#diff-830775d3afed08ce65fae4f10a024ba07dc0972ecfd28f48b42a39c1f4bcd5cbR446-R459'><strong>Overcapture Data Consistency</strong></a>

Numerous modules now reference overcapture fields (e.g. request_overcapture and overcapture_status). Ensure that the data conversions and propagation of these fields remain consistent across the update, including in the transformation and conversion routines.
</summary>

```rust
    payments::types::SurchargeDetails::from((&request_surcharge_details, &payment_attempt))
});

payment_intent.request_overcapture = request
    .request_overcapture
    .or(payment_intent.request_overcapture);

payment_attempt.overcapture_status = helpers::validate_and_get_overcapture_status(
    &payment_attempt.capture_method,
    &request.request_overcapture,
    &business_profile,
    request.confirm.unwrap_or_default(),
)?;

```

</details>

</td></tr>
</table>

2025-04-16 12:16 UTC, AkshayaFoiger commented on crates/router/src/core/payments/operations/payment_update.rs
> -            .or(payment_intent.force_3ds_challenge);
This isn't an intended change. Reverted the change.

2025-04-16 12:28 UTC, hrithikesh026 approved these changes

2025-04-22 11:53 UTC, hrithikesh026 approved these changes

2025-04-23 07:27 UTC, jarnura requested changes

2025-04-23 07:27 UTC, jarnura commented on migrations/2025-04-10-084950_add_request_overcapture/up.sql
> +ALTER TABLE business_profile ADD COLUMN IF NOT EXISTS always_request_overcapture BOOLEAN DEFAULT NULL;
we should create nullable field, not null addition we shouldn't do

2025-04-23 07:27 UTC, jarnura commented on migrations/2025-04-10-084950_add_request_overcapture/up.sql
> +ALTER TABLE payment_attempt
we should create nullable field, not null addition we shouldn't do

2025-04-23 07:27 UTC, jarnura commented on migrations/2025-04-10-084950_add_request_overcapture/up.sql
> +ALTER TABLE payment_intent ADD COLUMN IF NOT EXISTS request_overcapture VARCHAR(32) DEFAULT NULL;
we should create nullable field, not null addition we shouldn't do

2025-04-24 11:00 UTC, AkshayaFoiger commented
Refactoring Work In Progress 🚧

2025-08-06 11:20 UTC, AkshayaFoiger commented
Task done in a different PR

2025-08-06 11:20 UTC, closed without merging