feat(connector): [Placetopay] Implement Card 3ds
juspay/hyperswitch pull request #6834
Opened 2024-12-13 08:13 UTC by swangi-kumari

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Implement Card 3ds for Placetopay

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-12-16 11:32 UTC, deepanshu-iiitu requested changes

2024-12-16 11:32 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/placetopay/transformers.rs
> +                let return_url = item.router_data.request.complete_authorize_url.clone();
Is the request body same for 3ds and non-3ds request?
Should we pass complete_authorize_url in case of non-3ds payments?

2024-12-16 11:32 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/placetopay/transformers.rs
> +            PlacetopayTransactionStatus::Ok => Self::AuthenticationPending,
Should we map ok to AuthenticationPending for non-3ds payments?

2025-03-27 08:08 UTC, swangi-kumari commented
Blocked on connector.

2025-03-27 08:08 UTC, closed without merging