feat(connector): [Deutschebank] Implement Card 3ds
juspay/hyperswitch pull request #6844
Opened 2024-12-16 08:25 UTC by Debarshi-Gupta

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Implement Card 3ds for Deutschebank

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-12-18 08:26 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                        PaymentMethodData::Card(ccard) => {
In this case, the card payment request will only be constructed during a CIT (when customer acceptance is passed). Normal payments do not require customer acceptance. Please refactor the try_from implementation to support normal card payments as well.

2024-12-18 08:26 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                    None => Err(errors::ConnectorError::MissingRequiredField {
We throw a `MissingRequiredField` error when we fail to receive a mandatory parameter from the user to construct a request. In this case, throw an `UnexpectedResponseError` instead

2024-12-18 08:26 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                    resource_id: ResponseId::NoResponseId,
In case of `processed` state don't we get a txn_id ?

2024-12-18 08:26 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                    reason: None,
Populate reason also

2024-12-18 08:26 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                    connector_response_reference_id: None,
Map connector transaction id value to this field, wherever possible.

2024-12-19 06:41 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +            let redirect_response = item.router_data.request.redirect_response.clone().ok_or(
Prefer using the utils function `get_redirect_response_payload()`

2024-12-19 06:41 UTC, AkshayaFoiger commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                    field_name: "payload",
Throw`MissingConnectorRedirectionPayload` error

2024-12-19 07:18 UTC, AkshayaFoiger approved these changes

2024-12-19 08:03 UTC, deepanshu-iiitu requested changes

2024-12-19 08:03 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                .to_owned();
Try this if possible
```
let cres = redirect_response_payload
    .get("cres")
    .and_then(|v| v.as_str())
    .map(String::from)
    .ok_or(errors::ConnectorError::MissingRequiredField { field_name: "cres" })?;
```

2024-12-19 08:03 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                false => DeutschebankTransactionKind::Directdebit,
Add payment method validation here as well

2024-12-19 08:03 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +            },
Add payment method validation here as well

2024-12-19 08:03 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +            },
Add payment method validation here as well

2024-12-19 11:28 UTC, deepanshu-iiitu requested changes

2024-12-19 11:28 UTC, deepanshu-iiitu commented on crates/router/src/configs/defaults/payment_connector_required_fields.rs
> +                                            ),
This is not required as you have already added `billing.address.first_name` and `billing.address.last_name`

2024-12-19 11:28 UTC, deepanshu-iiitu commented on crates/router/src/configs/defaults/payment_connector_required_fields.rs
> +                                            ),
This is not required as you have already added `billing.address.first_name` and `billing.address.last_name`

2024-12-19 11:28 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                    status_code: 500,
```suggestion
                    status_code: item.http_code,
```

2024-12-19 11:28 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                    code: item.http_code.to_string(),
```suggestion
                    code: consts::NO_ERROR_CODE,
```

2024-12-19 11:28 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +                    reason: Some("Method_Required Flow is not currently supported".to_owned()),
```suggestion
                    reason: Some("METHOD_REQUIRED Flow is not currently supported for Deutsche Bank Cards 3DS Payments".to_owned()),
```

2024-12-19 11:28 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +            },
Add explicit matching where
 if sepa then value should be Directdebit
if cards + 3ds the value should be  Creditcard3ds20
else not supported error

2024-12-19 11:28 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +            },
Add explicit matching where
if sepa then value should be Directdebit
if cards + 3ds the value should be Creditcard3ds20
else not supported error

2024-12-19 11:28 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +            },
Add explicit matching where
if sepa then value should be Directdebit
if cards + 3ds the value should be Creditcard3ds20
else not supported error

2024-12-19 18:39 UTC, deepanshu-iiitu requested changes

2024-12-19 18:39 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +            })
This should be SEPA Bank Debit not just BankDebit

2024-12-19 18:39 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +            })
This should be SEPA Bank Debit not just BankDebit

2024-12-19 18:39 UTC, deepanshu-iiitu commented on crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
> +            })
This should be SEPA Bank Debit not just BankDebit

2024-12-20 05:05 UTC, deepanshu-iiitu submitted a review, later dismissed

2024-12-20 05:25 UTC, Chethan-rao submitted a review, later dismissed

2024-12-20 07:57 UTC, AkshayaFoiger submitted a review, later dismissed

2024-12-27 08:51 UTC, AkshayaFoiger submitted a review, later dismissed

2024-12-27 10:47 UTC, AkshayaFoiger approved these changes

2024-12-31 06:52 UTC, deepanshu-iiitu approved these changes

2024-12-31 07:37 UTC, Chethan-rao approved these changes

2025-01-13 11:19 UTC, likhinbopanna approved these changes

2025-01-13 11:47 UTC, merged