feat(router): add /relay endpoint
juspay/hyperswitch pull request #6870
Opened 2024-12-18 06:00 UTC by ShankarSinghC

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-12-18 17:20 UTC, sai-harsha-vardhan commented on api-reference/api-reference/relay/relay-retrieve.mdx
> +openapi: openapi_spec get /relay/{relay_id}
we'll have to make changes in `mint.json` also, we can test the api-reference changes locally using mintlify - https://mintlify.com/docs/development

2024-12-18 17:20 UTC, sai-harsha-vardhan commented on crates/api_models/src/relay.rs
> +    /// Identifier of the connector ( merchant connector account ) which was chosen to make the payment
Not only for a payment right?

2024-12-19 11:10 UTC, sai-harsha-vardhan commented on crates/api_models/src/relay.rs
> +    pub data: Option<RelayData>,
Please add `connector_reference_id` in the response

2024-12-19 11:10 UTC, sai-harsha-vardhan commented on crates/api_models/src/relay.rs
> +    /// The business profile that is associated with this payment request
```suggestion
    /// The business profile that is associated with this relay request
```

2024-12-19 11:36 UTC, sai-harsha-vardhan submitted a review, later dismissed

2024-12-19 14:04 UTC, jarnura requested changes

2024-12-19 14:04 UTC, jarnura commented on crates/api_models/src/relay.rs
> +    pub profile_id: common_utils::id_type::ProfileId,
move this to headers

2024-12-20 09:24 UTC, jarnura approved these changes

2024-12-20 10:46 UTC, sai-harsha-vardhan approved these changes

2024-12-20 14:34 UTC, merged

2024-12-20 15:06 UTC, Narayanbhat166 commented on crates/api_models/src/relay.rs
> +#[serde(rename_all = "snake_case", untagged)]
do not use untagged for deserialization. You can rely on the `relay_type` to infer this. Can be changed in the subsequent PRs as well