feat(router): Add support for retries with clear pan and network token payment method data
juspay/hyperswitch pull request #6905
Opened 2024-12-19 21:16 UTC by prasunna09

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Add support to retry a transaction with clear PAN or Network Token

### Additional Changes

- [x] This PR modifies the API contract
- [x] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2025-01-02 02:59 UTC, jarnura submitted a review, later dismissed

2025-01-02 07:20 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/helpers.rs
> +            let card_result = vault_data
This is not a result anymore right?

2025-01-02 07:24 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/helpers.rs
> +            let vd = current_payment_method_data.map(|data| match data {
Try to avoid abbreviations as much as possible

2025-01-02 07:32 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/helpers.rs
> +                        ) => match (vault_data, payment_method) {
Can we move this logic to a impl based fn on VaultData which operates on self and returns the updated VaultData?

2025-01-02 07:32 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/helpers.rs
> +                    match (current_payment_method_data, payment_method_data) {
Can we move this to a fn to get the updated vault data, and you can wrap PaymentMethodDataAction::ExistingVaultData at the end just before setting the vault operation

2025-01-02 07:35 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/retry.rs
> +        let original_connector_data = original_connector_data.clone();
why's this re-assignment required here?

2025-01-02 07:36 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/retry.rs
> +                    let is_network_token = matches!(
This can be a impl based fn on PaymentMethodData

2025-01-02 07:38 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/retry.rs
> +                    let connector = if should_retry_with_pan {
Please add relevant code comments here

2025-01-02 07:42 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/retry.rs
> +                        original_connector_data.clone()
Is clone required here?

2025-01-02 07:42 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/retry.rs
> +            false,
Add a comment here, why this is hardcoded to false here

2025-01-02 07:43 UTC, sai-harsha-vardhan commented on crates/router/src/core/payments/transformers.rs
> +            //
redundant change

2025-01-02 08:40 UTC, prasunna09 commented on crates/router/src/core/payments/helpers.rs
> +                        VaultFetchAction::FetchCardDetailsFromLocker
its not save card flow, its actually `saved_card_flow` which mean card has already been saved with us. will updated the code comment

2025-02-03 15:53 UTC, prasunna09 commented on crates/router/src/core/payments.rs
> +                false, //should_retry_with_pan is set to false in case of PreDetermined ConnectorCallType
we'll take this up in separate pr

2025-02-03 16:44 UTC, sai-harsha-vardhan submitted a review, later dismissed

2025-02-18 11:24 UTC, jarnura requested changes

2025-02-18 11:24 UTC, jarnura commented on migrations/2024-12-10-091820_add-clear-pan-possible-to-gsm/up.sql
> +ALTER TABLE gateway_status_map ADD COLUMN IF NOT EXISTS clear_pan_possible BOOLEAN NOT NULL DEFAULT FALSE;
what is the difference between `clear_pan_possible` and `is_clear_pan_retries_enabled`?

2025-02-19 07:21 UTC, jarnura approved these changes

2025-02-20 07:54 UTC, sai-harsha-vardhan approved these changes

2025-02-23 11:32 UTC, Aprabhat19 approved these changes

2025-02-27 06:44 UTC, Aprabhat19 approved these changes

2025-02-27 07:00 UTC, sai-harsha-vardhan submitted a review, later dismissed

2025-02-27 07:02 UTC, jarnura approved these changes

2025-03-03 06:58 UTC, sai-harsha-vardhan approved these changes

2025-03-03 06:58 UTC, jarnura approved these changes

2025-03-03 06:59 UTC, Aprabhat19 approved these changes

2025-03-03 09:21 UTC, merged