refactor(currency_conversion): re frame the crate to make api calls on background thread
juspay/hyperswitch pull request #6906
Opened 2024-12-20 06:29 UTC by prajjwalkumar17

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2025-01-06 08:33 UTC, Chethan-rao requested changes

2025-01-06 08:33 UTC, Chethan-rao commented on config/config.example.toml
> +redis_lock_timeout = 100          # Redis remains write locked for 100 s once the acquire_redis_lock is called
can we maintain all the ttl in seconds? I see few are milliseconds too

2025-01-06 08:33 UTC, Chethan-rao commented on crates/router/src/configs/settings.rs
>      pub call_delay: i64,
can this have negative values too?

2025-01-06 08:36 UTC, Chethan-rao requested changes

2025-01-06 08:36 UTC, Chethan-rao commented on crates/router/src/configs/settings.rs
>      pub api_timeout: u64,
I also see that `api_timeout` is not being using anywhere?

2025-01-06 08:44 UTC, Chethan-rao requested changes

2025-01-06 08:44 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
> +        Err(ForexCacheError::ConfigurationError.into())
you can do attach_printable here? instead of having separate debug log

2025-01-06 08:44 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
> +                let _ = acquire_redis_lock_and_fetch_data(&state, stale_redis_data).await;
You don't need to send the `stale_redis_data` to `acquire_redis_lock_and_fetch_data`? because anyways its a background thread and you are returning `stale_redis_data` right after spawning

2025-01-06 08:44 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
>  ) -> CustomResult<FxExchangeRatesCacheEntry, ForexCacheError> {
Also no need to return anything from here? as this method will be called by background thread?

2025-01-06 08:48 UTC, Chethan-rao requested changes

2025-01-06 08:48 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
> +            logger::debug!("forex_log: forex response from cache");
```suggestion
            logger::debug!("forex_log: forex found in cache");
```

2025-01-06 09:00 UTC, Chethan-rao requested changes

2025-01-06 09:00 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
> +            logger::debug!("forex_log: forex response from redis");
```suggestion
            logger::debug!("forex_log: forex found in redis");
```

2025-01-06 09:00 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
> +    logger::info!("forex_log: {:?}", fallback_forex_request);
mention `fallback_forex_request` as a field in log so that it will be identifiable

2025-01-06 11:06 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
> +                acquire_redis_lock_and_fetch_data(&state).await.ok();
You can propagate the error inside this method and log it here in one place instead of logging it all over

2025-01-06 11:10 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
> +            successive_fetch_and_save_forex(state, Some(local_rates)).await
rename this method as it is not successive anymore

2025-01-06 14:24 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
>      }
can be simplified 
```
async fn acquire_redis_lock_and_fetch_data(
    state: &SessionState,
) -> CustomResult<(), ForexCacheError> {
    let lock_acquired = acquire_redis_lock(state).await?;
    if !lock_acquired {
        Err(ForexCacheError::CouldNotAcquireLock.into())
    } else {
        logger::debug!("forex_log: redis lock acquired");
        let api_rates = fetch_forex_rates(state).await;
        match api_rates {
            Ok(rates) => successive_save_data_to_redis_local(state, rates).await,
            Err(error) => {
                logger::error!(forex_error=?error,"primary_forex_error");
                // API not able to fetch data call secondary service
                let secondary_api_rates = fallback_fetch_forex_rates(state).await;
                match secondary_api_rates {
                    Ok(rates) => successive_save_data_to_redis_local(state, rates).await,
                    Err(error) => {
                        release_redis_lock(state).await?;
                        Err(error)
                    }
                }
            }
        }
    }
}
```

2025-01-09 14:23 UTC, Chethan-rao approved these changes

2025-01-16 13:24 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
> +async fn check_local_cache_expiry_and_call_api(
function says check local cache but you are checking in redis. rename it accordingly 

```suggestion
async fn call_api_if_redis_forex_data_expired(
```

2025-01-16 13:39 UTC, Chethan-rao commented on crates/router/src/utils/currency.rs
> +        Ok(Some(data)) => check_redis_data_expiry_and_call_api(state, data, call_delay).await,
```suggestion
        Ok(Some(data)) => call_forex_api_if_redis_data_expired(state, data, call_delay).await,
```

2025-01-16 19:20 UTC, SanchithHegde approved these changes

2025-01-16 19:20 UTC, SanchithHegde commented on crates/router/src/utils/currency.rs
>          Some(redis_forex) => {
Nit: The `is_redis_expired()` function (just before the `match` arm) made me think that it returned a `bool`.

2025-01-17 09:49 UTC, Chethan-rao approved these changes

2025-01-18 03:46 UTC, ShivanshMathurJuspay approved these changes

2025-01-28 18:59 UTC, merged