refactor: [CYBERSOURCE, BANKOFAMERICA, WELLSFARGO] Move code to crate hyperswitch_connectors
juspay/hyperswitch pull request #6908
Opened 2024-12-20 10:56 UTC by awasthi21

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Move cybersource, bankofamerica, wellsfargo code to crate hyperswitch_connectors.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
https://github.com/juspay/hyperswitch/issues/6585

## How did you test it?
Moved the connector tot he hyperswitch crate (No logical Changes)

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

2024-12-26 09:29 UTC, deepanshu-iiitu requested changes

2024-12-27 06:39 UTC, deepanshu-iiitu approved these changes

2024-12-27 10:34 UTC, SanchithHegde commented on crates/common_utils/src/consts.rs
> +pub const REFUND_VOIDED: &str = "Refund request has been voided.";
Can we move these 2 consts to the `hyperswitch_connectors` crate itself?

2024-12-27 10:34 UTC, SanchithHegde commented on crates/router/src/consts.rs
>  pub(crate) const CONNECTOR_UNAUTHORIZED_ERROR: &str = "Authentication Error from the connector";
Aren't we removing the const from here, since it would be moved to the `hyperswitch_connectors` crate?

2025-01-03 05:06 UTC, awasthi21 commented on crates/router/src/consts.rs
>  pub(crate) const CONNECTOR_UNAUTHORIZED_ERROR: &str = "Authentication Error from the connector";
Yes, we are removing them, but these constants are currently being used in connectors that have not yet been moved to `hyperswitch_connectors`. For now, we are just copying these constants to `hyperswitch_connectors`. Once all the relevant connectors have been moved, we can remove them.

2025-01-03 05:06 UTC, awasthi21 commented on crates/common_utils/src/consts.rs
> +pub const REFUND_VOIDED: &str = "Refund request has been voided.";
moved

2025-01-06 09:31 UTC, deepanshu-iiitu approved these changes

2025-01-08 20:10 UTC, SanchithHegde approved these changes

2025-01-09 11:13 UTC, sai-harsha-vardhan approved these changes

2025-01-15 11:24 UTC, pixincreate commented
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/abb4098f-75bb-49e6-9edb-961f01d19a3b" />


@awasthi21 👀

2025-01-16 08:20 UTC, deepanshu-iiitu submitted a review, later dismissed

2025-01-16 10:08 UTC, deepanshu-iiitu submitted a review, later dismissed

2025-01-16 10:14 UTC, sai-harsha-vardhan approved these changes

2025-01-16 20:00 UTC, SanchithHegde submitted a review, later dismissed

2025-01-22 07:45 UTC, deepanshu-iiitu approved these changes

2025-01-22 07:58 UTC, sai-harsha-vardhan approved these changes

2025-01-22 18:23 UTC, merged