docs: Update naming conventions and added examples
juspay/hyperswitch pull request #709
Opened 2023-03-03 11:53 UTC by dracarys18

## Type of Change

- [x] Enhancement

## Description

Added examples and updated naming conventions in docs.

## Motivation and Context

Updated docs for better naming conventions.

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-03-03 11:57 UTC, bernard-eugine approved these changes

2023-03-04 14:54 UTC, SanchithHegde reviewed
Other than that, looks good to me!

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/enums.rs
> +/// The hyperswitch code of all the supported banks
```suggestion
/// Names of banks supported by HyperSwitch
```

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/payment_methods.rs
> +    #[schema(value_type = Vec<String>, example = json!(["stripe", "adyen"]))]
`value_type` need not be specified here.

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/payment_methods.rs
> +    #[schema(value_type = Vec<String>, example = json!(["stripe", "adyen"]))]
Same here.

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/payment_methods.rs
>      pub payment_method_types: Vec<ResponsePaymentMethodTypes>,
Same here, `value_type` need not be specified as all the types are either directly imported or are in the same module.

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/payment_methods.rs
>  pub struct ListPaymentMethod {
Consider renaming this and other types in this module to match the naming conventions.

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +    #[schema(value_type = Option<String>, example = "chase")]
`value_type` need not be specified here.

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +        #[schema(value_type = BankRedirectBilling)]
Same here.

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +        #[schema(value_type = BankRedirectBilling)]
Same here.

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
> +        #[schema(value_type = BankRedirectBilling)]
Same here.

2023-03-04 14:54 UTC, SanchithHegde commented on crates/api_models/src/payments.rs
>      #[serde(rename = "created.gte")]
Unrelated, please merge the `serde` attributes here.

2023-03-06 08:34 UTC, jarnura requested changes

2023-03-06 08:34 UTC, jarnura commented on crates/api_models/src/payment_methods.rs
> -// impl ResponsePaymentMethodTypes {
Remove commented codes

2023-03-06 08:49 UTC, dracarys18 commented on crates/api_models/src/payment_methods.rs
> -// impl ResponsePaymentMethodTypes {
It's not there in the code

2023-03-06 08:51 UTC, jarnura approved these changes

2023-03-06 08:51 UTC, jarnura commented on crates/api_models/src/payment_methods.rs
> -// impl ResponsePaymentMethodTypes {
My bad

2023-03-06 10:04 UTC, SanchithHegde approved these changes

2023-03-06 11:08 UTC, bernard-eugine requested changes

2023-03-06 11:23 UTC, jarnura approved these changes

2023-03-06 11:38 UTC, merged