feat(connector): add verify (card mandate) support for bluesnap connector
juspay/hyperswitch pull request #742
Opened 2023-03-14 09:52 UTC by vsrivatsa25

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added verify (card mandate) support for bluesnap connector

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-28 19:49 UTC, jarnura requested changes

2023-03-28 19:49 UTC, jarnura commented on crates/router/src/connector/bluesnap/transformers.rs
> +                                _ => api_enums::Currency::USD,
Why in otherwise cases we are passing USD?

2023-03-28 19:49 UTC, jarnura commented on crates/router/src/connector/bluesnap/transformers.rs
> +                        _ => api_enums::Currency::USD,
Why in otherwise cases we are passing USD?

2023-03-28 19:49 UTC, jarnura commented on crates/router/src/connector/bluesnap/transformers.rs
> +                        _ => 0.to_string(),
Why in otherwise cases we are passing 0?

2023-03-28 19:49 UTC, jarnura commented on crates/router/src/connector/bluesnap/transformers.rs
> +                                _ => 0.to_string(),
Why in otherwise cases we are passing 0?

2023-07-28 13:35 UTC, SamraatBansal commented
These changes are not required in the current roadmap plan and since this is an aging PR closing this for now.
If required these changes can be added on top of latest main rather spending resources to accommodate current changes with latest codebase

2023-07-28 13:35 UTC, closed without merging