added field frm_configs to MerchantConnectorAccount
juspay/hyperswitch pull request #831
Opened 2023-04-03 13:00 UTC by rishavkar

## Type of Change

- [ ] Bugfix
- [x ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

We need to accept frm_configs from the dashboard. So needed to do development for accepting new fields for endpoint: `/account/:account_id/connectors`

### Additional Changes

- [x ] This PR modifies the database schema : 
                    `ALTER TABLE "merchant_connector_account" ADD COLUMN frm_configs jsonb;`
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

It a new feature...we are going to integrate FRM services into hyperswitch, for which we required additional fields for create connector request. 
This PR will accept frm_configs field for create connector request, and accordingly persist in the db.

## How did you test it?

Following are the steps:
- Adding an extra field to the request body, to existing curl.
  ```
"frm_configs" : {
      "frm_enabled_pms" : ["card"],
      "frm_enabled_pm_types" : ["credit"],
      "frm_enabled_gateways" : ["stripe"],
      "frm_action": "cancel_txn",
      "frm_preferred_flow_type" : "pre"
  }
```
- Getting 200 and Expecting this same body in response.

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-04 16:03 UTC, jagan-jaya requested changes

2023-04-06 07:38 UTC, dracarys18 requested changes
Also please format the code

2023-04-06 07:38 UTC, dracarys18 commented on crates/api_models/src/admin.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
Do we need Deserialize here?

2023-04-06 07:38 UTC, dracarys18 commented on crates/api_models/src/enums.rs
> +    serde::Deserialize,
Do we need these derives?

2023-04-06 07:38 UTC, dracarys18 commented on crates/api_models/src/enums.rs
> +    serde::Deserialize,
Same here

2023-04-06 07:38 UTC, dracarys18 commented on crates/router/src/core/admin.rs
> +    let frm_value: serde_json::Value = utils::Encode::<api_models::admin::FrmConfigs>::encode_to_value(&req.frm_configs).expect("Error encoding frm_configs to value");
Don't use expect.

2023-04-06 07:38 UTC, dracarys18 commented on crates/router/src/core/admin.rs
> +    let frm_value: serde_json::Value = utils::Encode::<api::PaymentMethodsEnabled>::encode_to_value(&req.frm_configs).expect("Error encoding frm_configs to value");
Don't use expect. Expect panics

2023-04-06 08:55 UTC, rishavkar commented on crates/api_models/src/enums.rs
> +    serde::Deserialize,
We can remove Eq,Hash,PartialEq,

2023-04-06 09:02 UTC, rishavkar commented on crates/api_models/src/admin.rs
> +pub struct FrmConfigs {
done

2023-04-06 09:02 UTC, rishavkar commented on crates/api_models/src/admin.rs
> +    pub frm_configs : Option<FrmConfigs>,
done

2023-04-06 09:02 UTC, rishavkar commented on crates/api_models/src/enums.rs
> +    serde::Deserialize,
We can remove Eq,Hash,PartialEq

2023-04-06 09:03 UTC, rishavkar commented on crates/router/src/core/admin.rs
> +    let frm_value: serde_json::Value = utils::Encode::<api_models::admin::FrmConfigs>::encode_to_value(&req.frm_configs).expect("Error encoding frm_configs to value");
done

2023-04-06 10:17 UTC, jagan-jaya approved these changes

2023-04-06 10:39 UTC, dracarys18 approved these changes

2023-04-06 11:26 UTC, jarnura requested changes

2023-04-06 11:26 UTC, jarnura commented on crates/api_models/src/admin.rs
> +    //contains the frm configs for the merchant... it should be of this format:: "\"frm_configs\" : { \"frm_enabled_pms\" : [\"card\"], \"frm_enabled_pm_types\" : [\"credit\"], \"frm_enabled_gateways
Add as documentation comments, use schema to examples

2023-04-06 11:26 UTC, jarnura commented on crates/api_models/src/admin.rs
> +    //contains the frm configs for the merchant... it should be of this format:: "\"frm_configs\" : { \"frm_enabled_pms\" : [\"card\"], \"frm_enabled_pm_types\" : [\"credit\"], \"frm_enabled_gateways
```suggestion
    /// contains the frm configs for the merchant... it should be of this format:: "\"frm_configs\" : { \"frm_enabled_pms\" : [\"card\"], \"frm_enabled_pm_types\" : [\"credit\"], \"frm_enabled_gateways\" : [\"stripe\"], \"frm_action\": \"cancel_txn\", \"frm_preferred_flow_type\" : \"pre\" }"
```

2023-04-06 11:26 UTC, jarnura approved these changes

2023-04-06 11:58 UTC, merged