feat(connector) : add template code for connector nexinets
juspay/hyperswitch pull request #852
Opened 2023-04-11 06:08 UTC by srujanchikke

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Template code for Nexinets

### Additional Changes

- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

Raising PR for template file alone for new connector, so that flows PR can be easily reviewed

## How did you test it?

testing not required for template code

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-11 10:02 UTC, jagan-jaya requested changes

2023-04-11 10:02 UTC, jagan-jaya commented on crates/router/src/connector/nexinets/transformers.rs
> +//TODO: Fill the struct with respective fields
remove todo

2023-04-11 10:02 UTC, jagan-jaya commented on crates/router/src/connector/nexinets/transformers.rs
> +//TODO: Fill the struct with respective fields
remove todo

2023-04-11 10:02 UTC, jagan-jaya commented on crates/router/src/connector/nexinets/transformers.rs
> +//TODO: Fill the struct with respective fields
remove todo

2023-04-11 10:02 UTC, jagan-jaya commented on crates/router/src/connector/nexinets/transformers.rs
> +//TODO: Fill the struct with respective fields
remove todo

2023-04-11 10:02 UTC, jagan-jaya commented on crates/router/src/connector/nexinets/transformers.rs
> +//TODO: Fill the struct with respective fields
remove todo

2023-04-11 10:02 UTC, jagan-jaya commented on crates/router/src/connector/nexinets/transformers.rs
> +//TODO: Fill the struct with respective fields
remove todo

2023-04-12 05:00 UTC, ArjunKarthik approved these changes

2023-04-12 07:20 UTC, jagan-jaya approved these changes

2023-04-13 10:25 UTC, jarnura approved these changes

2023-04-13 10:33 UTC, ArjunKarthik approved these changes

2023-04-18 07:24 UTC, jagan-jaya approved these changes

2023-04-18 07:38 UTC, ArjunKarthik approved these changes

2023-04-18 07:41 UTC, jarnura approved these changes

2023-04-18 08:02 UTC, merged