feat(domain): add encryption for merchant account
juspay/hyperswitch pull request #865
Opened 2023-04-12 11:34 UTC by dracarys18

## Type of Change

- [x] Enhancement

## Description

Adding encryption fields for merchant account.

## Motivation and Context

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-04-14 11:14 UTC, NishantJoshi00 requested changes

2023-04-14 11:14 UTC, NishantJoshi00 commented on crates/api_models/src/admin.rs
> +    pub merchant_name: Option<Encryptable<Secret<String>>>,
Use the `OptionalEncryptableName`

2023-04-14 11:14 UTC, NishantJoshi00 commented on crates/api_models/src/admin.rs
> +    pub api_key: Option<Encryptable<Secret<String>>>,
Same here

2023-04-14 11:14 UTC, NishantJoshi00 commented on crates/router/src/types/domain/merchant_account.rs
> +    pub merchant_name: Option<Encryptable<Secret<String>>>,
same here

2023-04-17 06:54 UTC, NishantJoshi00 approved these changes

2023-04-17 11:29 UTC, jarnura requested changes

2023-04-17 11:29 UTC, jarnura commented on crates/router/src/core/admin.rs
> +    let merchant_details: Option<masking::Secret<serde_json::Value>> = Some(
use type alias for this Option<masking::Secret<serde_json::Value>>

2023-04-17 11:29 UTC, jarnura commented on crates/router/src/core/admin.rs
> +            .async_map(|inner| crypto::Encryptable::encrypt(inner.into(), &key, GcmAes256 {}))
use async_lift instead if async_map.

2023-04-17 11:29 UTC, jarnura commented on crates/router/src/core/admin.rs
> +            .async_map(|inner| crypto::Encryptable::encrypt(inner.into(), &key, GcmAes256 {}))
Update in other places too

2023-04-19 09:29 UTC, jarnura approved these changes

2023-04-19 09:29 UTC, merged