feat: Add merchant key store
juspay/hyperswitch pull request #873
Opened 2023-04-13 09:59 UTC by dracarys18

## Type of Change

- [x] Enhancement

## Description

This PR adds key store DB which stores encryption key per merchant account. The encryption key will be further encrypted by `master_key` which will further be KMS encrypted. 

### Additional Changes

- [x] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-04-17 07:34 UTC, jarnura requested changes

2023-04-17 07:34 UTC, jarnura commented on crates/router/src/core/admin.rs
> +            .change_context(errors::ApiErrorResponse::InternalServerError)?,
Add attach printable for InternalServerError.

2023-04-17 07:34 UTC, jarnura commented on crates/router/src/services.rs
> +) -> crate::core::errors::CustomResult<[u8; 32], common_utils::errors::CryptoError> {
```suggestion
) -> errors::CustomResult<[u8; 32], common_utils::errors::CryptoError> {
```

2023-04-19 10:32 UTC, NishantJoshi00 approved these changes
LGTM

2023-04-20 07:29 UTC, jarnura reviewed
Add proper labels for the changes

2023-04-21 07:29 UTC, jarnura requested changes
- All InternalServerError Should have attach_printable which explains the about the Error
- Import the mod and use mod::func in the application, change all functions which is imported as crate::mod::func to mod::func

2023-04-21 07:29 UTC, jarnura commented on config/config.example.toml
> +master_enc_key = "73ad7bbbbc640c845a150f67d058b279849370cd2c1f3c67c4dd6c869213e13a" # Master Encryption key used to encrypt merchant wise encryption key
use a dummy key here, like `sample_key`

2023-04-21 08:27 UTC, dracarys18 commented
> * All InternalServerError Should have attach_printable which explains the about the Error
> 
>     * Import the mod and use mod::func in the application, change all functions which is imported as crate::mod::func to mod::func

Done

2023-04-21 10:13 UTC, jarnura approved these changes

2023-04-21 10:13 UTC, merged