feat(domain): add domain types for certain structs
juspay/hyperswitch pull request #879
Opened 2023-04-14 08:37 UTC by dracarys18

## Type of Change

- [x] Enhancement

## Description

Encryption for merchant connector account.

## Motivation and Context

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-04-14 10:30 UTC, NishantJoshi00 approved these changes

2023-04-17 18:37 UTC, jarnura requested changes
Avoid importing function directly in import statement. 

Replace `get_merchant_enc_key` to `types::get_merchant_enc_key` in all places

2023-04-17 18:37 UTC, jarnura commented on crates/router/src/db/merchant_connector_account.rs
> +            super::cache::get_or_populate_redis(self, merchant_connector_id, find_call)
remove absolute path while calling function

2023-04-20 08:31 UTC, jarnura approved these changes

2023-04-20 08:31 UTC, merged