feat(connector) : add PayPal wallet support for Paypal
juspay/hyperswitch pull request #893
Opened 2023-04-17 05:48 UTC by prasunna09

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Add PayPal wallet support for Paypal.

### Additional Changes

- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

tested using postman.
<img width="1350" alt="Screenshot 2023-04-17 at 10 53 40 AM" src="https://user-images.githubusercontent.com/70575890/232393793-cc181817-97b8-431d-8a7b-6849f389bcd3.png">

<img width="1345" alt="Screenshot 2023-04-17 at 10 54 02 AM" src="https://user-images.githubusercontent.com/70575890/232393825-f57d3204-cdef-42f9-95ea-e618928cd648.png">

<img width="596" alt="Screenshot 2023-04-17 at 10 54 39 AM" src="https://user-images.githubusercontent.com/70575890/232393843-54ef5dda-6728-44f6-8aac-4e02b953f32a.png">

<img width="1349" alt="Screenshot 2023-04-17 at 10 55 30 AM" src="https://user-images.githubusercontent.com/70575890/232393867-4bb0eef7-eaf8-4736-bb32-454ce4d929ab.png">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-17 06:10 UTC, ArjunKarthik requested changes

2023-04-17 06:10 UTC, ArjunKarthik commented on crates/router/src/core/payments/transformers.rs
> +        );
```suggestion
        let connector = api::ConnectorData::get_connector_by_name(
            &additional_data.state.conf.connectors,
            &additional_data.connector_name,
            api::GetToken::Connector,
        )?;
```

By this way we can ignore the below match statement

2023-04-17 06:10 UTC, ArjunKarthik commented on crates/router/src/core/payments/transformers.rs
> +        let connectors = match connector {
This can be removed

2023-04-17 06:10 UTC, ArjunKarthik commented on crates/router/src/connector/paypal/transformers.rs
> +                    "Unknown Wallet in Payment Method".to_string(),
Let it be `Payment Method`.

2023-04-17 06:10 UTC, ArjunKarthik commented on crates/router/src/connector/paypal/transformers.rs
> +        for item2 in link_vec.iter() {
Let's move this logic to a new method, `get_redirect_url`

2023-04-17 07:03 UTC, ArjunKarthik commented
@prasunna09 You conflicts resolution removed some of your changes. Please verify your changes once again and update the PR with necessary changes

2023-04-19 06:38 UTC, ArjunKarthik commented
@prasunna09 please resolve conflicts

2023-04-20 08:56 UTC, ArjunKarthik approved these changes

2023-04-20 10:25 UTC, jarnura approved these changes

2023-04-20 22:17 UTC, merged