feat(core): [Stripe] add bank debits payment method to stripe
juspay/hyperswitch pull request #906
Opened 2023-04-18 07:35 UTC by Narayanbhat166

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

This PR will add support for creating payments using `bank_debits` payment method. This has been implemented for stripe.
- Ach Bank debit
```json
{
"payment_method": "bank_debit",
    "payment_method_type": "sepa",
    "payment_method_data": {
        "bank_debit": {
            "ach_bank_debit": {
                "billing_details": {
                    "name": "John Doe",
                    "email": "johndoe@example.com"
                },
                "account_number": "000123456789",
                "routing_number": "110000000"
            }
        }
    }
}
```

- Sepa
```json
{
"payment_method": "bank_debit",
    "payment_method_type": "sepa",
    "payment_method_data": {
        "bank_debit": {
            "sepa_bank_debit": {
                "billing_details": {
                    "name": "John Doe",
                    "email": "johndoe@example.com"
                },
                "iban": "DE89370400440532013000"
            }
        }
    }
}
```

- Becs
```json
{
"payment_method": "bank_debit",
    "payment_method_type": "becs",
    "payment_method_data": {
        "bank_debit": {
            "becs_bank_debit": {
                "billing_details": {
                    "name": "John Doe",
                    "email": "johndoe@example.com"
                },
                "account_number": "000123456",
                "bsb_number": "000000"
            }
        }
    }
}
```
- Bacs
```json
{
"payment_method_type": "bacs",
    "payment_method_data": {
        "bank_debit": {
            "bacs_bank_debit": {
                "billing_details": {
                    "name": "John Doe",
                    "email": "johndoe@example.com",
                    "address": {
                        "line1": "Street",
                        "line2": "Area",
                        "city": "LDN",
                        "zip": "SW1A",
                        "country": "GB"
                    }
                },
                "account_number": "00012345",
                "sort_code": "108800"
            }
        }
    }
}
```

## Motivation and Context

To support `bank_debits` payment method for anyone to use.

## How did you test it?

- ACH bank debit
<img width="844" alt="Screenshot 2023-04-18 at 12 43 41 PM" src="https://user-images.githubusercontent.com/48803246/232700078-0e6670df-810e-4aa0-ad50-c9988f676714.png">
- Microdeposit verification for ACH
![Screenshot 2023-04-18 at 12 45 26 PM](https://user-images.githubusercontent.com/48803246/232700520-a9980e9e-d21b-4ea3-ad62-fcc13e72f305.png)

- Sepa bank debit
<img width="829" alt="Screenshot 2023-04-18 at 12 56 24 PM" src="https://user-images.githubusercontent.com/48803246/232703129-ac241075-dcc2-40b9-b376-cabb05733a26.png">

- Bacs bank debit
- Becs bank debit

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-19 12:41 UTC, Abhicodes-crypto commented on crates/router/src/connector/stripe/transformers.rs
> +    pii::{self},
u can remove self here

2023-04-19 13:12 UTC, Abhicodes-crypto approved these changes
LGTM

2023-04-20 07:10 UTC, jarnura requested changes

2023-04-20 07:10 UTC, jarnura commented on crates/router/src/connector/stripe/transformers.rs
> +#[serde(untagged)]
Why we need untagged here the parent struct which use the this have method type we can infer that and serialize.

2023-04-20 08:46 UTC, jarnura approved these changes

2023-04-20 08:47 UTC, jarnura requested changes
Add required labels

2023-04-20 13:25 UTC, jarnura approved these changes

2023-04-21 07:06 UTC, jarnura approved these changes

2023-04-21 07:11 UTC, Abhicodes-crypto approved these changes
LGTM

2023-04-21 08:38 UTC, merged