feat: SEPA and BAC bank transfers through stripe
juspay/hyperswitch pull request #930
Opened 2023-04-20 10:08 UTC by Sangamesh26

## Type of Change

- [x] New feature

## Description

Add features SEPA and BACS bank transfers.

API contract for SEPA in hyperswitch :
```
   “payment_method”: “bank_transfer”
  “payment_method_type”: ”sepa”,
  "payment_method_data": {
    "bank_transfer": {
      "sepa_bank_transfer":{
        "billing_details": {
          "email": "johndoe@example.com",
          "name": "John"
        }
        "country": "FR"
    }
  }
},
```

API contract for BACS in hyperswitch :
```
  “payment_method”: “bank_transfer”
  “payment_method_type”: ”bacs”,
  "payment_method_data": {
   "bank_transfer": {
    "bacs_bank_transfer":{
        "billing_details": {
          "email": "johndoe@example.com",
          "name": "John"
        }
    }
  }
 },
```

Steps followed for SEPA and BACS :
1.  PaymentIntent call to stripe with customer_id 
2. We get the bank instructions in next action
3. The bank instruction are sent in confirm call of hyperswitch 
4. Hyperswitch receives webhook for the status

## Motivation and Context

New payment method , Bank transfer BACS and SEPA is implemented

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-05-18 09:44 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> +#[serde(untagged)]
Is this enum used for `Serialize` or `Deserialize`?

2023-05-18 09:44 UTC, Narayanbhat166 commented on crates/router/src/connector/stripe/transformers.rs
> +    pub name: String,
These fields are already there in 
https://github.com/juspay/hyperswitch/blob/a6cc8e08c560bec2e59c7c7290a6382d1611e8df/crates/router/src/connector/stripe/transformers.rs#L1723 can reuse the same

2023-05-19 06:34 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> +    pub name: String,
Make this field as a secret

2023-05-19 06:34 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> +    pub iban: String,
These fields should be secret too.

2023-05-19 06:34 UTC, Narayanbhat166 commented on crates/api_models/src/payments.rs
> +    pub sort_code: String,
These should be a secret too

2023-05-19 06:34 UTC, Narayanbhat166 commented on crates/router/src/connector/stripe/transformers.rs
> +    pub billing_address: StripeBillingAddress,
billing_address is already there in `PaymentIntentRequest`, you can use the same

2023-05-19 06:34 UTC, Narayanbhat166 commented on crates/router/src/connector/stripe/transformers.rs
> +                        )?,
Cannot raise this error when handling the response. We should handle the redirection if it is provided by the connector in response, if not this should be sent as none

2023-05-19 06:34 UTC, Narayanbhat166 commented on crates/router/src/connector/stripe/transformers.rs
> +            .change_context(errors::ConnectorError::RequestEncodingFailed)
This should be response handling failed

2023-05-19 06:55 UTC, jarnura requested changes

2023-05-19 06:55 UTC, jarnura commented on crates/api_models/src/payments.rs
> +    AchCreditTransfer(AchTransfer),
Use Box for all struct variants.

2023-05-19 06:55 UTC, jarnura commented on crates/router/src/connector/stripe/transformers.rs
> +    AchBankTransfer(AchBankTransferData),
Use Box for all struct variants

2023-05-19 06:55 UTC, jarnura commented on crates/router/src/connector/stripe/transformers.rs
>  #[serde(untagged)]
Add a comment which says, when de-serialise is added then untagged should be removed.

2023-05-19 07:58 UTC, jarnura approved these changes

2023-05-19 07:58 UTC, jarnura commented on crates/api_models/src/payment_methods.rs
> +    pub bank_transfers: Option<BankTransferTypes>,
Add Doc comments

2023-05-19 07:58 UTC, jarnura commented on crates/api_models/src/payment_methods.rs
> +    pub eligible_connectors: Vec<String>,
Add Doc comments

2023-05-19 07:59 UTC, jarnura requested changes
Add doc comments.

2023-05-19 09:17 UTC, jagan-jaya requested changes

2023-05-19 09:17 UTC, jagan-jaya commented on crates/router/src/connector/stripe/transformers.rs
> +                    })?,
```suggestion
                email: item.request.get_email()?,
```

2023-05-19 09:17 UTC, jagan-jaya commented on crates/router/src/connector/stripe/transformers.rs
> +            .change_context(errors::ConnectorError::ResponseHandlingFailed)
```suggestion
```
not required

2023-05-19 09:17 UTC, jagan-jaya commented on crates/router/src/connector/stripe/transformers.rs
> +            .change_context(errors::ConnectorError::ResponseHandlingFailed)
```suggestion
```
not required

2023-05-19 09:18 UTC, jagan-jaya commented
@Sangamesh26 Please run redirection tests once you are done with the changes

2023-05-19 11:49 UTC, Narayanbhat166 approved these changes

2023-05-19 12:34 UTC, HyperSwitchers approved these changes

2023-05-19 12:34 UTC, jagan-jaya approved these changes

2023-05-19 13:00 UTC, merged