feat(connector): add authorize, capture, void, psync, refund, rsync for Forte connector
juspay/hyperswitch pull request #955
Opened 2023-04-21 18:34 UTC by prasunna09

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Updating support for [Forte](https://www.forte.net) payment gateway
Payment Method: card
Supported payment flows:

Authorize
Capture
Void
PSync
Refund
RSync

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

![1149F011-08C8-4098-B4B3-1DA3496C3157_1_201_a](https://user-images.githubusercontent.com/70575890/233710113-ee27e873-9b74-478a-8085-51fe98ca8ba9.jpeg)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [x] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-22 04:11 UTC, Abhicodes-crypto commented on crates/router/src/connector/forte/transformers.rs
> +#[serde(rename_all = "snake_case")]
Since the fields are already in snake case. I guess this line isn't necessary.

2023-04-25 07:34 UTC, ArjunKarthik requested changes

2023-04-25 10:30 UTC, prasunna09 commented on crates/router/src/connector/forte/transformers.rs
> +    card: Card,
Yes, I have mailed them, waiting for their reply

2023-04-25 12:06 UTC, jagan-jaya requested changes

2023-04-25 12:06 UTC, jagan-jaya commented on crates/router/src/connector/forte/transformers.rs
> +            _ => Self::Failure,
```suggestion
    fn foreign_from((response_code, action): (ForteResponseCode, ForteAction)) -> Self {
        match response_code {
            ForteResponseCode::A01 => match action {
                ForteAction::Authorize => Self::Authorized,
                ForteAction::Sale => Self::Pending,
            },
            ForteResponseCode::A05 | ForteResponseCode::A06 => Self::Authorizing,
            _ => Self::Failure,
```

2023-04-25 12:06 UTC, jagan-jaya commented on crates/router/src/connector/forte/transformers.rs
> +    name_on_card: String,
mask it, name is PII data

2023-04-25 12:06 UTC, jagan-jaya commented on crates/router/tests/connectors/forte.rs
> +    assert_eq!(response.status, enums::AttemptStatus::Pending);
add reason for why it is pending, when this will succeed

2023-04-25 14:45 UTC, jagan-jaya approved these changes

2023-04-25 14:54 UTC, ArjunKarthik requested changes

2023-04-25 14:54 UTC, ArjunKarthik commented on crates/router/src/connector/forte/transformers.rs
> +    card: Card,
create a GitHub issue and add in the code

2023-04-25 14:54 UTC, ArjunKarthik commented on crates/router/src/connector/forte/transformers.rs
> +#[serde(rename_all = "snake_case")]
change it to lowercase

2023-04-25 14:54 UTC, ArjunKarthik commented on crates/router/src/connector/forte/transformers.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
As discussed use only necessary things

2023-04-25 14:55 UTC, ArjunKarthik requested changes

2023-04-26 12:44 UTC, jagan-jaya submitted a review, later dismissed

2023-04-26 13:48 UTC, ArjunKarthik approved these changes

2023-04-26 14:04 UTC, HyperSwitchers approved these changes

2023-04-26 14:05 UTC, jagan-jaya submitted a review, later dismissed

2023-05-02 08:52 UTC, jarnura approved these changes

2023-05-03 08:25 UTC, jarnura submitted a review, later dismissed

2023-05-03 08:28 UTC, jagan-jaya approved these changes

2023-05-03 08:30 UTC, ArjunKarthik submitted a review, later dismissed

2023-05-03 10:21 UTC, jagan-jaya submitted a review, later dismissed

2023-05-03 10:35 UTC, ArjunKarthik approved these changes

2023-05-03 12:54 UTC, jagan-jaya approved these changes

2023-05-04 14:13 UTC, merged