refactor(core): in PaymentData and RouterData make flow as concrete type
juspay/hyperswitch pull request #966
Opened 2023-04-24 16:37 UTC by Abhicodes-crypto

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

There is a generic type `F` which has been used across the codebase. It represents Flow. In this PR the following changes are made :
- Marker trait `Flow` is created and all the entities using `F` are constrained by `F: Flow`.
- Trait Flow implements Debug additionally. 
- A derive macro for Flow has been implemented and used wherever appropriate.
- If we want Flow as a string we use `format!("{:?}", F::default())),`, see `crates/router/src/services/api.rs:193`

While making the above changes I observed that `crates/router/src/connector/utils.rs:53` There was a trait RouterData which had getter methods on RouterData. So I removed the trait and instead made it `impl RouterData`. Let me know if this change needs to be reverted.

Also derive Debug impl seems to be unstable across rustc versions https://doc.rust-lang.org/std/fmt/trait.Debug.html#stability . I will impl Display on Flow.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

## How did you test it?

It compiled. But let me know if I have to test any specific flow.

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-04 12:52 UTC, jarnura requested changes
Looks good to me :)

2023-05-04 12:52 UTC, jarnura commented on crates/router/src/connector/utils.rs
> +// pub trait RouterData {
Remove comment code

2023-06-01 06:14 UTC, Narayanbhat166 approved these changes

2023-06-21 09:30 UTC, Narayanbhat166 submitted a review, later dismissed

2023-07-14 08:19 UTC, ashokkjag commented
@Abhicodes-crypto , can you check and rebase. can't have 406 files changed.

2024-10-03 08:16 UTC, Narayanbhat166 commented
Closing this PR since this change is no longer required

2024-10-03 08:16 UTC, closed without merging