fix(refund_list): updated refund list response status code when no refunds found.
juspay/hyperswitch pull request #974
Opened 2023-04-25 07:20 UTC by hrithikesh026

## Type of Change

- [x] Bugfix

## Description

* Changed `refund_list()` function in `crates/router/src/core/refunds.rs`  such that it returns only Ok response with Vec of refunds.
* Added  `size: usize` field to `RefundListResponse` in `crates/api_models/src/refunds.rs` just like in `PaymentListResponse`.

## Motivation and Context
"Get Refund List" would send an error response with status code 400 when no refunds are found.
Fixed it so it returns an empty list with status code 200 like "Get Payment List".

## How did you test it?

Manual

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code

2023-04-25 08:23 UTC, Abhicodes-crypto commented on crates/api_models/src/refunds.rs
> +    pub size: usize,
Fix schema

2023-04-25 08:25 UTC, Abhicodes-crypto requested changes
Schema change requested. Other than that LGTM.

2023-04-25 11:14 UTC, Abhicodes-crypto approved these changes

2023-04-25 18:37 UTC, SanchithHegde approved these changes

2023-05-02 20:25 UTC, jarnura approved these changes

2023-05-02 20:45 UTC, merged