feat(router): added support for optional defend dispute api call and added evidence submission flow for checkout connector
juspay/hyperswitch pull request #979
Opened 2023-04-25 10:38 UTC by sai-harsha-vardhan

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
1. added support for optional defend dispute api call in evidence submission flow if connector requires it.
2. added file upload and evidence submission flow for checkout connector.

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
There is a use case where we have to do 2 api calls for evidence submission (for connectors like checkout, adyen)
1. Attach the evidence to dispute
2. Defend the dispute
Added support for optional second call to connector to defend the dispute

## How did you test it?
Tested Manually
![image](https://user-images.githubusercontent.com/56996463/234251328-d61c41e5-f750-428a-aace-444e83f77076.png)

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-25 11:04 UTC, Abhicodes-crypto commented on crates/api_models/src/enums.rs
> +        matches!(self, Self::Stripe | Self::Checkout)
Can this be populated from config ?

2023-04-25 12:26 UTC, Abhicodes-crypto commented on crates/router/src/connector/checkout.rs
> +        ))
```suggestion
        Ok(format!(
            "{}disputes/{}/evidence"",
            self.base_url(connectors),
            req.request.connector_dispute_id,
        ))
```

2023-04-25 12:36 UTC, Abhicodes-crypto commented on crates/router/src/core/disputes.rs
> +        Err(err) => match err.message.as_ref() {
Can `err.code` be used here ?

2023-04-25 12:40 UTC, Abhicodes-crypto requested changes
Minor changes requested , other than that LGTM

2023-04-25 13:36 UTC, Abhicodes-crypto commented
Is there a limit on the file size that is uploaded to hyperswitch ?

2023-04-25 13:36 UTC, Abhicodes-crypto submitted a review, later dismissed

2023-04-27 07:41 UTC, Narayanbhat166 commented on crates/router/src/core/utils.rs
> +        response: Err(ErrorResponse::get_not_implemented()),
Is this error intentional? By default this should be `InternalServerError`

2023-04-28 07:08 UTC, Narayanbhat166 submitted a review, later dismissed

2023-04-28 09:46 UTC, Narayanbhat166 approved these changes

2023-04-28 10:30 UTC, Abhicodes-crypto approved these changes

2023-05-02 20:55 UTC, jarnura approved these changes

2023-05-03 01:55 UTC, merged