Feat/filter payments on available capture methods
juspay/hyperswitch pull request #999
Opened 2023-04-26 12:59 UTC by prajjwalkumar17

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
We are adding a filter for the payment methods list that whenever the capture method on payment_intent is set to Manual it will evaluate whether that connector issues for the manual capture of payment or not. If not it won't be visible in payments method list

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [x] This PR modifies application configuration/environment variables

## Motivation and Context\
As of now even if manual capture is not present for a connector, our route was showing the option from now it won't happen and only the methods allowed for manual capture will be visible to choose from

## How did you test it?
When we will make the payment create in manual mode we  will won't get the cards available as it don't supports manual capture

<img width="1728" alt="Screenshot 2023-04-26 at 18 26 15" src="https://user-images.githubusercontent.com/61520228/234581609-917e425a-fc8a-458e-a38a-fb94cbf8ed37.png">

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-26 20:46 UTC, SanchithHegde commented on .vscode/settings.json
Please untrack this file.

2023-04-26 20:46 UTC, SanchithHegde commented on config/development.toml
> +        #ACI,BrainTree,Klarna,Mollie,MultisafePay,Trustpay,Zen
I believe you should be able to remove this comment?

2023-04-26 20:46 UTC, SanchithHegde commented on crates/router/src/core/payment_methods/cards.rs
> +fn filter_for_capture_method(
This function could either use a better name or have a brief documentation as to what is does.

2023-04-27 06:24 UTC, NishantJoshi00 requested changes
Other than that, looks good!

2023-04-27 06:24 UTC, NishantJoshi00 commented on crates/common_enums/src/enums.rs
> +}
can we have it in snake case? it stands out quite a bit in the configuration file

2023-04-27 06:24 UTC, NishantJoshi00 commented on crates/router/src/core/payment_methods/cards.rs
> +use storage_models::{enums::CaptureMethod, payment_method};
avoid specific imports, instead import `enums` and in the later part of the code use `enums::CaptureMethod` instead

2023-04-27 06:24 UTC, NishantJoshi00 commented on crates/router/src/core/payment_methods/cards.rs
> +        .is_none()
It seems you are not using the value that, was specified for `absent_impl`, even though currently we don't require it, please add a match case, so in the future if any new filters were to be added, the developer would understand the logic that you have written and also the modifications would be much easier

2023-04-27 07:54 UTC, Narayanbhat166 approved these changes

2023-04-27 18:03 UTC, SanchithHegde submitted a review, later dismissed

2023-04-28 06:26 UTC, NishantJoshi00 submitted a review, later dismissed

2023-04-28 10:30 UTC, Narayanbhat166 commented on crates/router/src/configs/settings.rs
> +    pub not_available_flows: Option<NotAvailableFlows>,
The parent struct will have to be renamed, it's not only currency and country filter now.

2023-05-02 09:03 UTC, NishantJoshi00 submitted a review, later dismissed

2023-05-02 10:58 UTC, Narayanbhat166 approved these changes

2023-05-02 20:30 UTC, jarnura approved these changes

2023-05-03 08:21 UTC, jarnura submitted a review, later dismissed

2023-05-03 08:48 UTC, Narayanbhat166 submitted a review, later dismissed

2023-05-03 10:32 UTC, jarnura approved these changes

2023-05-03 10:40 UTC, dracarys18 approved these changes
LGTM

2023-05-03 11:02 UTC, merged